### ISSUE TITLE
MySQLParser: What am I doing wrong?

### ISSUE THREAD

**Issue by jesaremi** [antlr/grammars-v4#1001]
I used MySqParser and MySqlLexer.g4 to generate CSharp target.
Command line to generate targets:

`"C:\Program Files\Java\jdk1.8.0_144\bin\java" -Xmx500M -cp "antlr-4.7-complete.jar;" org.antlr.v4.Tool -o MySql -listener -visitor -Dlanguage=CSharp  MySqlParser.g4`

Then I used one of the "select" statements in the dml_select test vector.

`select col1 from t1 inner join t2 on (t1.col1 = t2.col2);`

If I use the statement as is then I get the following error:

> line 1:10 mismatched input '1' expecting {<EOF>, 'ALTER', 'ANALYZE', 'CALL', 'CHANGE', 'CHECK', 'CREATE', 'DELETE', 'DESC', 'DESCRIBE', 'DROP', 'EXPLAIN', 'GRANT', 'INSERT', 'KILL', 'LOAD', 'LOCK', 'OPTIMIZE', 'PURGE', 'RELEASE', 'RENAME', 'REPLACE', 'REVOKE', 'SELECT', 'SET', 'SHOW', 'UNLOCK', 'UPDATE', 'USE', 'BEGIN', 'BINLOG', 'CACHE', 'CHECKSUM', 'COMMIT', 'DEALLOCATE', 'DO', 'FLUSH', 'HANDLER', 'HELP', 'INSTALL', 'PREPARE', 'REPAIR', 'RESET', 'ROLLBACK', 'SAVEPOINT', 'START', 'STOP', 'TRUNCATE', 'UNINSTALL', 'XA', 'EXECUTE', 'SHUTDOWN', '--', '(', ';'}

If I convert the sql keywords to uppercase then I get the following error:

SELECT col1 FROM t1 INNER JOIN t2 ON (t1.col1 = t2.col2);

`line 1:18 no viable alternative at input 'SELECT col1 FROM t1'`

Here's the code snippet for the runtime:
```

            AntlrInputStream inputStream = new AntlrInputStream(sql);
            var helloLexer = new MySqlLexer(inputStream);
            CommonTokenStream commonTokenStream = new CommonTokenStream(helloLexer);
            var mysqlParser = new MySqlParser(commonTokenStream);
            var rootContext = mysqlParser.root();
            MyVisitor visitor = new MyVisitor();
            visitor.VisitRoot(rootContext);
```

**Comment by KvanTTT** [comment]
Duplicate: https://github.com/antlr/grammars-v4/issues/878
We are using case insensitive input stream.

**Comment by jesaremi** [comment]
Could you answer this then? When I convert the sql into upper case I get the following:
line 1:18 no viable alternative at input 'SELECT col1 FROM t1'
what does this mean?

**Comment by KvanTTT** [comment]
Such stream saves case of identifiers, see: https://github.com/antlr/antlr4/blob/master/doc/case-insensitive-lexing.md

**Comment by jesaremi** [comment]
i see. thanks for sharing.
