### ISSUE TITLE
mySQL grammar has out of place channels command

### ISSUE THREAD

**Issue by nicomp42** [antlr/grammars-v4#1010]
I get the error "parser rule 'channels' not allowed in lexer" when I build the code. 

I 'fixed' it by commenting out the channels and hard-coding the channel numbers:

@lexer::members {
	public static final int MYSQLCOMMENT = 1;
	public static final int ERRORCHANNEL = 2;
}
**//channels { MYSQLCOMMENT, ERRORCHANNEL };	// Commented out because it gives an error.**

// SKIP

SPACE:                               [ \t\r\n]+    -> channel(HIDDEN);
SPEC_MYSQL_COMMENT:                  '/*!' .+? '*/' -> channel(**1**);
COMMENT_INPUT:                       '/*' .*? '*/' -> channel(HIDDEN);
LINE_COMMENT:                        (
                                       ('-- ' | '#') ~[\r\n]* ('\r'? '\n' | EOF)
                                       | '--' ('\r'? '\n' | EOF)
                                     ) -> channel(HIDDEN);

...

_and all the way at the bottom of the file..._
ERROR_RECONGNIGION:                  .    -> channel(**2**);

**Comment by KvanTTT** [comment]
What version of ANTLR are you using?

**Comment by nicomp42** [comment]
Version 4.7

**Comment by AstroMen** [comment]
I also have the same issue. Do you have any solution? @nicomp42
