### ISSUE TITLE
What do "_lf_" and "_lfno_" mean in the Java 8 grammar?

### ISSUE THREAD

**Issue by jamesqo** [antlr/grammars-v4#1026]
There are particular rules with `lf` / `lfno` in their names in the Java 8 grammar. For example, [here](https://github.com/antlr/grammars-v4/commit/c73f510a56ae80bce76c76a0661afb8aa7eb6f19#diff-ce4027f8b738f72ece42edf6525f242bR137). What do these rules mean?

**Comment by KvanTTT** [comment]
I recommend using https://github.com/antlr/grammars-v4/tree/master/java grammar instead of Java8 one. It supports Java 8 as well. Moreover it's much faster.

**Comment by jamesqo** [comment]
@KvanTTT Skipped that one because I wasn't sure how to wire multiple `g4` files together so that ANTLR will generate 1 grammar encompassing both of them. Would you know how to?

**Comment by KvanTTT** [comment]
Sure. You have to generate the Lexer at first and the Parser after with the same arguments and in the same directory.

**Comment by KvanTTT** [comment]
Please follow the question on StackOverflow: [Explanation for “_lf_” and “_lfno_” pattern in Java8.g8 grammar for ANTLR4](https://stackoverflow.com/q/40268685/1046374).
