### ISSUE TITLE
Java: (non generic) method call is parsing apart method name and arguments

### ISSUE THREAD

**Issue by pejobo** [antlr/grammars-v4#1034]
The grammar `java/JavaParser.g4` parses method name and arguments into different AST branches. This makes code walking the AST really complicated :(

Example: 

The fragment `out.println(42);` is parsed into

`(expression (expression (expression (primary out)) . println) ( (expressionList (expression (primary (literal (integerLiteral 42))))) )) ;`

So `out.println` is the left branch while `(42)` is the right branch.

E.g. changing the corresponding rule (as an experiment) to `expression bop='.' IDENTIFIER '(' expressionList? ')'` would yield:

`(expression (expression (primary out)) . println ( (expressionList (expression (primary (literal (integerLiteral 42))))) )) ;`

This will keep `println` and the arguments `(42)` together.

Current parser rule (extract): 

    expression
        : primary
        | expression bop='.'
          (IDENTIFIER
          | THIS
          | NEW nonWildcardTypeArguments? innerCreator
          | SUPER superSuffix
          | explicitGenericInvocation
          )
        | expression '[' expression ']'
        | expression '(' expressionList? ')' // ***
    ...

    explicitGenericInvocation
        : nonWildcardTypeArguments explicitGenericInvocationSuffix
        ;
    ...

    nonWildcardTypeArguments
        : '<' typeList '>'
        ;

**Comment by KvanTTT** [comment]
Wrote the note in PR.

**Comment by pejobo** [comment]
fixed with #1037
