### ISSUE TITLE
Java: prefix and postfix operators (++ / --) not limited to variables

### ISSUE THREAD

**Issue by pejobo** [antlr/grammars-v4#1038]
The definition

    expression:
         <...>
         | expression postfix=('++' | '--')
         | prefix=('+'|'-'|'++'|'--') expression

also accepts code like `return 12++;` which does not comply to the JLS (see sections [15.15.1](https://docs.oracle.com/javase/specs/jls/se9/html/jls-15.html#jls-15.15.1), [15.15.2](https://docs.oracle.com/javase/specs/jls/se9/html/jls-15.html#jls-15.15.2), [15.14.2](https://docs.oracle.com/javase/specs/jls/se9/html/jls-15.html#jls-15.14.2), and [15.14.3](https://docs.oracle.com/javase/specs/jls/se9/html/jls-15.html#jls-15.14.3)). The java compile only accepts (numeric) variable references, so something like `IDENTIFIER postfix=('++' | '--')`.

There are some more issues like in the `expression` definition. Is this intentionally and should be handled by code using the produced grammar or do you accept pull requests making the grammar more restrictive?

**Comment by KvanTTT** [comment]
Yes, you can try to do the pull request.

**Comment by pejobo** [comment]
Okay, I assume that this is a major rework. Will it be okay if the `expression` rule is split into multiple rules?

How do you build test cases for non-parseable input? Any naming conventions to follow?

**Comment by KvanTTT** [comment]
> Will it be okay if the expression rule is split into multiple rules?

Is it possible just to replace `expression postfix=('++' | '--')` with `IDENTIFIER postfix=('++' | '--')`? Why multiple rules required?

> How do you build test cases for non-parseable input?

You can add a `file.java.error` file with expected errors for test data named `file.java`. See `three.g4` and `three.g4.errors` files in [antlr4 examples](https://github.com/antlr/grammars-v4/tree/master/antlr4/examples) directory.

> Any naming conventions to follow?

See [Grammar style](https://github.com/antlr/grammars-v4/blob/master/java/README.md#grammar-style) paragraph in README.md file in java directory.

**Comment by pejobo** [comment]
Thanks for your hints.

`IDENTIFIER postfix=('++' | '--')` is not sufficient. Here are some valid usages of the postfix increment operator:

     i++;
     intArray[0]++;
     this.i++;
     super.i++;
     my.package.MyClass.STATIC_FIELD++;
     something.returningAnArray()[0]++;
     something.returningAnObject().field++;

And I would also like to change the assignment rule, it considers e.g. `0 = 1` as a valid expression.

**Comment by pejobo** [comment]
> See [Grammar style](https://github.com/antlr/grammars-v4/blob/master/java/README.md#grammar-style) paragraph in README.md file in java directory.

The advice _Please use token names instead of literal names if possible and justified_ is often disrespected in the current grammar, at least for single character tokens.

**Comment by pejobo** [comment]
After some thinking about it I'm no longer sure that it is a good idea to change the grammar for this.

If you split the `expression` rule into e.g. `valueExpression` (everything which produces a value and may not appear on the left hand side of a java assignment, like a literal or a method call) and `assignable` (everything which may appear on the left hand side of an assignment, like a field or an indexed array access) you quickly realize that the 'natural' way of writing down an expression is to alternate between those two types:

     method().field.method2().field2 = value;

[_`method()` is not `assignable`, `method().field` is, `method().field().method2()` is not, but finally `method().field.method2().field2` is again, so the whole statement is correct_]

To satisfy ANTLR you have to duplicate rules (to not produce sets of rules which are mutually left-recursive). This blows up the grammar, and I'm not sure what this means for parsing performance.

@KvanTTT What's your opinion?

Another nasty and valid example for an allowed assignment in java:

        int a[] = new int[1];
        int b[];
        (b = a)[0] = 12;

**Comment by KvanTTT** [comment]
Yes, I think duplication rules are not a good idea.

**Comment by pejobo** [comment]
Ok, agree. I close this then.
