### ISSUE TITLE
javascript grammar does not support negative decimals, nor the Infinity symbol

### ISSUE THREAD

**Issue by alexkli** [antlr/grammars-v4#1039]
The [javascript](https://github.com/antlr/grammars-v4/tree/master/javascript) grammar, in particular the `DecimalInteger` rule, does not support negative decimals, nor the plus sign, which both are [supported in ES6](http://www.ecma-international.org/ecma-262/6.0/#sec-literals-numeric-literals):

```
var negative = -1;
var positive = +1;
```

Same for the special `Infinity`, with or without a sign (see [ES6 6.1.6](http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-language-types-number-type)):

```
var inf = Infinity;
var posinf = +Infinity;
var neginf = -Infinity;
```

**Comment by alexkli** [comment]
Here is a possible fix:

```
DecimalLiteral:                 UnsignedDecimalLiteral
              |                 '+' UnsignedDecimalLiteral
              |                 '-' UnsignedDecimalLiteral
              ;

UnsignedDecimalLiteral:         DecimalIntegerLiteral '.' [0-9]* ExponentPart?
                      |         '.' [0-9]+ ExponentPart?
                      |         DecimalIntegerLiteral ExponentPart?
                      ;
```

**Comment by alexkli** [comment]
Well, actually it seems the ES6 spec does not allow signs for literals in [section 11.8.3](http://www.ecma-international.org/ecma-262/6.0/#sec-literals-numeric-literals). My first spec link above was about the ToNumber string parsing syntax in [section 7.1.3.1](http://www.ecma-international.org/ecma-262/6.0/#sec-literals-numeric-literals), which is clearly a different thing.

However, browsers seem to support signs, [including negative hex or octal numbers](http://www.javascripter.net/faq/constant.htm), as well as the `Infinity` constant.

**Comment by KvanTTT** [comment]
Plus and minus operators are supported in [`singleExpression`](https://github.com/antlr/grammars-v4/blob/master/javascript/JavaScriptParser.g4#L284).

**Comment by alexkli** [comment]
You are right, my bad. Closing this issue again.

I was playing around with a stripped down grammar for a json-like subset, and I had `singleExpression` mostly commented out and missed that it covers the sign operators. Would be more intuitive to have them as part of the literal, but I guess that's how the language is structured anyway, even in the spec if I look at it again now.

Regarding `Infinity`, the [spec clearly says](http://www.ecma-international.org/ecma-262/6.0/#sec-tonumber-applied-to-the-string-type) it's not supported for number literals in the code (only for parsed strings using `ToNumber`:

> Infinity and –Infinity are recognized as a StringNumericLiteral but not as a NumericLiteral.

and the support in Browsers is likely an extension. Since this grammar is meant to be purely ES6 afaics, I think it's ok if it's not supported.
