### ISSUE TITLE
plsql: Invalid generated file PlSqlParser.py for Python3 target

### ISSUE THREAD

**Issue by bedorlan** [antlr/grammars-v4#1042]
```
$ java -jar antlr-4.7-complete.jar -Dlanguage=Python3 -no-listener -visitor plsql/*.g4
$ python3 plsql/PlSqlParser.py
  File "plsql/PlSqlParser.py", line 12112
    boolean version12=true;
                    ^
SyntaxError: invalid syntax
```
I think the line 25 in `PlSqlParser.g4` has something to do:
```
@members {boolean version12=true;}
```

**Comment by KvanTTT** [comment]
Just rewrite Java code fragments to Python code.

**Comment by bedorlan** [comment]
So this grammars are only for java? This should be clarified in the readme. Because a new user wont be able to work.

**Comment by kmillerdevx3** [comment]
This is a problem for *any* language that is not Java or does not have the "boolean" type. Yes, it's easy to fix (for many languages) but still annoying that the author has made significant assumptions about how the parser is used without stating those assumptions.

**Comment by KvanTTT** [comment]
@bedorlan you can this info by yourself.

**Comment by bedorlan** [comment]
@KvanTTT i don't understand you

**Comment by KvanTTT** [comment]
Ok, let's write about runtimes in the grammar description.

**Comment by KvanTTT** [comment]
I added `target-specific` label to this.
