### ISSUE TITLE
C grammar posfix expression problem

### ISSUE THREAD

**Issue by burfamur** [antlr/grammars-v4#1046]
Hi,

I am trying to get function calls in a c file.
For this i am looking for postfix expressions only.
(is this the correct way?). Some calls are not recognized
as postfix:

memset(abIv[0], 0);  --> recognized as postfix
memset(abIv[0]);  --> not recognized as postfix !!!
memset(&abIv[0]);  --> recognized as postfix

**Comment by burfamur** [comment]
Hi,
I dont know how issues are handled here.
Should i wait for someone to be assigned
for this issue?

**Comment by teverett** [comment]
The grammars are maintained on s strictly volunteer basis.  If someone choses to look at this issue, then they will, and hopefully they submit a PR.

**Comment by Marti2203** [comment]
Hi,
I just tested it out and the grammar catches all 3 as posffix expressions, so the issue can be closed.
