### ISSUE TITLE
ANTLR 4 C grammar cannot parse #include directive.

### ISSUE THREAD

**Issue by smwikipedia** [antlr/grammars-v4#1062]
I am trying to use the ANTLR C grammar to parse some UEFI C code.

I invoke the C grammar with the ANTLR TestRig:

`java org.antlr.v4.gui.TestRig C compilationUnit -tokens test.c`

The `test.c` contains below input:

```
#include <PiSmm.h>
#include <Protocol/SmmBase2.h>
#include <Library/SmmServicesTableLib.h>
#include <Library/DebugLib.h>
```

The grammar parsing gives these errors:

```
line 15:0 token recognition error at: '#i'
line 16:0 token recognition error at: '#i'
line 17:0 token recognition error at: '#i'
line 18:0 token recognition error at: '#i'
```

And btw, I noticed that in the `examples` folder for C grammar, there's no example that contains `#include` directive.

Or should the preprocessor handle this rather than the parser?

**Comment by teverett** [comment]
I believe this should be handled by the pre-parser.

**Comment by pflagerd** [comment]
Why then are pragmas, lines, and defines supported?  I suspect an accidental omission.

**Comment by pflagerd** [comment]
Consistent would be:

IncludeDirective
    :   '#' Whitespace? 'include' Whitespace ~[\r\n]*
        -> skip
    ;

Skipped, like all the other directives.

**Comment by lextm** [comment]
It is only a sample grammar, where #include lines are skipped due to `-> skip`.

You do have a few options to improve the grammar,

* Change `-> skip` to `-> channel(1)`  so such directives can be read from hidden channel.
* Or change this from a lexer rule to a parser rule (not quite obvious but I think doable).

Neither is trivial and requires familiarity on ANTLR.

**Comment by KvanTTT** [comment]
> Change -> skip to -> channel(1)

I recommend using `channel(HIDDEN)` instead of numeric arg.

**Comment by lextm** [comment]
@KvanTTT Right. Named channels can be better to remember.
