### ISSUE TITLE
"DIRECITVE" typo in ObjC ObjectiveCPreprocessorLexer

### ISSUE THREAD

**Issue by rloosemore** [antlr/grammars-v4#1068]
There are some typos of the word "DIRECTIVE" ... it is written "DIRECITVE".

See line 75 et seq in ObjectiveCPreprocessorLexer.g4

**Comment by teverett** [comment]
@rloosemore fair enough, however the spelling issue doesn't affect the operation of the grammar.  Feel free to submit a PR if you would like.

**Comment by rloosemore** [comment]
@teverett  Hey no problem, I was just being tidy :-)
