### ISSUE TITLE
plsql grammar: SELECT <field list> BULK COLLECT INTO ... not working

### ISSUE THREAD

**Issue by tnolli** [antlr/grammars-v4#1070]
Hi, first of all thanks for this great grammar.

I've noticed that statements like: `SELECT dummy BULK COLLECT INTO var FROM DUAL` are not working correctly.

`BULK` is considered to be a column alias for dummy and not part of the `into_clause`

I am not skilled enough in antlr to submit a fix to the grammar; at the minute I removed `BULK` from `non_reserved_keywords_pre12c` and it is working fine for my needs.

**Comment by KvanTTT** [comment]
Now it is being parsed without errors.
