### ISSUE TITLE
tsql: Token collision with column names

### ISSUE THREAD

**Issue by garymazz** [antlr/grammars-v4#1095]
I've had a few token collisions with column names, more specifically `DISK` and `URL`. 

Checking the tsql documentation, `DISK` and `URL` are not reserved words. Despite that fact, they are used explicitly in the `BACKUP` function.

**Comment by garymazz** [comment]
As a fix, which I don't like, but it works...

To TSqlLexer.g4:

Alter Token BACKUP:
from:
`BACKUP     'BACKUP';`

to:
`BACKUP     'BACKUP' -> pushMode(BackupTokens);`

And:
```
DISK:                                  'DISK';
TAPE:                                  'TAPE';
URL:                                   'URL';
```

Move following to EOF:
```antlr
mode BackupTokens;
DISK:                                  'DISK' -> popMode;
TAPE:                                  'TAPE' -> popMode;
URL:                                   'URL' -> popMode;

**Comment by garymazz** [comment]
Closed it accidently

**Comment by siggemannen** [comment]
I "fixed" this by adding them to list of "ok" keywords
