### ISSUE TITLE
CS0102	The type 'ANTLRv4Lexer' already contains a definition for 'Action'	Tool.Antlr	ANTLRv4Lexer.cs	157	

### ISSUE THREAD

**Issue by psllc** [antlr/grammars-v4#1102]
In a simple solution with the three antlr4 grammar files and the lexerAdapter... 

the generated ANTLRv4Lexer.cs file  contains `line 46) public const int Action = 2;` and `line 157) public override void Action(RuleContext _localctx, int ruleIndex, int actionIndex)`

the constant name conflicts with the method name...

**Comment by psllc** [comment]
i've 'fixed' this by renaming the lex mode 'Action' in ANTLRv4Lexer from 'Action' to 'LMAction'. i'm not sure yet if this has broken the grammar but it now compiles...

**Comment by KvanTTT** [comment]
I suggest name `ActionMode` or just `Action_`.

**Comment by psllc** [comment]
Thank you KvanTTT.  And thanks for adding the labels.  Sorry i overlooked this.  I did change the name, but opted for 'TargetAction' since, the particular lex mode is in fact for target language actions...

**Comment by psllc** [comment]
not sure if this is a result of this rename, but parsing this simple example: 

// define a grammar called Hello
grammar Hello;
r   : 'hello' ID;
ID  : [a-z]+ ;
WS  : [ \t\r\n]+ -> skip ;

fails with: 
line 3:8 mismatched input 'Hello' expecting {TOKEN_REF, RULE_REF}
line 4:0 mismatched input 'r' expecting {<EOF>, TOKEN_REF, RULE_REF, DOC_COMMENT, 'options', 'tokens', 'channels', 'import', 'fragment', 'protected', 'public', 'private', 'mode', AT}

parsing other more complex grammars (that build and operate as expected) also fails in the same manner...

**Comment by psllc** [comment]
didn't mean to close this. i realize the issue has probably not yet been resolved in the posted grammar. sorry.

**Comment by teverett** [comment]
Fixed and committed to master
