### ISSUE TITLE
tsql: identifier 'LANGUAGE' recognized as token

### ISSUE THREAD

**Issue by garymazz** [antlr/grammars-v4#1106]
I have a live database with a select statement including the token word `LANGUAGE` as a column name. The token  LANGUAGE disrupts select statement parsing.

```sql
SELECT 
    T1.C1,
    T1.LANGAUGE
FROM 
   T1
WHERE
     T1.C1 = T1.LANGAUGE
```

**Comment by garymazz** [comment]
A quick fix...

Add the token `LANGUAGE` to` rule simple_id`  in file TSqlParser.g4
````antlr
| LANGUAGE

**Comment by siggemannen** [comment]
This works now
