### ISSUE TITLE
MySql: not support lower case input stream of the examples

### ISSUE THREAD

**Issue by gundomcz** [antlr/grammars-v4#1121]
I try to  generate the grammar of mysql for Python3 like this:
```
    antlr4 -visitor -Dlanguage=Python3 MySqlLexer.g4 
    antlr4 -visitor -Dlanguage=Python3 MySqlParser.g4
```
But It return fail when I run with the examples, and the error message :
```
    input = FileStream(argv[1])
    lexer = MySqlLexer(input)
    stream = CommonTokenStream(lexer)
    parser = MySqlParser(stream)
    tree = parser.root()

    ./Example.py examples/ddl_create.sql 
line 3:16 extraneous input '_' expecting {, 'ALTER', 'ANALYZE', 'CALL', 'CHANGE', 'CHECK', 'CREATE', 'DELETE', 'DESC', 'DESCRIBE', 'DROP', 'EXPLAIN', 'GRANT', 'INSERT', 'KILL', 'LOAD', 'LOCK', 'OPTIMIZE', 'PURGE', 'RELEASE', 'RENAME', 'REPLACE', 'REVOKE', 'SELECT', 'SET', 'SHOW', 'UNLOCK', 'UPDATE', 'USE', 'BEGIN', 'BINLOG', 'CACHE', 'CHECKSUM', 'COMMIT', 'DEALLOCATE', 'DO', 'FLUSH', 'HANDLER', 'HELP', 'INSTALL', 'PREPARE', 'REPAIR', 'RESET', 'ROLLBACK', 'SAVEPOINT', 'START', 'STOP', 'TRUNCATE', 'UNINSTALL', 'XA', 'EXECUTE', 'SHUTDOWN', '--', '(', ';'}
line 3:27 no viable alternative at input '(like t1'
```
The problem is that I forgot to use case-insensitive input stream: https://github.com/antlr/antlr4/blob/master/doc/case-insensitive-lexing.md

And maybe it is better to add case-insensitive suport in the .g4 of MySql?

**Comment by ShenFeng312** [comment]
@KvanTTT  404 error https://github.com/antlr/antlr4/blob/master/doc/case-insensitive-lexing.md

**Comment by ShenFeng312** [comment]
> Hi. This page and instructions became outdated after releasing ANTLR 4.10. Please use [`caseInsensitive`](https://github.com/antlr/antlr4/blob/master/doc/options.md#caseinsensitive) option instead.

Can this work on java8?

**Comment by KvanTTT** [comment]
It might be but I'm not sure. See versions here: https://github.com/antlr/antlr4/releases
