### ISSUE TITLE
ANTLR 4 grammar not quite working (because of LexerAdapter?)

### ISSUE THREAD

**Issue by nikolayo** [antlr/grammars-v4#1122]
I tested the parser generated by the ANTLR 4 grammar on all grammars available in this project. Almost all were parsed successfully but for PhpLexer.g4 I got the following :

Parsing :/mnt/SSData/nikolay/Projects/niogen/src/test/resources/grammars/PhpLexer.g4

```
line 100:16 no viable alternative at input '['
line 100:37 mismatched input '(' expecting {BEGIN_ARGUMENT, 'options', 'returns', 'locals', 'throws', COLON, AT}
line 100:44 mismatched input ')' expecting {TOKEN_REF, RULE_REF, LEXER_CHAR_SET, STRING_LITERAL, BEGIN_ACTION, SEMI, LPAREN, OR, DOT, NOT}
```

The standard ANTLR 4 tool on the other hand parses the same file without a problem.

My suspicion is that the `LexerAdapter` is not quite working but I have not researched that in depth.

**Comment by nikolayo** [comment]
Apparently this got fixed somewhere along the way and does not occur anymore with a fresh fork of the repository.

**Comment by nikolayo** [comment]
There is still something fishy going on though. The lexer apparently refuses to recognize integers in Options mode even though it is supposed to:
```
grammar test;
options{k=3;}
tokens{A}
a : A;

results in:

[ Error ]test.g4:2:10 token recognition error at: '3'
[ Error ]test.g4:2:11 mismatched input ';' expecting {TOKEN_REF, RULE_REF, INT, STRING_LITERAL, BEGIN_ACTION}

```
The way I invoke the parser is:
```
 CharStream input = CharStreams.fromFileName(fileName);
 ANTLRv4Lexer parseTreeLexer = new ANTLRv4Lexer(input);
 CommonTokenStream tokens = new CommonTokenStream(parseTreeLexer);
 ANTLRv4Parser parseTreeParser = new ANTLRv4Parser(tokens);

```

**Comment by Marti2203** [comment]
Hello. I think this issue can be closed.
