### ISSUE TITLE
PlSql grammer : quotes inside quotes

### ISSUE THREAD

**Issue by nautilus-123** [antlr/grammars-v4#1129]
An assignment statement like below is not getting parsed

```sql
SQL_STMT := 'UPDATE EMP SET ENAME = 'LONG' WHERE EMPNO = :1
      RETURNING SAL INTO :2';
```

This is because of the rules below which do not allow quotes inside `CHAR_STRING`

```antlr
quoted_string
    : CHAR_STRING
    //| CHAR_STRING_PERL
    | NATIONAL_CHAR_STRING_LIT
    ;

CHAR_STRING: '\'' (~('\'' | '\r' | '\n') | '\'' '\'' | NEWLINE)* '\'';
```

**Comment by arpanraaj** [comment]
SQL_STMT := 'UPDATE EMP SET ENAME = ''LONG'' WHERE EMPNO = :1
      RETURNING SAL INTO :2';

This should work. Try this.

**Comment by nautilus-123** [comment]
Works fine with double quote inside single quotes
