### ISSUE TITLE
[JavaScript] Let declarations are not available outside of strict mode

### ISSUE THREAD

**Issue by rpelizzi** [antlr/grammars-v4#1138]
The lexer does not recognize `Let` tokens in non-strict mode. The purpose seems to be to recognize let as Identifier instead, so that they can be used in rules such as `var let = 1;`, which is only valid in non-strict mode.

But this has the unintended side effect of not allowing let declarations at all in non-strict mode! This simplest fix seems to be to make the lexer emit `StrictLet` and `NonStrictLet` tokens, and turn all appropriate `Identifier` references in the parser into references to a new `identifier` parser rule, which accepts `Identifier` and `NonStrictLet`. Then, the `keyword` and `varModifier` rules can accept both `NonStrictLet` and `StrictLet`.

**Comment by asadcr** [comment]
@KvanTTT @jsyeo Will this commit be merged ?. I have similar case.
