### ISSUE TITLE
Running Java8 Test doesn't work

### ISSUE THREAD

**Issue by Arminmsg** [antlr/grammars-v4#1143]
I get an error that `inspect` is not available in `java8/Test.java`

To fix it you need to change 
`tree.inspect(parser);` to `Trees.inspect(tree, parser);`

I can submit a pull request.

```
Error:(282, 37) java: cannot find symbol
  symbol:   method inspect(main.Java8Parser)
  location: variable t of type org.antlr.v4.runtime.ParserRuleContext
```

**Comment by teverett** [comment]
The PR would be welcome
