### ISSUE TITLE
mysql:get table and columns

### ISSUE THREAD

**Issue by z10one** [antlr/grammars-v4#1159]
Hi. I want to get table and columns from sql for mysql, but I don't have examples. Where can I get it?

**Comment by romber2001** [comment]
got the same problem, is there any document to tell us how to use this in python3?

**Comment by daikoz** [comment]
Use tool in https://github.com/daikoz/SQLWrapper

**Comment by imac-beep** [comment]
> Use tool in https://github.com/daikoz/SQLWrapper

Thx a lot. But is there a java port for this ?

**Comment by daikoz** [comment]
Hi,
It is in plan soon. I need just to create a XSLT for JAVA.
To do it quickly, you can help us to provide some sample.
Can you create an issue in:
[SQL Wrapper](https://github.com/daikoz/SQLWrapper)
to continue this discuss on appropriate topic.

**Comment by imac-beep** [comment]
> Hi,
> It is in plan soon. I need just to create a XSLT for JAVA.
> To do it quickly, you can help us to provide some sample.
> Can you create an issue in:
> [SQL Wrapper](https://github.com/daikoz/SQLWrapper)
> to continue this discuss on appropriate topic.

Sure I can create an issue in [SQL Wrapper](https://github.com/daikoz/SQLWrapper), and see how to provide the samples.
