### ISSUE TITLE
Powerbuilder grammar Issues

### ISSUE THREAD

**Issue by ramnar** [antlr/grammars-v4#1160]
The powerbuilder grammar for antlr4 in github is having issues
Couple of Issues which I noticed are

    PowerBuilder statements end with new line.But the grammar doesnt include this
    -datatype_decl rule in the grammar is not correct

**Comment by ramnar** [comment]
Reported the issue in antlr grammar

**Comment by vnvskumar** [comment]
Tom,

Thank you for porting Power Builder grammar. Lexar and Parser are generated, but while parsing the PB file, it gives lot of errors. Can you please help.
line 1:6 token recognition error at: 'x'
line 1:7 token recognition error at: 'p'
line 1:8 token recognition error at: 'or'
line 1:10 token recognition error at: 'tH'
line 1:12 token recognition error at: 'ea'
line 1:14 token recognition error at: 'de'
.
.
.
line 41:9 token recognition error at: 'l'
line 41:10 token recognition error at: '_'
line 41:11 token recognition error at: 'p'
line 41:12 token recognition error at: 'er'
line 41:14 token recognition error at: '_'
line 41:15 token recognition error at: 'i'
line 41:16 token recognition error at: 'd\r'
line 41:18 token recognition error at: '\n'
line 43:0 token recognition error at: 'en'
line 43:2 token recognition error at: 'd '
line 43:4 token recognition error at: 'function\r'
line 43:13 token recognition error at: '\n'





ine 41:9 token recognition error at: 'l'
line 41:10 token recognition error at: '_'
line 41:11 token recognition error at: 'p'
line 41:12 token recognition error at: 'er'
line 41:14 token recognition error at: '_'
line 41:15 token recognition error at: 'i'
line 41:16 token recognition error at: 'd\r'
line 41:18 token recognition error at: '\n'
line 43:0 token recognition error at: 'en'
line 43:2 token recognition error at: 'd '
line 43:4 token recognition error at: 'function\r'
line 43:13 token recognition error at: '\n'

Thank you

**Comment by teverett** [comment]
Can i pls see the file you're trying to parse?

**Comment by vnvskumar** [comment]
Thank you Tom, I sent the google drive link

Sri

**Comment by vnvskumar** [comment]
Tom, incase if you have a sample PB file to try it out can you pls share.

Thank you

**Comment by teverett** [comment]
Guys, with pr 1161 Ive made some changes that might help you.  That's the time I have for now and all I can do for you for now.

**Comment by vnvskumar** [comment]
Thanks a lot Tom.

Sri
