### ISSUE TITLE
Java grammar is not target agnostic

### ISSUE THREAD

**Issue by bdkearns** [antlr/grammars-v4#117]
The {Character.func} do not work on targets besides Java.
https://github.com/antlr/grammars-v4/blob/master/java/Java.g4#L983

Maybe something like what is documented here should be employed?
https://theantlrguy.atlassian.net/wiki/display/ANTLR4/Python+Target

2) The only production code absolutely required to sit with the grammar should be semantic predicates, like: `ID {$text.equals("test")}?`

Unfortunately, this is not portable, but you can work around it. The trick involves:
deriving your parser from a parser you provide, such as BaseParser
implementing utility methods in this BaseParser, such as "isEqualText"
adding a "self" field to the Java/C# BaseParser, and initialize it with "this"
Thanks to the above, you should be able to rewrite the above semantic predicate as follows:
`ID {$self.isEqualText($text,"test")}`?

**Comment by KvanTTT** [comment]
Try to use the new java grammar with language-specific code inserts.
