### ISSUE TITLE
Java8 Grammar doesn't support variadic arguments...

### ISSUE THREAD

**Issue by sunkin351** [antlr/grammars-v4#1194]
If someone could add this real fast, I'm using my application on production java code which uses variadic arguments and its throwing a NullReferenceException trying to access the last formal parameter.

**Comment by KvanTTT** [comment]
What grammar do you use? Formal [java8](https://github.com/antlr/grammars-v4/tree/master/java8) or fast [java](https://github.com/antlr/grammars-v4/tree/master/java)?

**Comment by sunkin351** [comment]
Java8

**Comment by KvanTTT** [comment]
No, it's a slow Java.

**Comment by racaljk** [comment]
it seems j8 grammar file contains the BNF rule of variadic parameter:
```antlr
methodDeclarator
	:	Identifier '(' formalParameterList? ')' dims?
	;

formalParameterList
	:	receiverParameter
	|	formalParameters ',' lastFormalParameter
	|	lastFormalParameter
	;

formalParameters
	:	formalParameter (',' formalParameter)*
	|	receiverParameter (',' formalParameter)*
	;

formalParameter
	:	variableModifier* unannType variableDeclaratorId
	;

variableModifier
	:	annotation
	|	'final'
	;

lastFormalParameter
	:	variableModifier* unannType annotation* '...' variableDeclaratorId
	|	formalParameter
	;

receiverParameter
	:	annotation* unannType (Identifier '.')? 'this'
	;

throws_
	:	'throws' exceptionTypeList
	;
```

**Comment by KvanTTT** [comment]
Is this issue still actual? Could you provide a code sample that doesn't work?

**Comment by Marti2203** [comment]
Is this issue still valid? @sunkin351  @KvanTTT from what i see, there was no response, nor any following message from anybody
