### ISSUE TITLE
Python Grammar for python target needs an update for new syntax

### ISSUE THREAD

**Issue by virresh** [antlr/grammars-v4#1201]
The current python grammar for python target cannot handle syntax like:
```python
variable = [{**{'name': bear}, **content} for bear, content in bears.items()]
```

Also it has `async` and `await` nodes missing

**Comment by KvanTTT** [comment]
What version of Python? 2 or 3?

**Comment by virresh** [comment]
[Python3 grammar for Python3 target](https://github.com/antlr/grammars-v4/tree/master/python3-py)

I replaced the rules from java grammar and they seem to [work fine](https://travis-ci.org/virresh/grammars-v4/builds/412075702?utm_source=github_status&utm_medium=notification). Don't know if that's the appropriate way to deal though.
