### ISSUE TITLE
PLSQL parser no support sql_plus?

### ISSUE THREAD

**Issue by JimKudo** [antlr/grammars-v4#1207]
my sql file has code as follows:

`spool D:\sale_20180814.log`

When I use plsqlparser to parser this sql file, there are some errors. Can plsqlparser.g4 support  'spool'?

**Comment by NormanDunbar** [comment]
`Spool` is not part of the pl/sql language. It is a command *specific* to the sqlplus utility, like `break`, `ttitle` (yes, with two 't's), `set`, etc.

There isn't a spool command in pl/sql.

HTH

Cheers,
Norm.
