### ISSUE TITLE
Memory Leak in JavaScript code that is generated by antlr java grammar

### ISSUE THREAD

**Issue by AkshayIyer12** [antlr/grammars-v4#1230]
I have attached the heap dump profile which can be loaded in chrome and viewed upon.
https://drive.google.com/file/d/1bnXRqTiy9NId4IWvqDGC8NZRtJ9woXBf/view?usp=sharing

The java grammar I had used is https://github.com/antlr/grammars-v4/tree/master/java

I tested on a nodejs server running on aws ec2 [t2 small] instance with 2GB RAM and single core.
I had bombarded the server using jmeter with 10000 concurrent users, Rampup period of 1second and loop count 1.

**Comment by KvanTTT** [comment]
What files did you try to parse? Could you attach them?

**Comment by AkshayIyer12** [comment]
@KvanTTT I had taken this file from ElasticSearch project. I have attached the same.
https://drive.google.com/file/d/130o0CFFqfzdqTY7eNOhhGGHZxBzFblzx/view?usp=sharing

**Comment by KvanTTT** [comment]
This issue doesn't relate to grammar itself, it's an issue about JavaScript ANTLR target.
