### ISSUE TITLE
MySQL Parser performance too bad

### ISSUE THREAD

**Issue by coanor** [antlr/grammars-v4#1231]
I have integrated a generated mysql parser (`antlr4 -Dlanguage=Go -o lexer MySqlLexer.g4 -o mysqlparser MySqlParser.g4 -package mysqlparser`) into my existing project, with some little complicated SQL like:

```sql
SELECT * FROM (
(SELECT p.id AS p_id,
  p.project_name as p_name,
  p.desc AS p_desc,
  COUNT(DISTINCT pa_0.account_id) AS p_account_sum,
  COUNT(DISTINCT pr.resource_id) AS p_resource_sum,
  p.network_id AS p_nwid,
  fp.`favourite` AS fp_p
FROM project AS p
LEFT JOIN project_account AS pa_0 on pa_0.project_id=p.id
LEFT JOIN project_resource AS pr ON (pr.project_id=p.id AND pr.status!=2)
LEFT JOIN favourite_project AS fp ON (fp.project_id=p.id and fp.account_id=pa_0.account_id)
GROUP BY p_id, p_name, p_desc, p_nwid, fp_p)
UNION
(SELECT p.id AS p_id,
  p.project_name AS p_name,
  p.desc AS p_desc,
  COUNT(DISTINCT pa_1.account_id) AS p_account_sum,
  COUNT(DISTINCT pr.resource_id) AS p_resource_sum,
  p.network_id AS p_nwid,
  fp.`favourite` AS fp_p
FROM project AS p
LEFT JOIN project_account AS pa_1 ON pa_1.project_id=p.id
LEFT JOIN project_resource AS pr ON (pr.project_id=p.id AND pr.status!=2)
INNER JOIN project_group AS pg ON pg.project_id=p.id
INNER JOIN `group` AS g on g.id=pg.group_id
INNER JOIN group_account AS ga ON ga.group_id=g.id
LEFT JOIN favourite_project AS fp ON (
  (fp.project_id=p.id and fp.account_id=pa_1.account_id) OR
  (fp.project_id=p.id and fp.account_id=ga.account_id)
  )

GROUP BY p_id, p_name, p_desc, p_nwid, fp_p)) T
GROUP BY p_id -- remove duplicated project ID
ORDER BY p_id DESC limit 0, 100;
```

I have benchmarked the run-time and CPU costs, it elapsed **24.797000 seconds** to parse the SQL (and the parse returns ok), during the parsing, the CPU got a 150% (Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz) and memory reach to %6 (total 8GB).  It's an _unacceptable_ performance in my existing project, why the parser eat so many resources during parsing?

And I tried case-sensitive and case-insensitive both, no performance difference founded between them. I have tested the SQLServer parser too, and the result is also unacceptable. 

---

UPDATE:
I run above bench under `go run test ...`.  When I parse the same SQL multiple (10) times, the first time, it consumes about 25 seconds, but the following 9 times, the time decreased to 4.6~4.9 seconds, why?

**Comment by KvanTTT** [comment]
Did you try Java or [C# optimized](https://github.com/tunnelvisionlabs/antlr4cs) runtime?

**Comment by coanor** [comment]
@KvanTTT :  Not yet, My existing project is Golang-base, I have Google some perf-related about ANTLR, it seems that we need to redefine some of the syntax to make the generated parser more faster.

**Comment by mike-lischke** [comment]
I don't know if this is related to the grammar or the target language, but the [grammar in MySQL Workbench](https://github.com/mysql/mysql-workbench/tree/8.0/library/parsers/grammars) with a C++ parser can process this statement in 172ms during the warm up phase and 2.6ms during all following runs. Just to give you a comparison.

**Comment by KvanTTT** [comment]
I also don't have problems with such SQL fragment with C# optimized runtime on the current [mysql](https://github.com/antlr/grammars-v4/tree/master/mysql) grammar in this repository. I think this is related to Go target performance problems.

**Comment by KvanTTT** [comment]
> I run above bench under go run test .... When I parse the same SQL multiple (10) times, the first time, it consumes about 25 seconds, but the following 9 times, the time decreased to 4.6~4.9 seconds, why?

Because ANTLR uses an internal cache for performance that is empty at the beginning.
