### ISSUE TITLE
Python3 Grammar: Comment at end of input causes "no viable alternative"

### ISSUE THREAD

**Issue by maiermic** [antlr/grammars-v4#124]
**input:**
```python
def func():
  return 42
  # comment
```
**parser reports error:**
```
line 3:11 no viable alternative at input '<EOF>'
```
**expected:**
no error
**my suggested solution:**
override `emitEof` and emit a NEWLINE and possibly more than 1 DEDENT token before calling `super.emitEof()`.

**Comment by bkiers** [comment]
@parrt, I think this one can be closed.

**Comment by maiermic** [comment]
Please reopen. My example leads to a similar error if you add a line break at the beginning:
**input:**
```python
# line break
def func():
  return 42
  # comment
```
**parser reports error:**
```
line 4:9 no viable alternative at input '<EOF>'
```
**expected:**
no error

**Comment by bkiers** [comment]
@maiermic probably (hopefully?) a similar solution exists. Will look into it and add some unit tests to cover both cases.

**Comment by bkiers** [comment]
Okay, this needn't be reopened since a new issue has been created.

**Comment by bkiers** [comment]
Got it: inside `nextToken()`, I thought `tokens.poll()` would always poll a `EOF` token. This is not correct. A fix (backed up by some extra unit tests in the original repo) will follow later today.
