### ISSUE TITLE
objc: two-step-processing/ObjectiveCPreprocessor.java won't compile

### ISSUE THREAD

**Issue by MurphysChaos** [antlr/grammars-v4#1263]
The pre-written `ObjectiveCPreprocessor.java` included with ObjC refers to a class that doesn't exist:

`ObjectiveCPreprocessor.java:12: error: cannot find symbol
public class ObjectiveCPreprocessor extends ObjectiveCPreprocessorParserBaseVisitor<String> {`

None of the code generated from the various `.g4` files produces such a symbol.

**Comment by Marti2203** [comment]
Hi,
The issue is that you need to give the flag -visitor. I think this issue can be closed as it is very old and fixable.
