### ISSUE TITLE
Java.g4: Arrays are not being recognized

### ISSUE THREAD

**Issue by bparadie** [antlr/grammars-v4#127]
Run this script:

``` bash
#!/bin/bash

LANG=Java
rm -f ${LANG}*.java ${LANG}*.class ${LANG}*.tokens
antlr4 ${LANG}.g4
javac -classpath /usr/local/Cellar/antlr/4.4/antlr-4.4-complete.jar:. ${LANG}*.java

cat <<EOF | grun ${LANG} compilationUnit -gui
public class Demo {
    public int[] intArray;
}
EOF
```

Note that `[]` of `int[]` are not recognized as array literals:

![java_tree](https://cloud.githubusercontent.com/assets/1578115/5332176/c97b2180-7e00-11e4-8d8e-4003f0cd3662.png)

In comparison this is the tree generated by `Java8.g4`:

![java8_tree](https://cloud.githubusercontent.com/assets/1578115/5332182/048270e4-7e01-11e4-9b9d-35e4935cd70c.png)

**Comment by KvanTTT** [comment]
I recommend to use Java8.g4 grammar instead Java.g4 one. Java grammar is not correct for annotation rules, which may cause to big performance issues.
