### ISSUE TITLE
EMCAScript.g4 parse "true || false && false" as "(true || false) && false"

### ISSUE THREAD

**Issue by yukoba** [antlr/grammars-v4#128]
Related to https://github.com/antlr/grammars-v4/issues/106.
EMCAScript.g4 parses ```true || false && false``` as ```(true || false) && false```.
This should be ```true || (false && false)```.

Also bit operators ```&```, ```^``` and ```|``` are wrong.
```1 | 0 & 0``` should be ```1 | (0 & 0)```.

**Comment by bkiers** [comment]
@parrt, I think this one can be closed.
