### ISSUE TITLE
partial fix for CPP14.g4 Stringliteral concatenation

### ISSUE THREAD

**Issue by Xyrio** [antlr/grammars-v4#1289]
this is correct code that fails with current grammar: `cout << "hello " "world";` 
example: https://ideone.com/aRPTIT

```
#include <iostream>
using namespace std;
 
int main() {
	//example a
	cout << "hello " "world" 
	"s" << endl;
	//example b
	cout << "hello " "world" \
	"s" << endl;
	return 0;
}
```

example a is not corrected but it should work too instead error is:
`line 9:26 token recognition error at: '\\r'`

i corrected example b like the following 
file CPP14.g4 line 2068:
before:
` | Stringliteral`
after:
` | Stringliteral+`

**Comment by teverett** [comment]
Please submit a PR

**Comment by teverett** [comment]
PR #1328
