### ISSUE TITLE
Different naming convention of file name and grammar name.

### ISSUE THREAD

**Issue by Dhiraj240** [antlr/grammars-v4#1290]
Here in [this](https://github.com/antlr/grammars-v4/blob/master/antlr4/ANTLRv4Lexer.PythonTarget.g4#L39) the name should be comparable to the file name i.e it should be ```ANTLRv4Lexer.PythonTarget``` instead of ```ANTLRv4Lexer```

**Comment by Dhiraj240** [comment]
I would love to send a PR on this.

**Comment by teverett** [comment]
go ahead and submit it.

**Comment by Dhiraj240** [comment]
Alright, going to do it.
