### ISSUE TITLE
TSql: Syntax checking

### ISSUE THREAD

**Issue by Dakado** [antlr/grammars-v4#1291]
First, I am sorry that I am writing this into issues, but I have no clue where else should I write it.

How should I use TSql parser from this collection ? I have generated .java classes but I have no idea how to use them, there are 3 billions of random methods, but I just need to check if the given string is correct TSQL or not. Any example please ?

Thanks.

**Comment by teverett** [comment]
Take a look at the example code here (https://github.com/teverett/antlr4example).

If the antlr parser can successfully parse the input file, then the input file is valid for the grammar.

**Comment by Dakado** [comment]
> Take a look at the example code here (https://github.com/teverett/antlr4example).
> 
> If the antlr parser can successfully parse the input file, then the input file is valid for the grammar.

Yes I have checked that out, but the method parser.equation() does not exist in my parser class.

**Comment by teverett** [comment]
Right, you need the start rule for tsql, which appears to be `tsql_file` so maybe try parser.tsql_file()

         /*
          * get the top node of the AST. This corresponds to the topmost rule of equation.q4, "equation"
          */
         EquationContext equationContext = parser.equation();

**Comment by Dakado** [comment]
I have managed to make it work, but with 0 documentation it was really hard, but this works:
`    public static void tsql(String args) {
        System.out.println("TSQL Check: " + args);
        CharStream stream = new ANTLRInputStream(args);
        TSqlLexer lexer = new TSqlLexer(stream);
        CommonTokenStream tokens = new CommonTokenStream(lexer);

        TSqlParser parser = new TSqlParser(tokens);

        parser.addErrorListener(new BaseErrorListener() {
            @Override
            public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol, int line, int pos, String msg, RecognitionException e) {
                System.out.println("Failed to parse at " + line + "," + pos + ":  " + msg);
                if (!msg.contains("<EOF>")) { //ANTRL BUG IGNORE IT 
                    mysqlresult = false;
                }
            }
        });

        parser.dml_clause().toStringTree(parser);
        //System.out.println(parser.dml_clause().toStringTree(parser));
        
        
        ParseTree tree = parser.dml_clause();
        ParseTreeWalker walker = new ParseTreeWalker();
        TSqlParserBaseListener listener = new TSqlParserBaseListener();
        ParseTreeWalker.DEFAULT.walk(listener, tree);
        
        System.out.println("TSQL Result: " + tsqlresult);
    }`
