### ISSUE TITLE
The clu.g4 file has some errors

### ISSUE THREAD

**Issue by Ebuka18** [antlr/grammars-v4#1294]
`warning(180): c:\Users\user\Desktop\ANTLR_Lingua\Grammars\Clu\clu.g4:278:11: chars '\'' used multiple times in set ['"']`
`warning(154): c:\Users\user\Desktop\ANTLR_Lingua\Grammars\Clu\clu.g4:39:0: rule procedure contains an optional block with at least one alternative that can match an empty string`
`warning(154): c:\Users\user\Desktop\ANTLR_Lingua\Grammars\Clu\clu.g4:43:0: rule iterator contains an optional block with at least one alternative that can match an empty string`
`warning(154): c:\Users\user\Desktop\ANTLR_Lingua\Grammars\Clu\clu.g4:47:0: rule cluster contains an optional block with at least one alternative that can match an empty string`
`error(119): c:\Users\user\Desktop\ANTLR_Lingua\Grammars\Clu\clu.g4::: The following sets of rules are mutually left-recursive [primary, invocation] and [expression] and [statement]`

**Comment by teverett** [comment]
@Ebuka18 yes,  this was noted in the readme.

https://github.com/antlr/grammars-v4/blob/master/clu/readme.txt

Pull requests are welcome
