### ISSUE TITLE
TSQL: Create function/procedure name cannot have server name and database name

### ISSUE THREAD

**Issue by dxingda** [antlr/grammars-v4#1295]
From MS document, [create function](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-function-transact-sql?view=sql-server-2017) and [create procedure](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-procedure-transact-sql?view=sql-server-2017), name cannot include server/database name.

```sql
func_proc_name
    : (database=id '.' (schema=id)? '.' | (schema=id) '.')? procedure=id
    | server=id '.' database=id '.' (schema=id)? '.' procedure=id
    ;
```

should be 

```sql
func_proc_name
    : ((schema=id) '.')? procedure=id
    ;
```

**Comment by siggemannen** [comment]
This is fixed =)
