### ISSUE TITLE
Cobol85 grammar

### ISSUE THREAD

**Issue by parikhabhi007** [antlr/grammars-v4#1298]
Hi @uwol, @teverett, @KvanTTT, @parrt and everyone,

I am trying to build the cobol85 grammar using the ANLTR4 and then test the generated parser. I was successfully able to get the java parser (.java) files but when I tried to compile using "javac", Cobol85Parser.java threw an error stating "UTF8 representation for the string at line 12 is too long for the constant pool". I am attaching a snapshot for the same. 

"Google" resources including Java documentation states that "A UTF-8 constant pool entry can be no more than 65535 bytes long." and there is no other way to avoid this error except for rectifying the buggy code. 

Please help me out to tackle this problem.

![antlr_cobol_error](https://user-images.githubusercontent.com/24873215/48691246-e8cd0580-ebf7-11e8-9d45-6acd62fb66c0.png)

**Comment by uwol** [comment]
The grammar is also used at the core of [ProLeap COBOL parser](https://github.com/uwol/proleap-cobol-parser) and compiling it with Java SE Development Kit 8 works well, even with a lot of additional Java classes for tests etc.
