### ISSUE TITLE
edif300 grammar

### ISSUE THREAD

**Issue by milesago** [antlr/grammars-v4#1307]
I am trying to use the edif300 grammar but it runs into problems straight away when generating in C++.

 
![image](https://user-images.githubusercontent.com/45823814/49876629-0ae72b80-fe24-11e8-8a8f-4d79e78492dc.png)

**Comment by teverett** [comment]
Try this and let us know if it works pls

https://github.com/teverett/grammars-v4/blob/master/edif300/EDIF300.g4

**Comment by milesago** [comment]
Yes that solves the problem, thanks.
