### ISSUE TITLE
Python3 Grammar: Unexpected indent not recognized

### ISSUE THREAD

**Issue by maiermic** [antlr/grammars-v4#133]
**input:**
```python
  def func():
  return 42
```
**parser reports:**
no error
**expected:**
An error message that indent before function definition is unexpected/extraneous.

**Comment by whitten** [comment]
I understand that you expect that the error message should be presented.
Is there something in the language standard or spec that supports your view
?

**Comment by maiermic** [comment]
I ran my example on the command line (Python 3.4.0):
```python
$ python my-example.py
  File "my-example.py", line 1
    def func():
    ^
IndentationError: unexpected indent
```

**Comment by whitten** [comment]
Is Python on the command line considered to be the reference server for
Python?
( I'm really asking because I don't know. I have no dog in this fight.)

I DO know making a grammar that is whitespace aware is harder than making
one
that ignores whitespace. This is probably going to require some tweaking of
the grammar,
possibly even intentionally putting a rule in to generate the error.

David

**Comment by bkiers** [comment]
When looking at the rule that is responsible for the creation of `INDENT` tokens, the `NEWLINE` rule, you can see that `INDENT` tokens are only created when the lexer "sees" a line break. Fixing it in the grammar would mean to use a predicate to check if we're at the start of the input stream followed by one or more spaces. 

At the moment it looks like:

```antlr
NEWLINE
 : ( '\r'? '\n' | '\r' ) SPACES?
   {
     ...
   }
 ;
```

and should be:

```antlr
NEWLINE
 : ( {atStartOfInput()}? SPACES
   | ( '\r'? '\n' | '\r' ) SPACES?
   )
   {
     ...
   }
 ;
```

where `atStartOfInput()` would look likt his:

```java
boolean atStartOfInput() {
  return super.getCharPositionInLine() == 0 && super.getLine() == 1;
}
```

Will make a PR later this day.

**Comment by bkiers** [comment]
I suppose this can be closed @parrt
