### ISSUE TITLE
PLSQL NULL conflict with macro in C++

### ISSUE THREAD

**Issue by brano543** [antlr/grammars-v4#1337]
Hello,

I am new to Antlr and I was trying to compile PlSqlLexer.g4 and PlSqlParser.g4, however this line in PlSqlLexer.g4
```
1123               NULL:                         'NULL';
```
results in generation of enum NULL = 1097 which conflicts with existing definition of NULL macro. I was able to fix it by changing this line to 
```
1123              NULLV:                         'NULL';
```
and replacing each occurence of NULL in PlSqlParser.g4 to NULLV. Would it be possible to fix this also in repository?

**Comment by teverett** [comment]
Would you be able to submit a PR for this change?

**Comment by KvanTTT** [comment]
Rename `NULL` to `NULL_`.
