### ISSUE TITLE
javascript grammar ClassCastException: class JavaScriptParser

### ISSUE THREAD

**Issue by javiertejedorm** [antlr/grammars-v4#1341]
Hello,

After installed ANTLR4 from the official website, I am executing the next steps and I am getting an exception:
```
cd grammars-v4/javascript
cp Java/* .
antlr4 JavaScriptLexer.g4
antlr4 JavaScriptParser.g4
javac *.java
grun JavaScriptParser program examples/ArrowFunctions.js -gui
```
```
Exception in thread "main" java.lang.ClassCastException: class JavaScriptParser
	at java.base/java.lang.Class.asSubclass(Class.java:3593)
	at org.antlr.v4.gui.TestRig.process(TestRig.java:135)
	at org.antlr.v4.gui.TestRig.main(TestRig.java:119)
```

Is it possible to test it with _grun_? Am I doing something wrong?

Thanks,
Regards.

**Comment by teverett** [comment]
Perhaps take a look at the example here:

https://github.com/teverett/antlr4example

**Comment by LanceZhu** [comment]
I use `grun JavaScript program examples/ArrowFunctions.js -gui`.  It works fine.

**Comment by gabriel-fallen** [comment]
Related to this: https://github.com/antlr/antlr4/issues/859

`grun JavaScript program <file path>` solves the issue as @LanceZhu wrote above.

I suggest to close as solved.
