### ISSUE TITLE
Srict misspell in javascript grammar

### ISSUE THREAD

**Issue by BlackGad** [antlr/grammars-v4#1345]
Lexer utility method missplelling

https://github.com/antlr/grammars-v4/blob/master/javascript/JavaScriptLexer.g4

```
'implements' {this.IsSrictMode()}?;
```
and so one

**Comment by KvanTTT** [comment]
What exactly do you mean? `implements` keyword exists in JacaScript spec: https://tc39.github.io/ecma262/#sec-future-reserved-words

**Comment by BlackGad** [comment]
this.IsSrictMode() -> this.IsS**T**rictMode()

**Comment by KvanTTT** [comment]
Ok, thanks :)
