### ISSUE TITLE
CPP unexpected behavior with >>= (rightshiftassign)

### ISSUE THREAD

**Issue by 4br3mm0rd** [antlr/grammars-v4#1348]
Hi,

I am trying to parse the following piece of code (extracted from a big file and made a bit clearer) with the CPP grammar:
`int func(){
    for (int d = 100; a() - b() < c; c >>= 1)
        --d;
}`

I get the following errors:
`line 2:39 mismatched input '>' expecting {')', '^', '&', '|', '==', '!=', '&&', '||', ','}
line 2:44 mismatched input ')' expecting {')', '^', '&', '|', '==', '!=', '&&', '||', ','}`

It seems like there is a problem handling the rightshift and the rightshiftassign here... Do you know how it could be handled?

Thank you!

**Comment by oxisto** [comment]
I've encountered that problem as well. It seems to stem from the following line:
```
   rightShift
      :
      //'>>' Greater Greater
      ;
```

Not sure, why this line is commented out. This also has some weird effects like qualified ids like std::string being recognised as shift expressions. I've fixed that in my own code where I use the grammar, I can try to bringt together a PR to fix that.

**Comment by Marti2203** [comment]
I think this can be closed
