### ISSUE TITLE
Cannot find tokens file

### ISSUE THREAD

**Issue by jannavarro** [antlr/grammars-v4#1351]
I am following this [ANTLR4 tutorial for C#](https://github.com/antlr/antlr4/tree/master/runtime/CSharp) and in step 4 I run the ANTLR java file in the C# grammar file I downloaded in your Github (grammars-v4/csharp/).
`java -jar antlr4-4.7.2.jar -Dlanguage=CSharp CSharpParser.g4`

The result is an error looking for tokens file: error(114): CSharpParser.g4:7:21: cannot find tokens file .\CSharpLexer.tokens

I am quite new to Antlr. Is this token file something I can get somewhere else?

**Comment by KvanTTT** [comment]
Firstly you should generate tokens file by command `java -jar antlr4-4.7.2.jar -Dlanguage=CSharp CSharpLexer.g4`

**Comment by matthew-dean** [comment]
@KvanTTT This doesn't work. I've tried a variety of languages, including CSharp and `.tokens` files are never generated.

**Comment by shyandsy** [comment]
i still get the error with "java.nio.file.NoSuchFileException: tokens" 
anyone knows why?
![image](https://github.com/antlr/grammars-v4/assets/5271457/eaefe869-d981-4e7e-b94e-48aecd02bbc7)
