### ISSUE TITLE
cpp14 does not handle nested namespaces

### ISSUE THREAD

**Issue by skelter** [antlr/grammars-v4#1365]
given the file namespaced_class.cpp

```cpp
namespace nsA {
  namespace nsB {
    // declare MyClass
    class MyClass {
      int i;
    };
  }
}
```

The grammar should parse.  Instead, it throws errors.

```
Parsing :/home/skelter/work/grammars-v4/cpp/examples/namespaced_class.cpp
line 6:2 no viable alternative at input 'namespacensA{namespacensB{classMyClass{inti;}}'
line 2:16 mismatched input '{' expecting '='
line 3:18 mismatched input '{' expecting {'decltype', 'operator', '(', '*', '&', '~', '&&', '::', ';', '...', Identifier}
com.khubla.antlr.antlr4test.AssertErrorsException: found 3 errors, but missing file namespaced_class.cpp.errors
```

**Comment by skelter** [comment]
thanks for the label.  I'll be working on it [here](https://github.com/skelter/grammars-v4/tree/bug-1365)

**Comment by skelter** [comment]
I am seeing this work on one machine.  Huh.

**Comment by skelter** [comment]
Seems to work as of 0c07bb11ec58f61f65e58f7148916d64388e4f0e. 
We can close this.  I'll re-open if I see it again.

**Comment by hristo-vrigazov** [comment]
@skelter I am having the exact same issue. How did you solve it?

**Comment by skelter** [comment]
@hristo-vrigazov I was unable to repro it on the HEAD of master, but had to go back to 0c07bb1.  I was using the simple class described above.  Does that break for you?  Are you running it by dropping your .h or .cpp file in the /examples dir and running 
mvn clean test?

**Comment by skelter** [comment]
@hristo-vrigazov I have to other files that show the grammar breaking on the branch I reference for issue-1050.
