### ISSUE TITLE
TSQL: Parse error when IDs with lowercase

### ISSUE THREAD

**Issue by zy735537** [antlr/grammars-v4#1367]

**Comment by zy735537** [comment]
I got error when pasering following scripts:
```
USE AdventureWorks2012;
GO
SELECT Name, ProductNumber, ListPrice AS Price
FROM Production.Product 
ORDER BY Name ASC;
GO
```
![grammarissue01](https://user-images.githubusercontent.com/27133454/52623778-16b8a200-2ee8-11e9-9a9b-eb6b20bd7d75.png)

Check into TSqlLexer.g4, I found ID definition (line 829) chaned ([a-z] removed). Doesn't support lowercase names, or I'm wrong?
ID:                  ( [A-Z_#] | FullWidthLetter) ( [A-Z_#$@0-9] | FullWidthLetter )*;

**Comment by KvanTTT** [comment]
It's a duplicate. Please take a look at https://github.com/antlr/antlr4/blob/master/doc/case-insensitive-lexing.md

**Comment by zy735537** [comment]
@KvanTTT, thank you very much for the information and effort you took .

I aslo take a look about your [disucssions ](https://github.com/antlr/antlr4/pull/2046). In my opinion that to support case insensitive/sensitive by grammars grammars is better than use standalone CaseChangingCharStream class that implemented by each languages.

Anyway, I respect the decision made by you guys.
