### ISSUE TITLE
TSQL: Parse error when all the select statments of UNION include order by clause

### ISSUE THREAD

**Issue by zy735537** [antlr/grammars-v4#1368]
```sql
SELECT top(1) 'first' AS which, number
        FROM @numbers
        ORDER BY number ASC
        UNION ALL
        SELECT top(1) 'last', number
        FROM @numbers
        ORDER BY number DESC
```

**Comment by zy735537** [comment]
I have a solution as below. But my concern is conflict with the syntax on [Microsoft offical doc](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-transact-sql?view=sql-server-2017) 
#1. Remove order_by_clause from[select_statement]:
`select_statement
    : with_expression? query_expression /*order_by_clause?*/ for_clause? option_clause? ';'?
    ;`
#2. Add order_by_clause to [query_specification]:
`query_specification
    : SELECT (ALL | DISTINCT)? top_clause?
      select_list
      // https://msdn.microsoft.com/en-us/library/ms188029.aspx
      (INTO table=table_source_item)?
      (FROM table_sources)?
    pivot_unpivot?
      (WHERE where=search_condition)?
      // https://msdn.microsoft.com/en-us/library/ms177673.aspx
      (GROUP BY (ALL)? group_by_item (',' group_by_item)*)?
      (HAVING having=search_condition)?
      order_by_clause?
    ;`

**Comment by brikken** [comment]
Your initial expression is illegal. Below query runs, but only if you do not include the first ORDER BY
```
with dummy as (select * from (values (1), (2), (3)) d(a))
select * from dummy
--order by a -- adding this will cause a syntax error
union all
select * from dummy
order by a
```
The [documentation](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-transact-sql?view=sql-server-2017) pretty clearly states that a SELECT has exactly one query_expression, which in turn can contain an arbitrary number of query_specification separated by UNION, followed by at most one ORDER BY.
The order_by_clause does belong to the select_statement.
```
<SELECT statement> ::=    
    [ WITH { [ XMLNAMESPACES ,] [ <common_table_expression> [,...n] ] } ]  
    <query_expression>   
    [ ORDER BY { order_by_expression | column_position [ ASC | DESC ] }   
  [ ,...n ] ]   
    [ <FOR Clause>]   
    [ OPTION ( <query_hint> [ ,...n ] ) ]   
<query_expression> ::=   
    { <query_specification> | ( <query_expression> ) }   
    [  { UNION [ ALL ] | EXCEPT | INTERSECT }  
        <query_specification> | ( <query_expression> ) [...n ] ]   
<query_specification> ::=   
SELECT [ ALL | DISTINCT ]   
    [TOP ( expression ) [PERCENT] [ WITH TIES ] ]   
    < select_list >   
    [ INTO new_table ]   
    [ FROM { <table_source> } [ ,...n ] ]   
    [ WHERE <search_condition> ]   
    [ <GROUP BY> ]   
    [ HAVING < search_condition > ]   
```

**Comment by brikken** [comment]
I suggest this issue is closed
