### ISSUE TITLE
ANTLR4 stops parsing in the middle of the code, because it expects EOF

### ISSUE THREAD

**Issue by YugoCode** [antlr/grammars-v4#1369]
I'm using ANTLR to parse all function names defined in a C++ file. 

While using the latest grammar (_CPP14.g4_), I got many errors parsing this file: https://android.googlesource.com/platform/system/bt/+/master/stack/avrc/avrc_api.cc

This are the errors:
```
line 517:10 token recognition error at: '"Received a CONTINUE/END without no corresponding START \\n'
line 518:77 token recognition error at: '");\n'
line 519:19 no viable alternative at input 'if(pkt_type!=AVRC_PKT_SINGLE&&cr==AVCT_RSP){if(pkt_type==AVRC_PKT_START){p_rcb->rasm_pdu=*p_data;p_rcb->p_rmsg=(BT_HDR*)osi_malloc(BT_DEFAULT_BUFFER_SIZE);memcpy(p_rcb->p_rmsg,p_pkt,sizeof(BT_HDR));memcpy((uint8_t*)(p_rcb->p_rmsg+1),(uint8_t*)(p_pkt+1)+p_pkt->offset,p_pkt->len);p_rcb->p_rmsg->offset=p_rcb->rasm_offset=0;osi_free(p_pkt);*pp_pkt=p_rcb->p_rmsg;p_rcb->p_rmsg->offset+=p_rcb->p_rmsg->len;req_continue=true;}elseif(p_rcb->p_rmsg==NULL){AVRC_TRACE_DEBUG((orpreviousfragmentedresponsewasdropped)drop_code=5;'
line 484:53 missing ';' at '{'
line 519:19 no viable alternative at input 'if(p_rcb->p_rmsg==NULL){AVRC_TRACE_DEBUG((orpreviousfragmentedresponsewasdropped)drop_code=5;'
line 513:38 missing ';' at '{'
line 519:19 no viable alternative at input 'AVRC_TRACE_DEBUG((orpreviousfragmentedresponsewasdropped)drop_code=5;'
line 522:6 mismatched input 'else' expecting '}'
line 573:2 mismatched input 'if' expecting <EOF>
```

I can detect all the functions defined until line 573, but all following functions are not detected.

The first two errors are based on a multiline string:

```
      AVRC_TRACE_DEBUG(
          "Received a CONTINUE/END without no corresponding START \
                                (or previous fragmented response was dropped)");
```

Can someone help with fixing this and the other errors? 

Or would it be a better idea to use a different grammar, since I only want to parse function names? I could remove all the parts of the grammar, which are not related to functions.

___ 
Here is the file: [avrc_api.cc.zip](https://github.com/antlr/grammars-v4/files/2859631/avrc_api.cc.zip)

**Comment by Marti2203** [comment]
Hi,
I just tested this file. It parses without any issues.
