### ISSUE TITLE
Dart2 Golang  compiler conflict resolved

### ISSUE THREAD

**Issue by innomon** [antlr/grammars-v4#1390]
The `Dart2.g4` code generated for go, using the command : `antlr4 -Dlanguage=Go Dart2.g4` failed. with  errors; all pertaining  to:
 `error(134): symbol type conflicts with generated code in target language or runtime` 
Since golang as a `type` and a keyword there was a conflict.
this was resolved by replacing `type` by `dtype` in the fille, `Dart2.g4`

Next, the generated code was not being compiled. This was due to the error:
`dart2_parser.go:11748:6: NewExpressionContext redeclared in this block`
This error was due to `newExpression` inside `Dart2.g4`. It was resolved by renaming the variable.

**Comment by innomon** [comment]
I solved this issue, but wanted to flag it for other developers.

**Comment by teverett** [comment]
Could you submit a PR with your fixes?
