### ISSUE TITLE
Mysql: some keyword are mising in Parser keywordsCanBeId

### ISSUE THREAD

**Issue by mrozieres** [antlr/grammars-v4#1395]
Actually some keywords in the paragraph commented as "Keywords, but can be ID" from the lexer are missing into the keywordsCanBeId list of the parser.

**Comment by mrozieres** [comment]
I made a pull request for this issue : #1396

**Comment by Naros** [comment]
Can this be closed, looks like PR #1396 was merged?

**Comment by mrozieres** [comment]
@Naros thanks for the update on the issue. I am closing it.
