### ISSUE TITLE
Antlr4 c grammar not skipping #include directive.

### ISSUE THREAD

**Issue by pflagerd** [antlr/grammars-v4#1398]
All the other preprocessor directives are skipped. Why don't skip `#includes` too?

```antlr
IncludeDirective
    :   '#' Whitespace? 'include' Whitespace ~[\r\n]*
        -> skip
    ;
```

**Comment by Marti2203** [comment]
First of all, I do not think this is the proper way to define #include.
Why not
```
IncludeDirective
    :   '#' Whitespace? 'include' ('"' .*? '"' | '<' .*? '>' ) NewLine
        -> skip
    ;

```
Maybe this will work?

**Comment by teverett** [comment]
Does it pass the tests?

**Comment by Marti2203** [comment]
I do not know, I have not tested, I just gave an example, but I can test it if you want to.

**Comment by teverett** [comment]
Sure.  let's test it and do a PR.

**Comment by Marti2203** [comment]
Okay, first the PR I am doing and after that this.

**Comment by Marti2203** [comment]
#1413 I just added the directive and tested it. It works on a test, but let us see on the test cases( which may not check #includes).

**Comment by Marti2203** [comment]
Hi @pflagerd , this issue can be closed.
