### ISSUE TITLE
cpp14 parsing error for raw string literal

### ISSUE THREAD

**Issue by zonggit** [antlr/grammars-v4#1400]
This is the cpp code `string a = R"(123)\")";`

Use below java code to get tokens:

```java
CPP14Lexer lexer = new CPP14Lexer(CharStreams.fromString(content));
CommonTokenStream stream = new CommonTokenStream(lexer);
stream.fill();
List<Token> tokens = stream.getTokens();
```

the result is:

![20190423](https://user-images.githubusercontent.com/19405663/56587320-e42bd380-6613-11e9-9a32-6cc829078bbb.jpg)

the string `R"(123)\")"` recognized two tokens, how to fix this error?

2.
parse below string:
`string eee = "123\`
`               456";`
throw error: **token recognition error at: '"123\\n'**
3.
`/*abcd*/`
can not parse as comments

**Comment by Marti2203** [comment]
Hi,
I understood issue one. Can you elaborate for 2. and 3.?
