### ISSUE TITLE
PHP Island Grammar & Switch-Case Not Working

### ISSUE THREAD

**Issue by vincenthend** [antlr/grammars-v4#1404]
I have issues when using island code features in PHP. It doesn't seem to detect the PHP close tag (`?>`) preventing me to switch to HTML context. Furthermore, it doesn't detect switch-case's `default` as a SwitchBlock

I use intelliJ's ANTLR plugin to generate the code

![image](https://user-images.githubusercontent.com/23435348/56867694-7f58ea80-6a12-11e9-90d1-6f5a8c5a56d8.png)
![image](https://user-images.githubusercontent.com/23435348/56867714-c050ff00-6a12-11e9-93b7-6bc1e8e29a5c.png)

**Comment by KvanTTT** [comment]
Semantic predicates are used in PHP lexer. Maybe they don't work properly with the IDEA plugin.

**Comment by bjansen** [comment]
The IntelliJ plugin does not use the generated lexer and parser in the Preview window, which means that `PhpBaseLexer` will never be run to handle `PHPEnd` as expected.
