### ISSUE TITLE
How to generate Mysql grammar tree by grun

### ISSUE THREAD

**Issue by AstroMen** [antlr/grammars-v4#1412]
I create a file named grun.sh including "java org.antlr.v4.gui.TestRig $*" and set grun as a command to system env.
After I generate .java of Lexer and Parser, I compile them using javac *.java
I want to generate by grun -tree as below:
grun GrammarName startRuleName
![image](https://user-images.githubusercontent.com/10647454/58150484-53d7c180-7c99-11e9-8902-1c04e90451e5.png)

However, I am not clear which rule name I could use to replace startRuleName.
Also, there are two .g4 file, MySqlLexer.g4 and MySqlParser.g4, how to compile them by manually. Is there any sequence?

Thanks.

**Comment by Marti2203** [comment]
Grun uses the parser rules to generate a tree. I think you should use "root" as I see that it is the topmost rule in MySqlParser.g4

**Comment by KvanTTT** [comment]
Have you resolved your issue eventually?

**Comment by AstroMen** [comment]
@KvanTTT Yeah, I used my IDE to generate it.
