### ISSUE TITLE
Improve and fix Golang grammar

### ISSUE THREAD

**Issue by KvanTTT** [antlr/grammars-v4#1423]
In progress. Follow the repo and link for tracking: https://github.com/PositiveTechnologies/grammars-v4/tree/GoLangRefactoring/golang

**Comment by ssst0n3** [comment]
will this repo will replace the version in master branch?
The issue(https://github.com/antlr/grammars-v4/issues/1056) that Golang.m4 cannot be build to go language is ridiculous. And i see this repo has no embeded JAVA code.

By the way, why we need a antlr version golang grammar? Go can generate AST by itself. What the advantage of antlr in go language?

**Comment by studentmain** [comment]
> By the way, why we need a antlr version golang grammar?

On the other hand, why not? With this, we can generate Go AST, for example, in browser. Of course, it's not fast as native parser, but it works.

Not only a language itself, if you need design your own language, an existing grammar file is a good reference.

**Comment by KvanTTT** [comment]
> Will this repo replace the version in master branch?

I hope. I'll make a pull request when it has been completed.
