### ISSUE TITLE
[JavaScript] doesn't detect an unclosed string

### ISSUE THREAD

**Issue by cajetaneducode** [antlr/grammars-v4#1449]
Hello,

The JavaScript parser is returning an IdentifierExpresionContext when I try to parse a JavaScript string that doesn't have an opening or a closing quote (double / single).

This would be the most basic example to try it with.
```JavaScript
var x = "myString;
```

Here is another example where I try to parse a string argument:
```JavaScript
puck.create(2, 11, "circle);
goal.create(23, 11);
```

The same result happens when there is no opening quotes:
```JavaScript
puck.create(2, 11, circle');
goal.create(23, 11);
```

I've looked into the JavaScriptLexer.g4 file but this goes way beyond my expertise.

StringLiteral are defines as such:

```
StringLiteral:      ('"' DoubleStringCharacter* '"'
             |       '\'' SingleStringCharacter* '\'') {this.ProcessStringLiteral();}
             ;
```

And the frapment rule is
```
fragment DoubleStringCharacter
    : ~["\\\r\n]
    | '\\' EscapeSequence
    | LineContinuation
    ;
```

Let me know if I can help you with more information. I'm just not sure where to go from here.

**Comment by studentmain** [comment]
> a JavaScript string that doesn't have an opening or a closing quote

Any standard or draft about this? I remember that JS has no such feature.

**Comment by cajetaneducode** [comment]
> Any standard or draft about this? I remember that JS has no such feature.

Sorry my English might not have been quite perfect. By quote I mean the symbol " (ascii 34) or the symbol ' (ascii 39)

From my understanding of the standard (found here: http://ecma-international.org/ecma-262/9.0/index.html#sec-literals-string-literals)
> A string literal is zero or more Unicode code points enclosed in single or double quotes.

A string must be surrounded by a pair of single/double quotes to be valid.


On another note, I've continued searching why it would do this and it seems that the lexer is a greedy algorithm and it will match as much as it can and ignore what couldn't be match (in this case an "extra" quote). I don't know enough (yet) about Lexers and Parsers to find if it's by design.
(Source: https://stackoverflow.com/questions/24557953/handling-string-literals-which-end-in-an-escaped-quote-in-antlr4). 

For now I will create a small validator to make sure strings are properly closed before sending it to the Lexer.

Once again, if I may help you with more information, let me know.

**Comment by studentmain** [comment]
So you mean javascript.g4 doesn't report an error for illegal string literal?

**Comment by cajetaneducode** [comment]
that's correct. 

Although I don't know if the error should be reported by the _ JavaScriptLexer.g4_ or the _JavaScriptParser.g4_ file.

**Comment by studentmain** [comment]
Use grun's -token flag to show tokens output by lexer. Problem might be here.

**Comment by studentmain** [comment]
Seems lexer just works...
```
func(1,2,"str);
[@0,0:3='func',<Identifier>,1:0]
[@1,4:4='(',<'('>,1:4]
[@2,5:5='1',<DecimalLiteral>,1:5]
[@3,6:6=',',<','>,1:6]
[@4,7:7='2',<DecimalLiteral>,1:7]
[@5,8:8=',',<','>,1:8]
[@6,9:9='"',<UnexpectedCharacter>,channel=2,1:9]
[@7,10:12='str',<Identifier>,1:10]
[@8,13:13=')',<')'>,1:13]
[@9,14:14=';',<';'>,1:14]
[@10,15:15='\n',<LineTerminator>,channel=1,1:15]
[@11,16:15='<EOF>',<EOF>,2:0]
```
Note that UnexpectedCharacter is in channel 2. Maybe you (or we, I'm not sure it is an expected behavior) need check it after lexer finish it's work.
https://github.com/antlr/grammars-v4/blob/08224bb3ab8a1c13f712b1c8ff46b5732c6aa267/javascript/JavaScriptLexer.g4#L186

**Comment by cajetaneducode** [comment]
Thank you so much for your help. 

I didn't knew to look in other channels for this. I confirm that I'm able to detect the _UnexpectedCharacter_ on the channel 2.

I guess we can close this as it's not a bug after all.
