### ISSUE TITLE
Code too large for try statement

### ISSUE THREAD

**Issue by rojaster** [antlr/grammars-v4#145]
I have a big rule for keywords - over 817 keywords, and when i compiled *java files Parser file crashed:

error: code too large for try statement
                catch (RecognitionException re) {
                ^

I found a solution to my code when identifier could be a keyword and have created a rule, example : 
identifier: [a-zA-Z]+ | keyword;

And when i looked into parser source i have saw that all keywords were inserted into code 'as is', what's wrong with my approach?

**Comment by rojaster** [comment]
may be i should rewrite this code to create a set , not just switch\case?

**Comment by parrt** [comment]
You must have some kind of huge list of keywords inside your parser, although you didn't specify.  Wrap keywords in a set like (A|B|C) without actions or anything else that could make it look anything like a set and it will collapse it from a switch to a set test.
