### ISSUE TITLE
New Grammar Request (or implementation help): Paradox scripting 

### ISSUE THREAD

**Issue by ReikaKalseki** [antlr/grammars-v4#1453]
Specifically the kind used for scripting things like events in their games like Stellaris. A sample of what that kind of code looks like can be found here:

https://github.com/ReikaKalseki/Alerans/blob/master/events/ongoing_events.txt#L1379-L1457

It is fairly similar to nested Lua table specification, but there are a few key differences, notably the fact that "left hand side" terms are often not keys but "scope changes" (eg "prev", "from", "every_owned_pop", or "solar_system") or logical operators (eg NOR); the right hand side is sometimes a value (like for id or show_sound) but more often part of code.

`#` denotes a comment from that character to the end of the line, much like `//` or `--` do in Java and Lua respectively.

I would try to implement this myself, probably by adapting the Lua one, but I have no idea whatsoever how to go about doing that, and have no understanding of regex to even enable me to try.

**Comment by studentmain** [comment]
Need more test, hope it will help.

```antlr
grammar paradox;

Comment: '#' ~[\r\n]* -> channel(HIDDEN);
Space: [ \t\f] -> channel(HIDDEN);
Newline: [\r\n] -> channel(HIDDEN);

content: expr*;
expr: key ('=' | '>' | '<') val;
key: id | attrib;
val: id | attrib | group;
attrib: id accessor (attrib| id);
accessor: '.'|'@'|':';
group: '{' (expr* | id) '}';
id: Identifier | String | Integer;

Identifier: IdentifierHead IdentifierBody*;
Integer: [+-]? IntegerFrag;
fragment IntegerFrag: [0-9]+;
fragment IdentifierHead: [a-zA-Z];
fragment IdentifierBody: IdentifierHead | [0-9_];
String: '"' ~["\r\n]* '"';
```

**Comment by teverett** [comment]
PR here

stellaris #1558

Feel free to update/edit/comment, etc.

@studentmain  thanks for the grammar

**Comment by ReikaKalseki** [comment]
I am going to try this out on my own files in the near future.
