### ISSUE TITLE
JavaScript grammar to get Javascript method counter

### ISSUE THREAD

**Issue by msriki12** [antlr/grammars-v4#1455]
Hello, this is my very first approach to ANTLR, I worked with it for a very simple Java Parser but I took all from an internet example. 

I actually work with JavaScript, and I want to make a graph with all function declarations and function calls on my libraries. I took the JavaScript example and it works but it shows me all token names of all characters of my code. I need only a list of functions in a console.log, and if is possible I want a count of them. I don't know how to edit .g4 to add javascript code, and I can't understand all JavaScriptLexer.js and JavaScriptParser.js code (+7000lines). I need to know how to do this with the grammar example. I'm using NodeJS to build a program that reads a piece of code and returns me a tree.toStringTree(parser.ruleNames) with all token names in my code.

This is my index.js program:

```js
const fs = require('fs');
const antlr4 = require('antlr4/index');
const JavaScriptLexer = require('./JavaScriptLexer.js').JavaScriptLexer;
const JavaScriptParser = require('./JavaScriptParser.js').JavaScriptParser;

//const input = fs.readFileSync('ArrowFunctions.js').toString();
const input = 'var nombre = nombre;function getNombre(){return nombre;}function getNombre2(){return nombre;}';

const chars = new antlr4.InputStream(input);

const lexer = new JavaScriptLexer(chars);

const tokens = new antlr4.CommonTokenStream(lexer);

const parser = new JavaScriptParser(tokens);
const tree = parser.program();

console.log(tree.toStringTree(parser.ruleNames));`
```

and I'm building all with antlr4 `-Dlanguage=JavaScript -no-listener JavaScriptParser.g4` and the same for the JavaScriptLexer.g4. (Actually, I don't know what is a listener for).

Please, I need help to know how it works. I'm using JavaScriptBaseLexer and JavaScriptBaseParser to run all the code. Thanks.

**Comment by studentmain** [comment]
>  I took the JavaScript example and it works but it shows me all token names of all characters of my code.

FYI, it's just work as intended, that example just show how to traverse tree using Visitor.

> I can't understand all JavaScriptLexer.js and JavaScriptParser.js code

You needn't understand it, you even needn't look at it.

> I don't know how to edit .g4 to add javascript code

See https://github.com/antlr/grammars-v4/blob/master/ecmascript/JavaScript/ECMAScript.g4

Use a Listener maybe better for your case, you may want remove `-no-listener` switch.

[Document for listener](https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md#how-do-i-create-and-run-a-custom-listener)

The grammar rule you interested:
https://github.com/antlr/grammars-v4/blob/e173da83afaccfcee74a9115753ee9aeec784f56/javascript/JavaScriptParser.g4#L174-L176

`const tree = parser.program()` generated parse tree. When you execute your listener, ANTLR will traverse the tree, if it found a node is generated by rule X, it will try to call enterX and exitX in your listener with current parser context (node and it's children, location in source code. etc).

In your case, it's `enterFunctionDeclaration`. As you see, the function name (that `Identifier`) is the 2nd child of `functionDeclaration node`. `Identifier` is a lexer rule, that mean `Identifier` has no child node. Just get it, and do what you want.

If you're using Typescript, you may interested in experiemental [antlr4ts](https://github.com/tunnelvisionlabs/antlr4ts), it's demo seems exactly what you want.

(Just wonder why you want using ANTLR in JS to parse JS. We already have esprima)

**Comment by msriki12** [comment]
Hello and thanks for your response. I'm working on reading all the info you just gave me and i think i can now go forward and get it by myself. I want to use ANTLR in JS cause the tool where i work (ServiceNow) only use JS scripts to work. I want to do a simple app to get a .gv file with relations between script functions, and i want to do it into the tool. Other option if this is too much hard, is build it with Python or Java, and use a Cloud System like Heroku, Google Cloud or Azure to send and receive messages with the information that i want. Thanks again for your response.
