### ISSUE TITLE
Why use '|)'

### ISSUE THREAD

**Issue by druud** [antlr/grammars-v4#1462]
When I see

```antlr
element
   : labeledElement (ebnfSuffix |)
   | atom (ebnfSuffix |)
   | ebnf
   | actionBlock QUESTION?
   ;
```

(pasted from ANTLRv4Parser.g4)
I wonder why `(ebnfSuffix |)` wasn't spelled as `ebnfSuffix ?`.

Is there a difference in meaning? processing? performance?

**Comment by KvanTTT** [comment]
I think there is no difference. It's just another type of syntax. It can be replaced with `ebnfSuffix?`
