### ISSUE TITLE
Any plan to support vlang grammar?

### ISSUE THREAD

**Issue by lijiansong** [antlr/grammars-v4#1464]
[vlang](https://vlang.io/) is a programming language which has similar syntax with golang. Now it is open-sourced at github, repo: <https://github.com/vlang/v>
Do you have any plan to add ANTLR grammar for vlang?

**Comment by ShenQingchuan** [comment]
I have written an incomplete version from Golang's grammar.
Please check it for V language !~

Click here https://github.com/ShenQingchuan/grammars-v4
and find the " v " folder !~

**Comment by ShenQingchuan** [comment]
https://github.com/ShenQingchuan/grammars-v4/tree/master/v
🤣I think just giving this URL would be more convenient..

**Comment by KvanTTT** [comment]
@ShenQingchuan you are welcome to make a pull request to this repository.

**Comment by ShenQingchuan** [comment]
@KvanTTT Ah….Thanks for your kind but I just did a little bit work about it…
It’s not very complete yet because :
- I just made some culling work from the Golang’s antlr4 file
- V language is still in the early stage… we all need to stay focus on that
