### ISSUE TITLE
Commercial

### ISSUE THREAD

**Issue by quantrpeter** [antlr/grammars-v4#1469]
Hi, i am going to developer a commercial close source c compiler base on grammar https://github.com/antlr/grammars-v4/blob/master/c/C.g4 . Is it ok? Or it is illegal?
thanks
Peter

**Comment by KvanTTT** [comment]
Yes, it's legal I think. C grammar is developed under the BSD license that allows using in both not commercial and commercial projects. But you should follow these items:

```
 1. Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.
 3. The name of the author may not be used to endorse or promote products
    derived from this software without specific prior written permission.
```
