### ISSUE TITLE
IDEA ANLTR4 plugin and  lexer and parser actions 

### ISSUE THREAD

**Issue by rojaster** [antlr/grammars-v4#147]
Does IDEA plugin support actions for lexer and parser ( @lexer::members, @parser::members )?

Cause why i'm askin my code isn't work: ( my question on stackoverflow has no answers )

<pre>
@members{

    public boolean isAsteriskCommentLine(){

        Token t[2];

        t[0] = this.getCurrentToken();

        t[1] = this.nextToken();

        if( ( t[0].getText().equals('\n') || t[0].getText().equals('\r') ) && t[1].getText().equals('*') )
            return true;

        return false;

    }

}

.....

COMMENT:  {getCharPositionInLine() == 0}?'*' ~[\r\n]*? (('\r'? '\n')| EOF) {isAsteriskCommentLine()}?;
</pre>

and i cant' understand what i'm doing wrong, book was read, documentation and examples from stackoverflow branches

**Comment by parrt** [comment]
plugin cannot *execute* java actions w/o generating code so not possible in live preview.
