### ISSUE TITLE
Extract code parts from grammar to separate runtime files for PHP

### ISSUE THREAD

**Issue by KvanTTT** [antlr/grammars-v4#1482]
See how it is implemented for [javascript](https://github.com/antlr/grammars-v4/tree/master/javascript).

Steps:

1. Create directories for each supported runtime with base lexer (`java/PhpBaseLexer.java`, `csharp/PhpBaseLexer.cs`, etc.). Parser grammar does not have code parts.
2. Add [`superclass`](https://github.com/antlr/antlr4/blob/master/doc/options.md#grammar-options) option to `PhpLexer.g4`:

```antlr
options {
    superClass=PhpBaseParser;
}
```
3. Move code part from [`@lexer::members`](https://github.com/antlr/grammars-v4/blob/master/php/PhpLexer.g4#L29-L129) section to the newly created super classes for all runtimes:

```java
public abstract class PhpBaseLexer extends Lexer
{
    // Insert code here
}
```

4. Replace code in [semantic predicates](https://github.com/antlr/antlr4/blob/master/doc/predicates.md) and actions with common constructions (for example, method invocations are the same in Java and C#):

```antlr
Shebang
    : '#' { _input.LA(-2) <= 0 || _input.LA(-2) == '\r' || _input.LA(-2) == '\n' }? '!' ~[\r\n]*
    ;
```

to

```antlr
Shebang
    : '#' { isNewLineOrStart(-2) }? '!' ~[\r\n]*
    ;
```

The method `isNewLineOrStart` will have the following implementation in `PhpBaseLexer.java`:

```java
protected boolean isNewLineOrStart(int pos) {
    return _input.LA(-2) <= 0 || _input.LA(-2) == '\r' || _input.LA(-2) == '\n' 
}
```

and the following in `PhpBaseLexer.cs`:

```cs
protected bool prev(string str)
{
    return _input.La(-2) <= 0 || _input.La(-2) == '\r' || _input.La(-2) == '\n' 
}
```

Finally, it should be a single lexer grammar with universal semantic predicates that has targets to several runtimes.

**Comment by thierrymarianne** [comment]
I've extracted code parts matching with semantic predicates and actions for each runtime files for PHP from https://github.com/antlr/grammars-v4/pull/1483. I'll probably need to apply some fixes depending on the upcoming continuous integration results.

**Comment by KvanTTT** [comment]
Thanks a lot, you are a great fellow. Yes, some tests are failed due to compilation errors, take a look https://travis-ci.org/antlr/grammars-v4/builds/570859426#L5092-L5093

**Comment by thierrymarianne** [comment]
You're very welcome. I've started to search for adequate fixes. The missing commas have been added but there are other issues regarding the use of not yet declared symbols from the base lexer class. 
I'll push the latest changes so that the compilation errors don't fail the test. I'm concerned with the other runtimes though. Are there test suites for Python / JavaScript and CSharp, which could also easily be run from the command-line in a development environment?

**Comment by KvanTTT** [comment]
> I'll push the latest changes so that the compilation errors don't fail the test.

I think such compilation errors due to the lack of superclasses support: https://github.com/antlr/antlr4/issues/1962 Also, it would be ideal to extract such a plugin to the separated repo: https://github.com/antlr/antlr4/issues/1961

> Are there test suites for Python / JavaScript and CSharp, which could also easily be run from the command-line in a development environment?

Unfortunately, it's not implemented yet, see the issue https://github.com/antlr/antlr4test-maven-plugin/issues/6

**Comment by thierrymarianne** [comment]
Thank you for the pointers to the three distinct issues!

I've validated manually the JavaScript runtime. I'll do the same for the CSharp / Python runtimes.

**Comment by thierrymarianne** [comment]
The work has been checked for JavaScript, CSharp and Python runtimes, however :
 - manual static member variables are to be imported manually for CSharp
 - manual declarations of prototype properties are required for JavaScript
