### ISSUE TITLE
Grammar for C# generates Java code in golang

### ISSUE THREAD

**Issue by fred1268** [antlr/grammars-v4#1485]
When using csharp grammar to generate a parser in Go (i.e. parse C# code from Go), there are some Java code that is generated in the csharp_lexer.go file:

```java
private int interpolatedStringLevel;
private Stack<Boolean> interpolatedVerbatiums = new Stack<Boolean>();
private Stack<Integer> curlyLevels = new Stack<Integer>();
private boolean verbatium;
```

Expected: all code should be generated in Go.

**Comment by fred1268** [comment]
This seems to be due to interpolated strings. Since I did not need them to be parsed, I removed them, however there is another problem in the csharp_parser.g4 file: the label emptyStatement conflicts with automatically generated code. Rewriting it as follow solves the problem:

```simple_embedded_statement
	: ';'                                                  #theEmptyStatement
	| expression ';'                                       #expressionStatement
```
(note: the "emptyStatement" label has been renamed to "theEmptyStatement")

**Comment by studentmain** [comment]
Maybe it's time to add other target language to unit test?

**Comment by KvanTTT** [comment]
You should develop a target for Go language or develop universal grammar. The last solution is better but more complicated. See [JavaScript](https://github.com/antlr/grammars-v4/tree/master/javascript) implementation as a sample.

**Comment by fred1268** [comment]
Hello @KvanTTT ,

I tried to do just what you suggested for Golang grammar (targets Golang & Java), but it seems I did something wrong, but I can't pinpoint it.
In the Golang target, the new methods are call out of the wild (noTerminatorbetween(), instead of being called from the receiver (p.noTerminatorBetween()), thus I have to tweak the generated file by hand (yep, it's ugly, hence my call for help!)
The Java target doesn't even compile, because, I assume, files in the Java directory did not get moved to the "right" place.

Can you direct me towards some useful documentation or give me any hint / help?

Thanks in advance.
Fred.

**Comment by KvanTTT** [comment]
I am afraid I'm not very familiar with Golang to give advise on how to correctly fix your issues.

> The Java target doesn't even compile, because, I assume, files in the Java directory did not get moved to the "right" place.

As I've already answered in [the comment in PR](https://github.com/antlr/grammars-v4/pull/1497#issuecomment-524311088): I afraid that is due to lack of super (base) classes support: antlr/antlr4#1962. Let's remove (comment out) Go language from Travis CI script for now: https://github.com/antlr/grammars-v4/blob/master/pom.xml#L123

**Comment by fred1268** [comment]
Hello @KvanTTT ,

This is probably where I go confused: I don't need help regarding the Go part of it, but rather, as you mentioned, on the ANTLR part of it. I took inspiration from the JavaScript as you mentioned, but I was supposing that putting the base classes in the Java (and Go) directories would work (out of the box).

Now I understand from your message this is not the case or I don't know how to make this work.

Fred

**Comment by KvanTTT** [comment]
> I was supposing that putting the base classes in the Java (and Go) directories would work (out of the box).

Unfortunately, it does not work even for Java on CI server :( But you can configure it on your local project.

**Comment by fred1268** [comment]
Hello @seifriedc , please see issue #1484 and related PR / Fix I did if you want to see how you can fix it. It won't be perfect, but will help you I guess. If I need Python at some time, I will do the fix myself, but I am not planning it any time soon.

**Comment by am11** [comment]
FWIW, here are the up-to-date grammar files:

* https://github.com/dotnet/roslyn/blob/5cae62a/src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4
* https://github.com/dotnet/roslyn/blob/5cae62a/src/Compilers/VisualBasic/Portable/Generated/VisualBasic.Grammar.g4

Could this project (somehow) consume the official grammar files (in order to support language versions higher than C# 6.0)?

**Comment by studentmain** [comment]
> consume the official grammar files

See mysql folder. Someone from MySQL Workbench team added a link to their official grammar.

**Comment by KvanTTT** [comment]
I don't see C# and VisualBasic lexer grammars. Where are they?

**Comment by am11** [comment]
Maybe I am mistaken, but I thought they have it as a combined grammar? The generator is located [here](https://github.com/dotnet/roslyn/tree/5cae62a/src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator).

**Comment by CyrusNajmabadi** [comment]
> Could this project (somehow) consume the official grammar files (in order to support language versions higher than C# 6.0)?

Highly unlikely.  These grammars were not generated with that in mind.  They're only intended to serve as documentation of the authoritative data structures the actual Roslyn compiler uses when parsing.

 > I don't see C# and VisualBasic lexer grammars. Where are they?

For c# that is in: https://github.com/dotnet/csharplang/blob/master/spec/lexical-structure.md

**Comment by am11** [comment]
Thanks for your answer and explanations on gitter. From our chat, I have understood that the most current/up-to-date sources (pertaining to syntax) are:

* https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Syntax/Syntax.xml.
* https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Syntax/Syntax.xml

which tools can use to emit elaborate output for antlr, textmate (https://github.com/dotnet/csharp-tmLanguage/issues/168) etc.

**Comment by CyrusNajmabadi** [comment]
That is correct :)

**Comment by slash-under** [comment]
This issue still seems present in the latest C# grammar, and is reproducible with Python 3.8.
