### ISSUE TITLE
Grammar for C# uses type - Should use typeType

### ISSUE THREAD

**Issue by fred1268** [antlr/grammars-v4#1486]
In the CSharpParser.g4 file, the piece that defines type won't compile in Go, since type is a reserved keyword in Go:

```g4
type 
	: base_type ('?' | rank_specifier | '*')*
	;
```

However, if rewritten like below (and fixing appropriate occurrences), it works:

```g4
typeType 
	: base_type ('?' | rank_specifier | '*')*
	;
```

**Comment by KvanTTT** [comment]
I suggest renaming it to `type_`. You are welcome to make a pull request to fix this issue.

**Comment by fred1268** [comment]
Pull Request submitted with type_ as suggested.
Note: the reason why I proposed typetype is because it was done that way in another grammar.

**Comment by KvanTTT** [comment]
> Note: the reason why I proposed `typetype` is because it was done that way in another grammar.

But it doesn't mean that it's correct :)
