### ISSUE TITLE
Grammer CPP14.g4 parsing code twice.

### ISSUE THREAD

**Issue by abd96** [antlr/grammars-v4#1491]
Hey,

i implemented a listener(using python) that inherits from CPP14Listener.py and started testing with defining enterFunctiondefinition(self, ctx:). I noticed that when i only define one function in my input code(input code below), the listener method enterFunctiondefinition() will be called twice.

I checked CPP14Parser.py to see if the listener method enterFunctiondefinition() is called twice but this is not the case.I tried implementing enterClassname()  and the same problem occurred, one class defined and enterClassname() was called twice.

My Input Code : 
```
struct X {
    int x, y;
    int operator()(int);
    void f()
        // the context of the following lambda is the member function X::f
        
        {
            return operator()(this->x + y); // X::operator()(this->x + (*this).y)
                                            // this has type X*
        };
    
};
```

Is this a problem from CPP14.g4 and can tweak it from there ? 

I also want to mention that after compiling CPP14.g4(Generating lexer/parser in .py code) i couldn't run my test because the python3 compiler has found a false syntax(line 13893) in  CPP14Parser.py, 
```
if((None if localctx.val is None else localctx.val.text).compareTo("0")!=0) 
throw new InputMismatchException(this);  

```  

```throw new```  is java syntax and python3 couldn't understand it.After commenting this line i was able to run my test successfully. 

I would appreciate your help.

Greetings

**Comment by raresraf** [comment]
Had the same issue with the `if((None if localctx.val is None else localctx.val.text).compareTo("0")!=0) throw new InputMismatchException(this);` syntax
