### ISSUE TITLE
Grammar PlSqlParser.g4 parsed uncorrect result

### ISSUE THREAD

**Issue by small-cat** [antlr/grammars-v4#1492]
I found an error when parsed plsql sentences, for example

```sql
select sex, name, phone from student;
```

the selected_element of the ParseTree contains `sex, name, phone`. When I go details into PlSqlParser.g4, I found that

```antlr
query_block
    : SELECT (DISTINCT | UNIQUE | ALL)? (ASTERISK | (','? selected_element)+)
      into_clause? from_clause where_clause? hierarchical_query_clause? group_by_clause? model_clause?
    ;

selected_element
    : select_list_elements column_alias?
    ;

select_list_elements
    : tableview_name '.' ASTERISK
    | (regular_id '.')? expressions
    ;

expressions
    : expression (',' expression)*
    ;
```

the rule named `select_list_elements` has a branch `(regular_id '.')? expressions`, my problem is here. `expressions` separated by `COMMA` if `(',' expression)` exists, so all the selected_elements were parsed to a single `seleced_element`. I don't check other rules which contain `select_list_elements`, so I just rewrite `query_block` like this and solve my problem. By the way, `(','? selected_element)+)` can match pattern `sex name phone`, because we don't know when `COMMA` exists, but in `query_block` `select_element` must exist at least one,  `select_element (COMMA selected_element)*` may be more correct.

```antlr
query_block
    : SELECT (DISTINCT | UNIQUE | ALL)? selected_list                                                                                                 
      into_clause? from_clause where_clause? hierarchical_query_clause? group_by_clause? model_clause?
    ;
 
selected_list
    : ASTERISK
    | selected_list_element (COMMA selected_list_element)*
    ;
 
selected_list_element
    : tableview_name PERIOD ASTERISK
    | expression  column_alias?
    ;
```

**Comment by KvanTTT** [comment]
Could you propose a PR to fix such behavior?

**Comment by Lesley-Thewdar** [comment]
Was going through this grammar myself today and found the same problem and then I noticed this PR. Funny coincidence, considering this bug has been there for so long since Nov 2017 with commit 193756240796931f2b193d488a6fc6dd486df27b
