### ISSUE TITLE
CPP14 COMMENT ERROR

### ISSUE THREAD

**Issue by TIIEHenry** [antlr/grammars-v4#1496]
The comments definition should not skip, use this:

```antlr
BlockComment
   : '/*' .*? '*/' -> channel(HIDDEN)
   ;

LineComment
   : '//' ~ [\r\n]* -> channel(HIDDEN)
   ;
```

**Comment by TIIEHenry** [comment]
i dont know cpp,but i added #ifdef
IFDEF
    :   '#ifdef' .*? '#endif' -> channel(HIDDEN)
    ;

**Comment by teverett** [comment]
Isn't ifdef and so on, part of the C++ preprocessor and therefore a different grammar?
