### ISSUE TITLE
Merge java8 java8-js and java8-ts grammar?

### ISSUE THREAD

**Issue by studentmain** [antlr/grammars-v4#1499]
As they're same grammar with different target.

Java8 g4 itself use `java.lang.Character.isJavaIdentifierStart`and `java.lang.Character.isJavaIdentifierPart` which is not portable. According to [doc](https://docs.oracle.com/javase/8/docs/api/java/lang/Character.html#isJavaIdentifierPart-int-), seems we can replace them with lexer rules to make it portable.

**Comment by KvanTTT** [comment]
Yes, it's a good idea. You can follow instructions from #1482 to make grammar universal.

FYI, original java grammar (without prefix) supports java8. I recommend using it because of it much faster than these formal java8 grammars.

**Comment by studentmain** [comment]
> You can follow instructions from #1482 to make grammar universal.

I'd prefer replace java native method with lexer rules, that will make a superClass unnecessary. According to their source code, they're essentially check JRE's builtin character database.
