### ISSUE TITLE
Why there's no grammar for PostgreSQL?

### ISSUE THREAD

**Issue by sulaukad** [antlr/grammars-v4#1501]
I'm looking for PostgreSQL grammar, but I can't find any solution. There are few 5 years old repos on git hub with a proprietary license which is not suitable for me.

**Comment by KvanTTT** [comment]
There are at least several implementations:

* https://github.com/tshprecher/antlr_psql It seems to me that quite actual, updated recently
* https://github.com/tunnelvisionlabs/antlr4-grammar-postgresql too old, updated 5 years ago
* https://github.com/valgog/pg_sql_parser also too old
* https://github.com/postgres/postgres/blob/master/src/backend/parser/gram.y full, official, but not ANTLR, need to be ported

Also, maybe it makes sense to look at our PL/SQL or MySQL grammars. Maybe there are a lot of things in common.

**Comment by mitar** [comment]
Related: https://github.com/lfittl/libpg_query

**Comment by yuanzhonglin** [comment]
hello,I'm also looking for PostgreSQL grammar files,have you found it? I would appreciate it if you could offer some help.

**Comment by Marti2203** [comment]
Check the two repositories linked and see if they are good enough for you. If not, message the maintainers of them to see what is going on. I am still interested in working on them.

**Comment by AXEPOH** [comment]
Hello, you can use our solution (it includes Postgres 12): 
https://github.com/pgcodekeeper/pgcodekeeper/blob/master/apgdiff/antlr-src/SQLParser.g4

**Comment by BowenXiao1999** [comment]
https://github.com/apache/shardingsphere/tree/master/shardingsphere-sql-parser/shardingsphere-sql-parser-dialect/shardingsphere-sql-parser-postgresql/src/main/antlr4
ShardingSphere also has a antlr4 for PG.

**Comment by studentmain** [comment]
#2260

**Comment by studentmain** [comment]
@KvanTTT we can close this now

**Comment by dioptre** [comment]
Looks like there's one here https://github.com/apache/shardingsphere/tree/24867f7bb33a94b6f7274c408372d421ab61a498/parser/sql/dialect/postgresql/src/main/antlr4/org/apache/shardingsphere/sql/parser/autogen
