### ISSUE TITLE
PlSqlLexer Python IsNewlineAtPos

### ISSUE THREAD

**Issue by zeekay18** [antlr/grammars-v4#1504]
Hi,

I am getting the error name is undefined for `IsNewlineAtPos` in the python3 lexer generated.

I had to use this to call the `IsNewlineAtPos` defined in the base class for it to work

`super().IsNewlineAtPos(-4)`

**Comment by KvanTTT** [comment]
You should use parameter [`-DsuperClass=PlSqlBaseLexer`](https://github.com/antlr/antlr4/blob/master/doc/options.md#grammar-options) during parser generation. Such class is defined in [plsql/Python3](https://github.com/antlr/grammars-v4/blob/master/plsql/Python3/PlSqlBaseLexer.py) directory.
