### ISSUE TITLE
 Make mysql case insensitive

### ISSUE THREAD

**Issue by gengu** [antlr/grammars-v4#1505]
Case sensitivity is customary

**Comment by KvanTTT** [comment]
It already is. You should use `CaseChangingCharStream`, see the doc [Case-Insensitive Lexing](https://github.com/antlr/antlr4/blob/master/doc/case-insensitive-lexing.md#custom-character-streams-approach) for detail and other issues with tag [case-insensitive](https://github.com/antlr/grammars-v4/issues?q=is%3Aissue+label%3Acase-insensitive+is%3Aclosed).
