### ISSUE TITLE
GraphQL golang compiler conflict resolved

### ISSUE THREAD

**Issue by innomon** [antlr/grammars-v4#1510]
There were the following errors, that occurred during golang code generation. 
*RESOLUTION:* : replace `type` with `dtype` 

```shell 
 antlr4 -Dlanguage=Go GraphQL.g4
error(134): GraphQL.g4:131:0: symbol type conflicts with generated code in target language or runtime
error(134): GraphQL.g4:112:18: symbol type conflicts with generated code in target language or runtime
error(134): GraphQL.g4:140:9: symbol type conflicts with generated code in target language or runtime
```
[GraphQl.g4](https://gist.github.com/innomon/df738b9cb60c8bff110777624890d43a)

**Comment by innomon** [comment]
**RESOLUTION**: replace type with dtype
[GraphQl.g4](https://gist.githubusercontent.com/innomon/df738b9cb60c8bff110777624890d43a/raw/dd3f844f000bfaae2c86e592cb9cd3286e0208a9/GraphQl.g4)

**Comment by KvanTTT** [comment]
Could you please replace `type` with `type_` as we did for other identifiers with [symbol-conflict](https://github.com/antlr/grammars-v4/issues?q=label%3Asymbol-conflict+is%3Aclosed) issues?

**Comment by innomon** [comment]
@KvanTTT : done!

**RESOLUTION**: replaced `type` with `type_`

[GraphQL.g4](https://gist.githubusercontent.com/innomon/df738b9cb60c8bff110777624890d43a/raw/482d62ff452a3ed5f612d89f8b67f9d1beb73f52/GraphQl.g4)
