### ISSUE TITLE
lexer grammer question

### ISSUE THREAD

**Issue by quantrpeter** [antlr/grammars-v4#1515]
Hi
    Why
```
ADD_		:	'+';
MIN_		:	'-';
MUL_		:	'*';
DIV_		:	'/';
MOD_		:	'%';
SQU_		:	'^';

MATH_EXPRESSION	:	(
						'0x' [0-9a-zA-Z]+
						|	[0-9]+
						|	ADD_
						|	MIN_
						|	MUL_
						|	DIV_
					)+
				;
```

failed to match these: 0x1+0x2*0x3+0xa2*0x23 ??
thanks

**Comment by studentmain** [comment]
In which g4 file?

How did you use it? `grun` or with your own code (in which language)?

Match this expression may require a parser rule.

**Comment by quantrpeter** [comment]
Thanks studentmain, i fixed it
