### ISSUE TITLE
How to create Lexer/Parser?

### ISSUE THREAD

**Issue by it19862** [antlr/grammars-v4#1522]
Used:
Visual Studio - 2019

To install `ANTLR` I use - [tunnelvisionlabs/antlr4cs // Github.com ](https://github.com/tunnelvisionlabs/antlr4cs) - 

I took the grammar here - [antlr/grammars-v4 // Github.com  ](https://github.com/antlr/grammars-v4/tree/master/csharp)
CSharpLexer.g4
CSharpParser.g4
CSharpPreprocessorParser.g4

I did:
1. Installed ANTLR;
2. Created a WinFrom application;
3. Added grammar;
Right-click the project or folder in Solution Explorer and select
`Add` →` Existing Element`.

**Question.**
What should I do next?
The instructions say that additional classes must be created.
![2019-10-07_09-03-33](https://user-images.githubusercontent.com/18245828/66288494-18553100-e8e2-11e9-9876-93015118bb1d.png)
![2019-10-07_09-04-09](https://user-images.githubusercontent.com/18245828/66288478-0d020580-e8e2-11e9-92de-de92aebb1cfb.png)
![2019-10-07_09-07-08](https://user-images.githubusercontent.com/18245828/66288496-1a1ef480-e8e2-11e9-98cb-fc3135cc652c.png)
![2019-10-07_09-06-20](https://user-images.githubusercontent.com/18245828/66288490-155a4080-e8e2-11e9-9f2a-020aa3b4ad6d.png)

**Comment by KvanTTT** [comment]
The question is not related to grammars.
