### ISSUE TITLE
can this repository add the  grammar for the ABB Robot Language 

### ISSUE THREAD

**Issue by heroinxj** [antlr/grammars-v4#1526]
hello,I find the  grammar for the KUKA robot language in this repository and I need generate the AST of ABB Robot language,so I wish this repository can add the RAPID(ABB robot use) language grammer.THANKS!

**Comment by teverett** [comment]
https://en.wikipedia.org/wiki/RAPID

**Comment by heroinxj** [comment]
> https://en.wikipedia.org/wiki/RAPID

**Comment by heroinxj** [comment]
> https://en.wikipedia.org/wiki/RAPID

so what do you mean

**Comment by loonydev** [comment]
It's just link for somebody who want to add this language.

**Comment by MSE1188** [comment]
[abbParser.zip](https://github.com/antlr/grammars-v4/files/5034505/abbParser.zip)

Hello I attached ABB Parser files, which I recently started to make. They are derived from the kuka grammar [https://github.com/antlr/grammars-v4/tree/master/kuka](url) and are still in progress.

In the current state you are able to parse variable declarations and assignments from ABB RAPID language files.

I am pretty new in ANTLR so sorry, if the grammar is not perfect. Maybe someone can expand the grammar and make a branch and pull request from it.

**Comment by heroinxj** [comment]
> [abbParser.zip](https://github.com/antlr/grammars-v4/files/5034505/abbParser.zip)
> 
> Hello I attached ABB Parser files, which I recently started to make. They are derived from the kuka grammar [https://github.com/antlr/grammars-v4/tree/master/kuka](url) and are still in progress.
> 
> In the current state you are able to parse variable declarations and assignments from ABB RAPID language files.
> 
> I am pretty new in ANTLR so sorry, if the grammar is not perfect. Maybe someone can expand the grammar and make a branch and pull request from it.

**Comment by heroinxj** [comment]
> [abbParser.zip](https://github.com/antlr/grammars-v4/files/5034505/abbParser.zip)
> 
> Hello I attached ABB Parser files, which I recently started to make. They are derived from the kuka grammar [https://github.com/antlr/grammars-v4/tree/master/kuka](url) and are still in progress.
> 
> In the current state you are able to parse variable declarations and assignments from ABB RAPID language files.
> 
> I am pretty new in ANTLR so sorry, if the grammar is not perfect. Maybe someone can expand the grammar and make a branch and pull request from it.

Hello, I would like to know if you have any new progress in ABB grammar file recently, thanks.

**Comment by KvanTTT** [comment]
@MSE1188 could you please make a pull request with your grammar to this repository?

**Comment by MSE1188** [comment]
@heroinxj I did not made any progress so far, as I can work with the current ones for my purposes. I will let you know, when I add more.

@KvanTTT It seems, that I do not have permission to push branches into this repository, so I am not able to make a PR here.

**Comment by KvanTTT** [comment]
In the beginning, you should make a [fork](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo) of this repository. You can do everything with your fork. After that, you should make pull request from your fork to this repository.

**Comment by heroinxj** [comment]
@MSE1188 Thanks for you help。

**Comment by MSE1188** [comment]
@KvanTTT Thanks, I didn't know about this fork-thing. I made a pull request in my own fork now. 
Not quite sure how the testing is done here. I added a short readme and example file next to the parser files.
