### ISSUE TITLE
[Tsql] An issue in select_list_elem: asterisk

### ISSUE THREAD

**Issue by wcx11** [antlr/grammars-v4#1532]
Dear author: I found out the following grammar in TsqlParser.g4 could be an issue.
(about line 3008 to 3011) :
`asterisk
    : '*'
    | table_name '.' asterisk
    ;`
it's equivalent to `asterisk: (table_name '.')* '*'` which means the selected_list_elem could be something like `table1.table1.table1.*`. 
Actually only things like `table1.*` or `*` are valid.
Could you please double check it? 
Thanks for providing such helpful tools~

**Comment by KvanTTT** [comment]
Would you like to suggest a pull request?

**Comment by wcx11** [comment]
Pull request created at : https://github.com/antlr/grammars-v4/pull/1533
