### ISSUE TITLE
Cool grammar issue with COMMA separated formal/expression

### ISSUE THREAD

**Issue by raresraf** [antlr/grammars-v4#1549]
Current COOL grammar wrongly accepts:
- methodCalls such as f(1 2), f(1, 2 3)
- formal parameters as (foo : String bar:String)

**Comment by raresraf** [comment]
The solution should be replacing `*)*` constructions for COMMA separated values into `*)?`:
```
-   : OBJECTID '(' (formal (',' formal)*)* ')' ':' TYPEID '{' expression '}' # method
+   : OBJECTID '(' (formal (',' formal)*)? ')' ':' TYPEID '{' expression '}' # method
```

```
-   : expression ('@' TYPEID)? '.' OBJECTID '(' (expression (',' expression)*)* ')' # methodCall
-   | OBJECTID '(' (expression (',' expression)*)* ')' # ownMethodCall
+   : expression ('@' TYPEID)? '.' OBJECTID '(' (expression (',' expression)*)? ')' # methodCall
+   | OBJECTID '(' (expression (',' expression)*)? ')' # ownMethodCall
```

**Comment by KvanTTT** [comment]
Could you suggest a pull request?

**Comment by raresraf** [comment]
Does there exists a Contributing Guide?

I do not have the permissions to push a local branch

```
ERROR: Permission to antlr/grammars-v4.git denied to raresraf.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by KvanTTT** [comment]
Sure, you can't push to the official repository directly. Firstly, you should [fork](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) it, push to your local repository and create a [pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) from your fork.
