### ISSUE TITLE
plsql maven clean install fail on latest version

### ISSUE THREAD

**Issue by biYTccKCiu** [antlr/grammars-v4#1559]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project plsql: Compilation failure: Compilation failure: 

This is the start of a multitude of errors when I try to run mvn clean install from within the plsql directory.

**Comment by KvanTTT** [comment]
This issue is not linked with grammars.
