### ISSUE TITLE
Writing for Oracle 12 & 18c Parser/Lexer using 11g Parser/Lexer

### ISSUE THREAD

**Issue by trraghav** [antlr/grammars-v4#1560]
Hi, 

Can I use this Oracle 11g Parser/Lexer and upgrade/modify it to Oracle 12c/18c and make it public ? What is the role of license here if I work and publish ? Can you please guide me on this ?

--Raghav

**Comment by studentmain** [comment]
It use Apache 2 license.

https://github.com/antlr/grammars-v4/blob/c9ae60507c63d4586ba63f89fe988ae38fa57480/plsql/PlSqlLexer.g4#L1-20

https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

**Comment by KvanTTT** [comment]
Yes, it's possible.
