### ISSUE TITLE
Support the grammar to parse Redis commands

### ISSUE THREAD

**Issue by jovany-wang** [antlr/grammars-v4#1562]
I'm new to use antlr4 to parse nosql statements in my project, whose grammar is similar to the redis, like:
```
put k1 v1       #redis
str.put k1 v1  # my project

lrange k1 0 2   # redis
list.get k1 0 2   # my project
```

thereby, my questions are:
1) Is there any example of redis grammar?
2) What's the best practice to write the g4 grammar rule for such nosql's statement?
---
ps: The g4 grammar rule of my project is [here](https://github.com/dst-project/dst/blob/master/parser/src/main/java/org/dst/parser/DstNewSQL.g4) .

**Comment by KvanTTT** [comment]
1. No
2. Your project is unavailable and the question is too broad
