### ISSUE TITLE
ANTLRv4Lexer does not support action blocks inside options spec

### ISSUE THREAD

**Issue by bjansen** [antlr/grammars-v4#1567]
Within an `options` construct, action blocks are not recognized as valid option values:

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/281528/69496087-7c51aa00-0ece-11ea-9ce1-04f75a26916a.png">

I suppose once an `LBRACE` has been detected, the following `{` should be a `BEGIN_ACTION` and start the `Action` mode.

I'll starting working on a PR to fix this.

**Comment by KvanTTT** [comment]
```antlr
options {
  foo = {};
}
```

I'm wondering what does it stand for? Should grammar support actions inside options block? It's a pretty strange case.

**Comment by bjansen** [comment]
Well it's [officially supported by `ANTLRParser.g`](https://github.com/antlr/antlr4/blob/master/tool/src/org/antlr/v4/parse/ANTLRParser.g#L263):
```antlr
optionValue
    : // If the option value is a single word that conforms to the
      // lexical rules of token or rule names, then the user may skip quotes
      // and so on. Many option values meet this description
      qid
    | STRING_LITERAL
	| ACTION<ActionAST>
    | INT
    ;
```

The Definitive ANTLR 4 Reference says this (emphasis mine):

> You can specify a number of options at the grammar and rule element levels.
(There are currently no rule options.) These change how ANTLR generates
code from your grammar. The general syntax is as follows:
options { name1=value1; ... nameN=valueN; } // ANTLR not target language syntax
where a value can be an identifier, a qualified identifier (for example, a.b.c), a
string, **a multiline string in curly braces {...}**, and an integer.

So from what I understand, it's actually a multiline string, but since it's the same construct as an action block (any content inside curly braces), the grammar simply reuses the `ACTION` token.

Anyway, I think it's a good idea to have a .g4 grammar that follows the .g grammar as much as possible. WDYT?

**Comment by KvanTTT** [comment]
Ok, I have no objections :)
