### ISSUE TITLE
I'm getting an error with C# Preprocessors

### ISSUE THREAD

**Issue by hamzawey** [antlr/grammars-v4#157]
Hi, 

I'm getting that error when using preprocessors in the csharp files i'm parsing: 
 
Result StandardError:	
line 20:0 missing '}' at '\t#if Testing\r\n'
line 28:0 extraneous input '}' expecting {<EOF>, 'abstract', 'class', 'delegate', 'enum', 'extern', 'interface', 'internal', 'namespace', 'new', 'override', 'partial', 'private', 'protected', 'public', 'readonly', 'sealed', 'static', 'struct', 'unsafe', 'virtual', 'volatile', '['}

this is the file i'm using to test:
namespace test.test1
{
    public class Testing
    {
		static void Main (string[] args){
	#if Testing
		String x = "abc"; 
	#else
		String y = "xyz"; 
	#endif
		String a, b;
	}
    }
}

**Comment by parrt** [comment]
you have to preprocess first i'm sure.

**Comment by hamzawey** [comment]
Thanks Terence, could you please advise how to preprocess first?

**Comment by parrt** [comment]
i'd have to google for you. sorry.
