### ISSUE TITLE
skipping NEWLINE-only lines any single_input in Python grammar

### ISSUE THREAD

**Issue by rockobonaparte** [antlr/grammars-v4#1570]
Note that this is quite possibly a screwup on my end and I have a lot of layers going on here that are making it hard to isolate back with just the original grammar, but I have advanced enough to try to file something, risk sounding stupid, and hopefully learn something at the worst.

I have been trying to use the C# Python3 grammar and I think I'm hitting a hiccup here:

https://github.com/antlr/grammars-v4/blob/8803cbe8aca1b3b6ebf73e13f5c41665f393b381/python3-cs/Python3.g4#L361

It's been parsing great from the file_input rule, but I'm starting to use the single_input rule in a REPL. That REPL is having a problem completing itself if I do a compound statement like:
```python
if True:
  a = 1

```
I'm using a parse error listener for now to try to tell line-by-line that I need to continue and use the secondary prompt. Per the Python REPL, I should terminate that inner block with a newline on its own line. However, I keep seeing an error that I'm missing a NEWLINE at <EOF>. If I look at the tokens, I have a growing pile of newlines as I keep hitting enter to try to send it through. The lexer is trying to make them into newlines.

Anyways, that skip on that line seems to trigger on these empty newlines. I am wondering if that could be a problem with the REPL.

I see that skip triggering for any file where I have newlines even if I have some white space before it. So let's say * is white space in this bit:
```python
if True:
**if True:
****a = 1
**

```

I'm generally curious what the NEWLINE logic is trying to do since it's kind of opaque to me, and I have some sense I might have tripped on a situation here. I don't know if the testing coverage includes REPL scenarios. I am kind of assuming not because it would imply a separate test bench that spoon feeds input into the parser.

**Comment by rockobonaparte** [comment]
Additional information: My setup does start working if I get rid of all the logic for evaluating when to skip around that block of code in the NEWLINE code. It looks like that is stripping out some NEWLINE tokens from the parser that satisfy the single_input rule.

So at this point I'm trying to figure out why that skip logic was added originally.

**Comment by rockobonaparte** [comment]
I was going to email @bkiers about this, but I saw in his profile to @ him first. This logic comes from the original that has the assisting code written in Java.

**Comment by bkiers** [comment]
> what the NEWLINE logic is trying to do

It determines if there is a need to insert `NEWLINE`, `INDENT` and `DEDENT` tokens to the lexer's token stream. For example, the input:

```py
numbers = [
  42
]
```
should not produce any `NEWLINE`, `INDENT` or `DEDENT` tokens (the newline occurs inside a list). Whereas the input:

```py
def q():
  return 42
```
does need to generate these tokens.

> I don't know if the testing coverage includes REPL scenarios

No, it does not.

**Comment by bkiers** [comment]
Btw, I'm  not entirely clear what problem you're really facing. If you have a question/problem, please try to create a (unit) test that others can run on their machine that clearly shows the issue. Goosd luck!

**Comment by KvanTTT** [comment]
I recommend using https://github.com/antlr/grammars-v4/tree/master/python grammar. It supports both python2 and python3 and does not skip any character from the input stream.

**Comment by rockobonaparte** [comment]
@bkiers the problem I'm having came up when I switched from using the file_input rule for complete code to the single_input rule for incomplete code since I started working on a REPL. For the sake of testing, I know exactly everything I want to feed it, but to test the UX I have to feed them in line-by-line like somebody's typing them out in the REPL prompt.

I'm trying to come up with the best way to determine when I'm parsing a compound statement that requires additional input. You know, when to go from `>>>` to `...`. What I've come up with so far is to add an IParseErrorListener that looks for:

1. RecognitionExceptions about a missing INDENT at the end.
2. Hitting \<EOF\> without a NEWLINE. This doesn't come up as an exception for whatever reason but the message is `Missing NEWLINE before <EOF>` and I have the other fields to kind of figure it out.

My REPL is building the input as a string--one line at a time. If it fully parses without an error then I run it and clear out that string to start over. If I hit those two error scenarios, then I don't run what was parsed and instead switch to the secondary prompt (`...`) on the notion that I need more input to finish. If I hit a different error, I report and abort.

I got the impression I should try to use the parser as my friend since I can use its output from the error listener as actual parse errors if one escapes outside of the logic I'm already testing. The Python REPL does the same thing if you are halfway into typing garbage.

If I use the file_input rule, it'll parse the first line inside a compound statement, but then it thinks it's done. So this case would fail using that method:
```python
if False:
  a = 1
  b = 2
```
b = 2 would get treated separately, where it would be properly treated if I fed it in whole. So to be more precise, this is the user experience from the REPL:
```
>>> if False:
...   a = 1
>>>   b = 2 # IndentationError would technically be the proper reaction given we're at a primary prompt now
```
Switching to single_input fixes that problem. I am also pretty sure that's what the regular Python interpreter is using from its own grammar according to [their spec](https://docs.python.org/3/reference/grammar.html). However, I can't get out of the secondary prompt because that NEWLINE logic is eating the trailing NEWLINEs:
```
>>> if False:
...   a = 1
...   b = 2
...
...
...
... # Help! I'm stuck!
```
If I omit the logic that skips emitting those NEWLINEs then it'll satisfy itself as expected:
```
>>> if False:
...   a = 1
...   b = 2
...
>>> # Yay!
```
I guess I can try to figure out how to change the code to only skip when most immediately scoped by certain tokens, but I have to admit my ANTLR kung fu is weak and I will probably screw it up.

@KvanTTT I am pretty invested in this grammar since I already have a lot of logic hooked up in the generated visitors for code generation. I can try to play around with it nonetheless if it can actually handle this scenario. However, I was just looking through it and I wonder if it passes through the scenario that @bkiers manages to avoid. Or perhaps is the proper thing to do is have the visitor itself just pluck out the newlines as junk?

**Comment by rockobonaparte** [comment]
I relearned how to set up a new ANTLR4 project to use the original Python3 C# grammar so I could isolate any little things I may have done to break it while editing my project. It looks like it's still a problem so either the C# version of the grammar is not a faithful recreation or the newline stripper is a little too enthusiastic and takes away the newlines I'd need to satisfy the single_input rule.

The core for the test is:
```C#
            var program = "if True:\n" +
                          "   a = 1\n" +
                          "   b = 2\n" +
                          "\n";

            var inputStream = new AntlrInputStream(program);
            var lexer = new Python3Lexer(inputStream);
            CommonTokenStream commonTokenStream = new CommonTokenStream(lexer);
            var parser = new Python3Parser(commonTokenStream);

            var antlrVisitorContext = parser.single_input();
            Console.ReadLine();
```

Output:
```
line 5:0 missing NEWLINE at '<EOF>'
```

The file_input() rule would work in this case, but it doesn't give me a change to incrementally feed in the input, line by line, like I would with the REPL. I believe there it's still technically eating the last newline but I haven't confirmed from the token stream yet.

I can also confirm the necessity for having something like it based on what @bkiers said because this screws up with both single_input and file_input if I try to reduce how much the newline skipping triggers:
```c#
            var program = "a = [\n" +
                          "\n" +
                          "# Look at me, I'm a riot!\n" +
                          "1\n" +
                          "]\n";
```
The comment inside the declaration in particular is evil.

As far as practical considerations, I can loosen up the logic for NEWLINE in my own grammar because there's a non-zero chance I'm the only one that'll ever use this and I can just not be a dufus. However, I think everybody can appreciate trying to be get some semblance of correctness.

I guess I can poke the grammar @KvanTTT linked this way next, but it's 3AM here and I better cut myself off.

**Comment by rockobonaparte** [comment]
I may have a kludge that comes from retaining final newlines since that's what's ultimately causing problems with the single_input rule:

```c#
int next = _input.La(1);
int nextnext = _input.La(2);
if (nextnext != -1 && (Opened > 0 || next == '\r' || next == '\n' || next == '\f' || next == '#'))
```
So if this is a newline right before EOF, then it retains the newline. Then the single_input rule that wants a NEWLINE gets its NEWLINE. I'm trying to determine if there are any other little gotcha's from this, but maybe this is enough for a PR as it is.
