### ISSUE TITLE
[TSQL] There can be parentheses in each left join expression.

### ISSUE THREAD

**Issue by orrindeng** [antlr/grammars-v4#1574]
For example, the current rule can parse
`FROM A LEFT JOIN B ON A.xx = B.xx LEFT JOIN C ON A.xxx = C.xxx`
But, it can't parse
`FROM (A LEFT JOIN B ON A.xx = B.xx) LEFT JOIN C ON A.xxx = C.xxx`

**Comment by GrzegorzLyp** [comment]
Looks like it is fixed.

table_source
    : table_source_item_joined
    | '(' table_source_item_joined ')'
    ;
