### ISSUE TITLE
How to java compile GoBaseParser, GoParser, GoLexer .java

### ISSUE THREAD

**Issue by better4636** [antlr/grammars-v4#1575]
I try to command javac Go*.java
but error message print 
error message is here
.\GoParserBase.java:10: error: duplicate class: GoParseTree.GoParserBase
public abstract class GoParserBase extends Parser
                ^
GoParser.java:12: error: cannot access GoParserBase
public class GoParser extends GoParserBase {
                              ^
  bad source file: .\GoParserBase.java
    file does not contain class GoParserBase
    Please remove or make sure it appears in the correct subdirectory of the sourcepath.

**Comment by XsongyangX** [comment]
I found the problem. The `GoParseBase` has a package declaration. Remove it so the compiler can find the class symbols in the default package aka. current directory.

**Comment by XsongyangX** [comment]
The base class shouldn't have that line to begin with.
