### ISSUE TITLE
PLSQL grammar missing Golang lexerbase and parserbase

### ISSUE THREAD

**Issue by wegoodwin** [antlr/grammars-v4#1588]
Hi,

The PLSQL grammar is missing Golang lexerbase and parserbase.  Has any one successfully used Golang with this grammer?

**Comment by KvanTTT** [comment]
You should implement basic Golang classes similar to others, see https://github.com/antlr/grammars-v4/tree/master/plsql

**Comment by wegoodwin** [comment]
Hi,

I tried the following:

package parser // PlSqlParser

import (
	"github.com/antlr/antlr4/runtime/Go/antlr"
)

// PlSqlLexerBase implementation.
type PlSqlLexerBase struct {
	*antlr.BaseLexer
}

// PlSqlParserBase implementation.
type PlSqlParserBase struct {
	*antlr.BaseParser
}

func isVersion12() bool {
	return true
}

func isVersion10() bool {
	return false
}

func IsNewlineAtPos(pos int) bool {

	return true

}

But when I try to execute the program I get the following error:

C:\Goodwin Ent LLC\Exemplar>go run test.go

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4c7e22]

goroutine 1 [running]:
_/C_/Exemplar/parser.NewPlSqlLexer(0x543e20, 0xc000840340, 0x26)
        C:/Exemplar/parser/plsql_lexer.go:15831 +0x62
main.main()
        C:/Exemplar/test.go:15 +0xe0
exit status 2

**Comment by MasonChen-ces** [comment]
func NewPlSqlLexer(input antlr.CharStream) *PlSqlLexer {
	l := new(PlSqlLexer)

// Does not init the PlSqlLexerBase point, Try to add the below line:
	l.PlSqlLexerBase = new(PlSqlLexerBase)
////////////
	l.BaseLexer = antlr.NewBaseLexer(input)
	l.Interpreter = antlr.NewLexerATNSimulator(l, lexerAtn, lexerDecisionToDFA, antlr.NewPredictionContextCache())
	l.channelNames = lexerChannelNames
	l.modeNames = lexerModeNames
	l.RuleNames = lexerRuleNames
	l.LiteralNames = lexerLiteralNames
	l.SymbolicNames = lexerSymbolicNames
	l.GrammarFileName = "PlSqlLexer.g4"
	// TODO: l.EOF = antlr.TokenEOF

	return l
}

**Comment by wegoodwin** [comment]
Hi @MasonChen-ces ,

That worked.  However I am not able to duplicate IsNewlineAtPos like the other languages because I haven't been able to figure out which struct to inherit from.  If I do this one:

func (p *PlSqlLexer) IsNewlineAtPos(pos int) bool {
	return true
}

 I will get several errors that IsNewlineAtPos is undefined.

**Comment by MasonChen-ces** [comment]
I encoounter the seem issue. I modified the source code, looks like: p. IsNewlineAtPos(). :)

**Comment by wegoodwin** [comment]
Hi @MasonChen-ces 

I made those changes to the source code.  I am not getting the same errors.  I changed the function to look like this:


func (p *PlSqlLexer) IsNewlineAtPos(pos int) bool {

	stream := p.GetInputStream()
	la := stream.LA(pos)
	return la == -1 || la == '\n'

}

It seems to work.  Do you see an issue with this?

**Comment by MasonChen-ces** [comment]
It works fine. but I don't kown how to create a parseTree. I have opened a SR.

**Comment by MasonChen-ces** [comment]
Hi, @wegoodwin 
I have change the followings,
plsql_lexer.go:18120:		return p.IsNewlineAtPos(-4)
plsql_lexer.go:18129:		return p.IsNewlineAtPos(-4)
plsql_lexer.go:18139:		return p.IsNewlineAtPos(-2)

**Comment by wegoodwin** [comment]
OK,

Should I close this thread?
