### ISSUE TITLE
How to create PLSQL ParseTree in Golang?

### ISSUE THREAD

**Issue by MasonChen-ces** [antlr/grammars-v4#1589]
I have a first start with ANTLR and with PLSQL grammar in particular. but it looks like there is nothing parser object can provide as a full parse tree. I have referred to issue #1355, but how to do it in go language?

```go
func main() {
	input := antlr.NewInputStream("select * from emp where emp in(:b1,:b2)")
	lexer := parser.NewPlSqlLexer(input)
	lexer.SetChannel(4)

	stream := antlr.NewCommonTokenStream(lexer,4)
	p := parser.NewPlSqlParser(stream)
	p.AddErrorListener(antlr.NewDiagnosticErrorListener(true))
	p.BuildParseTrees = true
	l := &TreeShapeListener{}
```

        **_tree := p.?_**

```go
	antlr.ParseTreeWalkerDefault.Walk(l, tree)

}
```

**Comment by MasonChen-ces** [comment]
I got the answer by myself. thx.

**Comment by wegoodwin** [comment]
Hi @MasonChen-ces,

Can you post how you were able to get the parse tree to work?

**Comment by wegoodwin** [comment]
tree := p.Sql_script()
