### ISSUE TITLE
Async is not a reserved keyword

### ISSUE THREAD

**Issue by phamvinh1712** [antlr/grammars-v4#1591]
According to ESMA
https://tc39.es/ecma262/#sec-future-reserved-words
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords
async is not a reserved or future reserved keyword. 
Why is it implemented as a reserved keyword in the Javascript grammar?
At the moment I cannot parse code that has async as a variable name

**Comment by studentmain** [comment]
Yes, it's an known issue

**Comment by studentmain** [comment]
#1555

**Comment by phamvinh1712** [comment]
Hi @studentmain , do you have any tip to quickly handle this? Or should I just remove everything relating to async as a temporary fix?
Thank you

**Comment by studentmain** [comment]
[js-esnext.zip](https://github.com/antlr/grammars-v4/files/4001126/js-esnext.zip)

Here's an alternate version maybe fixed all problems in that issue. If this one don't work, use your temporary fix.

**Comment by studentmain** [comment]
@phamvinh1712 Does it work?

**Comment by phamvinh1712** [comment]
@studentmain sorry I forgot to comment back. I only take the part you handle the keyword in the alternate version and it works great.
Thank you very much

**Comment by studentmain** [comment]
In case someone interested, that version is from https://github.com/studentmain/grammars-v4/tree/js-esnext . It changed too much, I'm not sure open PR (and merge it) is a good idea.

**Comment by KvanTTT** [comment]
> It changed too much, I'm not sure open PR (and merge it) is a good idea.

But why? It is backward compatible? If so, I don't see a reason not to accept such changes.

**Comment by studentmain** [comment]
> It is backward compatible?

I think no, I modified it to adopt ESTree node naming. (https://github.com/studentmain/grammars-v4/commit/b6a112dbca1db83c1d103a2ddaacd83d218fe68c)
