### ISSUE TITLE
Cannot create sqlite grammar for golang

### ISSUE THREAD

**Issue by wegoodwin** [antlr/grammars-v4#1592]
@bkiers

When I try to create the sqlite parsers for golang I get the following errors:

error(134): SQLite.g4:37:0: symbol error conflicts with generated code in target language or runtime
error(134): SQLite.g4:34:21: symbol error conflicts with generated code in target language or runtime

I tried to create it with the following command:

antlr4 -Dlanguage=Go -o sqliteparser SQLite.g4

Any Ideas on what I did wrong?

**Comment by studentmain** [comment]
rename 'error' to anything else

**Comment by wegoodwin** [comment]
Thanks,

That did it.

**Comment by studentmain** [comment]
You can create a PR for it.

**Comment by wegoodwin** [comment]
I am new to github.  What is a PR?

________________________________

**Comment by studentmain** [comment]
PR is pull request, to create a PR:

1. Fork this repository
2. Goto your forked repo, clone it to your computer
3. Do your change, and make a commit (your IDE will help)
4. Push your commit (your IDE will help you too)
5. Goto this repository > Pull request > New pull request
6. select compare accross fork, select your fork on right side. press create pull request

**Comment by KvanTTT** [comment]
Rename symbol `error` to `error_`.

**Comment by wegoodwin** [comment]
I am getting the following error when I try, I am logged in and I have tried logging out and logging back in.:

[cid:aabd1f43-1add-4c88-b688-5ecb3e5da719]

________________________________
