### ISSUE TITLE
(TSQL) SPLIT needs to be added to simple_id

### ISSUE THREAD

**Issue by Szhlopp** [antlr/grammars-v4#1594]
Here's an example of a TSQL query that fails, and the immediate fix is provided (by adding SPLIT to simple_id)

```sql
SELECT SPLIT.A.VALUE('.', 'INT') AS SPLV 
FROM 
	(SELECT 
		CAST('<SPL>' + REPLACE('1,2,3', ',', '</SPL><SPL>') + '</SPL>' AS XML) AS DTA
	) AS A 
  CROSS APPLY 
	DTA.NODES ('/SPL') AS SPLIT(A)
```

After adding SPLIT to simple_id, the problem goes away.

**Comment by siggemannen** [comment]
@KvanTTT i think this is fixed by my patch, the query example verifies fine now
