### ISSUE TITLE
Get listeners that are triggered during parse tree walk

### ISSUE THREAD

**Issue by wegoodwin** [antlr/grammars-v4#1599]
Hi,

New to antlr.  I have my grammer set up(PLSQL) and I don't have any issues using the parse tree walker.  I tried a function called antlr.NewDiagnosticErrorListener.  This will print out any errors that occur during the walk.  I am wonder if there is a similar function that will tell me what listeners were triggered during the walk.  PLSQL has a ton of listeners and I am not sure which ones will be triggered when parse tree walker is called.

**Comment by KvanTTT** [comment]
There are both generated and common listeners that you can use. The first one contains `Enter` and `Exit` methods for every grammar rule. The last one contains the common `Enter` and `Exit` methods that are being called for all grammar rules.

More detail in official doc: https://github.com/antlr/antlr4/blob/master/doc/listeners.md
