### ISSUE TITLE
Is someone mantaining a JavaParser based on the Java grammar presented here?

### ISSUE THREAD

**Issue by ftomassetti** [antlr/grammars-v4#160]
if so I could be interested to help :)

**Comment by parrt** [comment]
what do you mean maintaining a Java parser? we maintain grammars not parsers :)

**Comment by ftomassetti** [comment]
I was wondering if you knew about someone maintaining a parser based on this Java grammar. I have seen that it has a pretty liberal license and it seems a reasonably complete and high quality grammar so... it is tempting to use it to write a parser. I would like to do so unless someone has already started, in that case I would offer to help.

**Comment by parrt** [comment]
do you mean a handbuilt parser? I'm sure no one is bothering to do that.
