### ISSUE TITLE
License for Protobuf3.g4

### ISSUE THREAD

**Issue by gangeli** [antlr/grammars-v4#1601]
Would it be possible to add a license to the Protobuf3.g4 file in `protobuf3/Protobuf3.g4`? cc @KvanTTT @loonydev

**Comment by studentmain** [comment]
https://github.com/antlr/grammars-v4/blob/f6cbd3e2c22718a3e8e269a436c7ce30354573ee/protobuf3/Protobuf3.g4#L5 

According to the notice at the bottom of that page, the original code is licensed under Apache2
