### ISSUE TITLE
[C.g4] problem with #define

### ISSUE THREAD

**Issue by enen1** [antlr/grammars-v4#1602]
The number of tokens will be 0 if the program has ` #define`.
Maybe the `'#' Whitespace? 'define'  ~[#]*` in line 896 should be `'#' Whitespace? 'define'  ~[\r\n]*`?

**Comment by LauZyHou** [comment]
> The number of tokens will be 0 if the program has ` #define`.
> Maybe the `'#' Whitespace? 'define' ~[#]*` in line 896 should be `'#' Whitespace? 'define' ~[\r\n]*`?

Hello, thank you for your issue. I used your changes and now I can successfully get the parse tree. However, I found that there is no `define` in the parse tree.  Is this a normal phenomenon? As a beginner, I don't know much about this.

**Comment by enen1** [comment]
> The number of tokens will be 0 if the program has  #define.
> Maybe the '#' Whitespace? 'define' ~[#]* in line 896 should be '#' Whitespace? 'define' ~[\r\n]*?
> 
> Hello, thank you for your issue. I used your changes and now I can successfully get the parse tree. However, I found that there is no define in the parse tree.  Is this a normal phenomenon? As a beginner, I don't know much about this.


The compilation of C program includes four processes: Preprpcessing, Compilation, Assemble, Linking
During the preprocessing phase, some commands including `#define` are processed.
For example, if you have` #define ENG_PATH C:\Program`,then all `ENG_PATH` will be replaced by `C:\Program` and `#define ENG_PATH C:\Program` will be deleted.
C.g4 is used in compilation phase. Normally, When you use it, there should be no `#define` in your program. So, it doesn't know how to handle `#define` statement.
At that time, I just wanted to analyze a program in text level, so I modified C.g4. In fact, it's not formal.

**Comment by LauZyHou** [comment]
> > The number of tokens will be 0 if the program has  #define.
> > Maybe the '#' Whitespace? 'define' ~[#]* in line 896 should be '#' Whitespace? 'define' ~[\r\n]*?
> > Hello, thank you for your issue. I used your changes and now I can successfully get the parse tree. However, I found that there is no define in the parse tree.  Is this a normal phenomenon? As a beginner, I don't know much about this.
> 
> The compilation of C program includes four processes: Preprpcessing, Compilation, Assemble, Linking
> During the preprocessing phase, some commands including `#define` are processed.
> For example, if you have` #define ENG_PATH C:\Program`,then all `ENG_PATH` will be replaced by `C:\Program` and `#define ENG_PATH C:\Program` will be deleted.
> C.g4 is used in compilation phase. Normally, When you use it, there should be no `#define` in your program. So, it doesn't know how to handle `#define` statement.
> At that time, I just wanted to analyze a program in text level, so I modified C.g4. In fact, it's not formal.

No wonder! Thank you very much!
