### ISSUE TITLE
Clean up Python3 runtime code generation

### ISSUE THREAD

**Issue by david-29** [antlr/grammars-v4#1613]
Some baby steps to get rid of  a lot of the PEP-8 warnings in antlr-python3-runtime. This will get rid of noise when loading the ANTLR generated lexers, parsers, listeners and visitors into PyCharm and other IDE's that can enable Python PEP-8 standards checking. After that, we can focus on more serious issues in the generated code.  [Let me add that I don't endorse full compliance with PEP-8. There are some problematic issues with the standard. That's another discussion. But, many Python coders use it, so a tool designed to help most Pythonistas should generally follow that standard.]

1. Use one blank line to separate class methods, not many.

2. When separating code within methods, use one blank line, not many.

3. Use one space after a colon that introduces a type definition.

4. Use one space before and after a '=' that introduces a default value or an assignment of a value to a variable. Similarly, one space before and after other Python binary operators (e.g. '==', etc.)
      e.g. for 3 & 4:
           from:   `parent:ParserRuleContext=None,`
               to:     `parent: ParserRuleContext = None,`

5. Don't add extraneous spaces after '(' and before ')'.  Ditto for '[' .. ']' and '{' .. '}'.
      e.g.   `if hasattr( listener, "exitSymbolRef" ):`
          should be:    `if hasattr(listener, "exitSymbolRef"):`

6. This last one may be harder, can be deferred.  Define tagged fields in their class's __init__() method, not in class methods.
    e.g.: 
      `def vLineSubDirective(self):
        localctx = BasePfmtParser.VLineSubDirectiveContext(self, self._ctx, self.state)
        self.enterRule(localctx, 150, self.RULE_vLineSubDirective)
        self._la = 0 # Token type`

     here, `self._la` should be defined in `VLineSubDirectiveContext.__init__()`, not in
           `vLineSubDirective(self)`

I believe that the above presumably easy fixes (ex #6) would get rid of 80 - 90% of the current warnings in PyCharm for the generated code.

**Comment by KvanTTT** [comment]
It's an issue for ANTLR parser generator: https://github.com/antlr/antlr4/issues
