### ISSUE TITLE
Forward declarations in ANTLR4-python3-runtime

### ISSUE THREAD

**Issue by david-29** [antlr/grammars-v4#1614]
The following code is problematic for the MyPy lint checker:

```python
# need forward declaration
ParserRuleContext = None

class ParserRuleContext(RuleContext):
    def __init__(self, parent: ParserRuleContext = None, invokingStateNumber:int = None ):
```

It generates a cascade of hundreds of warnings throughout user-generated code.

The proper way to do this in Python3 is:

```python
class ParserRuleContext(RuleContext):
    def __init__(self, parent: 'ParserRuleContext' = None, invokingStateNumber: int = None ):
```

i.e. by making the current class name a literal string that signals the compiler that this is a type name that will be filled in later.

cf. PEP 484, 'Forward References':
                [https://www.python.org/dev/peps/pep-0484/#forward-references](url)

**Comment by KvanTTT** [comment]
As I understand, it is related to parser generator, not grammar. You should move your issue to another tracker: https://github.com/antlr/antlr4/issues
