### ISSUE TITLE
Upgrade from v3 to v4

### ISSUE THREAD

**Issue by zilipp** [antlr/grammars-v4#1615]
This is my grammar code from a previous version of antlr. 
`statement returns [Statement value]
    : s=base_statement       { $value = s; }
      ( ';' s=base_statement { $value = new SeqStatement($value,s); } )*
    ;`

However, the grammar is not supported by antlr v4. Specifically, s is not identified. I got the following error in Parser.java. `error: cannot find symbol ((StatementContext)_localctx).value =  new SeqStatement(_localctx.value,s);`

**Comment by KvanTTT** [comment]
What grammar do you mean?

**Comment by teverett** [comment]
@zilipp closing this since we don't know which grammar you mean.
