### ISSUE TITLE
Scala Grammar has issue over import statements

### ISSUE THREAD

**Issue by igvls** [antlr/grammars-v4#1617]
Antlr cannot parse scala scripts with import statements. If there are no import statements, I'm able to parse the Scala code. I assume there is some issue with Scala grammar, had verified it with **GRUN**. 

Kindly verify the grammar & help by providing a right Scala grammar (or) provide a workaround solution for this issue. @teverett  @KvanTTT

Enclosed sample code below which I could parse using Antlr,

```scala
package  xxx.yy.zz.aa.bb.commons.transformation
import  xxx.yy.zz.aa.bb.commons.constants.Forms
import  xxx.yy.zz.aa.core.configuration.KingTransformation
import  xxx.yy.zz.aa.core.engine.ProcessStatus
import xxx.yy.zz.aa.core.transformation.TransformationTrait
import org.apache.spark.sql.DataFrame
import org.apache.spark.sql.functions._
class AddingHoldingFlag1(val transformation: KingTransformation) extends TransformationTrait{
  def runTransformation: DataFrame = {
    val previousDF = ProcessStatus.components(transformation.previous.get(0))
    val outPutDataframe = addingHoldingFlag1(previousDF)
    outPutDataframe
  }
  def addingHoldingFlag1(previousDF: DataFrame): DataFrame = {
    // adding holding flag field when a customer has at least one account valid and is in scope for CS
    val addingFlag = previousDF
      .withColumn(Forms.HOLD_1, when(col(Forms.capamer).contains("WER") && col(Forms.FLCOUNT) === 1, lit("YES"))
      .otherwise(lit("NO")))
    addingFlag
    }
}
```

**Comment by studentmain** [comment]
minimal reproduce:
```
import a.b.c // work
import a.b // not work
```

**Comment by loonydev** [comment]
Hi, hah, I will check

**Comment by studentmain** [comment]
> 
> 
> Hi, hah, I will check

Just some info: problem not only in import statement. Grammar can't parse multiple topStmt when they aren't split by ';'

**Comment by loonydev** [comment]
Yep, but `topStatSeq` works incorrect. Parse only firs line. (of course some small changes in `stableId`)

My changes parse well this example
```
topStatSeq
   : topStat (Sep? topStat)*
   ;
```

**Comment by igvls** [comment]
Hi,
Even after doing a minimal import the parser fails to traverse the entire code.
I think the Scala grammar has some more issues that to be debug & tested.

Below are the example,
1. Without minimal import statements,
![image](https://user-images.githubusercontent.com/16795479/72888854-6b89ad00-3d34-11ea-98f2-1538effcaf24.png)

2. With minimal import statements, Here parse fails at **when** keyword
![image](https://user-images.githubusercontent.com/16795479/72888818-5876dd00-3d34-11ea-95ac-ae3f2f67c588.png)

Kindly look into it. Thanks!

**Comment by loonydev** [comment]
I already fix import (not commited yet), at this time I trying understand why he ignore class block... But yes, this grammar not organized, haven't clear test, etc.

**Comment by igvls** [comment]
@loonydev I tried to change the **_topStatSeq_** as you commented above, but now Antlr fails to generate the parser.
Enclosed Antlr response below for your reference,

```
> java org.antlr.v4.Tool Scala.g4
> error(153): Scala.g4:512:0: rule topStatSeq contains a closure with at least one alternative that can match an empty string
```

**Comment by igvls** [comment]
@loonydev @studentmain 
Import statements like this will make your grammar fail again.
**`> import org.apache.spark.sql.{DataFrame, Row, functions}`**

**Comment by loonydev** [comment]
Still work on it

**Comment by loonydev** [comment]
When this grammar was copied from EBNF, they missed that [] - it's option in EBNF. So grammar have a lot of error like "It's not an integer, cause haven't 'L' or 'l' in the end, but it's optional.

**Comment by loonydev** [comment]
@igvls FP in PR. You can check the result.

**Comment by igvls** [comment]
> @igvls FP in PR. You can check the result.

Thank you. It really helps a lot. @loonydev

**Comment by loonydev** [comment]
Hi @igvls
Check new grammar in PR. Maybe you have another gap?
