### ISSUE TITLE
Scala Grammar - Issue with direct value assignment

### ISSUE THREAD

**Issue by igvls** [antlr/grammars-v4#1623]
Hi @loonydev,

Antlr fails to parse the following code. Kindly verify,

```scala
package uuu.vvv.www.xxx.yyy.zzz

object Fields {
    val a : String = "Apple"
    val b : String = "Ball"
}

Thanks!
```

**Comment by loonydev** [comment]
Hi, 
Yep, checking, good findings.

**Comment by igvls** [comment]
Hi @loonydev ,

I got a RecursionError. 
1. If usage is `hiveContext.sql("DROP DATABASE IF EXISTS demo_test_app CASCADE")` -**PARSE SUCCESS**
2. If usage is `hiveContext.sql("""DROP DATABASE IF EXISTS demo_test_app CASCADE""")` -**PARSE FAILED**

Antlr fails to parse the following code,
```scala
package uuu.vvv.www.xxx.yyy.zzzz
import java.math.BigDecimal
import org.apache.spark.sql.hive.HiveContext

object CreateTable extends CreateTableInterface {
    def execute (hiveContext: HiveContext) = {
        hiveContext.sql("""DROP DATABASE IF EXISTS demo_test_app CASCADE""")
    }
}
```

Kindly help. Thanks!

**Comment by loonydev** [comment]
Thanks, fixed in PR

**Comment by igvls** [comment]
Hi @loonydev & @studentmain,

I found that 
- use of tab inside docstring """**_< tab >_**""" - fails to parse.
```scala
object Test 
{
    // Main Method 
    def main(args: Array[String]) 
    {
        println("""Hello	World!""") 
    }
}
```
- use of comment _**/* < code > */**_ - fail to parse
```scala
/*object Test 
{
    // Main Method 
    def main(args: Array[String]) 
    {
        println("""Hello	World!""") 
    }
}*/
```
`line 8:3 mismatched input '<EOF>' expecting {'implicit', 'lazy', 'case', '@', 'override', 'abstract', 'final', 'sealed', 'private', 'protected', 'import', 'class', 'object', 'trait', 'package'}
compilationUnit`

**Comment by loonydev** [comment]
Second case is invalid. You tried to parse empty file. Minimum it's have package construction. Parsing of `\* *\` in code works well.

First case fix soon.

**Comment by igvls** [comment]
Understood!
Thanks @loonydev
