### ISSUE TITLE
Scala Grammer - Issue with use of tab & doc string comment

### ISSUE THREAD

**Issue by gokulvenkats** [antlr/grammars-v4#1625]
Hi @loonydev & @studentmain,

I found that 
- use of tab inside docstring """**_< tab >_**""" - fails to parse.
```scala
object Test 
{
    // Main Method 
    def main(args: Array[String]) 
    {
        println("""Hello	World!""") 
    }
}
```
- use of comment _**/* < code > */**_ - fail to parse
```scala
/*object Test 
{
    // Main Method 
    def main(args: Array[String]) 
    {
        println("""Hello	World!""") 
    }
}*/
```
**Error Message:** `line 8:3 mismatched input '<EOF>' expecting {'implicit', 'lazy', 'case', '@', 'override', 'abstract', 'final', 'sealed', 'private', 'protected', 'import', 'class', 'object', 'trait', 'package'}
compilationUnit`

**Comment by loonydev** [comment]
No need to create new issue. You can reopen previous.

**Comment by igvls** [comment]
Hi @loonydev ,
I thought this is a different issue. So, I created a new one. Apologies!

Here is a another scenario where parsing fails,
- use of tab double quotes inside docstring """**_< " >_**""" - fails to parse. Enclosed a valid example below.
```scala
object Helloworld 
{
    // Main Method 
    def main(args: Array[String]) 
    {
        println("""
                  | CREATE TABLE retail(id string)
                  | WITH SERDEPROPERTIES ('separatorChar' = '"'
                """)
    }
}
```

**Comment by loonydev** [comment]
Fixed in my [fork](https://github.com/loonydev/grammars-v4/tree/fix-1623). Review pls.

**Comment by loonydev** [comment]
Hi @igvls do you check it done?

**Comment by igvls** [comment]
Hi @loonydev,
I am still testing, I found one issue. I'll let you know shortly. Working on it.

**Comment by igvls** [comment]
Hi @loonydev,

I found an issue with simpleExpr & literal - any([a-z]""" """) fails parsing.
Here,
`hiveContext.sql("""SELECT * FROM Table""")` - PARSE SUCCESS
`hiveContext.sql(s"""SELECT * FROM Table""")` - PARSE FAILED

Sample code below,
```scala
import java.io.File
import www.ccc.utils.JRMParam
import org.apache.spark.sql.hive.HiveContext

object RefExe extends RefExeInterface {
    def execute (hiveContext: HiveContext) = {
        val separator = File.separator
        val date=JRMParam.getODate
        val sourcePropPath = s"LOAD DATA LOCAL INPATH 'home${separator}src${separator}test${separator}resources${separator}sourceData${separator}"
        val dataFileName = "sales_partitions.csv"
        // hiveContext.sql("""SELECT * FROM Table""")
        //Load csv to the initial table
        hiveContext.sql("${sourcePropPath}${dataFileName}' into table sales_partitions PARTITION (date_processed='${date}')")
    }
}
```

Kindly verify. Thanks!

**Comment by loonydev** [comment]
Thanks,
Fix easy (FP in my fork) by add `'s'?` in `StringLiteral`, but this grammar not parse the variable in `s"$variableName"` or `s"${block_of_code}"` in this literal. 

I need a time, to move it from fragment to rule and add a variable and block parsing.

**Comment by igvls** [comment]
Thanks @loonydev,
Updated grammar is parsing mostly all Scala scripts except `s"${block_of_code}"`. 👍 
I'll report if I find any new issues.

**Comment by igvls** [comment]
Hi @loonydev,

I found one more issue with comment, i.e., comment of comments is not parsed.
Example:
**```/* /* <block of code comment> */ */``` - Parse Fails.**

**Comment by KvanTTT** [comment]
I suppose the following rule:

```g4
COMMENT
   :   '/*' .*? '*/' -> skip
   ;
```

should be replaced with the following one:

```
COMMENT
   :   '/*' (COMMENT | .)* '*/' -> skip
   ;
```

**Comment by loonydev** [comment]
Mmm, not really, we need to move it from Lexer to Parser, cause inside comment block can be a `block` rule or something. Yes, currently it's ignoring, but no the problem.

Btw, I haven't time, so if somebody want to fix it, you can use my fork with last changes.

**Comment by igvls** [comment]
Antlr thrown a warning 
`warning(131): Scala.g4:1347:25: greedy block ()* contains wildcard; the non-greedy syntax ()*? may be preferred`

So, I have modified the rule as below,
```antlr
COMMENT
   :   '/*' (COMMENT | .)*? '*/' -> skip
   ;
```

Is this right? @loonydev @KvanTTT

**Comment by KvanTTT** [comment]
Sorry, my mistake. I think non-greedy syntax is not required here. Try the following:

```g4
COMMENT
   :   '/*' (COMMENT | .)* '*/' -> skip
   ;
```
