### ISSUE TITLE
ECMAScript.g4 and ECMAScript.CSharpTarget.g4 use _input member, that hasn't been declared

### ISSUE THREAD

**Issue by saqw3r** [antlr/grammars-v4#165]
My target is a generated code for C# and when I generated it using ECMAScript.CSharpTarget.g4, I've found that it raise compilations errors like "The name '_input' does not exist in the current context". So, the name variable '_input' nowhere declared. And I don't know what type it could be to fix it.

**Comment by parrt** [comment]
There are likely java actions in there. you'll have to remove those.
