### ISSUE TITLE
"error(8): scala.g4:34:8: grammar name Scala and file name scala.g4 differ"

### ISSUE THREAD

**Issue by samuela** [antlr/grammars-v4#166]
```
$ antlr4 scala.g4
error(8): scala.g4:34:8: grammar name Scala and file name scala.g4 differ
```

I believe this should just be a matter of renaming `scala.g4` to `Scala.g4`.

**Comment by superraz375** [comment]
I can confirm this.
I created a pull request for this here: https://github.com/antlr/grammars-v4/pull/167

**Comment by shiva10162** [comment]
i believe there is still a problem with scala grammar . can anyone please confirm ? I am not able to parse scala file with antlr4 and scala grammar. It doesn't give me correct tokens.
