### ISSUE TITLE
Scala Grammar - Issue with argumentExprs

### ISSUE THREAD

**Issue by gokulvenkats** [antlr/grammars-v4#1660]
Hi @loonydev @studentmain ,

Scala grammar fails to parse argument expression with `{}` 
map () - is parsed 
map{} -  is failed.
Kindly help

enclosed the following code.
```scala
val connectedLAN : Array[String,String] = connectedWAN.collect().map{r => (res(0).toString,res(1).toString)}
```

Thanks!

**Comment by igvls** [comment]
Hi @KvanTTT @loonydev ,

I have modified the existing grammar to fix this issue, can you confirm its correct,
```antlr 
argumentExprs
   : ('(' | '{') exprs? ('}' | ')')
   | ('(' | '{') (exprs ',')? postfixExpr ':' '_' '*' ('}' | ')')
   | NL? blockExpr
   ;
```

![image](https://user-images.githubusercontent.com/16795479/76746689-e81d9280-679d-11ea-9d30-5d2ed8c64e71.png)


Thanks!

**Comment by studentmain** [comment]
then `map{)` will work...

use this
```antlr
argumentExprs
    : '(' args ')'
    | '{' args '}'
    | NL? blockExpr
    ;

args
    : exprs?
    | (exprs ',')? postfixExpr ':' '_' '*' // should be (':' | '_' | '*') ?
    ;
```

**Comment by igvls** [comment]
Thanks @studentmain !

**Comment by KvanTTT** [comment]
I agree with @studentmain. Could somebody make a pull request?

**Comment by gokulvenkats** [comment]
Hi,
@KvanTTT and @studentmain I have raised a PR.

**Comment by gokulvenkats** [comment]
Fixed in PR-1998
