### ISSUE TITLE
JavaScript does not detect static class members

### ISSUE THREAD

**Issue by asadcr** [antlr/grammars-v4#1665]
See following snippet

```js
import React from 'react';
import PropTypes from 'prop-types';

import ReactGA from 'react-ga';

const hasGAId = !!process.env.REACT_APP_GOOGLE_ANALYTICS;

if (hasGAId) {
  ReactGA.initialize(process.env.REACT_APP_GOOGLE_ANALYTICS);
}

class GAListener extends React.Component {

    static contextTypes = {
        router: PropTypes.object,
      };
      
      componentDidMount() {
    if (hasGAId) {
      this.sendPageView(this.context.router.history.location);
      this.context.router.history.listen(this.sendPageView);
    }
  }

  sendPageView(location) {
    ReactGA.set({ page: location.pathname });
    ReactGA.pageview(location.pathname);
  }

  render() {
    return this.props.children;
  }
}

export default GAListener;
```

this static member doesn't seem to be detected properly.

```js
static contextTypes = {
        router: PropTypes.object,
      };
```

**Comment by asadcr** [comment]
This grammar is being used `https://github.com/antlr/grammars-v4/tree/master/javascript/javascript`

**Comment by asadcr** [comment]
Also the import 
`import React from 'react';` is not getting identified
I believe that can be supported by replacing this
https://github.com/antlr/grammars-v4/blob/master/javascript/javascript/JavaScriptParser.g4#L94-L96
With
```antlr
importNamespace
    : '*' (As identifierName)?
    | identifierName (As identifierName)?
    ;
```

**Comment by KvanTTT** [comment]
Could you suggest a pull request with your fixes?

**Comment by KvanTTT** [comment]
Could you add a link to JS doc with such a feature (static class members)?

**Comment by asadcr** [comment]
@KvanTTT https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_fields

**Comment by asadcr** [comment]
@KvanTTT I see that the fixes are being done in https://github.com/KvanTTT/grammars-v4 Fork. Will this Fork be merged back to master ?

**Comment by KvanTTT** [comment]
Yes, my PR https://github.com/antlr/grammars-v4/pull/1669 fixes this case. You can also take a look.
