### ISSUE TITLE
Support for React JS Components HTML Tags

### ISSUE THREAD

**Issue by asadcr** [antlr/grammars-v4#1671]
Hi Guys, any plans to supporting HTML Tags for JavaScript Grammar.
A common convention in ReactJs

See the following Snippet
https://github.com/project-bobon/bobonroastprofile/blob/master/src/components/utils/Button.jsx

**Comment by KvanTTT** [comment]
I think it's quite complicated syntax to support. It looks like HTML islands inside JavaScript code. Not sure we'll support it soon.

**Comment by asadcr** [comment]
I have added the support for HTML. The current grammar works perfectly for nested Js and Html syntax. Please take a look at PR #1672
