### ISSUE TITLE
PLSQL: ELSE followed by a WHILE token is not working

### ISSUE THREAD

**Issue by pepecaceres** [antlr/grammars-v4#1673]
The following code does not treat `ELSE` part.

```sql
IF ifcond THEN
    a := 1;
ELSE
    WHILE whilecond LOOP
        a := 3;
    END LOOP;
END IF;
```

However, following code does:

```sql
IF ifcond THEN
    a := 1;
ELSE
    a := 2;
    WHILE whilecond LOOP
        a := 3;
    END LOOP;
END IF;
```

So, we are not able to detect the ELSE part for the first sample and the WHILE part is intended to be part of the IF block instead of the ELSE one.

We are using version 4.8

**Comment by mcpiroman** [comment]
Looks like it works on 4.9.1
