### ISSUE TITLE
Do you have the  grammars of velocity?

### ISSUE THREAD

**Issue by wenkang-du** [antlr/grammars-v4#1677]

**Comment by KvanTTT** [comment]
No. You are welcome to implement it!

**Comment by teverett** [comment]
This might be a place to start

https://velocity.apache.org/engine/1.7/vtl-reference.html

**Comment by szymonkorytnicki** [comment]
@wenkang-du - I was looking for a grammar to generate AST, but it's exposed already here: https://gist.github.com/rednaxelafx/704698 - check `getInitedAST()`.
