### ISSUE TITLE
protobuf3 license missing

### ISSUE THREAD

**Issue by elelay** [antlr/grammars-v4#1694]
https://github.com/antlr/grammars-v4/blob/master/protobuf3/Protobuf3.g4 doesn't mention a license.

#1601 was closed stating that
> According to the notice at the bottom of that page, the original code is licensed under Apache2

but do you really mean that independent antlr code derived from the spec is governed by the licence on *examples* on that page? Seems far-fetched.

I guess @mwillema is the original author, with this [repo](https://github.com/mwillema/protobuf-parser) containing the original code. Would it be possible to specify a license? I know it's no fun but that prevents me from using it.

Thanks,

**Comment by anatawa12** [comment]
fixed in #2083. the new file has SPDX License heater.

**Comment by elelay** [comment]
Cool, thanks :+1:
