### ISSUE TITLE
Lua: special Assigment will report error 

### ISSUE THREAD

**Issue by yjhmelody** [antlr/grammars-v4#1701]
Maybe it's go runtime bug. I use the latest antlr4 go runtime.

```lua
// ok
foo().bar = "some"
// ok
foo(arg1, arg2).bar = "some"

// error
foo(arg1).bar = "some"
```
Yes, when functions get one arg, it reports error.

The error is:

```
line 35:13 reportAttemptingFullContext d=26 (variable), input='(1).bar="some"'
line 35:3 reportContextSensitivity d=26 (variable), input='('
```

**Comment by studentmain** [comment]
can you test it in grun so we can narrow down where the problem is?

**Comment by yjhmelody** [comment]
@studentmain 
I cannot run `grun` normally like the [doc](https://github.com/antlr/antlr4/blob/master/doc/getting-started.md).

```bash
grun Lua -tree
a = 1
No method for rule -tree or it has arguments
```

**Comment by yjhmelody** [comment]
Anything idea about resolving the problem?
@studentmain

**Comment by studentmain** [comment]
So we can assume it's problem of go runtime...

**Comment by yjhmelody** [comment]
more strange example:
```lua
//ok
foo.read().byte(2)

//err
foo.read(1).byte(2)

//err
foo.read(3).byte(2)
```
