### ISSUE TITLE
ANTLR CPP14 grammar template supporting

### ISSUE THREAD

**Issue by m-zakeri** [antlr/grammars-v4#1702]
The ANTLR grammar for CPP14 does not accept nested template, for example, such code can not be parsed by the current grammar:

```cpp
class A
{
std::vector<std::unique_ptr<Controller>> controller_list_;
};
```

**Comment by DonMathi** [comment]
For reference:
With a space in between > and > it parses, OK
```
class A
{
std::vector<std::unique_ptr<Controller> > controller_list_;
};
```

**Comment by m-zakeri** [comment]
It's ok but how can I resolve this issue within the grammar? I have a huge source code.

**Comment by DonMathi** [comment]
How is it going?
I have been thinking about how it maybe should be done. Two template '<' pushes the lexer into sub rules. But if there could be a way to detect if an expression with a possible '>>' then maybe the lexer should be pushed into a sub-sub set of rules, until the expression ends. If the expression possible includes two template '<' then it should push the lexer into the sub-rule for the second time, and so on.

**Comment by romeo-cmd** [comment]
I got the same issue and solved it by changing lexer rule `RightShift` into parser rule `rightshift : '>' '>'` and change every reference to `RightShift` into a reference to `rightshift`.

**Comment by KvanTTT** [comment]
Yes, there is another issue for reference: https://github.com/antlr/grammars-v4/issues/1753

**Comment by DonMathi** [comment]
Here is a dummy example of the problem:
d is a variable of type a that has template parameter b, that has template parameter c right shifted 1.
`a< b< c>>1 > > d;`

Is there even any possible application for this?

**Comment by DonMathi** [comment]
Maybe this:
`std::array<std::array< int, 3>>1 >, 4>>2 > myArray{{1, 2},{3,4}};`

**Comment by romeo-cmd** [comment]
![antlr4_parse_tree](https://user-images.githubusercontent.com/61050967/84992942-e373cc00-b148-11ea-915b-02437c95a29e.png)
You are right it's an interesting point.

However I think that with enough lookup the parser is able to ditinguish the rightshift operator from the end of the template. Indeed, when parsing the rightshift operator `3>>` the parser find two matching rules in the rule table but then the hypothesis of rightshift operator rule is left because of the next double `>>` .

To be sure I tested your first example and obtained the good parse tree, as you can see in the attached document.

**Comment by DonMathi** [comment]
What is the purpose of the 3rd expansion in 
`memberdeclarator
   : declarator virtspecifierseq? purespecifier?
   | declarator braceorequalinitializer?
   | Identifier? attributespecifierseq? ':' constantexpression
   ;
`
This makes this valid:
`class A {
    :1;
};`

**Comment by Marti2203** [comment]
> What is the purpose of the 3rd expansion in
> 
> ```
> memberdeclarator
>    : declarator virtspecifierseq? purespecifier?
>    | declarator braceorequalinitializer?
>    | Identifier? attributespecifierseq? ':' constantexpression
>    ;
> ```
> 
> This makes this valid:
> `class A { :1; };`

I think that it should be `class A {int a :1;}` for bitfields?

**Comment by Marti2203** [comment]
@DonMathi

**Comment by Marti2203** [comment]
The issue was that declarations had a lower precedence than expressions in the statement rule, I just changed this and the string `std::array<std::array<int,3>>1> > myArray{{1,2},{3,4}};` is parsed properly.
