### ISSUE TITLE
smiles : scandium and Sulfur/carbon ambiguity

### ISSUE THREAD

**Issue by luvf** [antlr/grammars-v4#1705]
the Input `Sc`
is lexed 'Sc' and get a parsing error since Scandium is an `element_symbols`  and can only be seen in a bracket : `[Sc]`
and `Sc` shoud be lexed as `S`, `c`  for Sulfur `aliphatic_organic` and carbon `aromatic_organic`

For my project I have fixed this By removing `Sc` since it never occurs in my datas.
Futhermore there is probably other ambiguity of that kind that can appear.

**Comment by teverett** [comment]
@luvf  could you post an example that has the problem please?

**Comment by luvf** [comment]
`Sc` should be enough
'C1CN2CCC1C(C2)CN3c4ccccc4Sc5ccccc35` (mequitazine) should fail

**Comment by teverett** [comment]
Does this look right?

(smiles (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (chain (branched_atom (atom (aliphatic_organic C)) (ringbond 1))) (branched_atom (atom (aliphatic_organic C)))) (branched_atom (atom (aliphatic_organic N)) (ringbond 2))) (branched_atom (atom (aliphatic_organic C)))) (branched_atom (atom (aliphatic_organic C)))) (branched_atom (atom (aliphatic_organic C)) (ringbond 1))) (branched_atom (atom (aliphatic_organic C)) (branch ( (chain (branched_atom (atom (aliphatic_organic C)) (ringbond 2))) )))) (branched_atom (atom (aliphatic_organic C)))) (branched_atom (atom (aliphatic_organic N)) (ringbond 3))) (branched_atom (atom (aromatic_organic c)) (ringbond 4))) (branched_atom (atom (aromatic_organic c)))) (branched_atom (atom (aromatic_organic c)))) (branched_atom (atom (aromatic_organic c)))) (branched_atom (atom (aromatic_organic c)))) (branched_atom (atom (aromatic_organic c)) (ringbond 4))) (branched_atom (atom (aliphatic_organic S)))) (branched_atom (atom (aromatic_organic c)) (ringbond 5))) (branched_atom (atom (aromatic_organic c)))) (branched_atom (atom (aromatic_organic c)))) (branched_atom (atom (aromatic_organic c)))) (branched_atom (atom (aromatic_organic c)))) (branched_atom (atom (aromatic_organic c)) (ringbond 3) (ringbond 5))) (terminator \n))

**Comment by luvf** [comment]
yes it looks right

**Comment by teverett** [comment]
@luvf I'll close this defect.  Feel free to try the latest version and to submit more tickets.  Thanks for reporting this issue.

**Comment by luvf** [comment]
thanks will try this
