### ISSUE TITLE
Is it possible to write a grammer for english? 

### ISSUE THREAD

**Issue by mttbx** [antlr/grammars-v4#1710]
Is it possible to write a grammer for english? We don't need to write all words in lexer just the grammar.

**Comment by loonydev** [comment]
Hi @mttbx, it's a good question, but I guess no. 
For example, how to determinate a/the/<whitespace> before word, without the context of this word. Also we can't define time, without analyzing ends of the words.

For this case you can check books about natural language processing, like this one "Natural Language Processing with Python"

**Comment by KvanTTT** [comment]
It's impossible because there are plenty of context issues and ambiguities in any natural language.

**Comment by mttbx** [comment]
Thank you for your reply!
