### ISSUE TITLE
looking for AIDL(Android Interface Definition Language) grammar files

### ISSUE THREAD

**Issue by William-Wang1988** [antlr/grammars-v4#1715]
Hi, I'm looking for **AIDL**([Android Interface Definition Language](https://developer.android.com/guide/components/aidl#java)) grammar files, which is a pretty simple language. Would you like to give any solution to it? I would appreciate it if you could offer some help.

**Comment by AmesingFlank** [comment]
Hi! @wil1iam   I see that this issue is marked as completed, but I don't see any AIDL grammars in the repo. Any ideas where I can find it?
