### ISSUE TITLE
IDL grammar extended for IDL4

### ISSUE THREAD

**Issue by okellogg** [antlr/grammars-v4#1723]
Hi,

I extended [idl/IDL.g4](https://github.com/antlr/grammars-v4/blob/master/idl/IDL.g4) for [IDL4](https://www.omg.org/spec/IDL/4.2/PDF) [annotation](http://okellogg.de/omg/idl4.html#p109) applications, see the attachment [IDL.g4.diff.gz](https://github.com/antlr/grammars-v4/files/4640866/IDL.g4.diff.gz).

The extension does change the way some of the elements are accessed by visitors.
For example, beside `ID` there is a new rule `identifier` which prefixes optional annotations before the ID.
Thus, when a visitor previously accessed
```
  some_name.ID()
```
that may need to be changed to
```
  some_name.identifier().ID()
```

Since the extended grammar is not compatible for visitors, my question is:
Shall I make a new file "IDL4.g4" for the extended grammar instead of modifying the existing IDL.g4 file ?

**Comment by KvanTTT** [comment]
> Shall I make a new file "IDL4.g4" for the extended grammar instead of modifying the existing IDL.g4 file ?

I think the best way is to modify existing grammar because new features have more priority compare to visitors back compatibility.

**Comment by okellogg** [comment]
Thanks @KvanTTT.
I am integrating the work from eProsima at
https://github.com/eProsima/IDL-Parser/blob/master/src/main/antlr4/omg/com/eprosima/idl/parser/grammar/IDL.g4
to make a more general update to IDL4, not just for the annotations.
I am currently testing this and hope to make a pull request in a few days.

**Comment by okellogg** [comment]
Thanks for merging.

**Comment by Johnnyxy** [comment]
Hi @okellogg,
I am interested in the work you have done to the current IDL grammar.
My work mainly employs Vortex OpenSplice and RTI Connext DDS. Thus I am trying to stick to the standard when parsing IDL files.

I have gone through the OMG standard IDL v4.2 ([here](https://www.omg.org/spec/IDL/4.2/PDF)) and your modifications to the g4 rules and have some question which came up (until now :) ).

You have added a non standard rule "annapps" to several other rules. This contradicts the OMG standard rules (e.g. definition, const_type, ...). It looks like some kind of extension and does not change the outcome of standard comforming IDL files. Could you elaborate what is the reason behind this? Maybe I have overseen something.

This is directly related to the ```identifier``` rule you have introduced. Could you elaborate this too?



Best regards :)

**Comment by okellogg** [comment]
Hello @Johnnyxy,

The [IDL 4.2](https://www.omg.org/spec/IDL/4.2/PDF) standard defines the rule [annotation_appl](http://okellogg.de/omg/idl4.html#annotation-appl) but does not define usage of this rule within the EBNF.
It only gives a usage rule in prose; see page 100,

>An annotation may be applied to any IDL constructs or sub-constructs.
>Applying an annotation consists actually in adding the related meta-data to the element under annotation.

An issue has been raised at OMG to further discuss this, see https://issues.omg.org/browse/IDL43-27

The similar problem exists for `identifier` which also is only defined in prose, not in a formal grammar rule.
See section [7.2.3](http://okellogg.de/omg/idl4.html#p18),

> An identifier is an arbitrarily long sequence of ASCII alphabetic, digit and underscore (_) characters.
> The first character must be an ASCII alphabetic character. All characters are significant.

**Comment by Johnnyxy** [comment]
Ah. Thanks for the clarification.
It looks like you are deep in the standard. Would it be possible to reach out to you by some other means? As this issue is not qualified as Q&A.

**Comment by okellogg** [comment]
How about using [comp.object.corba](https://groups.google.com/g/comp.object.corba)? That way others may chime in.

**Comment by Johnnyxy** [comment]
Ok, I will have a look. Thanks.
