### ISSUE TITLE
New Grammar: VMF (Valve Map File)

### ISSUE THREAD

**Issue by ReikaKalseki** [antlr/grammars-v4#1730]
I am back with another request for a new grammar. This time for VMF files, which are the main map files for most (possibly all) Valve games, like Portal, TF2, and CS:GO. Despite being called "map" files, they often describe *parts* of maps, like a given test element in a Portal test chamber.

The actual format is pretty simple, being a text file divided into a number of "named blocks", ie a titled {} block with some values inside. Every VMF has a few "header" and "footer" blocks which are mostly consistent in structure, and then a bunch of world/entity blocks which represent the actual contents of the map (brushes and entities respectively).

For example, here is a copy of the VMF defining a [cube dropper](https://i1.theportalwiki.net/img/9/98/Vital_Apparatus_Vent_Portal_2.png): https://pastebin.com/iRg5AwUA

The blocks like `versioninfo` and `viewsettings` are the headers; `world` and `entity` describe the brushes/entities (the former being defined as `solid` blocks inside the `world` one), and their appropriate data, and the `cameras` and `cordons` are the footer blocks.

**Comment by ReikaKalseki** [comment]
Some more info:

https://developer.valvesoftware.com/wiki/KeyValues

**Comment by teverett** [comment]
@ReikaKalseki  pls take a look at PR #1732

**Comment by ReikaKalseki** [comment]
I looked at it, but lack the functional understanding to interpret it beyond "yay, it is planned". :P

**Comment by teverett** [comment]
@ReikaKalseki  the grammar is there now.   I'll close this PR and you can open a new one if you find issues.
