### ISSUE TITLE
CPP14 grammar does not allow const reference

### ISSUE THREAD

**Issue by romeo-cmd** [antlr/grammars-v4#1762]
The syntax `MyClass &const myclass;` is not allowed by the grammar because of the rule

```g4
ptroperator
   : '*' attributespecifierseq? cvqualifierseq?
   | '&' attributespecifierseq?
   | '&&' attributespecifierseq?
   | nestednamespecifier '*' attributespecifierseq? cvqualifierseq?
   ;
```

However I think it's a legal C++ code since it is compiled by my MSVC 2019 compiler. Therefore I would add `cvqualifier?` at the end of each rule concerning references.

**Comment by rafeeque1** [comment]
Please Close this, @rafeeque1
Updated Fixed -> CPP14 grammar does not allow const reference,
Already you merged the code, But Issue is still open.

**Comment by Marti2203** [comment]
@romeo-cmd  or @KvanTTT  time to close?
