### ISSUE TITLE
[CPP14 grammar] Unrecognized operator new[] 

### ISSUE THREAD

**Issue by romeo-cmd** [antlr/grammars-v4#1765]
The operator `new[]` is not recognized. For instance, the code `void* operator new[](size_t);` gives the following AST:

![antlr4_parse_tree](https://user-images.githubusercontent.com/61050967/85879606-f0448f80-b7da-11ea-8350-c01a02f04536.png)

which is a wrong interpretation since the operator is interpreted as an operator `new` and not `new[]`. Of course, this issue also raises with the operator `delete[]`.

To correct this, it is possible to replace the rule

```g4
theoperator
   : New
   | Delete
   | New '[' ']'
   | Delete '[' ']'
   ...
   ;
```

by the following:

```g4
theoperator
   : New
   | Delete
   | Newarray
   | Deletearray
   ...
   ;

Newarray
   : New '[' ']'
   ;

Deletearray
   : Delete '[' ']'
   ;
```

This allows the lexer to tokenize `new[]` as one plain token so that the parser is not able to split it and spread it through multiple rules.

**Comment by romeo-cmd** [comment]
For operator `delete[]`, the rule deleteexpression has also to be modified in order to handle this update.

**Comment by Marti2203** [comment]
This can be fixed more easily with just making the brackets optional, the issue is that `New` has a bigger precedence than `New LeftBracket RightBracket` and the grammar takes it. I am gonna add a fix now.
