### ISSUE TITLE
ECMAScript.g4 - problems with automatic semicolon insertion

### ISSUE THREAD

**Issue by cshapeshifter** [antlr/grammars-v4#179]
I'm not sure what exactly is going on, but I notice that even in very simple cases, automatic semicolon insertion is not working properly using the [ECMAScript grammar](https://github.com/antlr/grammars-v4/blob/master/ecmascript/ECMAScript.g4), and that the resulting trees are missing branches, essentially mangling follow-up lines into branch with the missing semicolon. I've created a test case gist [here](https://gist.github.com/cshapeshifter/5ff47f7652918e5a5717#file-broken-js)

The resulting output is included, but as long as java/javac is on the PATH, you can run the test case yourself by simply doing
```
git clone https://gist.github.com/5ff47f7652918e5a5717.git
cd 5ff47f7652918e5a5717
chmod +x run-test.bash
./run-test.bash
```
It will download antlr 4.5, generate the parser and use it to parse two files. One with semicolons, and one where some are missing. These are the two examples:

```
function Test() {
  o = {};
  o.n = "alice";
  o.n = null;
  o.n = "bob";
}
```
```
function Test() {
  o = {};
  o.n = "alice"
  o.n = null
  o.n = "bob"
}
```
In the second example, a lot of errors are printed and the resulting tree is essentially mangling the "null" and "bob" lines into the "alice" branch.
```
line 4:2 no viable alternative at input 'function Test() {\n  o = {};\n  o.n = "alice"\n  o'
line 1:16 extraneous input '{' expecting {'[', '(', ';', ',', '=', '?', '.', '++', '--', '+', '-', '*', '/', '%', '>>', '<<', '>>>', '<', '>', '<=', '>=', '==', '!=', '===', '!==', '&', '^', '|', '&&', '||', '*=', '/=', '%=', '+=', '-=', '<<=', '>>=', '>>>=', '&=', '^=', '|=', 'instanceof', 'in'}
line 4:2 extraneous input 'o' expecting {'[', '(', ';', ',', '=', '?', '.', '++', '--', '+', '-', '*', '/', '%', '>>', '<<', '>>>', '<', '>', '<=', '>=', '==', '!=', '===', '!==', '&', '^', '|', '&&', '||', '*=', '/=', '%=', '+=', '-=', '<<=', '>>=', '>>>=', '&=', '^=', '|=', 'instanceof', 'in'}
line 5:2 no viable alternative at input '.n = null\n  o'
line 5:2 extraneous input 'o' expecting {'[', '(', ';', ',', '=', '?', '.', '++', '--', '+', '-', '*', '/', '%', '>>', '<<', '>>>', '<', '>', '<=', '>=', '==', '!=', '===', '!==', '&', '^', '|', '&&', '||', '*=', '/=', '%=', '+=', '-=', '<<=', '>>=', '>>>=', '&=', '^=', '|=', 'instanceof', 'in'}
line 6:0 no viable alternative at input '.n = "bob"\n}'
line 6:0 mismatched input '}' expecting {'[', '(', ';', ',', '=', '?', '.', '++', '--', '+', '-', '*', '/', '%', '>>', '<<', '>>>', '<', '>', '<=', '>=', '==', '!=', '===', '!==', '&', '^', '|', '&&', '||', '*=', '/=', '%=', '+=', '-=', '<<=', '>>=', '>>>=', '&=', '^=', '|=', 'instanceof', 'in'}
(program (sourceElements sourceElement (sourceElement function) (sourceElement (statement (expressionStatement (expressionSequence (singleExpression (singleExpression Test) (arguments ( )))) <missing ';'>))) (sourceElement (statement (block { (statementList (statement (expressionStatement (expressionSequence (singleExpression (singleExpression o) = (expressionSequence (singleExpression (objectLiteral { }))))) ;)) (statement (expressionStatement (expressionSequence (singleExpression (singleExpression (singleExpression (singleExpression (singleExpression (singleExpression (singleExpression o) . (identifierName n)) = (expressionSequence (singleExpression (literal "alice") o))) . (identifierName n)) = (expressionSequence (singleExpression (literal null) o))) . (identifierName n)) = (expressionSequence (singleExpression (literal "bob"))))) <missing ';'>))) })))) <EOF>)
```
The gist also include an output of the tree as it should be (with 4 statement branches inside the block, instead of just 2).

**Comment by cshapeshifter** [comment]
I've added the PNGs generated by ANTLR:

Working (4 statements in a block): 
![working](https://cloud.githubusercontent.com/assets/3042135/8621548/73e4878c-2726-11e5-8269-4bb2500c63c9.png)

Broken (tree is mangled somehow):
![broken](https://cloud.githubusercontent.com/assets/3042135/8621547/73c408ea-2726-11e5-8e98-189c61455272.png)

**Comment by adrianherrera** [comment]
So I've had a bit of a look at this bug, and have gotten some ways towards solving it (see pull request #190).

For example, the following code now successfully parses:

```javascript
o = {};
o.n = "alice"
o.n = null
o.n = "bob"
```

But the following code (i.e. your test code) still does not successfully parse:

```javascript
function test(){
    o = {};
    o.n = "alice"
    o.n = null
    o.n = "bob"
}
```

Interestingly, the following code does successfully parse:

```javascript
function test(){
o = {};
o.n = "alice"
o.n = null
o.n = "bob"
}
```

But this code fails (note the indentation):

```javascript
    o = {};
    o.n = "alice
    o.n = null
    o.n = "bob"
```

Suggesting that there is still some sort of white space issue. I will continue looking into it and hopefully find a fix

**Comment by cshapeshifter** [comment]
Thanks for looking into this and for the tip about whitespaces. I was able to figure out what's happening:

In  ```lineTerminatorAhead()```, we look at the "previous" token on the token stream as such

```int possibleIndexEosToken = this.getCurrentToken().getTokenIndex() - 1;```

But the problem is that white space is also on the HIDDEN channel and with ```-1``` we're not going back far enough to discover the LineTerminator token and instead, we're looking at a WhiteSpaces token and return ```false```. So I rewrote ```lineTerminatorAhead()``` like this and that seems to work:

```
private boolean lineTerminatorAhead() {

    // Get the token ahead of the current index.
    int possibleIndexEosToken = this.getCurrentToken().getTokenIndex() - 1;
    Token ahead = _input.get(possibleIndexEosToken);

    if (ahead.getChannel() != Lexer.HIDDEN) {
        // We're only interested in tokens on the HIDDEN channel.
        return false;
    }

    if (ahead.getType() == LineTerminator) { return true; }

    if (ahead.getType() == WhiteSpaces) {
      possibleIndexEosToken = this.getCurrentToken().getTokenIndex() - 2;
      ahead = _input.get(possibleIndexEosToken);
    }

    String text = ahead.getText();
    int type = ahead.getType();

    // Check if the token is, or contains a line terminator.
    return (type == MultiLineComment && (text.contains("\r") || text.contains("\n"))) ||
            (type == LineTerminator);
}
```
But I'm not sure how this could interfere with the multi-line comment stuff.

**Comment by adrianherrera** [comment]
Cool, you beat me to it! I found the issue was with looking at the whitespace token in the ``lineTerminatorAhead`` method, but I hadn't found a fix yet.

I tested your code with the following test cases and none of them failed:

```javascript
function test() {
    var o;
    o.n = null
    o.n = "bob";
}
```

```javascript
function test() {
    var o;
    o.n = null
    o.n = "bob"
}
```

```javascript
function test() {
    var o;
    o.n = null
    o.n = "bob"
    }
```

```javascript
function test() {
    var o;
    o.n = null        // this is a comment
o.n = "bob"
}
```

```javascript
function test() {
    var o;
    o.n = null /* this is a multiline
comment */ o.n = "bob"
}
```

```javascript
function test() {
    var o;
    o.n = null /* this is a multiline
comment spread over
multiple lines
*/
    o.n = "bob"
}
```

So I think you've found the fix! I'll submit a pull request (including the ports to the C# and Python backends).

**Comment by cshapeshifter** [comment]
Fix is merged, I think we can close this. Thanks everyone.
