### ISSUE TITLE
License for LexerAdaptor.* is missing

### ISSUE THREAD

**Issue by onur-eken-celonis** [antlr/grammars-v4#1806]
Hello 

I would like to use antlr4 grammar parser in one of my projects. The relevant g4 files are provided with BSD licenses however the lexer file inherits from LexerAdaptor which does not specify any license. Could you address this problem?

In particular java implementation: https://github.com/antlr/grammars-v4/blob/master/antlr/antlr4/src/main/java/org/antlr/parser/antlr4/LexerAdaptor.java

Thanks!

**Comment by Marti2203** [comment]
Hello,
What seems to be the issue? You want to be sure what the license is? I think all of the files have the same license.

**Comment by onur-eken-celonis** [comment]
One needs `LexerAdaptor` code (which has implementations in various languages such as cpp, java etc.) in order to use provided .g4 files. These implementations do not have license header, as a result I cannot use the parser for ANTLR. Could you also add license headers to those files?

**Comment by onur-eken-celonis** [comment]
`LexerAdaptor` seems to be specific for the antlr3 and antlr4 grammars. Grammars for other languages seem to work standalone.
`https://github.com/antlr/grammars-v4/tree/master/antlr`

**Comment by Marti2203** [comment]
Okay. @KvanTTT I will add a BSD license to the files and do a pull request

**Comment by Marti2203** [comment]
I think this is done
