### ISSUE TITLE
How to detect null character in string?

### ISSUE THREAD

**Issue by avnibharne** [antlr/grammars-v4#181]
I am writing a lexer using eclipse IDE. I want to check if a string contains "null character".
Previously when i tried to write the same in Flex i used "\x00" to detect null character. I tried the same but it did not work. 
Currently for string constants i am using the following rule: 
STR_CONST :   '"'
        (   '\\'
            (   'n'     {buf.append('\n');}
            |   't'     {buf.append('\t');}
            |   'b'     {buf.append('\b');}
            |   'f'     {buf.append('\f');}
            |	'r'	{buf.append('\r');}
            |   '"'     {buf.append('\"');}
            |   '\''    {buf.append('\'');}
            |	'\\'	{buf.append('\\');}
            )
        |  ~('\\'|'"')  {buf.append((char)_input.LA(-1));}
        )*
        '"'

**Comment by parrt** [comment]
This is for bugs not questions.
