### ISSUE TITLE
Support for C++ .h headerfiles

### ISSUE THREAD

**Issue by Nos-** [antlr/grammars-v4#1820]
I tried to parse C++ with the great CPP-grammar and ran into some problems with ambiguousness. Parsing the .h files before the .cpp files should help. But there are some problems doing so. Maybe something is missing in the cpp-grammar to be able to parse C++ Headerfiles too.

**Comment by Marti2203** [comment]
Hi, I made a PR to the grammar yesterday. What do you mean exactly by issues with ambiguousness? That is an inherent issue in grammars that can define types and especially C++ where `f(b);` may be a function or constructor call.

**Comment by KvanTTT** [comment]
There is no difference between .cpp and .h files in terms of syntax. Your issue is probably related to C++ syntax.
