### ISSUE TITLE
Question about the Lua.g4

### ISSUE THREAD

**Issue by yldiscover** [antlr/grammars-v4#1827]
Hi, Why the Lua.g4 has some special modification of the BNF?

```antlr
prefixexp
    : varOrExp nameAndArgs*
    ;

functioncall
    : varOrExp nameAndArgs+
    ;

varOrExp
    : var | '(' exp ')'
    ;

var
    : (NAME | '(' exp ')' varSuffix) varSuffix*
    ;

varSuffix
    : nameAndArgs* ('[' exp ']' | '.' NAME)
    ;

nameAndArgs
    : (':' NAME)? args
    ;

And why the following definition is commented?
/*
var
    : NAME | prefixexp '[' exp ']' | prefixexp '.' NAME
    ;

prefixexp
    : var | functioncall | '(' exp ')'
    ;

functioncall
    : prefixexp args | prefixexp ':' NAME args
    ;
*/
```

**Comment by studentmain** [comment]
ANTLR can't handle left recursive well

**Comment by KvanTTT** [comment]
ANTLR handles left recursive, but direct. It can not handle indirect left recursion. Commented out code has such a case: `prefixexp -> functioncall`, `var -> prefixexp`.

**Comment by yldiscover** [comment]
Is there any general method to handle this kind of LR problem?

**Comment by KvanTTT** [comment]
Just rewrite rules without indirect left recursion. Or use another parsing approach (LR) where such recursion is not a problem, but other problems can take place.

**Comment by yldiscover** [comment]
> 
> 
> Just rewrite grammar without indirect left recursion. Or use another parsing approach (LR) where such recursion is not a problem, but other problems can take place.
Hi,
  1.  Could you show some example of rewrite grammar without indirect left recursion?
   2. another parsing approach? What do u mean? other tools?

**Comment by KvanTTT** [comment]
1. Read articles about removing left recursion. For instance, see Wikipedia: https://en.wikipedia.org/wiki/Left_recursion#Removing_left_recursion
 2. Yes, other tools that are based on other parsing algorithms.

**Comment by Marti2203** [comment]
This issue should be closed I think.
