### ISSUE TITLE
TSQLParser.g4 appears to be upper-case bound

### ISSUE THREAD

**Issue by Huwmungous** [antlr/grammars-v4#1828]
Forgive my cross-posting; I have a StackOverflow question [here](https://stackoverflow.com/questions/63577227/antlr4-tsqlparser-g4-tsqllexer-g4-case-sensitivity-issue)

I have a C# antlr target with the latest TSqlParser.g4 & TSqlLexer.g4 but it appears to be ignoring lowercase letters.

A stored procedure parameter defined `@ABC BIGINT` will be parsed correctly.  If the parameter is defined `@AbC BIGINT` this is interpreted as a Parameter `@A` datatype `C`.

I believe this to be a wider problem than just Stored Procedure parameters but am unsure if I am making som basic rookie error, or if there is a fundamental problem with the grammar.

**Comment by KvanTTT** [comment]
It works fine. Please read the doc https://github.com/antlr/antlr4/blob/master/doc/case-insensitive-lexing.md and use case insensitive stream `CaseChangingCharStream` (also, it's duplicate).
