### ISSUE TITLE
Question about "else if"

### ISSUE THREAD

**Issue by yldiscover** [antlr/grammars-v4#1853]
Hi, In Verilog2001.g4, the `else if` statement is written as:

```antlr
'if' '(' expression ')' function_statement_or_null ('else' 'if' '(' expression ')' function_statement_or_null)* ('else' function_statement_or_null)?
```

I wonder, why not combine `else` and `if` together to `else if`?

**Comment by Marti2203** [comment]
`else if` and `else` `if` have two different meanings - the first one requires exactly one space between them, while the second one does not require that. The proposal makes the grammar less flexible.

**Comment by Marti2203** [comment]
I think this issue can be closed? @yldiscover @KvanTTT
