### ISSUE TITLE
Introducing myself; asking about the CPP14 grammar

### ISSUE THREAD

**Issue by mycroft8** [antlr/grammars-v4#1862]
Hi... more on a hobby basis, I'm experimenting with writing my own "C/C++" compatible preprocessor, based on the lexer in the CPP14 grammar, and then overloading the "nextToken" method.  Just my idea of fun...
As I expected the CPP14 grammar can't handle a lot of special cases from gcc/g++/glibc, though I'm making progress.  I can handle some, but NOT ALL, glibc headers.
Just wondering if there would be any interest eventually in merging changes back.

One note: the definition of the Literal tokens in the lexer seems to break the parser "linkageSpecification" rule.  The parser sees "extern Literal", not "extern StringLiteral".  Literal is a parent rule for StringLiteral.

I'm currently working on how to handle this glibc case, where there is a GCC specific attribute construct both before and after the return type of a function.
Line(63:12) Error(no viable alternative at input 'extern__inline__attribute__((__gnu_inline__))wint_t__attribute__((__leaf__))btowc')

Thanks,
Dave

**Comment by Marti2203** [comment]
Hi, currently I am working on a PR for the C++14 grammar to fix some things(issue with nested templates and other stuff)? Can you give me a little more info so I can have it for later after I read the C++ 14 ISO grammar spec?

**Comment by mycroft8** [comment]
The CPP14 linkageSpecification rule, which recognizes sequences like 'extern "C"' is as follows:
linkageSpecification:
	Extern StringLiteral (
		LeftBrace declarationseq? RightBrace
		| declaration
	);
In the lexer, two rules are relevant...

StringLiteral:
	Encodingprefix? '"' Schar* '"'
	| Encodingprefix? 'R' Rawstring;

Literal:
	IntegerLiteral
	| CharacterLiteral
	| FloatingLiteral
	| StringLiteral
	| BooleanLiteral
	| PointerLiteral
	| UserDefinedLiteral;

The problem is that the Literal rule appears first.  So when the parser tries to recognize 'extern "C"' it sees the token sequence "Extern Literal".  And an unrecognizable error is issued.  One alternative is to move the Literal rule after the StringLiteral definition.  But there is another use of Literal in the parser where it wants the semantics of Literal (matching any string, character or number).  

There is a similar issue with the asmDefinition parser rule.
Still thinking of the best way to fix this; maybe by getting rid of Literal altogether and then have the parser consistently look for all acceptable types.  Just working around the issue for now.

**Comment by Marti2203** [comment]
Okay, just saw it also and understood you. Fixed it by making literal a parser rule.

**Comment by Marti2203** [comment]
For the GCC specific attribute, I think this is a GCC extension to the grammar itself and I wish not to touch the main grammar, but I think it is kind of possible by reworking the attibuteSpecifier rule.

**Comment by Marti2203** [comment]
It would be easier to make a GCC compatible CPP14 Grammar

**Comment by mycroft8** [comment]
That might be the best way to go forwards.  Gcc/G++ seems to have subtly different asm semantics, some differences in throw and restrict, some different inline semantics, etc.
I may just go ahead and add a "fill" method overload  to let me do something similar to "gcc -E" and directly compare preprocessor output.
Dave

**Comment by cima** [comment]
Thank you so much. It really made my day. I was struggling to figure out why the
```c
extern "C" { }
```
keeps failing because all the rules looks good. I'd never figure out the order/lexer->parser trick.
Thousand times thank you. 🥰
