### ISSUE TITLE
Add hacktoberfest topic to take participance in this event

### ISSUE THREAD

**Issue by KvanTTT** [antlr/grammars-v4#1871]
@teverett , participation can motivate more users to improve grammars or fix bugs. See details here: https://hacktoberfest.digitalocean.com/details#maintainers

**Comment by KvanTTT** [comment]
This topic should be added to the repository.

**Comment by teverett** [comment]
I think only @parrt can do that.

**Comment by parrt** [comment]
Seems like we're good now, right? I see the label.

**Comment by KvanTTT** [comment]
Where? It should be added to [repository topics](https://github.blog/2017-01-31-introducing-topics/), not only to issue. But I don't see in repository:

![image](https://user-images.githubusercontent.com/1150330/95050512-599a3f80-06f4-11eb-8d5d-423465825903.png)

**Comment by teverett** [comment]
Here's a screen shot from one of my other repos.   It shows topics, and
I see no topics for grammars-v4 

On 2020-10-05 01:21, Ivan Kochurkin wrote:

> Where? It should be added to repository topics [1], not only to issue. But I don't see in repository: 
> 
> [2] 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].
 

Links:
------
[1] https://github.blog/2017-01-31-introducing-topics/
[2]
https://user-images.githubusercontent.com/1150330/95050512-599a3f80-06f4-11eb-8d5d-423465825903.png
[3]
https://github.com/antlr/grammars-v4/issues/1871#issuecomment-703450626
[4]

**Comment by teverett** [comment]
![Screen Shot 2020-10-05 at 9 35 11 AM](https://user-images.githubusercontent.com/1226086/95100288-310f4700-06ee-11eb-9bb2-3df7bf649269.png)

**Comment by parrt** [comment]
oh. topics vs labels. ok.

**Comment by parrt** [comment]
Done
