### ISSUE TITLE
Python Listener Documentation?

### ISSUE THREAD

**Issue by andrfgs** [antlr/grammars-v4#1912]
Is there any documentation on how to parse the Python grammar in Python? I know Antlr4 has almost no documentation on the Python backend (the most widely used language in Antlr4 seems to be Java) and that this problem is very grammar specific but is there any example at all on how to use the PythonListener with Python?

I know the listener receives a `PythonParser._Context` where `_` depends on the symbol/block. For example in the `enterParameters` it receives as argument a context `ctx: PythonParser.ParametersContext`. But how do I actually do anything with it? Are there any examples I am missing? They don't seem to be in this repository, or maybe I'm not really looking into the right place.

**Comment by KvanTTT** [comment]
Python parsing does not differ from the parsing of other languages generated with ANTLR. Please read the [official doc](https://github.com/antlr/antlr4/blob/master/doc/python-target.md) or ask more concrete questions preferably on [StackOverflow](https://stackoverflow.com/questions/tagged/antlr4) or [Google Groups](https://groups.google.com/forum/#!forum/antlr-discussion).

**Comment by andrfgs** [comment]
My bad if this was not the right place to ask this question.
