### ISSUE TITLE
CPP14 doesn't parse zero-parameter lambda expressions

### ISSUE THREAD

**Issue by patrik-ronnqvist** [antlr/grammars-v4#1940]
Example C++ code:
`[&] () -> std::tuple <std::string, std::string> {}`

The parser gets stuck at the parentheses.
I fixed it by making parameterDeclarationClause in lambdaDeclarator optional. (Just like it is in parametersAndQualifiers.)

Original CPP14Parser.g4:
`lambdaDeclarator: LeftParen parameterDeclarationClause RightParen Mutable? exceptionSpecification? attributeSpecifierSeq? trailingReturnType?;`

With added question mark:
`lambdaDeclarator: LeftParen parameterDeclarationClause? RightParen Mutable? exceptionSpecification? attributeSpecifierSeq? trailingReturnType?;`

**Comment by patrik-ronnqvist** [comment]
On a similar note I think this line:
`captureDefault: And | Equal;`

Should be:
`captureDefault: And | Assign;`

Because don't you write `[=]` rather than `[==]` in lamda expressions?

**Comment by patrik-ronnqvist** [comment]
Also, the lexer doesn't account for escaped literal newlines, such as:
`std::string s = "hello\`
`world";`

I fixed that by adding this to Simpleescapesequence:
`| ('\\' ('\r' '\n'? | '\n'))`

**Comment by patrik-ronnqvist** [comment]
Two more things.

1. The parser missed `operator>` functions, so I added `| Greater` to `theOperator`.

2. The parser accidentally spanned over newlines when parsing regex strings like `R"..."`, so I changed:
`fragment Rawstring: '"' .*? '(' .*? ')' .*? '"';`
To:
`fragment Rawstring: '"' (~[\r\n])*? '(' (~[\r\n])*? ')' (~[\r\n])*? '"';`
I'm not sure if you can put literal newlines in regex strings, though. I haven't seen that use case yet, but that could be a problem. Maybe someone who knows the syntax for regex strings can write something like `Simpleescapesequence` for `Rawstring`?

Sorry, that's a lot of things. Should I have made separate issues for all these?

**Comment by teverett** [comment]
I think one PR is fine.   It would be helpful if you added new test cases with your PR that test the new functionality you've added.

**Comment by kaby76** [comment]
> Also, the lexer doesn't account for escaped literal newlines, such as:
> `std::string s = "hello\`
> `world";`
> 
> I fixed that by adding this to Simpleescapesequence:
> `| ('\\' ('\r' '\n'? | '\n'))`

This is not ISO 14882:2014, but it is accepted by the Gnu g++, even with `g++ '-std=c++14' -pedantic-errors`. #2328
