### ISSUE TITLE
Comparing Java8 and Java9 Grammar Parsing Speed

### ISSUE THREAD

**Issue by cpt9m0** [antlr/grammars-v4#1973]
Hi, I was working on parsing java grammars via ANTLR. I realized that parsing with java8 grammar is much faster than java9 grammar.

Java9 took 33,737 ms while Java8 took 15,564 ms with the same CPU and input file.

**My questions:**
1. Why there is so much difference?
2. Is there any faster version of Java grammar than this or not?

**Comment by KvanTTT** [comment]
What Java8 grammar have you tried? FYI [java](https://github.com/antlr/grammars-v4/tree/master/java/java) works much faster than [java8](https://github.com/antlr/grammars-v4/tree/master/java/java8).

**Comment by kaby76** [comment]
The main diff is that Java8 uses `Identifier` while Java9 uses `identifier` I used "strip" of Antlrvsix/Trash on the two grammars, then diffed the cleaned up grammars to determine this. So, there's going to be an extra parse tree node constructed for all those id's in Java9. I think I mentioned this before somewhere--the spec says specifically how to do this in the lexer. (I wrote fine-grain "diff" for grammars, but it's super slow comparing these two grammars cause it uses Zhang-Shasha.)

**Comment by cpt9m0** [comment]
> 
> 
> What Java8 grammar have you tried? FYI [java](https://github.com/antlr/grammars-v4/tree/master/java/java) works much faster than [java8](https://github.com/antlr/grammars-v4/tree/master/java/java8).

The Java8 and Java9 grammars that exist in this repository.
OK, I'll try the grammar you mentioned. thanks.

**Comment by KvanTTT** [comment]
And what results with the comparison with [java](https://github.com/antlr/grammars-v4/tree/master/java/java) version?

**Comment by cpt9m0** [comment]
> 
> 
> And what results with the comparison with [java](https://github.com/antlr/grammars-v4/tree/master/java/java) version?

It was significantly faster than java9 and java8.

**Comment by KvanTTT** [comment]
Maybe it makes sense to upgrade this version up to java9 at least.
