### ISSUE TITLE
Antlr4 grammar should accept escaped quote (single or double), e.g. "[\']", lexer char sets

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#1974]
I have been working on a [BNFC](https://github.com/BNFC/bnfc) parser for Antlrvsix. I generated a parser for the [the LBNF example](https://github.com/BNFC/bnfc/blob/master/examples/LBNF/LBNF.cf), and noticed that my extension does not parse the generated lexer grammar lbnfLexer.g4. However, the Antlr tool v4.9 accepts the grammar fine. My extension uses the the current Antlr4 grammar, which seems to [have a bug with LEXER_CHAR_SET_BODY](https://github.com/antlr/grammars-v4/blob/f17c5577bb8f46da71c843d87a653888d1fedafc/antlr/antlr4/ANTLRv4Lexer.g4#L519). It's just not accepting the escaped single quote in a set, even though it seems it should. I've seen other cases like this, and there might be something wrong with the generated lexer automaton. In any case, the rule should be tweaked to move past this bug. This problem also occurs with [Mike Lischke's extension](https://github.com/mike-lischke/vscode-antlr4) because he uses the same grammar.

**Comment by kaby76** [comment]
Somehow I made a mistake--Antlr4 tool 4.9 does not accept "[\']". So the Antlr4 grammar is fine.

**Comment by EwoutWal** [comment]
Hi kaby,

You mention the lexer rule `RULENAME: ['];` is not supported by Antlr, yet I seem to be able to parse this just fine using the 4.9 jar. This is using C# though, but I do not believe this is any different (i.e. uses the same Java jar).

I also noticed that the rule LEXER_CHAR_SET_BODY may never actually be reached, because the mode it is under `LexerCharSet` is never entered as far as I can tell.

Do you have a workable example of what you were trying to parse that I could try?

Thanks in advance!

**Comment by kaby76** [comment]
> Hi kaby,
> 
> You mention the lexer rule `RULENAME: ['];` is not supported by Antlr, yet I seem to be able to parse this just fine using the 4.9 jar. This is using C# though, but I do not believe this is any different (i.e. uses the same Java jar).
> 
> I also noticed that the rule `LEXER_CHAR_SET_BODY` may never actually be reached, because the mode it is under `LexerCharSet` is never entered as far as I can tell.
> 
> Do you have a workable example of what you were trying to parse that I could try?
> 
> Thanks in advance!

@EwoutWal Yeah, `[']` is okay; `[\']` (a backslash preceding the quote) is not valid Antlr4. I use Java with the latest official antlr...4.9-complete.jar, not Harwell's C# tool to generate the parser. I guess I edited the file to remove the backslash, ran it through the tool, and forgot I just edited the damn file, then said to myself the tool takes `[\']`! My mistake. I guess I got distracted (I'm adding BNFC parsing to my extension), and I should always double or triple check any result.
