### ISSUE TITLE
C# isn't in CI builds, sql/plsql for C# not targeting NET Standard build of Antlr

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#1976]
It looks like [sql/plsql](https://github.com/antlr/grammars-v4/tree/master/sql/plsql) for C# has a few problems:

* [PlSqlLexerBase.cs]() is written against a specific namespace, while [PlSqlLexerBase.java]() over in the Java side is not. This is inconsistent.
* The C# code is targeted for Harwell's version of Antlr C#--**which hasn't been updated for years**, and isn't supported by the official Net Standard version of Antlr 4.9. Fortunately, I have a shim to fix this.
* I don't see any Appveyor.yml at the top-level directory for the repository. It's likely that CI isn't being done at all for C# targets. This really should be fixed. People check in all sorts of crap.

**Comment by studentmain** [comment]
AFAIK CI is only running with Java runtime (some times we even skipped some grammar). BTW we use GitHub Actions for CI.

**Comment by kaby76** [comment]
Yes, I see the logs [here](https://github.com/antlr/grammars-v4/actions). There are no rules for a Dotnet build and test. It's likely that there is no CI build for C# because there is no "official" MSBuild rule file for C# Antlr programs. Fortunately, I also have a fix for this that's based on Harwell's Antlr4BuildTasks. I forked that code and have been cleaning up for years. But, it is very frustrating to see this go on year after year after year.

**Comment by kaby76** [comment]
Based on the absence of a build for C#, I am enumerating the design requires for CI of the C# target here.

1) The CI for C# must run with Github Actions. G.A. supports any OS environment, but the current CI tests for grammars-v4 test [all environments](https://github.com/antlr/grammars-v4/blob/master/.github/workflows/main.yml#L13). However, as I don't want to write a mess of tools, I will require the Bash toolchain for scripting, and will require xml2 to extract information from a pom.xml file, which is at the center of the current CI testing.
2) C# is platform independent with NET 5. It works on Linux and Windows. It is installed in Github Actions. Therefore, C# CI will use the NET 5 SDK.
3) There are two runtimes for C#, the [standard official release](https://www.nuget.org/packages/Antlr4.Runtime.Standard/) and [Harwell's Antlr4cs](https://www.nuget.org/packages/Antlr4.Runtime/). The Antlr4cs runtime has not been updated for over 3 years, and it is several versions behind the current official runtime. Therefore the tests will use the [standard official release](https://www.nuget.org/packages/Antlr4.Runtime.Standard/).
4) I will be using my [Antlr4BuildTasks](https://www.nuget.org/packages/Antlr4BuildTasks/) build tool. This is a fork of Harwell's excellent tool, updated, extended, and refined over several years to work with the  [standard official release](https://www.nuget.org/packages/Antlr4.Runtime.Standard/). It works with the NET 5 SDK, as well as the older NET Frameworks and MSBuild chain.
5) The pom.xml files specify what to test. The pom.xml file encodes essential information such as the start symbol, additional source files, and the tests to run. Duplicating this information for C# CI is unnecessary and will introduce problems with maintainance. In particular, this precludes adding in .csproj files into the sources. That stamps the runtime to link to and the driver, which I don't want to do. Therefore, the C# CI test tooling must extract information from the pom.xml files.
6) The grammar sources do not encode a driver code. The pom.xml file defines the rules for creating a Java driver program from a template. Further, how a driver works--whether to read stdin, or to use an argument to the program to specify what to parse--is an implementation detail, and should not be part of the sources for the grammar. Therefore, there should not be any source code in a grammar directory for a driver.

I am nearly complete with an implementation for C# CI testing. I have a Dotnet template generator that works well and can run on any OS. It creates a directory "Generated/", and a driver application in this temporary directory. This generator reads the sources and integrates the .g4 grammars and any C# code into a build.

Any comments, let me know. --Ken

**Comment by studentmain** [comment]
That's good!

Problem you'll need take consideration:

- pom.xml only provide information for java runtime (e.g. base class)
- Some grammar are using base class for multiple language. Some just have multiple g4 and writing language specific code in it.
- And grammars can have C# base class and Java specific code at the same time. (it won't compile, and it's another story about antlr itself...)

I can expect many grammars will failed in C# runtime at the moment. We need time, ability to bypass some grammar, and maybe another branch to fix them without breaking the workflow.

**Comment by studentmain** [comment]
To make future test framework easier, here's my suggestions:

- If all language folders are well organized. Adding more runtime tests will easier.
  - When semantic predicate is necessary, always use base class.
  - Put base class at corresponding sub folder (e.g. `./csharp`,`./typescript`,...)
  - Always put tests in `./examples`
  - If we have a new java test framework, pom.xml can be replaced by a smaller, language independent and simpler config file.
- AFAIK, current sematic predicate syntax can't be language independent even with base class. Different language and runtime have different name convention, different syntax when calling methods on `this`. New syntax may needed to call class member in language independent way. (e.g. `{:method(args)}?`, you write `{:LookAhead(1,a,"b")}?`, ANTLR compile it into `{this.LookAhead(1,this.a,"b")}?` for java,  `{self.look_ahead(1,self.a,"b")}?` for python)

**Comment by kaby76** [comment]
Yes, we'll have to skip some of the grammars and fix these up later on. But, I just would like to get the C# CI build started.

The grammars are pretty well organized, but it could be improved. But, the generator should work however it's organized because it copies the grammar and C# files into the temporary directory. MSBuild/Dotnet will handle finding the files just fine.

The script I have reads the top-level pom.xml file and recursively goes the sub-directories for other pom.xml, recursing to the next referenced pom.xml--just as Maven would do, but completely as a Bash function! When it gets to a grammar that I know is targeted to something specific like Java (i.e., it doesn't build), I skip the grammar. This "skip list" is experimentally determined and it's hardwired into the script because I don't want to break current builds. So far, there are 63 grammars that don't build, and 169 that do. The only problem here is that one can't run this on Windows per se because I need an XML parser, hence xml2. But, Windows has WSL, so if you want to test on your Windows machine, just start a WSL and run the test as it's just Linux.

I thought about writing the whole damn thing in C# dotnet, but I don't think it's worth it. C# is not really a scripting language, Bash is.

For sure, I'd like to see a "target-independent" semantic predicate. But, that's another story.

--Ken

**Comment by studentmain** [comment]
> I thought about writing the whole damn thing in C# dotnet, but I don't think it's worth it. C# is not really a scripting language, Bash is.

Technically, Powershell is a cross platform scripting language, have an XML parser, but it's dotnet too... 

Using WSL in github actions seems possible: https://github.com/marketplace/actions/setup-wsl

**Comment by kaby76** [comment]
I have a 200-line Bash script that performs regression testing in C# using xml2 ([here](https://github.com/kaby76/grammars-v4/blob/master/csharp-regression-tests.sh)). The real meat--and what took a bit of time--is the development of my Antlr C# template driver generator, which sets up a C# project driver for an Antlr grammar. The Bash script can be rewritten in another, more modern language, but I just want to get something working first. (I am not an expert at Powershell as I cannot stand the syntax and so I don't use it often). The main problem is that of the ~200 grammars there are ~70 that do not build, mainly because there is Java action code within the grammar. However, several of these produce a parser that fails when compared to the Java target. I haven't investigated that yet, because I am planning to first submit a PR to integrate the script into the builds, then deal with fixing as many of the 70 grammars to work with C#. Windows is my development environment, and WSL works fine--for now. So, this will take a few iterations to get it all right.

The default behavior of the script and C# regression testing is that whenever anyone adds a new grammar, it'll also have C# testing if it has Java testing. In order to not test it with C#, the script would have to be changed to explicitly bypass testing for that grammar. I implemented it that way because I think people need to be "nudged" into writing target-independent grammars.

**Comment by KvanTTT** [comment]
> There are two runtimes for C#, the standard official release and Harwell's Antlr4cs. The Antlr4cs runtime has not been updated for over 3 years, and it is several versions behind the current official runtime. Therefore the tests will use the standard official release.

Please don't drop support of C# optimized runtime because it differs from standard runtime a bit and I'm using it in work projects. Actually, it's possible to support both runtimes using preprocessor directives, something like this:

```cs
public const int Eof =
#if CSharpOptimized
        IntStreamConstants.Eof;
#else
        IntStreamConstants.EOF;
#endif

#if CSharpOptimized
    public override int La(int i)
#else
    public override int LA(int i)
#endif
```

**Comment by studentmain** [comment]
> Actually, it's possible to support both runtimes using preprocessor directives

Maybe we can create a wrapper package for optimized runtime?

**Comment by KvanTTT** [comment]
It's better to unify member names in Standard and Optimized runtimes (use `IntStreamConstants.Eof` everywhere in the sample above).

**Comment by kaby76** [comment]
This is a hard problem. There's a divergence in the names of runtime objects across targets. I think the shim I wrote actually is for Antlr Java to Antlr C# Standard (allow a Java-targeted grammar to "work" with Antlr C# Standard), but I'll have to review [the code](https://github.com/kaby76/Antlr4RuntimeShim). But, that doesn't solve the problem. Some actions work with a string. Even if you unify the runtime names, the Java and C# runtimes, let alone that for more diverse language targets, can't be unified. I forgot where those are, but I'll update you with a list when I go over the 70 skipped grammars of why these all don't build in the next few days.

**Comment by KvanTTT** [comment]
I meant only C# runtimes. For more generalized unification there is another issue https://github.com/antlr/antlr4/issues/1045

**Comment by kaby76** [comment]
Are you thinking about merging [Antlr4cs C# runtime](https://github.com/tunnelvisionlabs/antlr4cs/tree/master/runtime/CSharp/Antlr4.Runtime) and [Antlr4 C# Standard runtime](https://github.com/antlr/antlr4/tree/master/runtime/CSharp)? Antlr4cs also includes [a C# translation of the Antlr tool](https://github.com/tunnelvisionlabs/antlr4cs/tree/master/runtime/CSharp/Antlr4.Tool).

**Comment by KvanTTT** [comment]
Not merging but methods renaming in ANTLR Standard: `IntStreamConstants.EOF` -> `IntStreamConstants.Eof` and similar.

**Comment by kaby76** [comment]
My recommendation is to keep a narrow focus first in order to fix the grammars in this repo such that they work across targets and runtimes. Write the grammars so the action code is a predicate method in a lexer and/or parser superclass. That will mean splitting the grammars because I think the `superClass` option only works with split grammars. Further, move the `@members` code to the appropriate base class. Offer the grammar with a C# Standard or C# Antlr4cs or Java or whatever target base classes so the grammar itself doesn't need to be constantly tweaked per target.

Regarding the renaming of the API. Replacing the Antlr4 C# Standard API names with that in Antlr4cs will break the code of one group or another. There are people that code to the Antlr4 C# Standard. And, there are methods in Antlr4cs that aren't available in Antlr4 C# Standard, e.g., [Atn.ClearDFA()](https://github.com/tunnelvisionlabs/antlr4cs/blob/master/runtime/CSharp/Antlr4.Runtime/Atn/ATN.cs#L96), [ContextCacheSize](https://github.com/tunnelvisionlabs/antlr4cs/blob/master/runtime/CSharp/Antlr4.Runtime/Atn/ATN.cs#L112), etc. I've found that if you've offered an API in the past, people have made use of it. I think it would be best to merge the runtimes and offer a deprecated surface in the next release of Antlr in December. That should be enough time to do a merge.

**Comment by kaby76** [comment]
As the code in `CSharp/` directories is written against Antlr4cs, for now, I will update my shim to be a reference assembly shim so the C# code in grammars-v4 (e.g., `sql/plsql/`) does not have to be changed whatsoever.  I now notice that Harwell made an update to his Antlr4cs code a few weeks ago for NET Standard. I'll probably add code to my template driver generator to also output code for his runtime. I already have an option to output a driver for Java, and will probably do it for all the other targets at some point.
