### ISSUE TITLE
Rust grammar doesn't appear to support all raw strings

### ISSUE THREAD

**Issue by jellymann** [antlr/grammars-v4#1985]
The rules for raw strings in the rust grammar are as follows:

```antlr
RAW_STRING_LITERAL: 'r' RAW_STRING_CONTENT;
fragment RAW_STRING_CONTENT: '#' RAW_STRING_CONTENT '#' | '#"' .*? '"#';
```

This looks like it requires at least one pair of hashes (`#`) surrounding the quoted part. However, the [rust reference](https://doc.rust-lang.org/reference/tokens.html#characters-and-strings) specifies 0 or more `#` sets.

**Comment by studentmain** [comment]
```antlr
​fragment​ ​RAW_STRING_CONTENT​: ​'​#​'​ ​RAW_STRING_CONTENT​ ​'​#​'​ | ​'​"​'​ .*? ​'​"'​;
```
