### ISSUE TITLE
JavaScript grammar reports unexpected error on incomplete 'block' statement

### ISSUE THREAD

**Issue by torrentg** [antlr/grammars-v4#1994]
I'm trying to match incomplete javascript statements against the `sourceElement` rule. I found unexpected errors related to `block` rule. The grammar is reporting `no viable alternative` on valid incomplete statements (see RESULT vs EXPECTED) :

```
CASE         | RESULT                                    | EXPECTED
-------------------------------------------------------------------------------
{}           | OK                                        | OK
{            | no viable alternative at input '{'        | mismatched input '<EOF>' expecting ...
{ a          | no viable alternative at input '{ a'      | missing '}' at '<EOF>'
{ a =        | no viable alternative at input '{ a ='    | mismatched input '<EOF>' expecting ...
{ a = 1      | no viable alternative at input '{ a = 1'  | missing '}' at '<EOF>'
{ a = 1;     | missing '}' at '<EOF>'                    | missing '}' at '<EOF>'
{ a = 1; }   | OK                                        | OK
-------------------------------------------------------------------------------
if (a==1)    | mismatched input '<EOF>' expecting ...    | mismatched input '<EOF>' expecting ...
if (a==1) {  | no viable alternative at input '{'        | mismatched input '<EOF>' expecting ...
-------------------------------------------------------------------------------

```
Rule `objectLiteral` may be involved in the malfunction: if we replace the initial `{` by `#` in the `objectLiteral` rule then all works as expected.

**Comment by studentmain** [comment]
I don't think it's unexpected...

For `{a`, it can be a part `{a:1}` and  `{a=1;}`, parser needs more input to determine it's type. Parser basically tried every possible situation and nothing match, then it reports no viable alternative. For `{a=1;`, it must be a part of block, it's easy to say it needs a '}'.

**Comment by Marti2203** [comment]
Hi, 
I am not sure the thing yo expect is correct. On what grounds do you think it should be the expected output?
