### ISSUE TITLE
Algol60 grammar - arithmetic_expression rule is infinite loop

### ISSUE THREAD

**Issue by matevosmehrabyan** [antlr/grammars-v4#2038]
Algol60 grammar's rule `arithmetic_expression` produces infinite loop:

`arithmetic_expression
    : 'step' arithmetic_expression 'until' arithmetic_expression
    | arithmetic_expression 'while' boolean_expression
;`

**Comment by kaby76** [comment]
The Antlr tool doesn't check for this. It should.

**Comment by kaby76** [comment]
I have a fix for this. I started from the ISO 1538 Spec, typing it in by hand, and adding various examples scrounged over the Internet. Details and PR at some point soon.

**Comment by kaby76** [comment]
Please review the PR change for this bug. @matevosmehrabyan

**Comment by matevosmehrabyan** [comment]
Hi, I added a comment on your PR.
