### ISSUE TITLE
Sqlite grammar - order_by_expr_asc_desc rule is infinite loop

### ISSUE THREAD

**Issue by matevosmehrabyan** [antlr/grammars-v4#2039]
Sqlite parser grammar's rule `order_by_expr_asc_desc` produces infinite loop:

`order_by_expr_asc_desc: ORDER BY order_by_expr_asc_desc;`

**Comment by dpmm99** [comment]
This was fixed and should be closed. https://github.com/mike-lischke/grammars-v4/commit/76b1d66d768902f821b7a7440507bfdb9b6a32f9

**Comment by matevosmehrabyan** [comment]
You are right. It's fixed. Great!
