### ISSUE TITLE
Pike grammar - expression3 rule is infinite loop

### ISSUE THREAD

**Issue by matevosmehrabyan** [antlr/grammars-v4#2041]
Pike grammar's `expression3` rule produces infinite loop:

`expression3
   : expression4 '?' expression3 ':' expression3
   ;`

**Comment by Marti2203** [comment]
Hi, the whole grammar has problems. I will look into fixing that.

**Comment by Marti2203** [comment]
This can be closed.

**Comment by matevosmehrabyan** [comment]
This issue is not fixed. The infinite loop is still there

**Comment by matevosmehrabyan** [comment]
I will reopen it

**Comment by Marti2203** [comment]
Yes, my mistake. I have not fixed that, I will do it now.
