### ISSUE TITLE
Pike grammar - mutually left recursive rules [expression6, call, index, arrow]

### ISSUE THREAD

**Issue by matevosmehrabyan** [antlr/grammars-v4#2042]
ANTLR failed to generate lexer and parser for Pike grammar, with the following error message:

`The following sets of rules are mutually left-recursive [expression6, call, index, arrow]`

ANTLR supports only direct left recursion. This can be fixed by removing `call`, `index`, `arrow` rules and replacing `expression6` rule with the following:

` 
expression6
   : STRING
   | NUMBER
   | FLOAT
   | catch_
   | gauge
   | sscanf
   | lambda
   | class
   | constant_identifier
   | expression6 '(' expression_list ')'
   | expression6 '[' expression ('..' expression)? ']'
   | mapping
   | multiset
   | array
   | parenthesis
   | expression6 '->' IDENTIFIER
   ;
`

**Comment by Marti2203** [comment]
This can be closed.
