### ISSUE TITLE
Error while generating lexer and parser for grammar tinyos_nesc by ANTLR

### ISSUE THREAD

**Issue by matevosmehrabyan** [antlr/grammars-v4#2043]
ANTLR fails to generate lexer and parser for tinyos_nesc grammar with the following error message:
`error(177): grammars-v4/tinyos_nesc/TinyosLexer.g4:152:45: WHITESPACE is not a recognized channel name`

**Comment by Marti2203** [comment]
Hello, yeah. This is an issue, I will make a PR with a fix.

**Comment by Marti2203** [comment]
This is fixed @matevosmehrabyan

**Comment by matevosmehrabyan** [comment]
Thanks
