### ISSUE TITLE
IBM TSO/E REXX standardization

### ISSUE THREAD

**Issue by bknaysi** [antlr/grammars-v4#2060]
Hello,

I work for IBM building developer tools for mainframe users. We are using your ANTLR grammar for REXX in our LSP implementation, and have found that the grammar does not fully comply to the IBM TSO/E REXX standard. We have made a few changes that we would like to contribute back to this project, but received the following permission denied error when trying to push a branch with changes to this repository. Let me know if there is anything I need to do to get permission.

<img width="1112" alt="Git Push Permission Denied Error" src="https://user-images.githubusercontent.com/78445752/109838692-63c55900-7c14-11eb-9114-cf3e5c1e2ac4.png">

Thanks,
Bradley Knaysi

**Comment by studentmain** [comment]
Thank you!

Like other projects on the GitHub, this project use GitHub fork and pull requests. You should follow these steps:

1. create a fork
2. push the branch to the forked repository
3. create a pull request at this repository

Here's the [official document](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests) and a [tutorial](https://gist.github.com/Chaser324/ce0505fbed06b947d962) of how to do it.

**Comment by teverett** [comment]
@bknaysi  your contribution would be very welcome.  Please reach out if you need help opening a PR.

**Comment by bknaysi** [comment]
I created the Pull Request! There will be more down the road, but #2092 is the first set of changes.

**Comment by Marti2203** [comment]
I think this issue can be closed?

**Comment by bknaysi** [comment]
Can we keep it open? There are still more change sets to come.

**Comment by Marti2203** [comment]
Oh yeah, sorry. I am just going through various issues to see what I can work on.

**Comment by bknaysi** [comment]
All good, thanks for keeping me on my toes!

**Comment by RossPatterson** [comment]
@bknaysi Please keep in mind that the changes that are specific to TSO/E (like that weird "X=;" assignment statement) should be isolatable.  They aren't "standard Rexx", any more than some of the specifics for OS/2, ARexx, B-Rexx, and Regina.

**Comment by bknaysi** [comment]
@RossPatterson You make a good point. How would you define "standard REXX" in this case?

**Comment by RossPatterson** [comment]
@bknaysi 
Well, as a someone who's had a few beers with Mike, I'd say TRL2 (_aka_ Language Level 4.00)  :-)  But realistically, I think the ANSI standard (X3.274-1996 plus [errata](https://www.rexxla.org/document.rsp?base=rexxlang/standards&doc=stan_err&title=The%20Rexx%20Language%20-%20ANSI%20Rexx%20Standard%20Errata)) would be the correct  choice.  Anything else ought to be approached as a variant from the standard, even CMS, where Rexx started.

I'll look around at how some of the other Rexx implementations have addressed incompatibilities.  I know Regina uses the OPTIONS instruction to manage the many dialects / language levels it supports.

**Comment by bknaysi** [comment]
Good to know, I think for us TSO/E REXX is really the target, but we'll keep the general standard in mind!
