### ISSUE TITLE
[JSX] url inside html tag are mistakenly put into the hidden channel

### ISSUE THREAD

**Issue by Markz666** [antlr/grammars-v4#2063]
```javascript
import React from 'react';
class SummaryContainer extends React.Component {
    render() {
        return (
            <div>Content：<a target="_blank" href="https://www.github.com">https://www.github.com</a>
            </div>
        );
    }
}
```
content after "//" are missing due to the following rule in lexer:
```
SingleLineComment:              '//' ~[\r\n\u2028\u2029]* -> channel(HIDDEN);
```
Related file: https://github.com/antlr/grammars-v4/blob/master/javascript/jsx/JavaScriptLexer.g4

**Comment by Marti2203** [comment]
Hi, 
A simple solution is to move all the comment definitions after the string definitions. I am going to make a PR for that.

**Comment by Marti2203** [comment]
Another issues is that https://www.github.com is also not caught and that I will include in the PR as well.
