### ISSUE TITLE
Add support for TSQL PARTITION

### ISSUE THREAD

**Issue by scrappyCoco** [antlr/grammars-v4#2066]
Is it possible to add support for Transact SQL [$PARTITION](https://docs.microsoft.com/en-us/sql/t-sql/functions/partition-transact-sql?view=sql-server-ver15)?
```sql
SELECT $PARTITION.TRANSACTION_RANGE_PF1(TRANSACTIONDATE) AS PARTITION,   
COUNT(*) AS [COUNT] FROM PRODUCTION.TRANSACTION_HISTORY   
GROUP BY $PARTITION.TRANSACTION_RANGE_PF1(TRANSACTIONDATE)  
ORDER BY PARTITION; 
```
![image](https://user-images.githubusercontent.com/4902515/110105415-690fd880-7db9-11eb-82dc-2bf1418ac770.png)

Thanks!

**Comment by siggemannen** [comment]
Hi, it's pretty simple if someone wants to add this.

**TSQLLexer:**
`DOLLAR_PARTITION:                      '$PARTITION';`
**TSQLParser:**
Add this to end of function_call rule list:

```
    | partition_function                                #PARTITION_FUNC
    ;

```
And finally add this rule:
```

partition_function
    : (database=id '.')? DOLLAR_PARTITION '.' func_name=id '(' expression ')'
    ; 
```

**Comment by scrappyCoco** [comment]
@siggemannen, You will have no complaints if I do PR?

**Comment by siggemannen** [comment]
@scrappyCoco pls go ahead. I'm not really a friend with git yet so it will take too long for me to setup a PR myself =)
