### ISSUE TITLE
Symbol conflicts, missing target-specific code in Part 1 of N

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#2069]
Dotnet-antlr now generates parsers for CSharp, Java, JavaScript, Dart, Python3, and Go. The following Bash script is what I used to test the first set of grammars in the repo. The script has detected a number of problems in symbol conflicts, and I list these below. But, this is just the first grammars alphabetically in the repo, and I expect more. In the notes below, I list other issues that should be fixed.

Notes: (1) The dotnet-antlr version is 2.2.0. (2) The Go and Dart runtimes need work because there are missing APIs. (3) The runtime for the Dart target is slow. But when the program is compiled, it works better. (4) I have compared the six targets against grammars-v4/html, one of the slowest in the CI test suite. I have tested the first five examples in grammars-v4/html/examples, and have some interesting results. In general, Java is the fastest, Python3 the slowest, often times 4 times slower, sometimes 50 times slower. For Go, I had to kill the parse of "cnn1.html". It's likely that some of the runtimes implement some data structures that do not scale because they deviate non-linearly from Java for the larger tests like "cnn1.html". In other words, for example, it's not a constant "5 times slower" for Python3. (5) There are several bugs in 4.9.1 Antlr which are starting to become an issue in testing grammars-v4, e.g., idl and parse failures in C#, Python3, Go targets. Looks like we're going to get a new release soon!

    #
    shopt -s expand_aliases
    ls -l ~/.bash_profile
    if [ -f ~/.bash_profile ]
    then
        echo sourcing
        . ~/.bash_profile
    fi

    for i in CSharp Java JavaScript Dart Python3 Go
    do
        echo $i
        rm -rf Generated
        dotnet-antlr -t $i -m
        if [[ "$?" != "0" ]]
        then
            rm -rf Generated
            continue
        fi
        pushd Generated
        ls
        make
        if [[ "$?" != "0" ]]
        then
            rm -rf Generated
            continue
        fi
        if [[ -d ../examples ]]
        then
            for file in `find ../examples -type f`
            do
    # NOTE: Python3 has a tendency to just hang with compile errors.
    # So, we avoid reading from stdin for Python3, but may as well do for
    # others.
    #           cat $file | make run
                make run RUNARGS="-file $file"
            done
        else
            make run RUNARGS="-input 1+2 -tree"
        fi
        popd
        rm -rf Generated
    done

* abb/abbParser.g4, type - Python3
* algol60/algol60.g4, type
* antlr grammars - missing several target-specific code
* apex - missing several target-specific code
* arithmetic/arithmetic.g4, file - Python3
* asm/asm6502/asm6502.g4, string - Go
* asm/asm8080/asm8080.g4, string - Go
* asm/asm8086/asm8086.g4, string - Go
* asm/ masm and asmMASM are both incomplete. There is a grammar on the MS website.
* asm/asmZ80/asmZ80.g4, string - Go
* asn/asn/ASN.g4, object - Python3
* asn/asn_3gpp - target-specific code for Java but no conflicts
* aspectj - skipping
* atl - no examples! ATL.g4, library - Dart

**Comment by studentmain** [comment]
I added support for other target in test script, https://github.com/studentmain/grammars-v4/pull/4

They are not using makefile, I found that build them step by step seems easier than configure make on windows then switch between cmd/bash/pwsh... For golang, I can't build it without a module, so I moved some file and replaced one line of code to transform generated code into a module.

**Comment by studentmain** [comment]
Finally I finished the test, now I got a really long TODO list...

https://github.com/studentmain/grammars-v4/blob/1e816ff24d76b4722a6b70e353b6469f7001b534/_scripts/test.ps1#L6-L140

**Comment by kaby76** [comment]
@studentmain Looks good. I see Bcpl on a list or two, but I know there's a problem with mutual recursion. I was planning to fix that in a few days because BCPL was one of the first languages I learned so many years ago, and wrote a peephole optimizer for a compiler for it. But, first rewrite dotnet-antlr as StringTemplates.

**Comment by Marti2203** [comment]
@studentmain hi, can you make this a seperate issue as checklist if possible? I am interested in fixing some of the bugs.

**Comment by kaby76** [comment]
@Marti2203 @studentmain I'm going to make a PR so far of what I corrected with this issue. I only got the symbol conflicts completed for the grammars in the repo that start with the letter "a". I didn't rewrite the grammars with the partitioned target source code (i.e., as was done for antlr/antlr[234]). Nor did I work on the BCPL mutual left recursion.

I am now stuck on rewriting the "dotnet-antlr" program so that it works off of templates. It's starting to work but it's going to take a few days to get this right, replacing all the nasty WriteLine()'s with a resurrected StringTemplate library for C#. The rewrite of dotnet-antlr with StringTemplates is in a new branch [here](https://github.com/kaby76/Antlr4BuildTasks/tree/StringTemplates/dotnet-antlr).

You folks can comment below on a checklist, or just create a new issue with what you are going to do, or just take up an existing issue and make a new comment in it that you are working on it.

--Ken

**Comment by kaby76** [comment]
I created the PR for what I done [here](https://github.com/antlr/grammars-v4/pull/2073). Working on StringTemplates and dotnet-antlr.

**Comment by studentmain** [comment]
> 
> 
> @studentmain hi, can you make this a seperate issue as checklist if possible? I am interested in fixing some of the bugs.

working, I need some time to analyze the log

**Comment by studentmain** [comment]
[errors.xlsx](https://github.com/antlr/grammars-v4/files/6112443/errors.xlsx)

@Marti2203 The reason in the table is for reference only, you need check it again before start fix something.

**Comment by kaby76** [comment]
@studentmain Good work! This is a great start. I agree: most problems are caused by symbol conflicts and a lack of target-specific base code. I'm not sure about how the Dart and Go targets will impact the grammar. I had to change some of the calls in the grammar semantic predicate actions to have a "this." prefix. I don't know if that will work for Dart, Go, and even Python3. So, this needs a little investigation.

I have string templates in dotnet-antlr starting to work. The program will come with a set of default templates, but I'll make it easy so one can swap in whatever templates one wants to use.

**Comment by kaby76** [comment]
Closing this issue since the PR has been merged. Yes, we know there is still a lot of work to be done. I will be submitting a PR for issue #2074 in an hour or so. The dotnet-antlr tool, version 3.0.2, has been updated. This will contain (1) templates for this repo; (2) updated regtest.sh and test.ps1.
