### ISSUE TITLE
Infinite loop in SingletonPredictionContext

### ISSUE THREAD

**Issue by patrik-ronnqvist** [antlr/grammars-v4#2080]
Using the CPP14 lexer & parser I ran into this troublesome function:

```
void some::thing (std::map<short, std::vector< some::thing> >& param1, std::map<short, std::map<std::string, double> >& param2, std::map<short, std::map<std::string, double> >& param3, std::map<short, std::map<std::string, double> >& param4, std::map<short, std::map<std::string, double> >& param5)
{
	// ...
}
```

For one thing I had to update CPP14Parser.g4 and put simpleTemplateId as an option in className, because it couldn't handle template parameters:

`className: Identifier | simpleTemplateId | Typename_;`

But even after fixing that, ANLTR couldn't seem to handle all the less and greater symbols. If I removed them it parsed fine, or if I just had one argument it parsed fine, but with all of them at the same time it got stuck in an infinite loop in SingletonPredictionContext. I tried changing the .g4 files some more to fix the problem, but that didn't work.

Then I looked at the actual line ANTLR got stuck on in the SingletonPredictionContext.equals(Object o) method:

`return returnState == s.returnState && (parent!=null && parent.equals(s.parent));`

I changed it to:

`return returnState == s.returnState;`

With that change the function is correctly parsed in less than a second. So I guess ANTLR had two identical objects, but refused to believe they were the same because they happened to be in different locations? I think those objects are the parameter types 2-5 in this specific case.

**Comment by kaby76** [comment]
Hi, I've been reviewing this issue. I have a couple questions.

First, this test parses as is using: (1) the source code in test.cpp; (2) a generated parser/driver via `dotnet-antlr -m true -t CSharp` version 3.0.10; (3) the CPP14*.g4 grammar altered to remove the semantic predicate, which wouldn't execute here anyways.

	void some::thing (std::map<short, std::vector< some::thing> >& param1, std::map<short, std::map<std::string, double> >& param2, std::map<short, std::map<std::string, double> >& param3, std::map<short, std::map<std::string, double> >& param4, std::map<short, std::map<std::string, double> >& param5)
    {
        // ...
    }

Could you provide the test case that doesn't parse?

Second, `className: Identifier | simpleTemplateId;` comes directly from the [spec](https://timsong-cpp.github.io/cppwp/n4140/draft.pdf), page 223. And, it is the same in later specs. Why do you need to deviate from the spec?

Thanks,

Ken

**Comment by patrik-ronnqvist** [comment]
Oh... I tried the test again with the original CPP14 files and it does parse correctly... It looks like the errors must've been caused by other changes I've made to the CPP14 files. Other than the infinite loop, the the problem was that antlr kept interpreting those less and greaters as relationalExpression instead of simpleTemplateId.

The reason I'm making changes to the CPP14 files in the first place is that I've got a few million lines of legacy code I'm trying to parse, about 30 years worth, from various different versions of C and C++ with heavy use of macros. Some of the problems I've run into are:
- Old code that uses now-keywords as identifiers:
`std::str class = "string called class";`
- Alternative operators (xor, bitand, bitor, compl...):
`if ( a xor b ) { }`
- String concatenation without pluses:
`std::str s = "some" "string" "here";`
- Lines that end with backslashes (escaped newlines):
```
std::str s = \
     "not sure" + \
     "why you'd" + \
     "do this";
```
- Rawstrings (I have to add every delimiter to the lexer):
```
std::str s = R"BLAH(
Literally anything goes here. Can break all syntax. " ; ( ) < > ? \ / ~
)BLAH";
```
- Lines that contain both a preprocessor statement and the beginning of a comment block:
```
#ifdef foo /*
multiline comment
*/
```
- Direct memory address assignment (yes, this case deliberately causes a crash):
`*(int*) 0 =42;`
- asm functions with special syntax: [https://en.cppreference.com/w/cpp/language/asm](https://en.cppreference.com/w/cpp/language/asm)
- sqc files that contain a mixture of C++ and SQL code
- Macros that break conventional syntax (not ending a macro with a semicolon, using a macro instead of a catch-clause, using a macro instead of a namespace, using a macro instead of a keyword...):
```
try {
    // ...
} MACRO_CATCH_CLAUSE
```
- Preprocessor statements that include code fragments rather than whole files:
`std::str s = #include<file_with_a_string.c>`
`someFunction( #include<file_with_parameters.c> )`
- Preprocessor if-else-statements where including both blocks causes a syntax error; one of the blocks MUST be ignored:
```
#ifdef foo
    if (foo) {
#else
    if (bar) {
#endif
        // ...
    }
```
- Various other syntax that CPP14 wasn't accounting for (postfixExpression can contain Volatile, unaryExpression can contain castExpression, simpleDeclaration can contain castExpression...)
