### ISSUE TITLE
Unreferenced rules in wln.g4

### ISSUE THREAD

**Issue by nordlow** [antlr/grammars-v4#2097]
https://github.com/antlr/grammars-v4/blob/959b8b3183fbb43bf1e3bf2160a8d003f9fd9f44/wln/wln.g4#L152

Are upper-case (non-fragment) rules semantically different from lower case rules?

I wonder because I'm working on a parser generator supporting .g4 as input. When producing the parser (currently recursive descent) for the grammar I need to detect the root-rule. My algorithm currently detects root-rule as a rule whose name is not referenced in other rules and gives an error when there is more than one root rule. In the case of wln.g4 this becomes both the rule `wln` and `AMP`.

**Comment by studentmain** [comment]
Upper case rule (e.g. Identifier, NEWLINE) is lexer rule.
Lower case is parser rule.

You can find a more feature-rich example in javascript/javascript folder.

**Comment by nordlow** [comment]
Thanks.

Still, the `AMP` lexer rule is unreferenced.
