### ISSUE TITLE
Haskell Grammar 

### ISSUE THREAD

**Issue by rajmahendra** [antlr/grammars-v4#210]
Its good if we have a pre built Haskell .g grammar in repo.

**Comment by parrt** [comment]
Yep! Wanna start? ;)

**Comment by rajmahendra** [comment]
@parrt I dont have much knowledge in lex,parser etc :(

**Comment by cshapeshifter** [comment]
A few hints to get started:

* The Haskell 2010 report contains a [syntax description](https://www.haskell.org/onlinereport/haskell2010/haskellch10.html#x17-17500010)
* Haskell [is not context free](http://trevorjim.com/haskell-is-not-context-free/) which means that things like indentations matter (like in Python, for example)
* Haskell knows a [whole lot of extensions](https://hackage.haskell.org/package/Cabal-1.14.0/docs/Language-Haskell-Extension.html) to the language, which probably need to be supported as well for the grammar to be useful.
* GHC uses the [haskell-src-exts](https://hackage.haskell.org/package/haskell-src-exts) library to parse Haskell code. The library supports all common extensions and its [Lexer](https://hackage.haskell.org/package/haskell-src-exts-1.16.0.1/docs/Language-Haskell-Exts-Lexer.html) could serve as an inspiration in addition to the Haskell report.

**Comment by rajmahendra** [comment]
@parrt @cshapeshifter I found one with old version http://eclipsefp.sourceforge.net/repo/net.sf.eclipsefp.haskell.core.jparser/antlr-src/haskell-lexer.g

**Comment by KvanTTT** [comment]
I'm reopening this task because of haskell grammar is still not exist.
