### ISSUE TITLE
Mysql Positive-Technologies : no viable alternative at input 'Load from'

### ISSUE THREAD

**Issue by raphaelauv** [antlr/grammars-v4#2109]
Hin I use debezium and the sql Positive-Technologies grammar

the query :

```sql
Grant Load from S3 ON YYYY.* TO 'XXXX'
```
is not parsable, the error is 
```shell
 no viable alternative at input  'Grant Load'
```

and also 
```sql
Load from S3 ON YYYY.* TO 'XXXX'
```

give
```shell
line 1:5 no viable alternative at input 'Load from'
```

Thank you

**Comment by jpechane** [comment]
Downstream PR available at https://github.com/debezium/debezium/pull/2265

Will provide upstream one upon clarification about the second statement.

**Comment by raphaelauv** [comment]
Hey I tried in local your fix , but it's not working

it give 

```shell
line 1:11 no viable alternative at input 'GRANT Load from'
```

**Comment by jpechane** [comment]
Please provide the complete statement

**Comment by KvanTTT** [comment]
If it does not break compatibility with the original version and it's commonly used syntax then why not.

**Comment by raphaelauv** [comment]
its an aws thing , you're right. thanks :+1:
