### ISSUE TITLE
CI builds should be robust

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#2114]
The CI scripts need a little tweaking to make them more robust in the face of download failures.
* [Invoke-WebRequest is failing many times](https://github.com/antlr/grammars-v4/runs/2235847245?check_suite_focus=true#step:6:20). [Invoke-WebRequest](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.1) should be called with `-MaximumRetryCount n` and `-RetryIntervalSec m` e.g., [here](https://github.com/antlr/grammars-v4/blob/master/.github/workflows/main.yml#L62) and [here](https://github.com/antlr/grammars-v4/blob/master/.github/workflows/main.yml#L70). Both calls should check the return code, not just the first.
* [Dart download failure](https://github.com/antlr/grammars-v4/runs/2189725203?check_suite_focus=true#step:8:403). The download for Dart is a `dart pub get` call, [here](https://github.com/antlr/grammars-v4/blob/master/_scripts/templates/Dart/makefile#L12) and [here](https://github.com/antlr/grammars-v4/blob/master/_scripts/templates/Dart/tester.psm1#L11).

These are just two places that should be fixed, but there are probably others for the other targets.

--Ken

**Comment by kaby76** [comment]
This failed again yesterday (pr2115). I'm making a quick change for this now. -Ken

**Comment by studentmain** [comment]
> probably others for the other targets.

technically: `npm i`, `go get`, `pip install -r`, even `dotnet build` will download dependency too, so it's every targets except Java.

I think it's just because Dart's package manager is not stable enough. and we download the dependency many times, so we got a much higher failure rate than other repo.

**Comment by kaby76** [comment]
@teverett @KvanTTT I have changed the title of this issue, #2114, to now be "CI build should be robust". There is a process that's been running for >4 hours (JavaScript/macosx build and test) and I cannot kill it. Can you kill the [non-terminating GitHub Action running](https://github.com/antlr/grammars-v4/pull/2157/checks?check_run_id=2462848725)?

In fact, not only is there no `kill -9` button in Github Actions, but there is no way I can see exactly where it hanged in the test in order to determine why: Github Actions only likes to show a glossy overview of what it's doing, but there's no access of stdout/stderr logs until the build has actually finished.

Worse, Antlr JavaScript 4.9.2 is not trustworthy. I have always felt uneasy after JavaScript testing was added to CI builds in antlr/grammars-v4. There is a critical bug in Antlr4.9.2 JS that I pointed out (https://github.com/antlr/antlr4/issues/3135 , transition edges in an ATN are mutating while parsing). Not only does it give invalid parses, but it also causes non-terminating Node.js. I gave a likely solution ([last sentence of last comment](https://github.com/antlr/antlr4/issues/3135#issuecomment-804706824) of that issue), but the conversation was dropped. @parrt  So, when the build is somehow killed, I will remove JavaScript from testing in antlr/grammars-v4. Antlr4 JavaScript 4.9.2 does not work until hanging builds in Github Actions are resolved or Antlr JS is fixed.

**Comment by parrt** [comment]
@ericvergnaud  Sounds like we have a critical issue in JavaScript that we should address?

**Comment by ericvergnaud** [comment]
GitHub actions are clearly not mature yet, but self-hosted macs is the only option available so I'd say we have to live with that for now and cross fingers that it will improve rapidly.

**Comment by ericvergnaud** [comment]
@kaby76 sorry for the lack of action but I've been dealing with family issues for the past 5 weeks...
Can you submit a PR with the proposed change?

**Comment by kaby76** [comment]
@ericvergnaud Sorry to hear. I will try to make a PR within a few days. --Ken

**Comment by kaby76** [comment]
I'm closing the PR and Issue off because the change is no longer needed. Downloading from the Internet has not been a problem, and watchdogging the build is now a separate Issue.
