### ISSUE TITLE
CPP14.g4 does not recognize assignment of negative number

### ISSUE THREAD

**Issue by ylemoigne** [antlr/grammars-v4#212]
Hi and thanks for your work.

Given
```cpp
double foo=0.0;
foo=-1;
```

The CPP grammar don't recognize (no viable alternative) this construct : 
```cpp
foo=-1;
````

I tried to take a look to fix and PR it, but i'm really a beginner with antlr and I fear to do more harm than good.

**Comment by KvanTTT** [comment]
@ylemoigne, indeed!

**unaryoperator** rule does not have '-' terminal: https://github.com/antlr/grammars-v4/blob/master/cpp/CPP14.g4#L206

**Comment by ylemoigne** [comment]
@KvanTTT Thanks. I made the PR.
