### ISSUE TITLE
cannot find symbol class PhpLexerBase

### ISSUE THREAD

**Issue by acuna-public** [antlr/grammars-v4#2123]
Hello, I'm trying to parse the PHP using Java runtime, but generated lexer cannot find the `PhpLexerBase` class. Only what I see is that it must be generated in PhpLexer grammar:

```antlr
options {
    superClass=PhpLexerBase;
}
```

Thanks.

**Comment by kaby76** [comment]
Are you looking for [this Java code](https://github.com/antlr/grammars-v4/blob/master/php/Java/PhpLexerBase.java)? The target-specific code is organized in directoryies corresponding to the name of the target, i.e., [php/Java/](https://github.com/antlr/grammars-v4/tree/master/php/Java). Copy the file into where the generated files are placed, then it should compile. --Ken

**Comment by acuna-public** [comment]
Oh my, thanks, I didn't know that there's situations needs to make something manually, so didn't copy this folders to my project.
