### ISSUE TITLE
"golang" grammar doesn't build and run for Go target

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#2136]
The [golang](https://github.com/antlr/grammars-v4/tree/master/golang) grammar does not work for the Go target. I have to admit that I'm partially to blame, having made untested changes. It's now time to fix this.

I now have a working version Go parser with the Go target. Here are the problems that need to be corrected.

* The package for the Go parser base code must be changed to "parser" and not anything else. Go doesn't handle "no package": the Antlr tool generates "package parser" by default. To add to the problem, I modified the driver generator dotnet-antlr, which is now called trgen and part of the Trash toolkit, to hardwire the package to "parser" as well.
* The semantic predicates in the grammar, e.g., `checkPreviousTokenText()`, need to be made Go specific. Unfortunately, the Go compiler seems to require an object syntax, e.g., `p.checkPreviousTokenText()` not `checkPreviousTokenText()`. Therefore, a copy of the grammar must be placed in the Go/ subdirectory, and modified with this syntax.
* The syntax for the C# method "String.Contains(string)" should be "strings.Contains(foo, bar)" in Go/go_parser_base.go.
* Tabs are evil because tab stops are editor specific. They should be replaced with spaces.
* Go/go_parser_base.go contained some Java-specific syntax which does compile in Go. `} else {` should be on one line.
* Semi-colons at the end of statements in Go are not required. They should be removed.
* The indentation for the code in various targets is terrible. One example I made is that when I removed the package decl in C#, I didn't unindent the code.
* Some of the token types in go_parser_base.go have a GoParser prefix, but others have a GoLexer prefix. It should be consistent and parallel the other targets. 
* The CI should be updated to add the golang grammar for the Go target.

I have a fix, and the Go target for golang now works fine.

--Ken

**Comment by Marti2203** [comment]
Hi,
I made the changes yesterday. I can take responsiblity and fix them if it is not too late.

**Comment by kaby76** [comment]
@Marti2203 Don't worry, I got this. I picked it up from where you left it, which improved on things. There is a change required in the trgen program to place the go_parser_base.go file in parser/ directory. So, it's best all these changes happen in one PR, one check in, later today. I'll pass it over for your review. --Ken

**Comment by Marti2203** [comment]
Okay, nice :)
