### ISSUE TITLE
Make some methods in generated parser static

### ISSUE THREAD

**Issue by kstallard** [antlr/grammars-v4#2143]
I am only looking at this from a CPP perspective, but it would be nice if some methods in the generated code were static.  Essentially anything that doesn't have to do with the parsing state during parsing would be helpful if they were static.

For example, getRuleNames().  

I would like to get access to the rule names without have to have an instance of the Parser.

Just a suggestion.

Thanks
Kevin

**Comment by KvanTTT** [comment]
I guess your issue is related to ANTLR itself? Try to search in its tracker: https://github.com/antlr/antlr4/issues

**Comment by kstallard** [comment]
@KvanTTT  duh!  I wasn't thinking..sorry about that....yeah, that would be a better place.  Thank you :)
