### ISSUE TITLE
Antlr4 grammar does not parse apt/ and sql/tsql/ grammars

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#2149]
The grammar antlr/antlr4/, which I use in a multitude of Antlr tools, does not parse apt/apt.g4 and sql/tsql/TSqlParser.g4. That's because `options` is a keyword, and it is being used in the grammars as an identifier. The problem was introduced in [the "Update for v4.5 compatibility" commit](https://github.com/antlr/grammars-v4/commit/36c7c5a1768dc21c93729a8a33770e18c6065aa0#diff-d5b3cfafc91b37f567bb42d4e8822fb5c848acea229f79ed463fd2a0cdfe01b2) made six years ago. At the time, apt/ and tsql/ did not exist in this repo.

The grammar antlr/antlr4/ needs to either do what the Antlr4 tool does, which has [lexer rules](https://github.com/antlr/antlr4/blob/master/tool/src/org/antlr/v4/parse/ANTLRLexer.g#L440) for 'options' and the open curly), or continue with the current "mode" lexer. However, the Antlr tool itself does not use "modes" for lexing options, tokens, and channels. When the Antlr tool grammar is updated with changes, the changes should be propagated to the grammar here in this repo automatically. Hence, the grammar here should roll back to the non-modes implementation.

The antlr/antlr4/ grammar is used in other Antlr tools, e.g., [Mike Lischke's Antlr4 Visual Studio Code extension](https://github.com/mike-lischke/vscode-antlr4/blob/master/grammars/ANTLRv4Lexer.g4#L125). @mike-lischke

I found this problem when applying [trparse](https://github.com/kaby76/Domemtech.Trash/tree/main/trparse) to all the grammars in this repo. Fortunately, I have a preliminary fix using the rules in Antlr4 tool. With the change, all the grammars in the repo parse.

**Comment by kaby76** [comment]
[These changes](https://github.com/kaby76/Domemtech.TrashBase/commit/a5482f7321771c1baf293177ae7ea3941d2e7787) in the Trash tool set fix the problem with the Antlr4 grammar parsing other Antlr4 grammars. I'll submit a change request shortly.

**Comment by mike-lischke** [comment]
I'm suprised the 2 grammars are not identical. What's the sense of having 2 different ANTLR4 grammars? 

Aside from that, similar rules should apply to all grammars, where possible symbol conflicts could occur. That includes IMO also conflicts with ANTLR4 itself. So the keyword `options` should not be allowed anywhere else than defining an options block, and instead the grammar should use `options_` or similar.

**Comment by mike-lischke** [comment]
> [These changes](https://github.com/kaby76/Domemtech.TrashBase/commit/a5482f7321771c1baf293177ae7ea3941d2e7787) in the Trash tool set fix the problem with the Antlr4 grammar parsing other Antlr4 grammars. I'll submit a change request shortly.

Make sure you also fix the comment above your changes, which talks about different grammar modes, which are no longer used after your patch is applied.

**Comment by kaby76** [comment]
@KvanTTT This issue should get the [antlr4](https://github.com/antlr/grammars-v4/labels/antlr4) label. It's a problem with the antlr4 grammar, only incidentally associated with symbol conflicts because the trrename tool couldn't parse two grammars as it uses the antlr/antlr4/ grammar for parsing. I can't seem to change the labeling for this issue. Thanks. --Ken Domino.
