### ISSUE TITLE
Rewrite Java8 grammar using alternative labels

### ISSUE THREAD

**Issue by KvanTTT** [antlr/grammars-v4#215]
Use [alternative labels](https://theantlrguy.atlassian.net/wiki/display/ANTLR4/Parser+Rules#ParserRules-AlternativeLabels) at least for expressions in order to simplify and shorten grammar.
The good sample of grammar with alternative labels is [ECMAScript.g4](https://github.com/antlr/grammars-v4/blob/master/ecmascript/ECMAScript.g4#L624)

This improvement also should bring performance increase.

**Comment by bjansen** [comment]
How much performance increase are we talking here? One a rather simple file like [this](https://raw.githubusercontent.com/ceylon/ceylon-web-ide-backend/master/src/main/java/com/redhat/ceylon/js/repl/Autocompleter.java), the current grammar takes something like 10s and 1.5GB of memory to parse the file :/

**Comment by KvanTTT** [comment]
I don't know, but it should improve performance. I tested grammar without left-recursion and with left-recursion (my not yet approved [PHP grammar](https://github.com/antlr/grammars-v4/pull/224)). Moreover, grammars with left recursion have a more clear syntax.

Current Java8 grammar have an excess rules which decreased performance too. 
Nonetheless current Java7 grammar not an ideal too (very slow performance on some files compare to Java8).

I hope, that I'll rewrite Java8 grammar if community approved.

@bjansen , did you try to parse your file with Java7 grammar?

**Comment by parrt** [comment]
optimizing the grammar can make MASSIVE improvements. ALL(*) has a very high constant in some cases.

**Comment by bjansen** [comment]
It seems I get approximately the same results using the Java 7 grammar. I'll try using a few alternative labels to see if it helps.

**Comment by parrt** [comment]
hmm...oh, are you using the (two-phase parsing strategy](https://theantlrguy.atlassian.net/wiki/pages/viewpage.action?pageId=1900591)? It is critical.

**Comment by bjansen** [comment]
Yeah I tried it but phase 1 fails, so it switches back to phase 2, which is very slow.

```
org.antlr.v4.runtime.InputMismatchException
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:85)
	at org.antlr.v4.runtime.Parser.match(Parser.java:229)
```

**Comment by parrt** [comment]
rats. well, I'd have to verify which java7 grammar I actually have up there. not sure it's my latest.

**Comment by KvanTTT** [comment]
@parrt , there is my sample with very slow parsing performance for Java.g4 (compare to Java8.g4): [ManyStringConcatenation.java](https://gist.github.com/KvanTTT/bf20f6a4aac708b49df2) (It's bad style code, but it's based on the real sample).

One of  the possible reason of such slow performance is Java7 *elementValue* rule for annotation include *assignment* subrule, wheres Java8 *elementValue* does not. I added parts of these grammars for comparsion.

**Java7**
```ANTLR
annotation
    :   '@' annotationName ( '(' ( elementValuePairs | elementValue )? ')' )?
    ;
    
annotationName : qualifiedName ;

elementValuePairs
    :   elementValuePair (',' elementValuePair)*
    ;

elementValuePair
    :   Identifier '=' elementValue
    ;

elementValue
    :   expression
    |   annotation
    |   elementValueArrayInitializer
    ;
    
expression
    : 
    ...
    <assoc=right> expression // contains 'assignment' subrule.
        (   '='
        |   '+='
        |   '-='
        |   '*='
        |   '/='
        |   '&='
        |   '|='
        |   '^='
        |   '>>='
        |   '>>>='
        |   '<<='
        |   '%='
        )
        expression
    ;
```

**Java8**

```ANTLR
annotation
	:	normalAnnotation
	|	markerAnnotation
	|	singleElementAnnotation
	;
    
normalAnnotation
	:	'@' typeName '(' elementValuePairList? ')'
	;
    
elementValuePairList
	:	elementValuePair (',' elementValuePair)*
	;
    
elementValuePair
	:	Identifier '=' elementValue
	;
    
elementValue
	:	conditionalExpression // not contains 'assignment' subrule
	|	elementValueArrayInitializer
	|	annotation
	;

...

assignmentExpression
	:	conditionalExpression
	|	assignment
	;

assignment
	:	leftHandSide assignmentOperator expression
	;
```

**Comment by parrt** [comment]
ah. yes, ANTLR is not very fast on deep expressions using the left recursive description for expressions.

**Comment by KvanTTT** [comment]
@bjansen, could you please upload your file **Autocomple.java** or another file with slow parsing performance? Your link is broken. I am trying to improve Java8.g4.

**Comment by bjansen** [comment]
Here's a link that works: https://raw.githubusercontent.com/ceylon/ceylon-web-ide-backend/e2089a0d9d1b821ba08d33c883354a7a2e87929f/src/main/java/com/redhat/ceylon/js/repl/Autocompleter.java

**Comment by KvanTTT** [comment]
@bjansen it is an interesting issue. Parser for .NET runtime runs much faster (0.35 sec) compare to Java runtime (4.5 sec, IntelliJ IDEA). But our advices really work. I'll upload new version soon.

**Comment by parrt** [comment]
Are you using the ANTLR plugin profiler?

**Comment by KvanTTT** [comment]
Yep. Does profiling significally influence on performance? Anyway parsing time less than 10 sec as @bjansen noticed. Expression rewriting brought less memory consuption (plugin is not crashing with default java settings :)

**Comment by drbo** [comment]
@KvanTTT Profiling does not improve performance directly, but does tell the programmer what to optimize.

**Comment by bjansen** [comment]
Hi guys, did you have time to look at this grammar and improve performance?

**Comment by KvanTTT** [comment]
@bjansen, I have simplified version of this grammar. But actually I did not measure performance. But I can send it to you :)

**Comment by bjansen** [comment]
@KvanTTT Well if it works and it is faster than the current version, then yes I'm interested :D
Can you put it in a gist please?

**Comment by KvanTTT** [comment]
@bjansen here is grammar: [Java8.g4](https://gist.github.com/KvanTTT/49bae73e8df45bf00981). I have not completed, therefor have not make PR.

**Comment by KvanTTT** [comment]
@bjansen, Java and Java8 grammars should be rewritten as it described in my publication about source code parsing: [Java and Java8](http://blog.ptsecurity.com/2016/06/theory-and-practice-of-source-code.html#java--and-java8-grammars).

**Comment by bjansen** [comment]
Interesting read, that confirms what you said in your previous comment. By the way, did you have time to complete the new version of the grammar?

**Comment by parrt** [comment]
guys we have competing goals here. Oracle asked me to make one that was just like the spec. but we need a fast java8. perhaps we need to fork into new subdir for fast one?

**Comment by bjansen** [comment]
That's fine by me, as long as I can have access to a fast grammar 😉

**Comment by KvanTTT** [comment]
Ok, I hope to upload an optimized Java8 grammar closer to the autumn. At present time [PHP](https://github.com/antlr/grammars-v4/tree/master/php) grammar combines relative high performance parsing and good deep expressions processing at it described in abovementioned topic.

**Comment by sharwell** [comment]
The Java 8 grammar I wrote originally was not designed *at all* with performance in mind. The goal was to write the grammar as close to the JLS as possible so we could try and parse the JDK 8 source code and see if any known Java 8 code didn't conform to the specification. Unsurprisingly, the grammar proved to be sufficiently slow that my optimized fork was required to get it to run on that codebase in a reasonable time (many optimizations of my fork "undo" the negative performance impact associated with certain grammar design choices).

**Comment by KvanTTT** [comment]
Try a new optimized [java8-pt](https://github.com/antlr/grammars-v4/tree/master/java8-pt) grammar that based on Java7 grammar.
