### ISSUE TITLE
Java8, Java9, and Apex all need to be fixed

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#2156]
Java8, Java9, and Apex all need fixing for target-independent coding.

* The Java9 grammar is currently not strictly target-independent because it contains semantic predicates.
* The rules with semantic predicates (e.g., [here](https://github.com/antlr/grammars-v4/blob/master/java/java9/Java9Lexer.g4#L487)) are based on the Java Language Spec. There are implementations in grammars-v4/java/java/ and grammars-v4/java/java8 that are predicate-free (see the rules in the Java8 grammar starting [here](https://github.com/antlr/grammars-v4/blob/e53d7a1228505bfc80d8637808ef60e7eea92cc2/java/java8/Java8Lexer.g4#L469)). It's possible to rewrite this without action code.
* The apex/ grammar is essentially a derivative of Java9. It too can be rewritten to not use action code.
* Java8 is a predicate-free solution, but it can be improved: Antlr supports a 32-bit code point value in the grammar and runtime (see [this](https://github.com/antlr/antlr4/pull/1633)).
* Not all targets or runtimes can handle the 32-bit code point value notation in Antlr4 grammars. Some targets will need to have a separate grammar and source code. The Antlr4cs tool does not accept 32-bit code points. The encoding feature in the Dart runtime doesn't seem to work.
* The CI driver scripts should be updated to be able to create a stream that can handle an encoding, although it wouldn't be used in any tests.
* '<>' is implicitly defined in a parser rule. It needs to be explicitly defined in the lexer.
* Java8 has commented out rules [here](https://github.com/antlr/grammars-v4/blob/e53d7a1228505bfc80d8637808ef60e7eea92cc2/java/java8/Java8Lexer.g4#L449). The old rules should be deleted for readability.
* The Java Language Spec defines JavaLetter and JavaLetterOrDigit operationally. A question should be asked of the authors of the Java Language Specification as to why it's necessary to use an operational definition.

**Comment by studentmain** [comment]
StringTemplate grammar is using Java identifier rule too.

**Comment by kaby76** [comment]
There is a statistical diff between the PR grammar (slower) and original java/java/ (Parr et al) grammar (faster), t = -45, N = 49751, but the average slowdown is 0.002 s, and there are no big outliers to indicate some pathological case for some input. (C#, NET6 pre-release, Ryzen2200G, 16G DDR4, SSD, blah blah blah) Out of 49751, 1412 failed. This is with a clone of the current jdk/ sources (using `find jdk -name '*.java' -type f`), and some may be intentional tests with parse errors.

**Comment by kaby76** [comment]
Closing issue in order to redo everything one issue one change at a time. At least four issues will now be created.
