### ISSUE TITLE
CI build fails in Dice

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#2204]
The build of the CSharp target for the Dice grammar fails, likely because there was an update in Github Actions for msbuild/dotnet (which I explain somewhat [here](https://github.com/antlr/grammars-v4/pull/2201#issuecomment-845565481)). I tried recreating the problem on my Linux box, but I haven't.

**Comment by kaby76** [comment]
@KvanTTT This seems to have taken care of the problem in so far as the build not crashing at this point. It's the first build in what looks like three days that is finally working. The grammar wasn't following the usual practice of a split grammar. I recommend it be merged at this point. I will make a note that there's a bug here with Antlr4BuildTasks. But, the build here should probably be modfied to not rely on Antlr4BuildTasks. So I will create a new Issue for that. --Ken

**Comment by KvanTTT** [comment]
Yes, grammar splitting is good.
