### ISSUE TITLE
Possible problem in typeDeclaration

### ISSUE THREAD

**Issue by ektagd** [antlr/grammars-v4#222]
If I wrote a class as follows:
public private class ABC
{
}
this grammar accepts it, even though it isn't right.
Why?

**Comment by KvanTTT** [comment]
What grammar?

**Comment by rojaster** [comment]
classModifier* - match zero or more

**Comment by rojaster** [comment]
Java8.g4 ?

**Comment by teverett** [comment]
Should we close this one?

**Comment by teverett** [comment]
@rojaster  can we close this?
