### ISSUE TITLE
Antlr generates wrong c++ code for antlrv4.g4

### ISSUE THREAD

**Issue by Changochen** [antlr/grammars-v4#2239]
When using `antlr-4.9.2` to generate parser for `ANTLRv4*.g4` in [here](https://github.com/antlr/grammars-v4/tree/master/antlr/antlr4), the c++ code generated in `ANTLRv4Lexer.cpp` contains the following code:

```cpp
  63 void ANTLRv4Lexer::BEGIN_ARGUMENTAction(antlr4::RuleContext *context, size_t actionIndex) {
  64   switch (actionIndex) {
  65     case 0:  this.handleBeginArgument();  break; // `this` is a pointer!!
  66
  67   default:
  68     break;
  69   }
  70 }
```

How to reproduce:
```
mkdir generated
LOCATION=antlr-4.9.2-complete.jar
java -jar $LOCATION -Dlanguage=Cpp -listener -visitor -o generated/ ANTLRv4Lexer.g4 ANTLRv4Parser.g4
```

Is this a bug or is it because I didn't use the `LexerAdaptor.cpp/h` ? I also found that the generated `ANTLRv4Lexer.h` depends on `LexerAdaptor.h` but doesn't include it.

**Comment by kaby76** [comment]
These are bugs in the grammar; the port for Cpp is incorrect. The code should declare "ANTLRv4Lexer & self", which should be assigned "*this", and all "this" refs replaced with "self". The header include needs to be added in the grammar.

**Comment by Changochen** [comment]
Thanks for the reply, Ken! Could you give more hints about how to declare "ANTLRv4Lexer & self" in the grammar? I couldn't find instructions about it.

> The header include needs to be added in the grammar.
Yeah. I found that we can use `@header` for it. Thanks!

**Comment by kaby76** [comment]
Check out the code [here](https://github.com/kaby76/grammars-v4/tree/issue-2222/sql/plsql/Cpp). It might help give you an idea on how to implement a solution.

**Comment by Changochen** [comment]
Thanks for the hint! It works now.
