### ISSUE TITLE
java 8 grammar fails to parse string with unicode

### ISSUE THREAD

**Issue by mlorek** [antlr/grammars-v4#2264]
grammar fails to parse string  "\"" when \ character is represented using unicode notation:

```java
class Foo {

	String s = "\u005c"";
    
}

**Comment by studentmain** [comment]
I remember java replace all \uxxxx before parse, so `cl\u0061ss A{}` is valid too

**Comment by studentmain** [comment]
https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.2

A custom input stream or a preprocessor is needed.

**Comment by mlorek** [comment]
how about this?

fragment EscapeSequence
    : '\\' [btnfr"'\\]
    | '\\' ([0-3]? [0-7])? [0-7]
    | '\\' 'u'+ HexDigit HexDigit HexDigit HexDigit
    | '\\u005c' [btnfr"'\\]
    ;

**Comment by studentmain** [comment]
> how about this?
> 
> fragment EscapeSequence
> : '\' [btnfr"'\]
> | '\' ([0-3]? [0-7])? [0-7]
> | '\' 'u'+ HexDigit HexDigit HexDigit HexDigit
> | '\u005c' [btnfr"'\]
> ;

Problem is not only "string with unicode", problem is everything with unicode
