### ISSUE TITLE
TSql square bracket optional in column definition

### ISSUE THREAD

**Issue by AMagistroni** [antlr/grammars-v4#2282]
There is a problem with the column definition in TSql grammar.

```sql
CREATE TABLE [dbo].[myTable] (
	[Description] [varchar](max) NULL
)
```

The TSql grammar is 

```antlr
data_type
    : scaled=(VARCHAR | NVARCHAR | BINARY_KEYWORD | VARBINARY_KEYWORD) '(' MAX ')'
```

So the column datatype without brackets

```sql
[Description] varchar(max) NULL
```

works well. I think that the square should be optional or mandatory, but now the parser doesn't work with the brackets.

Other columns definition such as

```sql
[nameOfColumn] [int] NULL
```

works fine both with brackets and without them.
The problem seem related to MAX. With a number it's work

**Comment by RupertAvery** [comment]
It looks like the rule `id_ `is taking precedence due to it handling `SQUARE_BRACKET_ID`.

Even if I try adding a rule with square brackets around the VARCHAR part, _id still takes precedence.
