### ISSUE TITLE
cpp grammar does not recognize includes

### ISSUE THREAD

**Issue by teverett** [antlr/grammars-v4#230]
This snippet of code:

<pre>

/* Hello World program */

#include<stdio.h>

main()
{
    printf("Hello World");

}

</pre>

Produces this result:

<pre>
Compiling grammar files...
warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openide.modules.PatchedPublicProcessor' less than -source '1.7'
warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openide.util.ServiceProviderProcessor' less than -source '1.7'
warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openide.util.NamedServiceProcessor' less than -source '1.7'
warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openide.util.NbBundleProcessor' less than -source '1.7'
4 warnings
Arguments: [C, primaryExpression, -tokens, -tree, -gui, /Users/teverett/Desktop/helloworld.c]
line 4:0 token recognition error at: '#i'
[@0,30:35='nclude',<105>,4:2]
[@1,36:36='<',<65>,4:8]
[@2,37:41='stdio',<105>,4:9]
[@3,42:42='.',<103>,4:14]
[@4,43:43='h',<105>,4:15]
[@5,44:44='>',<67>,4:16]
[@6,47:50='main',<105>,6:0]
[@7,51:51='(',<59>,6:4]
[@8,52:52=')',<60>,6:5]
[@9,54:54='{',<63>,7:0]
[@10,60:65='printf',<105>,8:4]
[@11,66:66='(',<59>,8:10]
[@12,67:79='"Hello World"',<107>,8:11]
[@13,80:80=')',<60>,8:24]
[@14,81:81=';',<87>,8:25]
[@15,84:84='}',<64>,10:0]
[@16,87:86='<EOF>',<-1>,12:0]
(primaryExpression nclude)

</pre>

**Comment by parrt** [comment]
That would have to be done by the C preprocessor prior to C++ parsing. :)

**Comment by KvanTTT** [comment]
Does result output related to snippet of code? I guess it should be ```#include  <stdio.h>```.

**Comment by teverett** [comment]
@KvanTTT same result

`
Compiling grammar files...
warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openide.modules.PatchedPublicProcessor' less than -source '1.7'
warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openide.util.ServiceProviderProcessor' less than -source '1.7'
warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openide.util.NamedServiceProcessor' less than -source '1.7'
warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openide.util.NbBundleProcessor' less than -source '1.7'
4 warnings
Arguments: [C, primaryExpression, -encoding, UTF-8, -tokens, -tree, -gui, /Users/tom/Desktop/x.c]
line 3:0 token recognition error at: '#i'
[@0,29:34='nclude',<105>,3:2]
[@1,36:36='<',<65>,3:9]
[@2,37:41='stdio',<105>,3:10]
[@3,42:42='.',<103>,3:15]
[@4,43:43='h',<105>,3:16]
[@5,44:44='>',<67>,3:17]
[@6,47:50='main',<105>,5:0]
[@7,51:51='(',<59>,5:4]
[@8,52:52=')',<60>,5:5]
[@9,54:54='{',<63>,6:0]
[@10,60:65='printf',<105>,7:4]
[@11,66:66='(',<59>,7:10]
[@12,67:79='"Hello World"',<107>,7:11]
[@13,80:80=')',<60>,7:24]
[@14,81:81=';',<87>,7:25]
[@15,84:84='}',<64>,9:0]
[@16,85:84='<EOF>',<-1>,9:1]
(primaryExpression nclude)
`

**Comment by parrt** [comment]
`cc -E t.c` will get the actual C++ input :)
