### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by patrik-ronnqvist** [antlr/grammars-v4#2315]
I have a Java project that uses ANTLR to parse about 100 000 files written in Java, C++ and Cobol. After a file has been parsed it is closed down and the result is saved in an external database.

There seems to be a memory leak causing the JVM to eat more and more memory until the whole program slows to a crawl. No actual OutOfMemoryError is thrown. I attached a monitor to measure the memory consumption. It just goes up over time, and it looks like most of it is used by ANTLRs internal classes.

I make sure to drop all references to the lexers and parsers once I'm done with them. I also call removeErrorListeners(), removeParseListeners() and reset() before dropping them, but it doesn't seem to make a difference. I only use ANTLRs context classes that I get from the listeners locally within methods, so no references to them should remain either.

Has anyone used ANTLR for a project on this scale before? Is there any way I can make sure ANTLR clears out its internal classes after parsing a file? Intuitively classes like ATNConfig should drop to zero instances between each file, there's no reason there should be any data remaining. Worst case I could run ANTLR in a separate JVM and restart it periodically, but that seems like it shouldn't be necessary.

![Memory1](https://user-images.githubusercontent.com/61742864/131507622-abec4c79-e54a-452d-bb3b-30c25ba38dbf.PNG)
![Memory2](https://user-images.githubusercontent.com/61742864/131507623-acfb46f9-adc0-4afb-8abf-99f8164a18eb.PNG)

**Comment by kaby76** [comment]
This is a known problem. https://github.com/antlr/antlr4/issues/1944 But it depends on the grammar. [Harwell mentioned](https://github.com/antlr/antlr4/issues/1944#issuecomment-314451939) that "[l]ong lookahead sequence[s] with branching grammars tend to produce the highest memory usage." There may be perf flags that one can use to determine the rules that are problematic, which could then be rewritten. Which grammars in this repo are you using?

**Comment by patrik-ronnqvist** [comment]
Using clearDFA() to clear the static _decisionToDFA variable in the lexers/parsers and setInterpreter() to avoid using the static _sharedContextCache variable as shown in the other issue seems to have worked.

It's not very intuitive and ANTLR gives you no warning that you might need to do this. The lexers and parsers could really use a more straightforward method to clear out the caches. Or better yet, **I'd suggest using soft references on the caches so the garbage collector can clear them out automatically when running low on memory**.

Once you're done using a lexer/parser for the remainder of the program those caches are just dead weight anyway. If you're going through multiple languages like in my use case they really should just be dropped afterwards.
