### ISSUE TITLE
Failed to run `mvn clean test`

### ISSUE THREAD

**Issue by smartnewsdingli** [antlr/grammars-v4#2326]
I clone all repo and run `mvn clean test`. Below are errors:

`[ERROR] Failed to execute goal com.khubla.antlr:antlr4test-maven-plugin:1.18:test (default) on project abb: Execution default of goal com.khubla.antlr:antlr4test-maven-plugin:1.18:test failed: Unable to load the mojo 'test' in the plugin 'com.khubla.antlr:antlr4test-maven-plugin:1.18' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com/khubla/antlr/antlr4test/GrammarTestMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.khubla.antlr:antlr4test-maven-plugin:1.18
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/dingli/.m2/repository/com/khubla/antlr/antlr4test-maven-plugin/1.18/antlr4test-maven-plugin-1.18.jar
[ERROR] urls[1] = file:/Users/dingli/.m2/repository/org/antlr/antlr4-runtime/4.9.2/antlr4-runtime-4.9.2.jar
[ERROR] urls[2] = file:/Users/dingli/.m2/repository/org/antlr/antlr4/4.9.2/antlr4-4.9.2.jar
[ERROR] urls[3] = file:/Users/dingli/.m2/repository/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar
[ERROR] urls[4] = file:/Users/dingli/.m2/repository/org/antlr/ST4/4.3/ST4-4.3.jar
[ERROR] urls[5] = file:/Users/dingli/.m2/repository/org/abego/treelayout/org.abego.treelayout.core/1.0.3/org.abego.treelayout.core-1.0.3.jar
[ERROR] urls[6] = file:/Users/dingli/.m2/repository/org/glassfish/javax.json/1.0.4/javax.json-1.0.4.jar
[ERROR] urls[7] = file:/Users/dingli/.m2/repository/com/ibm/icu/icu4j/61.1/icu4j-61.1.jar
[ERROR] urls[8] = file:/Users/dingli/.m2/repository/commons-io/commons-io/2.8.0/commons-io-2.8.0.jar
[ERROR] urls[9] = file:/Users/dingli/.m2/repository/org/codehaus/plexus/plexus-utils/3.3.0/plexus-utils-3.3.0.jar
[ERROR] urls[10] = file:/Users/dingli/.m2/repository/org/bitbucket/cowwoc/diff-match-patch/1.2/diff-match-patch-1.2.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]`

Here is my java version
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment Corretto-8.292.10.1 (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM Corretto-8.292.10.1 (build 25.292-b10, mixed mode)
```

**Comment by studentmain** [comment]
try java11?

**Comment by smartnewsdingli** [comment]
Thank you @studentmain . Does it only work on Java 11?

**Comment by smartnewsdingli** [comment]
Confirmed, run with java 11 is fine. Close it.
