### ISSUE TITLE
It's too slow to parse some functionDecl in Go

### ISSUE THREAD

**Issue by kirito41dd** [antlr/grammars-v4#2327]
It takes **forever** to parse only **15** code lines ! Could someone take a look of this problem plz? 

env:
- go version go1.16.7 darwin/amd64
- ANTLR Parser Generator  Version 4.9
- runtime github.com/antlr/antlr4/runtime/Go/antlr v0.0.0-20210803070921-b358b509191a
- syntax file: golang/Go/GoParser.g4 (with golang/Go/go_parser_base.go)

demo:
```go
package cmd

var featStructCmd = &cobra.Command{
	Run: func(cmd *cobra.Command, args []string) {

		fileFilter := util.NewFileFilter(
			util.Exists,
			func(s string) bool {
				return !util.IsDir(s)
			},
			util.FilterFileBySuffix(suffix),
		)

	},
}

```
test code:
```go
package main

import (
	"time"

	parser "xxx/gen/parser/go_parser"

	"github.com/sirupsen/logrus"

	"github.com/antlr/antlr4/runtime/Go/antlr"
)

func main() {
	logrus.SetLevel(logrus.TraceLevel)
	fstream, err := antlr.NewFileStream("bin/test-demo/domo.gos")
	if err != nil {
		panic(err)
	}
	lexer := parser.NewGoLexer(fstream)
	tokenStream := antlr.NewCommonTokenStream(lexer, antlr.LexerDefaultTokenChannel)
	goparser := parser.NewGoParser(tokenStream)
	start := time.Now()
	goparser.SourceFile()
	logrus.Infof("%d seconds", time.Now().Sub(start)/time.Second)
}
```
output:
```
INFO[0227] 227 seconds
```

**Comment by studentmain** [comment]
it's a known problem, go target is slow.
#2272
https://github.com/antlr/antlr4/issues/2152

you can use golang official compiler api to parse go in go
https://pkg.go.dev/go/parser@go1.17

**Comment by KvanTTT** [comment]
I'm closing because it does not relate to grammar but to runtime.
