### ISSUE TITLE
PHPLexerBase not found (parsing php code using c++)

### ISSUE THREAD

**Issue by andrejmz** [antlr/grammars-v4#2330]
Hi

After having built the runtime I cant compile because PHPLexerBase implementation is missing
Having seen this https://github.com/antlr/grammars-v4/issues/2123, does it mean I have to dowlnload PHPLexerBase.cpp from somewhere ?

Best regards.

**Comment by KvanTTT** [comment]
Unfortunately, PHPLexerBase.cpp file does not exist, you should write it by yourself. You can take [C#](https://github.com/antlr/grammars-v4/blob/master/php/CSharp/PhpLexerBase.cs) or other version as reference.

**Comment by andrejmz** [comment]
Hi 

Thanks! Actually I am not very familiar with Antlr and i wouldn't even know what to put inside that particular file.
Do you know where I can find informations as to how it works ?

Best regards

**Comment by andrejmz** [comment]
Ok thanks!

Best regards.

**Comment by KvanTTT** [comment]
And port C# or Java code to C++ as I mentioned above. Also, ideally, publish your changes to this repository in the end.

**Comment by halx99** [comment]
I have done: https://github.com/antlr/grammars-v4/pull/3015/files, please review
