### ISSUE TITLE
cql3 assignmentMap problem

### ISSUE THREAD

**Issue by tangxueming** [antlr/grammars-v4#2331]
https://github.com/antlr/grammars-v4/blob/ec72bc2dac7c0362ce357b7afcbace3dfc3b233b/cql3/CqlParser.g4#L588-L590

lack of "syntaxComma"

```g4
assignmentMap 
    : syntaxBracketLc (constant syntaxColon constant) ( syntaxComma constant syntaxColon constant)* syntaxBracketRc 
    ; 
```

**Comment by KvanTTT** [comment]
Could you please suggest a fix using pull request?

**Comment by tangxueming** [comment]
> Could you please suggest a fix using pull request?

It is my pleasure!
https://github.com/antlr/grammars-v4/pull/2332
