### ISSUE TITLE
calculator.g4 parser imaginary number(like (2+1i)+(3+2i)) error

### ISSUE THREAD

**Issue by wuwujiang** [antlr/grammars-v4#2333]
in calculator.g4 defines constant I, does it means \sqrt{-1} constant ? I user it to parser imaginary number(like (2+1i)+(3+2i)), it return extraneous input 'i' expecting ')' error

**Comment by teverett** [comment]
The calculator grammar was written as an academic exercise so that new ANTLR users have a grammar, like calculator, to learn from.  The arithmetic grammar is similar.
