### ISSUE TITLE
Tsql to allow IDs in lower case?

### ISSUE THREAD

**Issue by suntong** [antlr/grammars-v4#2339]
Trying to parser SQL, and I came up with my first step using the Lexer:

https://play.golang.org/p/4sY8ZFg9biC

    package main
    
    import (
    	"fmt"
    
    	"github.com/antlr/antlr4/runtime/Go/antlr"
    
    	//"github.com/bramp/antlr4-grammars/tsql"
    	"github.com/go-sqlparser/antlr4-grammars/tsql"
    )
    
    const sql = `
    SELECT LastName, FirstName
    FROM Person.Person c
    INNER JOIN HumanResources.Employee e
    ON c.BusinessEntityID = e.BusinessEntityID
    JOIN Sales.SalesPerson s 
    ON e.BusinessEntityID = s.BusinessEntityID;
    `
    
    func main() {
    	is, _ := antlr.NewInputStream(sql)
    
    	lexer := tsql.NewTSqlLexer(is)
    
    	// Read all tokens
    	for {
    		t := lexer.NextToken()
    		if t.GetTokenType() == antlr.TokenEOF {
    			break
    		}
    		fmt.Printf("%s (%q)\n", lexer.SymbolicNames[t.GetTokenType()], t.GetText())
    	}
    }

But it seems I have to deal with symbols myself, as I'm getting the following:

```
SELECT ("SELECT")
ID ("L")
line 3:8 token recognition error at: 'a'
line 3:9 token recognition error at: 's'
line 3:10 token recognition error at: 't'
ID ("N")
line 3:12 token recognition error at: 'a'
line 3:13 token recognition error at: 'm'
line 3:14 token recognition error at: 'e'
COMMA (",")
ID ("F")
line 3:18 token recognition error at: 'i'
```

I thought that it should have been taken care of by the lexer, then I realize that the ID are defined only in upper case:

https://github.com/antlr/grammars-v4/blob/dc1f91967c7085edf6d2b7b1f24b365ef65d55f0/sql/tsql/TSqlLexer.g4#L891

I'd propose the following changes:

```diff
--- a/tsql/TSqlLexer.g4
+++ b/tsql/TSqlLexer.g4
@@ -884,9 +884,9 @@ LINE_COMMENT:       '--' ~[\r\n]* -> channel(HIDDEN);
 DOUBLE_QUOTE_ID:    '"' ~'"'+ '"';
 SINGLE_QUOTE:       '\'';
 SQUARE_BRACKET_ID:  '[' (~']' | ']' ']')* ']';
-LOCAL_ID:           '@' ([A-Z_$@#0-9] | FullWidthLetter)*;
+LOCAL_ID:           '@' ([A-Za-z_$@#0-9] | FullWidthLetter)*;
 DECIMAL:             DEC_DIGIT+;
-ID:                  ( [A-Z_#] | FullWidthLetter) ( [A-Z_#$@0-9] | FullWidthLetter )*;
+ID:                  ( [A-Za-z_#] | FullWidthLetter) ( [A-Za-z_#$@0-9] | FullWidthLetter )*;
 STRING:              'N'? '\'' (~'\'' | '\'\'')* '\'';
 BINARY:              '0' 'X' HEX_DIGIT*;
 FLOAT:               DEC_DOT_DEC;
@@ -929,9 +929,9 @@ BIT_OR:              '|';
 BIT_AND:             '&';
 BIT_XOR:             '^';
 
-fragment LETTER:       [A-Z_];
+fragment LETTER:       [A-Za-z_];
 fragment DEC_DOT_DEC:  (DEC_DIGIT+ '.' DEC_DIGIT+ |  DEC_DIGIT+ '.' | '.' DEC_DIGIT+);
-fragment HEX_DIGIT:    [0-9A-F];
+fragment HEX_DIGIT:    [0-9A-Fa-z];
 fragment DEC_DIGIT:    [0-9];
 
 
@@ -950,4 +950,4 @@ fragment FullWidthLetter
     | '\uff00'..'\ufff0'
     // | '\u10000'..'\u1F9FF'  //not support four bytes chars
     // | '\u20000'..'\u2FA1F'
-    ;
\ No newline at end of file
+    ;
```

Comments/concerns?

**Comment by KvanTTT** [comment]
Please use case insensitive input streams for SQL grammars, see https://github.com/antlr/antlr4/blob/master/doc/case-insensitive-lexing.md
