### ISSUE TITLE
ATL grammar does not parse

### ISSUE THREAD

**Issue by teverett** [antlr/grammars-v4#235]
The ATL grammar appears to use the reserved word "rule"

<pre>
oscar:atl tom$ mvn clean package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.antlr.grammarsv4:atl:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.antlr:antlr4test-maven-plugin is missing. @ com.antlr.grammarsv4:atl:[unknown-version], /Users/tom/projects/grammars-v4/atl/pom.xml, line 31, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ATL grammar 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ atl ---
[INFO] Deleting /Users/tom/projects/grammars-v4/atl/target
[INFO] 
[INFO] --- antlr4-maven-plugin:4.5.1-1:antlr4 (default) @ atl ---
[INFO] ANTLR 4: Processing source directory /Users/tom/projects/grammars-v4/atl
[INFO] Processing grammar: ATL.g4
[ERROR] error(134): ATL.g4:59:0: symbol rule conflicts with generated code in target language or runtime
[ERROR] /Users/tom/projects/grammars-v4/atl/ATL.g4 [59:0]: symbol rule conflicts with generated code in target language or runtime
[ERROR] error(134): ATL.g4:43:25: symbol rule conflicts with generated code in target language or runtime
[ERROR] /Users/tom/projects/grammars-v4/atl/ATL.g4 [43:25]: symbol rule conflicts with generated code in target language or runtime
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.452 s
[INFO] Finished at: 2015-10-30T20:41:10-06:00
[INFO] Final Memory: 12M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.antlr:antlr4-maven-plugin:4.5.1-1:antlr4 (default) on project atl: ANTLR 4 caught 2 build errors. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
oscar:atl tom$ 

</pre>

**Comment by parrt** [comment]
Fixed with 305af585fa7641385f18930a1c7a98c9b42331da
