### ISSUE TITLE
Alias treated as a keyword

### ISSUE THREAD

**Issue by AMagistroni** [antlr/grammars-v4#2350]
A simple query like 

`SELECT col ADD FROM dbo.tbl`

give me an error: 

> extraneous input 'ADD' expecting {<EOF>, 'ALTER', 'BACKUP', .....

If I change the name of the alias, it's work. 
I think that the alias it's treated as a keyword, and not as an id_

**Comment by KvanTTT** [comment]
Fixed by #2351
