### ISSUE TITLE
javascript grammar: Add template depth support for all targets (Cpp, Go, Python3)

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#2382]
There's a [fix](https://github.com/antlr/grammars-v4/pull/2381) for the javascript grammar to provide a template depth calculation. For whatever reason, this is being done piecemeal in separate PRs. It needs to be addressed for all targets, including Cpp, Go, Python3. When fixed, make sure to update the "skip lists".

**Comment by gordon-cc-run** [comment]
This was added to the `.g4` files in https://github.com/antlr/grammars-v4/pull/2206 but only appears to have been added to the Java target. My PR also is only for `javascript/javascript` and the original change adds it to `javascript/typescript` as well (but not the other dialects, not sure if they're also applicable or not).

**Comment by studentmain** [comment]
see also #2257
