### ISSUE TITLE
Use Antlr 4.9.3 in cross-target/platform build

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#2386]
Antlr 4.9.3 has been released, so the [test.pm1](https://github.com/antlr/grammars-v4/blob/master/_scripts/test.ps1) build needs to be updated. Looking through where the version is referenced, these files need to be changed:

        _scripts/readme.md
        _scripts/regtest.sh
        _scripts/templates/CSharp/Test.csproj
        _scripts/templates/Dart/pubspec.yaml
        _scripts/templates/JavaScript/package.json

I noticed that the Go and Python3 targets don't specify a version of the Antlr runtime to use, probably taking whatever is the latest provided. When I wrote the templates for these targets, the examples and readme instructions on the Antlr runtimes don't show how to do pick a specific Antlr version. If a specific version can be specified, it's probably best to update these targets to use specifically Antlr 4.9.3. We don't currently test Cpp, Swift, Python2.

**Comment by studentmain** [comment]
golang use the "latest" code in git repo if version is not specified (in `go get` command), that's why we can see the golang runtime was broken in #2365 even before v4.9.3 is released.

**Comment by kaby76** [comment]
@studentmain  Correct. The build should not use a specific version of the tool, but then turn around and use a different version of the runtime. That's bad programming practice. I've looked up how Python3 and Go should be done, and have added that into the PR for this issue.
