### ISSUE TITLE
Confusing error message (conflates correct and incorrect lines) for Java7/Java8 grammar

### ISSUE THREAD

**Issue by lispercat** [antlr/grammars-v4#2409]
I am trying to build my own parser based on the existing Java grammar
Even if I use the Java7 grammar from the source [repo](https://github.com/antlr/grammars-v4/tree/master/java/java) and generate the parser and then use the TestRig from antlr-4.9.3-complete.jar given the code:
```
public class Test {
    public static void main() {
        test
        int b = 1;
    }
}
```

I got following error:
`line 4:8 no viable alternative at input 'test\n        int' `

So it for some reason conflates the incorrect "test" line with correct "int" line.
Also it says "line 4:8" pointing at the "int" line when it should be pointing to "test" line (3).
In a regular Java editor I would see a correct error highlighting for the "test" word which would sound like:
`"Syntax error, insert "VariableDeclarators" to complete LocalVariableDeclaration"`

What do I do to arrive at a similar error with ANTLR so it only picks on the wrong "test" line?

(btw, when I use antlr4ts to generate the parser and an error listener, it gives pretty much the same error message)

**Comment by KvanTTT** [comment]
This problem doesn't relate to Java grammar but to ANTLR runtime itself. Please ask the question on StackOverflow or on GitHub ANTLR discussions.
