### ISSUE TITLE
Tables function Occurs repeatedly in a class in php

### ISSUE THREAD

**Issue by PandaLIU-1111** [antlr/grammars-v4#2412]
i use `antlr4 -Dlanguage=PHP ./MySqlParser.g4`   generate `MySqlParser.php` file, but, Tables function Occurs repeatedly in a class

![image](https://user-images.githubusercontent.com/26201936/144701639-6234b64b-2b05-4c12-8935-6341c1f0d3df.png)

**Comment by KvanTTT** [comment]
It's the collision between token `TABLES` and parse rule `tables`. It's definitely a bug in PHP runtime, your [issue](https://github.com/antlr/antlr4/issues/3388) in the ANTLR repository is relevant.
