### ISSUE TITLE
Is NEWLINE token needed at the end of the simple_stmt in Python3 grammar?

### ISSUE THREAD

**Issue by ThreadedStream** [antlr/grammars-v4#2420]
I might be completely wrong, but when i'm trying to parse the following piece of python3 code 
```py
 def sum(x:float, y:float, z:float) -> float: return x + y + z
```
parser throws an error, as return statement eventually boils down to parsing the following rule

```
simple_stmt: small_stmt (';' small_stmt)* (';')? NEWLINE;
```
Wouldn't it be correct to make NEWLINE token optional? That is,  

```
simple_stmt: small_stmt (';' small_stmt)* (';')? NEWLINE?;
```

**Comment by kaby76** [comment]
The Antlr grammar comes directly from the official Python.org website: https://docs.python.org/3/reference/grammar.html , which is derived from their formal grammar for CPython: https://github.com/python/cpython/blob/3.10/Grammar/python.gram#L64 . It's wrong?

**Comment by RobEin** [comment]
I don't know which grammar you used, but I'm afraid the indentation is treated badly in that parser.
Try this:
https://github.com/antlr/grammars-v4/tree/master/python/python3-without-actions

**Comment by ThreadedStream** [comment]
@kaby76 @RobEin thanks for helpful suggestions. It's very probable that the source of a problem may turn out to be an incorrect parsing of the following rule, as i don't use antlr for parsing -- i'm doing it on my own. I probably should post a piece of code responsible for parsing of that particular rule. I'll do it a bit later.

**Comment by ThreadedStream** [comment]
Here's a promised piece of code
```cpp

// simple_stmt: small_stmt (';' small_stmt)* (';')? NEWLINE;
Node *parseSimpleStmt(PyLexer &lexer) {
    auto simple_stmt = new SimpleStmt({});
    const auto node = parseSmallStmt(lexer);

    simple_stmt->small_stmts.push_back(node);
    while (lexer.curr->getType() == Python3Lexer::SEMI_COLON) {
        lexer.consume(Python3Lexer::SEMI_COLON);

        // handle a terminal semicolon
        if (lexer.curr->getType() == Python3Lexer::EOF ||
            lexer.curr->getType() == Python3Lexer::NEWLINE) {
            break;
        }
        const auto node = parseSmallStmt(lexer);
        simple_stmt->small_stmts.push_back(node);
    }

    lexer.consume(Python3Lexer::NEWLINE);

    return simple_stmt;
}
```

**Comment by kaby76** [comment]
Your code seems correct. So, "Is NEWLINE token needed at the end of the simple_stmt in Python3 grammar `[https://github.com/antlr/grammars-v4/tree/master/python/python3]`?". Yes, NEWLINE is **not** optional. It was adapted from the Python3 documented grammar. If you look at the generated source for the grammar to CPython ([here](https://raw.githubusercontent.com/python/cpython/3.10/Parser/parser.c), look for "simple_stmts_rule(Parser *p)"), the function prints out an error if the new line is not found. Of course, maybe _PyPegen_expect_token() returns non-NULL on the EOF condition in some cases? When I type `echo -n 'print(1); print(2)' | python`, no error is produced. Who knows what the CLI does with the input (append a new line?), or what entry point it uses.

**Comment by ThreadedStream** [comment]
Okay, I'd probably better close this issue. Thanks everyone!
