### ISSUE TITLE
GDScript: Only up to Two Parameters Allowed

### ISSUE THREAD

**Issue by ogrady** [antlr/grammars-v4#2422]
The parser grammar for GDScript [allows only for exactly one or two parameters](https://github.com/antlr/grammars-v4/blob/master/gdscript/GDScriptParser.g4#L74). Replacing `?` with `*` should fix this issue.

**Comment by kaby76** [comment]
Yep, that was "scraped" wrong from the "official grammar". But, there's lot's more wrong: expression alts are in the wrong order. For example, for this input:

	const FOO = 1+2/3

the parse tree is:


	( program
	  ( topLevelDecl
	    ( constDecl
	      ( CONST i=2 txt=const tt=9 DEFAULT_TOKEN_CHANNEL
	      ) 
	      ( IDENTIFIER i=8 txt=FOO tt=47 DEFAULT_TOKEN_CHANNEL
	      ) 
	      ( ASSIGN i=12 txt== tt=56 DEFAULT_TOKEN_CHANNEL
	      ) 
	      ( expression
		( expression
		  ( expression
		    ( literal
		      ( INTEGER i=14 txt=1 tt=51 DEFAULT_TOKEN_CHANNEL
		  ) ) ) 
		  ( ADD i=15 txt=+ tt=90 DEFAULT_TOKEN_CHANNEL
		  ) 
		  ( expression
		    ( literal
		      ( INTEGER i=16 txt=2 tt=51 DEFAULT_TOKEN_CHANNEL
		) ) ) ) 
		( DIV i=17 txt=/ tt=93 DEFAULT_TOKEN_CHANNEL
		) 
		( expression
		  ( literal
		    ( INTEGER i=18 txt=3 tt=51 DEFAULT_TOKEN_CHANNEL
	      ) ) ) ) 
	      ( NEWLINE i=19 txt=\r\n tt=46 DEFAULT_TOKEN_CHANNEL
	  ) ) ) 
	  ( EOF i=21 txt= tt=-1 DEFAULT_TOKEN_CHANNEL
	) ) 

That's `(1+2)/3`. Usually, it's `1+(2/3)`. The grammar was rewritten for expressions.

Also, from the original grammar https://docs.godotengine.org/en/stable/development/file_formats/gdscript_grammar.html `arrayDecl` and `dictDecl` have the comma right before the closing bracket. The grammar mistakenly places `expression` last https://github.com/antlr/grammars-v4/blob/master/gdscript/GDScriptParser.g4#L238 .

Finally, I ported the GDScriptLexerBase.java to CSharp, but it said "// copy pasted from Python3LexerBase.java". So, being "smart", I decided to copy the source from [grammars-v4/python/python3/CSharp](https://github.com/antlr/grammars-v4/tree/master/python/python3/CSharp), but the Java over from python/python3/Java has a mod. Best to just remove all these comments so we don't get confused.
