### ISSUE TITLE
CPP14 - static member initialization vs pure virtual function

### ISSUE THREAD

**Issue by bvanheu** [antlr/grammars-v4#249]
Hi,

The CPP14 parser is broken on static member initialization, it tries to parse the '= 1' as a pure-specifier with Antlr 4.5.

For example, the following file `test.h`:

```cpp
class Foo {
    static const int bar = 1;
};
```

Will break at the pure-specifier rule:

```
$ grun CPP14 translationunit -trace ./test.h
[...]
consume [@7,37:37='=',<94>,2:25] rule purespecifier
consume [@8,39:39='1',<126>,2:27] rule purespecifier
line 2:28 mismatched input ';' expecting Integerliteral
[...]
```

The section of the grammar that deals with pure-specifier:

```antlr
memberdeclarator
:
    declarator virtspecifierseq? purespecifier?
    | declarator braceorequalinitializer?
    | Identifier? attributespecifierseq? ':' constantexpression
    ;
```

Excerpt from the C++ standard regarding static member initialization:

> If a non-volatile const static data member is of integral or enumeration type, its declaration in the class definition can specify a brace-or-equal-initializer in which every initializer-clause that is an assignment-expression is a constant expression (5.20). A static data member of literal type can be declared in the class definition with the constexpr specifier; if so, its declaration shall specify a brace-or-equal-initializer in which every initializer-clause that is an assignment-expression is a constant expression. [Note:In both these cases, the member may appear in constant expressions.— end note] The member shall still be defined in a namespace scope if it is odr-used (3.2) in the program and the namespace scope definition shall not contain an initializer.

Side effect of this bug, if the `brace-or-equal-initializer` is `= 0`, `bar` will be parsed as a pure-virtual function.

Also, there is already a special case for pure-specifier, but there is not many details surrounding the issue:

```antlr
/*
purespecifier:
    '=' '0' //Conflicts with the lexer
 ;
*/

purespecifier
:
    Assign val = Integerliteral
    {if($val.text.compareTo("0")!=0) throw new InputMismatchException(this);}

;
```

I don't have much experience with Antlr to provide a fix, but we should probably check for parenthesis `()` just after the `declarator` to see if we should look for a pure-specifier initialization (although I'm not sure if it's mandatory for a pure virtual function in C++?).

**Comment by Camiloasc1** [comment]
I already fixed it.
[Pull Request](https://github.com/antlr/grammars-v4/pull/271)

**Comment by Marti2203** [comment]
This is merged and fixed so time to close?

**Comment by KvanTTT** [comment]
Yes, thanks for the tracking.
