### ISSUE TITLE
SQLite does not recognize INNER JOIN, NATURAL JOIN etc.

### ISSUE THREAD

**Issue by egeogretmen** [antlr/grammars-v4#250]
When an sql statement is given such as

``` sql
SELECT * FROM t1 INNER JOIN t2 ON t1._id = t2.t1_id
```

"INNER" is perceived as table_alias
The problem is only solved if a table_alias is already given such as

``` sql
SELECT * FROM t1 as t INNER JOIN t2 ON t1._id = t2.t1_id
```

**Comment by inglesp** [comment]
I *think* I was able to fix this by changing

```
any_name
 : IDENTIFIER 
 | keyword
 | STRING_LITERAL
 | '(' any_name ')'
 ;
```

to

```
any_name
 : IDENTIFIER 
 | STRING_LITERAL
 | '(' any_name ')'
 ;
```

I don't know whether this breaks anything else though!

**Comment by inglesp** [comment]
This issue is also reported upstream at https://github.com/bkiers/sqlite-parser/issues/3.

**Comment by teverett** [comment]
Have you considered submitting a pull request?

**Comment by inglesp** [comment]
Yes, I'll follow this up upstream.

**Comment by Marti2203** [comment]
@inglesp was this fixed?

**Comment by inglesp** [comment]
@Marti2203 Doesn't look like it, sorry.  TBH I can't remember what I did four weeks ago, let alone four years...

**Comment by Marti2203** [comment]
No problem, I am gonna play around with it today

**Comment by Marti2203** [comment]
The grammar now catches it properly.

**Comment by Marti2203** [comment]
@teverett  can you close this issue please?
