### ISSUE TITLE
Question about why whitespace is the child of RuleContext in Python grammar

### ISSUE THREAD

**Issue by Zero0one1** [antlr/grammars-v4#2541]
I found whitespace and indentation are recognized as children of RuleContext when running the following Java. I don't know if it's by design and I didn't find any clue from the `Python3Parser.g4`. PS: It seems that Java grammar doesn't recognize spaces as children.
```python
  public void serializeFile(String f, String startSymbol) {
      ...
      Python3Lexer lexer = new Python3Lexer(CharStreams.fromFileName(f));
      CommonTokenStream tokens = new CommonTokenStream(lexer);
      vocab = lexer.getVocabulary();
      Python3Parser parser = new Python3Parser(tokens);

      ParserRuleContext t = parser.file_input();
      printChild(t, tokens);
      ...
  }
  private void printChild(RuleContext t, CommonTokenStream tokens) {
    
    int n = t.getChildCount();

    for (int i = 0; i < n; i++) {
      ParseTree tree = t.getChild(i);
      if (tree instanceof TerminalNodeImpl) {
        System.out.println(tree.getText() + ";");
      } else {
        printChild((RuleContext) tree, tokens);
      }
    }
  }
```
Here is part of the input Python file and its printed output.
```
code snippet of Python file:
is_keyword(tokens[0]):
        val = tokens

output:
is_keyword;
(;
tokens;
[;
0;
];
);
:;
 ;
        ;
val;
=;
tokens;
```

**Comment by kaby76** [comment]
Yes, white space is part of the parse tree using the [python3](https://github.com/antlr/grammars-v4/blob/cecaa091430c3e4b64d8f11f82b435dcf95f39c5/python/python3/Java/Python3LexerBase.java#L127) grammar. Python is one of those languages, like FORTRAN, where indentation matters. Us "old school" programmers learned that designing a language this way is really stupid. But, somewhere along the way, everyone ignored what we said about FORTRAN and punched cards. Waiting patiently for them to come back; I got a box of cards ready to go. 💯

**Comment by Zero0one1** [comment]
I see. Thanks for your explanation!
