### ISSUE TITLE
In Python3 Parser I am not able to get values of variable , function and class

### ISSUE THREAD

**Issue by DivyaSrivastava45** [antlr/grammars-v4#2555]
1. for Variables I am using **atom_expr and atom** 
but it is giving the values which are not considered as variable in python 
2. for Functions which are **not declared using def keyword** , or e.g call functions 
no grammar for it ?
 please help me regarding this

**Comment by kaby76** [comment]
Which Python3 grammar? There are many, https://github.com/antlr/grammars-v4/tree/master/python

**Comment by DivyaSrivastava45** [comment]
I have used grammar folder -->  grammars-v4/python/python3
generated grammar using there two files 
1. python3lexer.g4
2. python3parser.g4

**Comment by kaby76** [comment]
Do you have a Python3 input file that demonstrates the problem so as I can then generate the parse tree and discuss it?

**Comment by kaby76** [comment]
* The first thing to note is that some of the examples do not parse. That should be addressed, but not immediately.

	for i in ../../../../Hackerrank_30daysOFcode/30daysOFcode_Python/*.py; do echo "$i"; trparse "$i" > /dev/null;  done

	../../../../Hackerrank_30daysOFcode/30daysOFcode_Python/day 03.py
	line 1:2 no viable alternative at input '''

	../../../../Hackerrank_30daysOFcode/30daysOFcode_Python/day 12.py
	line 40:30 no viable alternative at input '<EOF>'

	../../../../Hackerrank_30daysOFcode/30daysOFcode_Python/day 15.py
	line 28:23 no viable alternative at input ';'

	../../../../Hackerrank_30daysOFcode/30daysOFcode_Python/day 22.py
	line 30:20 no viable alternative at input '<EOF>'

	../../../../Hackerrank_30daysOFcode/30daysOFcode_Python/day 24.py
	line 44:22 no viable alternative at input ';'

* I should also note that this grammar is (or at least should be) scraped directly from the CPython parser generator grammar that Python itself uses. Deviations in the grammar should be used sparingly.
* I use XPath to specify exactly and precisely what nodes in the parse tree I want to talk about. Compiler writers need to use a precise language to discuss problems. I implemented an XPath2 engine for Antlr4, and a cheatsheet for the syntax is [here](http://codinggorilla.com/blog/2022/02/10/xpath-cheatsheet.html). It's implemented in a toolkit called [Trash](https://github.com/kaby76/Domemtech.Trash).
* Let's take "day 04.py".
    * The parse tree is here.
[tree.txt](https://github.com/antlr/grammars-v4/files/8333712/tree.txt)
    * The variables in this file, starting from the top, are: self (several methods), initialAge, t, i, age (not within the class, as that is a "field"), p, j.
    * As I think you noted, there are many `//atom_expr/atom/NAME' nodes that include nodes that are not considered variables, e.g., "print". For example, these should not include a "trailer" node that begins with a "(" because that denotes a function call.
    * So, `trparse ../../../../Hackerrank_30daysOFcode/30daysOFcode_Python/day\ 04.py | trxgrep '//atom_expr/atom[not(following-sibling::trailer/OPEN_PAREN)]/NAME/text()'` returns a list of nodes eliminating function calls: age, initialAge, self, initialAge, self, self, self, self, self, t, i, t, age, p, age, j. This list still contains more nodes that should not be there, e.g., "age" because that is a field of the class. You will need to further refine the XPath expression.

**Comment by DivyaSrivastava45** [comment]
Thank you for  your help i understand the process but I never used xpath could you give me any source from where I can undertand xpath concept.

**Comment by kaby76** [comment]
XPath is a expression language used to navigate around a tree. See [wikipedia](https://en.wikipedia.org/wiki/XPath#Overview). The output of a parsing is a parse tree. The [W3Schools](https://www.w3schools.com/xml/xpath_intro.asp) tutorial is okay. Also see [my cheatsheet page](http://codinggorilla.com/blog/2022/02/10/xpath-cheatsheet.html).

Note, Antlr4 has an XPath API in some of the runtimes (Java, C#), but it's missing in others. And the [XPath API in the runtime](https://github.com/antlr/antlr4/blob/master/doc/tree-matching.md) is not XPath2, so it has a very limited usefulness.

The main point of my previous comment is that you need to consider the context of a particular node in the parse tree. You can't just pick off "atom" nodes and say that those are the identifiers. If you are using an Antlr Visitor or Listener and using that to find identifiers, then you will need to navigate around the parse tree and verify the context of the "atom" node.

**Comment by DivyaSrivastava45** [comment]
Thanks you . After Parsing I am getting " extraneous input ' ' expecting" at the end of files if there is an whitespace and because of this it is throwing syntax error is there anyway to handle this ?
