### ISSUE TITLE
"unexpected token: grammar"

### ISSUE THREAD

**Issue by QazCetelic** [antlr/grammars-v4#2563]
I have the following grammar.
```antlr
grammar Main;

A: 'a';
B: 'b';
rule: A|B;
```
However, when I try to compile it, I get the following:
```
[qaz@fedora antlr]$ antlr Main.g4
ANTLR Parser Generator   Version 2.7.7 (2006-11-01)   1989-2005
Main.g4:1:1: unexpected token: grammar
Main.g4:1:1: rule grammar trapped:
Main.g4:1:1: unexpected token: grammar
Exiting due to errors.
```
I can't find anything in the documentation about what could be wrong. Am I missing something, or is there an issue with the tool itself?

**Comment by KvanTTT** [comment]
* The issue does not relate to grammars but to core
* You are using the outdated version of ANTLR 2. Actual version: ANTLR 4

**Comment by QazCetelic** [comment]
> * The issue does not relate to grammars but to core
> 
>  * You are using the outdated version of ANTLR 2. Actual version: ANTLR 4

I'm currently using `org.antlr:antlr4:4.9.3`.

**Comment by QazCetelic** [comment]
Oh, I didn't notice that, the default ANTLR package on Fedora is 2.
