### ISSUE TITLE
plsql c++

### ISSUE THREAD

**Issue by nIxedoahz** [antlr/grammars-v4#2567]
Are the plsql parsing rules correct, and compilation references will be reported as errors

**Comment by nIxedoahz** [comment]
![Uploading F9677443-FA4E-4EF5-AE2A-0F26C0B76443.jpeg…]()

**Comment by nIxedoahz** [comment]
generated/PlSqlLexer.h:213:5: error: expected identifier before '(' token
     NAN = 881, NANVL = 882, NATIONAL = 883, NATIVE_FULL_OUTER_JOIN = 884,
     ^
generated/PlSqlLexer.h:213:5: error: expected '}' before '(' token
generated/PlSqlLexer.h:213:5: error: expected identifier before string constant
     NAN = 881, NANVL = 882, NATIONAL = 883, NATIVE_FULL_OUTER_JOIN = 884,
     ^
generated/PlSqlLexer.h:213:5: error: expected ',' or '...' before string constant
In file included from main.cpp:16:0:
generated/PlSqlLexer.h:18:3: error: new types may not be defined in a return type
   enum {
   ^
generated/PlSqlLexer.h:18:3: note: (perhaps a semicolon is missing after the definition of 'antlrcpptest::PlSqlLexer::<anonymous enum>')
generated/PlSqlLexer.h:213:14: error: invalid pure specifier (only '= 0' is allowed) before ',' token
     NAN = 881, NANVL = 882, NATIONAL = 883, NATIVE_FULL_OUTER_JOIN = 884,
              ^
generated/PlSqlLexer.h:563:51: error: expected ';' at end of member declaration
     START_CMD = 2251, REGULAR_ID = 2252, SPACES = 2253
                                                   ^
generated/PlSqlLexer.h:566:42: error: expected ')' before '*' token
   explicit PlSqlLexer(antlr4::CharStream *input);
                                          ^
generated/PlSqlLexer.h:567:16: error: expected constructor, destructor, or type conversion before ';' token
   ~PlSqlLexer();
                ^
generated/PlSqlLexer.h:569:50: error: 'virtual' outside class declaration
   virtual std::string getGrammarFileName() const override;
                                                  ^
generated/PlSqlLexer.h:569:50: error: virt-specifiers in 'getGrammarFileName' not allowed outside a class definition
generated/PlSqlLexer.h:569:50: error: non-member function 'std::__cxx11::string antlrcpptest::getGrammarFileName()' cannot have cv-qualifier
generated/PlSqlLexer.h:570:64: error: 'virtual' outside class declaration
   virtual const std::vector<std::string>& getRuleNames() const override;
                                                                ^
generated/PlSqlLexer.h:570:64: error: virt-specifiers in 'getRuleNames' not allowed outside a class definition
generated/PlSqlLexer.h:570:64: error: non-member function 'const std::vector<std::__cxx11::basic_string<char> >& antlrcpptest::getRuleNames()' cannot have cv-qualifier
generated/PlSqlLexer.h:572:67: error: 'virtual' outside class declaration
   virtual const std::vector<std::string>& getChannelNames() const override;


generated/PlSqlLexer.h:572:67: error: virt-specifiers in 'getChannelNames' not allowed outside a class definition
generated/PlSqlLexer.h:572:67: error: non-member function 'const std::vector<std::__cxx11::basic_string<char> >& antlrcpptest::getChannelNames()' cannot have cv-qualifier
generated/PlSqlLexer.h:573:64: error: 'virtual' outside class declaration
   virtual const std::vector<std::string>& getModeNames() const override;
                                                                ^
generated/PlSqlLexer.h:573:64: error: virt-specifiers in 'getModeNames' not allowed outside a class definition
generated/PlSqlLexer.h:573:64: error: non-member function 'const std::vector<std::__cxx11::basic_string<char> >& antlrcpptest::getModeNames()' cannot have cv-qualifier
generated/PlSqlLexer.h:574:65: error: 'virtual' outside class declaration
   virtual const std::vector<std::string>& getTokenNames() const override; // deprecated, use vocabulary instead
                                                                 ^
generated/PlSqlLexer.h:574:65: error: virt-specifiers in 'getTokenNames' not allowed outside a class definition
generated/PlSqlLexer.h:574:65: error: non-member function 'const std::vector<std::__cxx11::basic_string<char> >& antlrcpptest::getTokenNames()' cannot have cv-qualifier
generated/PlSqlLexer.h:575:58: error: 'virtual' outside class declaration
   virtual antlr4::dfa::Vocabulary& getVocabulary() const override;
                                                          ^
generated/PlSqlLexer.h:575:58: error: virt-specifiers in 'getVocabulary' not allowed outside a class definition
generated/PlSqlLexer.h:575:58: error: non-member function 'antlr4::dfa::Vocabulary& antlrcpptest::getVocabulary()' cannot have cv-qualifier
generated/PlSqlLexer.h:577:64: error: 'virtual' outside class declaration
   virtual const std::vector<uint16_t> getSerializedATN() const override;
                                                                ^
generated/PlSqlLexer.h:577:64: error: virt-specifiers in 'getSerializedATN' not allowed outside a class definition
generated/PlSqlLexer.h:577:64: error: non-member function 'const std::vector<short unsigned int> antlrcpptest::getSerializedATN()' cannot have cv-qualifier
generated/PlSqlLexer.h:578:50: error: 'virtual' outside class declaration
   virtual const antlr4::atn::ATN& getATN() const override;
                                                  ^
generated/PlSqlLexer.h:578:50: error: virt-specifiers in 'getATN' not allowed outside a class definition
generated/PlSqlLexer.h:578:50: error: non-member function 'const antlr4::atn::ATN& antlrcpptest::getATN()' cannot have cv-qualifier
generated/PlSqlLexer.h:580:97: error: 'virtual' outside class declaration
   virtual bool sempred(antlr4::RuleContext *_localctx, size_t ruleIndex, size_t predicateIndex) override;
                                                                                                 ^
generated/PlSqlLexer.h:580:97: error: virt-specifiers in 'sempred' not allowed outside a class definition
generated/PlSqlLexer.h:582:1: error: expected unqualified-id before 'private'
 private:
 ^
generated/PlSqlLexer.h:610:1: error: expected declaration before '}' token
 }  // namespace antlrcpptest

**Comment by KvanTTT** [comment]
It's explainable since C++ helper class is absense for PL/SQL: https://github.com/antlr/grammars-v4/tree/master/sql/plsql

**Comment by kaby76** [comment]
Try generating a parser without `-package` as that is not a concept that exists on all targets. Consequently, the code does not have a namespace. You'll have to modify the headers if you insist on one.

In any case, the grammar compiles and the built executable works with:
* gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
* cmake version 3.16.3
* Ubuntu 20.04.4 LTS
* GNU Make 4.2.1

I used trgen to generate the driver code.
* dotnet 6.0.201
* trgen 0.15.1

To generate a driver with trgen:
* Install the NET SDK
* Run `dotnet tool install -g trgen`
* `cd sql/plsql`
* `trgen -t Cpp`

**Comment by nIxedoahz** [comment]
Is there a problem with the file generated with that command I used above? @kaby76 @KvanTTT

**Comment by kaby76** [comment]
Can you put all source and generated files in a zip or tar.gz, including .g4, stdout and stderr from the build, attach here? What is your environment? I still don't know of any details like OS, compiler. For me, the command is fine, generated code compiles fine, runs fine.

**Comment by nIxedoahz** [comment]
I tried to compile with aarch64-linux-gnu-g++ and reported an error, the above error, is not currently supported for ARM ？ @KvanTTT @kaby76

**Comment by nIxedoahz** [comment]
gcc version 4.8.1(Wind River Linux Sourcery CodeBench 4.9-45)

**Comment by nIxedoahz** [comment]
arrch64-linux-gnu-g++ -v    is  5.3.1 version

**Comment by nIxedoahz** [comment]
I know why
The NAN and VOERFLOW in the g4 file conflict with the macros in aarch64 @kaby76

**Comment by kaby76** [comment]
> I know why The NAN and VOERFLOW in the g4 file conflict with the macros in aarch64 @kaby76

@nIxedoahz Thanks.

We need to update the grammar, and add in these symbols to the "symbol conflict" for Cpp. And, we need to add Arm testing to this repo ASAP.
