### ISSUE TITLE
Upgrade testing to Antlr 4.10

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#2572]
Modifications are going to be needed for Antlr 4.10.

* [here](https://github.com/antlr/grammars-v4/blob/06a69f69d2fef19295c8c48dbfc209622d1bc76d/.github/workflows/main.yml#L73)
* [here](https://github.com/antlr/grammars-v4/blob/06a69f69d2fef19295c8c48dbfc209622d1bc76d/_scripts/regtest.sh#L167)
* [here](https://github.com/antlr/grammars-v4/blob/06a69f69d2fef19295c8c48dbfc209622d1bc76d/_scripts/regtest.sh#L173)
* [here](https://github.com/antlr/grammars-v4/blob/06a69f69d2fef19295c8c48dbfc209622d1bc76d/_scripts/remaster.sh#L10)
* [here](https://github.com/antlr/grammars-v4/pull/2569/files)

There are likely others. It might be a good idea to yank all these explicit version references to one place.

**Comment by KvanTTT** [comment]
[Bump antlr.version from 4.9.3 to 4.10](https://github.com/antlr/grammars-v4/pull/2569) should be updated together with [Bump antlr4test-maven-plugin from 1.19 to 1.20](https://github.com/antlr/grammars-v4/pull/2570)

**Comment by kaby76** [comment]
I think we need to a "mvn -fae ....." [here](https://github.com/antlr/grammars-v4/blob/06a69f69d2fef19295c8c48dbfc209622d1bc76d/.github/workflows/main.yml#L24) and get the whole story rather than `( mvn; fix; )+`.

**Comment by kaby76** [comment]
Explicit case folding lexer grammars is supported directly in 4.10, but what is the minimum supported Antlr version?

**Comment by KvanTTT** [comment]
It was introduced in ANTLR 4.10, see https://github.com/antlr/antlr4/releases/tag/4.10 I'm working on transforming case insensitive grammars to the new format.

**Comment by kaby76** [comment]
> It was introduced in ANTLR 4.10, see https://github.com/antlr/antlr4/releases/tag/4.10 I'm working on transforming case insensitive grammars to the new format.

If you do that, then those grammars will be 4.10+ only, and will probably need to warn people.

**Comment by kaby76** [comment]
Closing this, and opening a new Issue instead to address merging version strings in .github/workflows/main.yml, _scripts/templates/..., and pom.xml.
