### ISSUE TITLE
Can you add syntax parsing files for other databases? .g4 file

### ISSUE THREAD

**Issue by nIxedoahz** [antlr/grammars-v4#2578]
kingbaseES and DM

**Comment by teverett** [comment]
@nIxedoahz  can you provide URLs to those please?

**Comment by nIxedoahz** [comment]
> 

sorry i don’t understand 
What URL do I need to provide

**Comment by nIxedoahz** [comment]
@teverett 
sorry i don’t understand
What URL do I need to provide

**Comment by nIxedoahz** [comment]
@teverett @KvanTTT @mspiegel @felipebz 
Here     https://help.kingbase.com.cn/stage-api/profile/document/kes/v8r6/html/development/ref/ref-keywords/index.html

Thanks ！！！！！！！！！！！

**Comment by studentmain** [comment]
It's likely you are on your own now. New grammar request usually takes few months or years to process -- like many open source projects, this project rely on volunteer to running. A Chinese specific closed source database is hard to attract worldwide developers too.

But keep calm, you can do it. Parsing is not magic, start with existed SQL grammar, test it with your own example, fix error, your examples are the best tool.

---

如果紧急的话你很可能需要自己写。新语法一般需要几个月甚至几年，这个项目和其他很多项目一样是靠爱发电。而且国产闭源数据库很难引起全世界范围开发者的兴趣。

不过编写语法不是魔法。从现有的语法开始，用你手中有的示例逐一测试，逐一修改错误，你的示例是最好的工具。其中遇到的具体问题可以到 [stackoverflow](https://stackoverflow.com/questions/tagged/antlr4) 提问。

**Comment by g422** [comment]
> @teverett @KvanTTT @mspiegel @felipebz Here https://help.kingbase.com.cn/stage-api/profile/document/kes/v8r6/html/development/ref/ref-keywords/index.html
> 
> Thanks ！！！！！！！！！！！

Can you tell me about username and password?
