### ISSUE TITLE
WebIDL.g4 : required is not recognized as IDENTIFIER_WEBIDL

### ISSUE THREAD

**Issue by ylemoigne** [antlr/grammars-v4#258]
Hi,

Given the following def :

```
interface HTMLInputElement : HTMLElement {
           attribute boolean required;
};
```

required should be accepted as IDENTIFIER_WEBIDL, but it's not :
line 2:29 mismatched input 'required' expecting {'[', '?', IDENTIFIER_WEBIDL}

Thanks for any help.
cc @rainerschuster

**Comment by rainerschuster** [comment]
Thanks for pointing out this issue. I've fixed it in the grammar in #259 and it is now correctly recognized as attributeNameKeyword. Btw. the grammer is now also up to date with the current specification draft.

**Comment by ylemoigne** [comment]
Thanks to you for fixing it.

I have a couple of issues, but I don't know if it's the grammar or my webidl which is not correct. (I use the parser against a bunch of webidl downloaded from mozilla sources).

First issue, the files contains some sort of "forward declaration", so i changed the rule `interface_` to :
```
interface_
	: interfaceForwardDeclaration
	| interfaceDeclaration
;

interfaceForwardDeclaration
	: 'interface' IDENTIFIER_WEBIDL ';'
;

interfaceDeclaration
	: 'interface' IDENTIFIER_WEBIDL inheritance '{' interfaceMembers '}' ';'
;```

Then, there is some preprocessor directive, so at the end of the grammar file, I've added 
```
PREPROCESSOR_DIRECTIVE : '#' ~[\r\n]* -> channel(HIDDEN);
```

And finally, I have declaration which seems valid at syntax level (checked against w3c idl checker)
```
interface HTMLOptionsCollection : HTMLCollection {
  [Throws]
  setter creator void (unsigned long index, HTMLOptionElement? option);
};
```
but I got this error : `line 3:17 extraneous input 'void' expecting {'(', '?', IDENTIFIER_WEBIDL}`
(And I don't know how to fix this last one).

**Comment by rainerschuster** [comment]
The output is a bit misleading because the problematic keyword is "creator". The concept of creators was removed in newer versions of WebIDL.
