### ISSUE TITLE
Missing GROUPING SETS syntax

### ISSUE THREAD

**Issue by grzeng-go** [antlr/grammars-v4#2590]
eg:

```sql
SELECT
    aggregate_function(column_1)
    column_2,
    column_3,
FROM
    table_name
GROUP BY
    GROUPING SETS (
        (column_2, column_3),
        (column_2),
        (column_3),
        ()
);
```

**Comment by grzeng-go** [comment]
### TSqlLexer.g4
**add:**
SETS:                                   'SETS';

------------------------------------------------------------------------------

### TSqlParser.g4
**change:**
query_specification
    : SELECT allOrDistinct=(ALL | DISTINCT)? top=top_clause?
      columns=select_list
      // https://msdn.microsoft.com/en-us/library/ms188029.aspx
      (INTO into=table_name)?
      from=from_clause?
      where=where_clause?
      // https://msdn.microsoft.com/en-us/library/ms177673.aspx
      (GROUP BY ((groupByAll=ALL? groupBys+=group_by_item (',' groupBys+=group_by_item)*) | GROUPING SETS '(' groupSets+=grouping_sets_item (',' groupSets+=grouping_sets_item)* ')'))?
      (HAVING having=search_condition)?
    ;
**add:**
grouping_sets_item
    : '('? groupSetItems+=group_by_item (',' groupSetItems+=group_by_item)* ')'?
    | '(' ')'
    ;

**Comment by KvanTTT** [comment]
It would be very helpful if you suggested a pull request with fix.
