### ISSUE TITLE
An error occurred when PLSQL generated parse tree

### ISSUE THREAD

**Issue by nIxedoahz** [antlr/grammars-v4#2594]
```sql
SELECT a FROM b;
```

a and b are incorrect

```
token recognition error at : 'a'
token recognition error at : 'b'
```

How to solve it?

**Comment by kaby76** [comment]
sql/plsql requires a "case folding" lexer. See [this](https://github.com/antlr/grammars-v4/blob/dd39ad01f43c7a31af5e8562b880681bc1dc78c2/sql/plsql/pom.xml#L45). You can solve the problem several ways:
* Add the case changing char stream code. Unfortunately, it was all removed. [here](https://github.com/antlr/antlr4/tree/93c18aa690504d7ce96c5862707c3b2ba33ac82d/doc/resources).
* Modify the grammar to use `options { caseInsensitive = true; }` [documented here](https://github.com/antlr/antlr4/blob/master/doc/options.md#caseinsensitive).
* Modify the input to uppercase everything.
* There is a [PR](https://github.com/antlr/grammars-v4/pull/2576) with [this change](https://github.com/antlr/grammars-v4/pull/2576/files#diff-bdee0cb6471d575396cbc465c9d91fc1657a4d93154604b92cac75b32fb43190R25), but hasn't been merged yet.

**Comment by nIxedoahz** [comment]
I use antlr4.9.3 &nbsp;cpp&nbsp;
can’t support&nbsp;caseInsensitive = true;
can i use antlr4.10 now?



发自我的iPhone


------------------ Original ------------------
From: Ken Domino ***@***.***&gt;
Date: Sun,Apr 24,2022 0:05 AM
To: antlr/grammars-v4 ***@***.***&gt;
Cc: nIxedoahz ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [antlr/grammars-v4] An error occurred when PLSQL generated parsetree (Issue #2594)

**Comment by kaby76** [comment]
> I use antlr4.9.3 &nbsp;cpp&nbsp; can’t support&nbsp;caseInsensitive = true; can i use antlr4.10 now? 

Yes, you can move forward to 4.10 or 4.10.1 even. I've been using 4.10 with the original grammar and it works okay (minus the performance issue that I pointed out [here](https://github.com/antlr/grammars-v4/issues/2589#issuecomment-1105718389)). But, the build currently uses the code as is. I haven't tried the `caseInsensitive` yet.

**Comment by nIxedoahz** [comment]
thanks
by the way&nbsp;
Is it a stable version at present &nbsp;-&gt;&nbsp;antlr4.10&nbsp;
And&nbsp;Please check the issues of #2578



发自我的iPhone


------------------ Original ------------------
From: Ken Domino ***@***.***&gt;
Date: Sun,Apr 24,2022 0:22 AM
To: antlr/grammars-v4 ***@***.***&gt;
Cc: nIxedoahz ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [antlr/grammars-v4] An error occurred when PLSQL generated parse tree (Issue #2594)





  
I use antlr4.9.3 &nbsp;cpp&nbsp; can’t support&nbsp;caseInsensitive = true; can i use antlr4.10 now?
  
Yes, you can move forward to 4.10 or 4.10.1 even. I've been using 4.10 with the original grammar and it works okay (minus the performance issue that I pointed out here). But, the build currently uses the code as is. I haven't tried the caseInsensitive yet.

**Comment by kaby76** [comment]
> [Are 4.10 or 4.10.1] stable version[s] at present?

Yes. It's used in the PR builds of this repo.

> #2578 

Sorry, I don't have time for adding new grammars. All work I do is volunteer work. I haven't been employed for decades in this ridiculous profession.

**Comment by KvanTTT** [comment]
I think the issue can be closed since there are several ways of resolving.
