### ISSUE TITLE
swift: treat comments as whitespace

### ISSUE THREAD

**Issue by kazzmir** [antlr/grammars-v4#261]
infix operator /+{}
    func /+(a:Int, b:Int) -> Int { return a }
    print(2 /+//
    3)

This program currently fails to parse because "//\n" is not treated as a whitespace token, so isBinaryOp("/+") is false. I added the following line to rightWS in SwiftSupport.java and the program successfully parsed.

     rightWS.set(SwiftParser.Line_comment);

Probably Block_comment should be added to rightWS, as well as to leftWS.

**Comment by parrt** [comment]
Interesting. I was wondering about `3/*hi*/+ 4` means too

**Comment by parrt** [comment]
Fixed with https://github.com/antlr/grammars-v4/commit/ea30cdc72c3bd1ffa27480688bcc5c9f12ed47cd
