### ISSUE TITLE
[scss] Introducing backing changes to grammar

### ISSUE THREAD

**Issue by SergeyRusskih** [antlr/grammars-v4#2619]
I want to contribute to the scss grammar but I noticed the grammar doesn't follow the spec and fixing it is impossible without introducing breaking changes. Also, the original author isn't active. 

1.  Can I introduce breaking changes for the sake of standardization? Following the standard is essential to add new features.
2. Can I take over the repository if the author is not active? The last commit was 8 years ago.

Looking forward to hearing from you.

Sergei

**Comment by KvanTTT** [comment]
> Can I introduce breaking changes for the sake of standardization? Following the standard is essential to add new features.

Yes.

> Can I take over the repository if the author is not active? The last commit was 8 years ago.

It is even welcome.

**Comment by kaby76** [comment]
I'm quite confused. Is it "SCSS" or "SASS"? Is the specification for SCSS here? https://github.com/sass/sass/tree/main/spec#sass-specificiation . Or, is it here? https://sass-lang.com/documentation/syntax/structure . It seems the spec is vastly different from [the grammar in grammars-v4 repo](https://github.com/antlr/grammars-v4/tree/master/scss). And, if we are talking about [this spec in github](https://github.com/sass/sass/tree/main/spec#sass-specificiation), the spec looks ill-defined in itself. [stylesheet](https://github.com/SergeyRusskih/grammars-v4/blob/78f33267fd0c06fb9c9d20e3127cd69452f1101d/scss/ScssParser.g4#L33) and [statement](https://github.com/SergeyRusskih/grammars-v4/blob/78f33267fd0c06fb9c9d20e3127cd69452f1101d/scss/ScssParser.g4#L37)--just to name a couple--are in the grammar but not in the spec. There's no definition for non-terminal [Statements](https://github.com/sass/sass/blob/8cbe77da7ccf4ff81d7ab4d72eb925fce0c52ad7/spec/at-rules/for.md?plain=1#L16) in the spec. There's no version number for the "spec". Anyway, it would be good to include a link to the spec in a readme.md. Thanks.

**Comment by SergeyRusskih** [comment]
> > Can I introduce breaking changes for the sake of standardization? Following the standard is essential to add new features.
> 
> Yes.
> 
> > Can I take over the repository if the author is not active? The last commit was 8 years ago.
> 
> It is even welcome.

Got it! Thank you! I'll proceed with the changes and submit the merge requests as I go.

**Comment by SergeyRusskih** [comment]
> I'm quite confused. Is it "SCSS" or "SASS"? Is the specification for SCSS here? https://github.com/sass/sass/tree/main/spec#sass-specificiation . Or, is it here? https://sass-lang.com/documentation/syntax/structure . 

SCSS is a flavour of SASS - one of the possible [syntaxes](https://sass-lang.com/documentation/syntax). Another one is SASS itself. 

> It seems the spec is vastly different from [the grammar in grammars-v4 repo](https://github.com/antlr/grammars-v4/tree/master/scss). And, if we are talking about [this spec in github](https://github.com/sass/sass/tree/main/spec#sass-specificiation), the spec looks ill-defined in itself. [stylesheet](https://github.com/SergeyRusskih/grammars-v4/blob/78f33267fd0c06fb9c9d20e3127cd69452f1101d/scss/ScssParser.g4#L33) and [statement](https://github.com/SergeyRusskih/grammars-v4/blob/78f33267fd0c06fb9c9d20e3127cd69452f1101d/scss/ScssParser.g4#L37)--just to name a couple--are in the grammar but not in the spec. There's no definition for non-terminal [Statements](https://github.com/sass/sass/blob/8cbe77da7ccf4ff81d7ab4d72eb925fce0c52ad7/spec/at-rules/for.md?plain=1#L16) in the spec. There's no version number for the "spec". Anyway, it would be good to include a link to the spec in a readme.md. Thanks.

This is exactly the issue I'm facing. In addition to that, the current scss grammar doesn't follow the CSS spec, the superset of which it should be. This all results in the fact that the grammar cannot process basic structures in real project. What I'm doing is trying to get the syntax from different project and checking if the grammar can process it. The next step would be contributing to the scss spec itself I think.

**Comment by SergeyRusskih** [comment]
Thank you for the quick responses! I'm closing the issue.
