### ISSUE TITLE
tree.inspect() does not exist in antlr4

### ISSUE THREAD

**Issue by kazzmir** [antlr/grammars-v4#262]
java/Test.java, java8/Test.java, and swift/java/Test.java all make a call to tree.inspect(parser) where tree has the type ParserRuleContext. There is no such method in the ParserRuleContext class or any of its super classes. Instead the proper API to use seems to be Trees.inspect(tree, parser).

I am using antlr 4.5.1.jar for reference.

swift/java/Test.java
    
    Trees.inspect(tree, parser);
    // tree.inspect(parser);

**Comment by parrt** [comment]
Ah. good point. I think that 4.5.1 moved it. thanks. that was really just my little test program to play around. The maven stuff is being updated.

**Comment by biezhi** [comment]
Has the same problem in `4.7`

**Comment by parrt** [comment]
we moved to the tools area of antlr jar so use antlr4-complete.
