### ISSUE TITLE
TSqlLexer.g4 for VisualStudio 2019

### ISSUE THREAD

**Issue by ai2soft** [antlr/grammars-v4#2626]
Hi , this is the first time i'm using antlr.  
I want to make a t-sql parser.  i searched a lot and found antlr4.
I'm not sure my steps were right or not.
1. create a .net framework wpf project .
2. using nuget add antlr4.
3. create a folder , named "g4"
4. download TSqlLexer.g4 and TSqlParser.g4 , and move them to "g4"
5. set TSqlLexer.g4 and TSqlParser.g4 's property Build Action : Antlr4, Custom Tool : MSBuild:Compile,  Custom Tool NameSpace : {project namespace}
6. build the project , then error found as bellow:

Severity	Code	Description	Project	File	Line	Suppression State
Error		mismatched input 'options {' expecting COLON while matching a lexer rule	SQL_parser	D:\Works\SQL_parser\SQL_parser\TSqlLexer.g4	900	
Error		mismatched input '=' expecting COLON while matching a rule	SQL_parser	D:\Works\SQL_parser\SQL_parser\TSqlLexer.g4	900	
Error		mismatched input ';' expecting COLON while matching a rule	SQL_parser	D:\Works\SQL_parser\SQL_parser\TSqlLexer.g4	900	
Error		mismatched input 'options {' expecting COLON while matching a lexer rule	SQL_parser	D:\Works\SQL_parser\SQL_parser\TSqlLexer.g4	948	
Error		mismatched input '=' expecting COLON while matching a rule	SQL_parser	D:\Works\SQL_parser\SQL_parser\TSqlLexer.g4	948	
Error		mismatched input ';' expecting COLON while matching a rule	SQL_parser	D:\Works\SQL_parser\SQL_parser\TSqlLexer.g4	948	

the project source code 

[SQL_parser.zip](https://github.com/antlr/grammars-v4/files/8713897/SQL_parser.zip)

**Comment by studentmain** [comment]
Use latest Antlr.Runtime.Standard and Antlr4BuildTask instead.

https://github.com/studentmain/SempredTranslation/blob/4cace00d559d0365673933fb72956f17623893f2/SempredTranslation/SempredTranslation.csproj (remember to update dependency version)

There are two ANTLR4 C# runtime and code generator, "standard" and "optimized". TSqlLexer.g4 require a new feature in ANTLR 4.10, which is not available in "optimized" one.

**Comment by ai2soft** [comment]
Thanks for reply.
1. unload  Antlr4, Antlr4.Runtime,Antlr4.CodeGenerator from the project with nuget
2. add reference Antlr4.Runtime.Standard and Antlr4BuildTasks to the project with nuget 
3. modify .csproject

manual add
```
<ItemGroup>
	<PackageReference Include="Antlr4.Runtime.Standard" Version="4.10.1" />
  </ItemGroup>
```
even if there already was a reference 
```
    <Reference Include="Antlr4.Runtime.Standard, Version=4.10.1.0, Culture=neutral, PublicKeyToken=e78b2c5abd1fcb3f, processorArchitecture=MSIL">
      <HintPath>..\packages\Antlr4.Runtime.Standard.4.10.1\lib\netstandard2.0\Antlr4.Runtime.Standard.dll</HintPath>
    </Reference>
```

if you did not add the PackageReference , there would be an error
```
  Severity	Code	Description	Project	File	Line	Suppression State
Error		You are not referencing Antlr4.Runtime.Standard in your .csproj file. Antlr4BuildTasks requires a reference to it in order
to identify which version of the Antlr Java tool to run to generate the parser and lexer.   at Antlr4.Build.Tasks.RunAntlrTool.SetupAntlrToolJar()
   at Antlr4.Build.Tasks.RunAntlrTool.Execute()	SQL_parser			

```

after added PackageReference , there was another error

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Cannot find Java executable''   at Antlr4.Build.Tasks.RunAntlrTool.SetupJava()
   at Antlr4.Build.Tasks.RunAntlrTool.Execute()	SQL_parser			

```

it seams that , Antlr4.Build.Tasks needs .jar which is specified by "AntlrProbePath".   where is it ?

**Comment by kaby76** [comment]
Could you just paste your .csproj here?

**Comment by ai2soft** [comment]
ok , this is project 
[SQL_parser.zip](https://github.com/antlr/grammars-v4/files/8725082/SQL_parser.zip)
and all the source code
[SQL_parser.zip](https://github.com/antlr/grammars-v4/files/8725084/SQL_parser.zip)

**Comment by kaby76** [comment]
> ok , this is project [SQL_parser.zip](https://github.com/antlr/grammars-v4/files/8725082/SQL_parser.zip)

As I said, the .csproj must use `<PackageReference>` for both Antlr4BuildTasks and Antlr4.Runtime.Standard because I programmed the package to scan the .csproj for `<PackageReference>`, not `<Reference>`.

Here is the fixed .csproj file: https://github.com/antlr/grammars-v4/files/8728435/SQL_parser.csproj.txt . You can do a diff to see what I changed. The build works fine for me, but the UI for setting Antlr4 options does not work, at least not in VS2022. I don't know why, but I think it's because this is an old-style .csproj. So, I will likely add code in Antlr4BuildTasks to check for these old-style projects and disallow usage. In Visual Studio 2022, creating a WPF application results in a 10-line .csproj in the new SDK-style format.

In any case, give this hand-edited .csproj a try (renaming, of course, SQL_parser.csproj.txt to SQL_parser.csproj).

**Comment by ai2soft** [comment]
hi , guys.
my vs is vs2019 version 16.11.15. 
i have jave installed , JAVA_HOME =>C:\Program Files\Java\jdk1.8.0_91  , added %JAVA_HOME%\bin to System Path
i had replace SQL_parser.csproj with yours. 
finally , i got an error
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The Antlr4 tool failed.	SQL_parser			

```
no more information.

**Comment by ai2soft** [comment]
Thanks, guys. it was successfully compiled after install jdk 11.7
and the code
```
        private void Test()
        {

            var fileName = "SQLQuery1.sql";

            using (StreamReader fileStream = new StreamReader(fileName))
            {
                AntlrInputStream inputStream = new AntlrInputStream(fileStream);

                var lexer = new TSqlLexer(inputStream);
                CommonTokenStream commonTokenStream = new CommonTokenStream(lexer);
                var parser = new TSqlParser(commonTokenStream);

                //parser.root(); //what to do next ?
            }
        }
```
has no error.
but,  how can i get the sql keys?
and when i debug the project , i got 4 runtime exceptions. 


the project source code
[SQL_parser.zip](https://github.com/antlr/grammars-v4/files/8734861/SQL_parser.zip)
