### ISSUE TITLE
sqlserver

### ISSUE THREAD

**Issue by nIxedoahz** [antlr/grammars-v4#2634]
Is the resolution of the sqlserver database currently supported?

**Comment by nIxedoahz** [comment]
Is parsing of sqlserver databases currently supported? Or is the syntax of sqlserver similar to which database?

**Comment by studentmain** [comment]
https://github.com/antlr/grammars-v4/tree/master/sql/tsql

**Comment by nIxedoahz** [comment]
> https://github.com/antlr/grammars-v4/tree/master/sql/tsql

antlr-4.9.3-complete.jar error
what should i do?

java -jar ../../antlr-4.9.3-complete.jar -Dlanguage=Cpp -listener -visitor -o generated -package antlrcppSqlServer SqlServerLexer.g4  SqlServerParser.g4
error(50): /home/test/demo/Sqlserver/SqlServerLexer.g4:900:7: syntax error: mismatched input 'options {' expecting COLON while matching a lexer rule
error(50): /home/test/demo/Sqlserver/SqlServerLexer.g4:900:32: syntax error: '=' came as a complete surprise to me while matching rule preamble
error(50): /home/test/demo/Sqlserver/SqlServerLexer.g4:900:40: syntax error: '}' came as a complete surprise to me while matching a lexer rule
error(50): /home/test/demo/Sqlserver/SqlServerLexer.g4:948:25: syntax error: mismatched input 'options {' expecting COLON while matching a lexer rule
error(50): /home/test/demo/Sqlserver/SqlServerLexer.g4:948:50: syntax error: '=' came as a complete surprise to me while matching rule preamble
error(50): /home/test/demo/Sqlserver/SqlServerLexer.g4:948:58: syntax error: '}' came as a complete surprise to me while matching a lexer rule

**Comment by studentmain** [comment]
update to antlr4.10+ or use https://github.com/antlr/grammars-v4/tree/02a99eff4482f809626812dba0fcc9a8a4bf49a4/sql/tsql
