### ISSUE TITLE
Tsql spaces are removed issue

### ISSUE THREAD

**Issue by nIxedoahz** [antlr/grammars-v4#2641]
TsqlPaeser parser(&tokens)
TokenStreamRewriter Rewriter(&tokens)
cout << Rewriter.getText() <<endl;

The output is “select*fromtable”
instead of “select * from table”

**Comment by studentmain** [comment]
https://github.com/antlr/grammars-v4/blob/93308b91dcb33eb51e1b3d2034191d981284c3e3/sql/tsql/TSqlLexer.g4#L888

It's in HIDDEN channel

**Comment by nIxedoahz** [comment]
> https://github.com/antlr/grammars-v4/blob/93308b91dcb33eb51e1b3d2034191d981284c3e3/sql/tsql/TSqlLexer.g4#L888
> 
> It's in HIDDEN channel

So do I need to comment out this line? 
I need this "select * from table"

**Comment by KvanTTT** [comment]
No, you have you use another method to get text, please try to clarify it on StackOverflow.
