### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by nIxedoahz** [antlr/grammars-v4#2699]
SQL statements I only need to parse to the "where" keyword before, what should I do?

Should I make the following changes？
parser.g4 ->      where_caluse
                          :  WHERE EOF

**Comment by nIxedoahz** [comment]
The arguments passed in are the complete sql statement

**Comment by kaby76** [comment]
There isn't a good way to stop a parse in the middle of some input. Antlr tries to parse all the input. I recommend that you try asking this on StackOverflow.com.
