### ISSUE TITLE
listener not call enter but only exit?

### ISSUE THREAD

**Issue by scmod** [antlr/grammars-v4#2722]
I have generate the Parser and Lexer of javascript.
and then I call
```
public static void main(String[] args) {
    JavaScriptLexer l = new JavaScriptLexer(CharStreams.fromString("typeof ++a;b ** b"));
    JavaScriptParser p = new JavaScriptParser(new CommonTokenStream(l));
    Lis4 lis = new Lis4();
    p.addParseListener(lis);
    p.program();
}

public static class Lis4 extends JavaScriptParserBaseListener {
    public void enterPreIncrementExpression(PreIncrementExpressionContext ctx) {System.out.println("enterPreIncrementExpression");}
    public void enterTypeofExpression(TypeofExpressionContext ctx) {System.out.println("enterTypeofExpression");}
    public void exitTypeofExpression(TypeofExpressionContext ctx) {System.out.println("exitTypeofExpression");}
    public void exitPreIncrementExpression(PreIncrementExpressionContext ctx) {System.out.println("exitPreIncrementExpression");}
}
```
it only prints
```
exitPreIncrementExpression
exitTypeofExpression
```
antlr 4.10.1

**Comment by bkiers** [comment]
You should be using `ParseTreeWalker.DEFAULT.walk(...)`:

```java
JavaScriptLexer l = new JavaScriptLexer(CharStreams.fromString("typeof ++a;b ** b"));
JavaScriptParser p = new JavaScriptParser(new CommonTokenStream(l));
ParseTreeWalker.DEFAULT.walk(new Lis4(), p.program());
```

Output:

```
enterTypeofExpression
enterPreIncrementExpression
exitPreIncrementExpression
exitTypeofExpression
```

**Comment by parrt** [comment]
Interesting. i guess we'll have to test Java to see if that's correct. if so, the template differences should make the fix clear.

**Comment by kaby76** [comment]
Yes, it appears to also be in Java. (I generated a parser with `trgen -t Java`, edited the driver to `addParserListener(), and added the listener class`):
```
make run RUNARGS="-file x"
trwdog java -classpath C:/Users/Kenne/Downloads/antlr4-4.10.1-complete.jar\;. Program -file x
exitPreIncrementExpression
Time: 0.078
Parse succeeded.

```
```
import org.antlr.v4.runtime.*;
public class ParseListener extends JavaScriptParserBaseListener
{
    @Override public void enterPreIncrementExpression(JavaScriptParser.PreIncrementExpressionContext ctx) {
	System.out.println("enterPreIncrementExpression");
    }
    @Override public void exitPreIncrementExpression(JavaScriptParser.PreIncrementExpressionContext ctx) {
	System.out.println("exitPreIncrementExpression");
    }
}
```
Looks like might be easy to fix--but for me, the templates can be tricky to get used to because parameters are passed all around from one rule to the next.

**Comment by scmod** [comment]
Thank you all.
After taking a look at Parser.addParseListener javadoc.
I saw there is difference between addParseListener and ParseTreeWalker.DEFAULT.walk.
one is called in parsing, and one is called after parse is complete.
```
Inparticular, rule entry and exit events may occur in a different orderduring the parse than after the parser. In addition, calls to certainrule entry methods may be omitted.
```
so it seems using ParseTreeWalker.DEFAULT.walk is a better choice?

**Comment by kaby76** [comment]
> so it seems using ParseTreeWalker.DEFAULT.walk is a better choice?

If the parse does not depend on the listener, use ParseTreeWalker.DEFAULT.walk() after the parse.

But, there is still a problem with the code that calls listeners called during the parse. An issue should be created over in github.com/antlr/antlr4 so the templates can be tweaked for this other use case.

**Comment by parrt** [comment]
I believe we did mention some thing in the documentation about left recursive function or something having some unusual behavior when listening directly during the parts. Much better to walk the tree afterwards. I don't have time to dig into it right now but I think there may be a known quirk because of the left recursion removal that we do. I can't remember.

**Comment by KvanTTT** [comment]
> Much better to walk the tree afterwards.

If performance matters and file is big, it's much faster and memory-friendly to process the tree on the fly (with option `buildParseTree = false`).

**Comment by parrt** [comment]
Yes if performance is critical then doing your actions on the fly is it good idea, what you can do with actions directly in the grammar or with the parts listener. With the caveat of course that I think it's not able to handle certain circumstances.

**Comment by scmod** [comment]
👌
