### ISSUE TITLE
Python Runtime incompatibilities with PHP Grammar 

### ISSUE THREAD

**Issue by dkazantzas** [antlr/grammars-v4#2730]
There are multiple occurences of actions and predicates such as the following:
https://github.com/antlr/grammars-v4/blob/0c9a11ea096dd182862dac03f25766cd5546ff95/php/PhpLexer.g4#L47
https://github.com/antlr/grammars-v4/blob/0c9a11ea096dd182862dac03f25766cd5546ff95/php/PhpLexer.g4#L63

When the Python files are generated, they result in cases such as the following:
```
def Shebang_sempred(self, localctx:RuleContext, predIndex:int):                                                                                                                     
    if predIndex == 0:                                                                                                                                                          
        return  this.IsNewLineOrStart(-2)   
```

However, as the `self` keyword is used instead of `this`, the result is Python throwing a name error.

Not sure what the correct solution to this issue would be. At the very least, a warning should be added to the `README.md`, so that people that wish to use the Python runtimes don't have this issue.

**Comment by kaby76** [comment]
This PHP grammar is a mess. The solution is to follow exactly what I did here: https://github.com/antlr/grammars-v4/commit/4794c0c5371ce6b0711a306256f8f7706394ec6d , adding transformGrammar.py, a new Readme.md, etc. In this PR, I added instructions to run "python3 transformGrammar.py". That will modify the grammar for Python3. There is no universal "object reference call to method" across all targets. The only viable solution is to standardize on "this." object reference calls, and modify them to produce a grammar that works with the target. Could you add this code please?

**Comment by dkazantzas** [comment]
Good idea. I've added the file. This will save help users automate the whole process

**Comment by kaby76** [comment]
@dkazantzas Thank you so much! I'll peek at the PR to make sure it's working.
