### ISSUE TITLE
LexBasic.g4:136:15: reference to undefined rule: DOT

### ISSUE THREAD

**Issue by BertVerhees** [antlr/grammars-v4#274]
The fragment Dot is defined, not the fragment DOT, I think that is an error

**Comment by teverett** [comment]
in which grammar directory is this problem?

**Comment by BertVerhees** [comment]
It is a problem in ANTLRv4Lexer.g4, it imports Lexbasic.g4, when using the antlr-grammar this problem occurred.

**Comment by teverett** [comment]
Is this still a problem?  I see this in LexBasic.g4

`fragment Dot			: '.'	;`

and this in ANTLRv4Lexer.g4

`DOT			: Dot			;`

So "DOT" is defined as "Dot" which is defined as "'.'".  I think it's ok like this?
