### ISSUE TITLE
[GrammarTest] Grammar tester doesn't support parsers with `options { superClass=...;}`

### ISSUE THREAD

**Issue by RossPatterson** [antlr/grammars-v4#2755]
There doesn't seem to be a way to make the [grammar tester](https://github.com/antlr/grammars-v4/tree/master/_grammar-test) work for a grammar that uses `options {superClass=...;}`.  Specifically, there doesn't appear to be a way to feed the GenericParser a set of grammar files that includes either the Java source file for the superclass or a compiled class from it.  Or, for that matter, superclass files for any language.

I'd love to be wrong, because I'm trying to use `GrammarTest` to test my changes for [[rexx] Hexstrings and binarystrings aren't parsed correctly](https://github.com/antlr/grammars-v4/issues/2741).

@julianthome - Am I missing something key here?

**Comment by kaby76** [comment]
Why does [grammar-test](https://github.com/antlr/grammars-v4/tree/master/_grammar-test) exist? It duplicates information in the pom.xml, including:
* [a hardwired grammar file](https://github.com/antlr/grammars-v4/blob/1e98d43a5c5439e14569df9bcc3eb5b86723ce8d/_grammar-test/src/test/java/TestAbnf.java#L9);
* [a hardwired list of files in examples/ at a specific point in time](https://github.com/antlr/grammars-v4/blob/1e98d43a5c5439e14569df9bcc3eb5b86723ce8d/_grammar-test/src/test/java/TestAbnf.java#L10);
* [a hardwired start rule](https://github.com/antlr/grammars-v4/blob/1e98d43a5c5439e14569df9bcc3eb5b86723ce8d/_grammar-test/src/test/java/TestAbnf.java#L17).
 
If the grammar changes, this code must also change! I've assumed that all the information for the grammar would be in the pom.xml. Now I see that it doesn't. (Note, in absence of a pom.xml, trgen could deduce all the information in pom.xml,.)

We have already ***three*** methods of testing grammars:
* Maven:
    * cd abnf; mvn clean test
* _scripts/regtest.sh:
    * cd abnf; bash ../regtest.sh Java
 * _scripts/test.ps1.

The latter two employ trgen, which generates a driver+build files for any target, any platform.

**Comment by RossPatterson** [comment]
I'm guessing [`grammar-test`](https://github.com/antlr/grammars-v4/tree/master/_grammar-test) is unused.  It apparently hasn't been able to compile since commit 45133256c6fefc649ebcf9aa451096883eec4bc4 on 2020-11-14, which updated the `inmemantlr` dependency to one that no longer has `org.snt.inmemantlr.tree.Ast` - it was renamed to `ParseTree`, and `grammar-test` was never updated.  Which means that it certainly isn't being used in the CI pipeline, which means it's not useful for the Rexx unit tests I wanted to write.

Time to find a Plan B for my tests.

**Comment by kaby76** [comment]
Usually I just run a "mvn clean test" in the directory to do a quick overall test for Java. That usually clears up most problems. Then, after that if you are working on a port to another target, you can use regtest.sh or just submit the code, and either it will go through a build, or I'll see it stuck there, and try the fork myself on my machine.

**Comment by RossPatterson** [comment]
#2818 removed the Grammar tester.
