### ISSUE TITLE
Retire or update the _grammar-test directory

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#2818]
[_grammar-test](https://github.com/antlr/grammars-v4/tree/2e2dcd917de910e21e94e893ac1bf1c366cfc9b5/_grammar-test) is a test suite based on Maven, which tests selected grammars in this repo. It should be removed or updated for several reasons:
* [It's not integrated into the CI build](https://github.com/antlr/grammars-v4/blob/2e2dcd917de910e21e94e893ac1bf1c366cfc9b5/pom.xml#L327) when it was removed from the root pom.xml 4 years ago.
* Uses [org.snt.inmemantlr](https://search.maven.org/artifact/com.github.julianthome/inmemantlr-api/1.9.2/jar)
    * That package [parses](https://github.com/julianthome/inmemantlr/blob/2e23ab407ed4200f5808e8a0bfd5bf6ea0d39e4d/inmemantlr-api/src/main/java/org/snt/inmemantlr/tool/InmemantlrTool.java#L122) then [generates code for the grammars](https://github.com/julianthome/inmemantlr/blob/2e23ab407ed4200f5808e8a0bfd5bf6ea0d39e4d/inmemantlr-api/src/main/java/org/snt/inmemantlr/comp/StringCodeGenPipeline.java#L227) in [Antlr](https://github.com/antlr/antlr4/blob/aa1f1f12a846846fcb78544bdb2ad135471376db/tool/src/org/antlr/v4/codegen/CodeGenerator.java#L44).
    * But, [inmemantlr uses Antlr 4.9.3](https://github.com/julianthome/inmemantlr/blob/2e23ab407ed4200f5808e8a0bfd5bf6ea0d39e4d/pom.xml#L27), and hasn't been updated since [Dec 2021](https://github.com/julianthome/inmemantlr/commit/056d73b566ae91c3d7c7073403d597fb6ee80d87).
* Maintaining both [_grammar-test](https://github.com/antlr/grammars-v4/tree/2e2dcd917de910e21e94e893ac1bf1c366cfc9b5/_grammar-test)/[inmemantlr](https://github.com/julianthome/inmemantlr/tree/2e23ab407ed4200f5808e8a0bfd5bf6ea0d39e4d) and the pom.xml/[antlr4-maven-plugin](https://github.com/antlr/antlr4test-maven-plugin/tree/213120e28d859993eb23f288b8c0818cc8bf7353) is unsustainable, because _grammar-test duplicates the information encoded in the pom.xml in each grammar directory. E.g., for antlr/antlr4, the grammars in [_grammar-test/src/test/java/TestAntlr4.java](https://github.com/antlr/grammars-v4/blob/2e2dcd917de910e21e94e893ac1bf1c366cfc9b5/_grammar-test/src/test/java/TestAntlr4.java#L31-L32) vs [antlr/antlr4/pom.xml](https://github.com/antlr/grammars-v4/blob/2e2dcd917de910e21e94e893ac1bf1c366cfc9b5/antlr/antlr4/pom.xml#L39-L40); support code for parser in [_grammar-test/src/test/java/TestAntlr4.java](https://github.com/antlr/grammars-v4/blob/2e2dcd917de910e21e94e893ac1bf1c366cfc9b5/_grammar-test/src/test/java/TestAntlr4.java#L24) vs [antlr/antlr4/pom.xml](https://github.com/antlr/grammars-v4/blob/2e2dcd917de910e21e94e893ac1bf1c366cfc9b5/antlr/antlr4/pom.xml#L26); start rule in [_grammar-test/src/test/java/TestAntlr4.java](https://github.com/antlr/grammars-v4/blob/2e2dcd917de910e21e94e893ac1bf1c366cfc9b5/_grammar-test/src/test/java/TestAntlr4.java#L80) vs [antlr/antlr4/pom.xml](https://github.com/antlr/grammars-v4/blob/2e2dcd917de910e21e94e893ac1bf1c366cfc9b5/antlr/antlr4/pom.xml#L60); specific tests in [_grammar-test/src/test/java/TestAntlr4.java](https://github.com/antlr/grammars-v4/blob/2e2dcd917de910e21e94e893ac1bf1c366cfc9b5/_grammar-test/src/test/java/TestAntlr4.java#L77) vs a collection of tests in [antlr/antlr4/pom.xml](https://github.com/antlr/grammars-v4/blob/2e2dcd917de910e21e94e893ac1bf1c366cfc9b5/antlr/antlr4/pom.xml#L63).
*  [_grammar-test](https://github.com/antlr/grammars-v4/tree/2e2dcd917de910e21e94e893ac1bf1c366cfc9b5/_grammar-test) misses testing of many grammars (see [source code](https://github.com/antlr/grammars-v4/tree/master/_grammar-test/src/test/java)).
* [_grammar-test](https://github.com/antlr/grammars-v4/tree/2e2dcd917de910e21e94e893ac1bf1c366cfc9b5/_grammar-test) does not include testing of ToStringTree() that is in the [Maven test plugin](https://github.com/antlr/antlr4test-maven-plugin).
* [_grammar-test](https://github.com/antlr/grammars-v4/tree/2e2dcd917de910e21e94e893ac1bf1c366cfc9b5/_grammar-test) only tests the Java target, not the other targets.
* The accepted practice for testing a grammar is ["maven clean test"](https://github.com/antlr/grammars-v4/wiki#how-do-i-test-the-grammars). The doc makes no reference to _grammar-test.

**Comment by KvanTTT** [comment]
I vote for retirement, I'm interested in decreasing dependencies.
