### ISSUE TITLE
Add support for parse tree verification in tests

### ISSUE THREAD

**Issue by RossPatterson** [antlr/grammars-v4#2837]
In [ANTLR discussion 3321](https://github.com/antlr/antlr4/discussions/3321#discussioncomment-3642335), @kaby76  wrote:

> The [line for calling the parser](https://github.com/antlr/grammars-v4/blob/553522db0536ca80e0535351a19bdd8cbcc14e77/_scripts/templates/Java/test.sh#L14) doesn't do anything with doing tree diffs. It should be fixed.

I've got a change in progress that will do this.

**Comment by RossPatterson** [comment]
In the process of implementing this, I've found two anomalies:

1. All the `_scripts/tempates/*/test.sh` scripts incorrectly test an unset `$stat` variable if there is a `.errors` file for the test.  I've fixed that.
2. The `_scripts\test.ps1` script fails all tests on my machine (Windows 11, version 21H2, OS Build 22000.978).  The issue is that the test filenames returned from [`Get-ChildItem`](https://github.com/antlr/grammars-v4/blob/master/_scripts/test.ps1#L146) are relative to the parent directory on my machine.  They appear to be absolute in the CI builds (see https://github.com/antlr/grammars-v4/actions/runs/3064889059/jobs/4948444850#step:17:39 for an example).  I've fixed that in a manner that will work regardless of the `Get-Childitem` results, but it's disturbing.  I can't find any documentation that states or implies the absolute pathname results.

**Comment by kaby76** [comment]
Right, I noticed I could never do a `pwsh ../_scripts/test.ps1` in any one grammar. It would be nice if that could be fixed. I did write testreg.sh to work on single grammars though. Thanks for working on this stuff.

**Comment by RossPatterson** [comment]
I'd appreciate a code review of this change before I send in the PR.  I don't have the full setup necessary for testing. 

I've run the Java tests for Rexx on Windows 11 and Ubuntu (under WSL), and they all pass, including the ones that have tree-reference files.  I've manually broken the reference files, and re-run those tests, and observed them failing as they should.  I have carefully `diff`ed the modified files in `_scripts\templates\Java` against all the other templates, and there are no unexpected changes.  But I haven't run any tests for any target other than Java, and I can't.  

I'd rather not blow up the entire CI build system at 22:00 EST over a stupid mistake.

Here's the comparison link: https://github.com/antlr/grammars-v4/compare/master...RossPatterson:grammars-v4:issue_2837_treefile?expand=1

**Comment by kaby76** [comment]
Seems good. Yes, the only thing that we actually need on stdout of a program is the tree and the parse errors. The rest, like time for the parse, can go to stderr.

**Comment by RossPatterson** [comment]
At this point, I believe this work is complete, and PR #2842  ready to merge.

- Java CI builds now skips `grammars-v4/php`, due to [`antlr4` issue #2677](https://github.com/antlr/antlr4/issues/2677).
- All templates now send tree output to stdout, and everything else to stderr.
- All bash test drivers now correctly report successful parses that were expected to fail as test failures.    The PowerShell test drivers already did so.
- All test drivers now create tree output, and if there is a reference file, compare against it.
- All PowerShell test drivers now correctly process UTF-8 tree data.  The bash test drivers already did so.
- The Java and Python3 test drivers now correctly process UTF-8 tree data.  The other target test drivers already did so.
- The Cpp test driver now correctly reports when a test generates lexer or parser errors.    The other target test drivers already did so.
- The strange behaviour of the [`grammars-v4/b` macos Go test](https://github.com/antlr/grammars-v4/actions/runs/3131603578/jobs/5083108367#step:17:980) is not reproducible.  Since the errors appear within a block that was generated by the `antlr4` tool, I'm not going to dig into it.
- All non-skipped tests are succeeding.
