### ISSUE TITLE
Implement full .errors verification in tests

### ISSUE THREAD

**Issue by RossPatterson** [antlr/grammars-v4#2838]
In [grammars-v4 issue 2821](https://github.com/antlr/grammars-v4/issues/2821), I  wrote:

> I'm experimenting now with making `trgen` verify ... the [`.errors`](https://github.com/RossPatterson/grammars-v4/blob/master/_scripts/templates/Java/test.sh#L16-L32)  reference files, as `antlr4test-maven-plugin` does in [AssertErrorsErrorListener](https://github.com/antlr/antlr4test-maven-plugin/blob/master/src/main/java/com/khubla/antlr/antlr4test/AssertErrorsErrorListener.java#L54-L74) ...  I'm interested in the `.errors` capability because it seems like it should be fully supported.

As I said, I've got an experiment in progress to do this.

**Comment by teverett** [comment]
@RossPatterson this is great news.  Thank-you!

**Comment by RossPatterson** [comment]
I encountered the `grammars-v4/csharp` examples `issue-2612` error described in [`antlr4` issue #3700](https://github.com/antlr/antlr4/issues/3700) during work on this.  I expect I'll have to add it to `grammars-v4/_scripts/skip_csharp.txt`.

**Comment by RossPatterson** [comment]
At this point, I believe this work is complete, and PR #2855 is ready to merge.

- The `build-csharp` CI job now skips `csharp`, due to [`antlr4` issue #3700](https://github.com/antlr/antlr4/issues/3700).
- The `build-php` CI job now skips `logo/logo`, due to issue #2859.
- The `build-php` CI job and all JavaScript `build-pwsh` CI jobs now skip `python/python3alt`, as it has Java code in the `@members` sections.  All other non-Java builds already skipped it.
- All test drivers (_e.g._, `_scripts/*/Program.*`) now dump out the detected errors to stdout in the expected format, and only dump the parse tree if there are no errors.
- All test scripts (_i.e._, `_scripts/*/test.sh`, `_scripts/*/tester.psm1`) now check the detected errors against the reference files, and only check the parse tree if there are no errors.
- The Java test driver now dumps out the errors in UTF-8.  All the other test drivers already did so.
- All the non-skipped grammars that have `.errors` files in their `examples` directory generate all and only those errors.
- All non-skipped tests are succeeding.
