### ISSUE TITLE
[Bug] JavaScript singleExpression needs a redesign

### ISSUE THREAD

**Issue by caoccao** [antlr/grammars-v4#2843]
After carefully analyzed `singleExpression` in JavaScript, I found the current model might be improper and would like to propose a redesign.

# Problems

`singleExpression` is a general concept that is misused by `singleExpression` itself. E.g.

- `ClassExpression` + `BitAndExpression` results in `class A {} ^ class B {}` being valid. V8 reports `SyntaxError: Unexpected token '^'`.
- `ClassExpression` + `PostIncrementExpression` results in `class A {}++;` being valid. V8 reports `SyntaxError: Unexpected token ';'`.

There could be all kinds of invalid expressions passing antlr.

# Proposal

I'd like to propose a new type of expression which is a subset of `singleExpression` so that some expressions like `ClassExpression`, `FunctionExpression`, etc. could be excluded and the parser could be more strict.

I'm afraid that would be a major change to the antlr consumers. I'm quite new to this project. Your feedback is appreciated.

**Comment by bkiers** [comment]
It is quite normal for a parser (grammar) to accept certain input that is semantically incorrect. The V8 engine is not a parser, but rather an interpreter. After the parser is done, the generated parse tree can be inspected (using a listener or visitor) to check if certain statements are invalid.

**Comment by KvanTTT** [comment]
They don't look semantics errors:

```
SyntaxError: Unexpected token '^'
SyntaxError: Unexpected token ';'
```

**Comment by caoccao** [comment]
Thank @bkiers and @KvanTTT for the input. It makes sense.

The problem I'm facing is to find a proper library which can generate an AST from the JS code and follow the way V8 does.

- V8 compiles the code super fast, but cannot generate the AST. Actually generating the AST has never been a goal to the V8 team.
- Babel is able to partially do that. But, it is even less strict than Antlr does, and its performance is really poor.
- Antlr seems to be in the middle ground in terms of the strictness and performance.

I really like to improve the grammar for JavaScript so that it can align with V8. Now, I realize that might not be the goal of the antlr/grammars-v4 project (please correct me if I'm wrong). I'm considering creating a fork with my goal. I understand creating a custom listener could resolve that, but I hold concern on the performance, extra dev work because I think that could be done by tweaking the g4 file with relatively small dev work. Also, I believe the need for a strict AST generator is out there and the gap needs to be filled. If there have already been some other tools doing so, I'd really appreciate if you could leave their names.

Thank you.

**Comment by KvanTTT** [comment]
I have no objection of making the grammar more strict if it's possible.

**Comment by caoccao** [comment]
> I have no objection of making the grammar more strict if it's possible.

Sounds good. I'll try to introduce [LeftHandSideExpression](https://262.ecma-international.org/13.0/#sec-left-hand-side-expressions).

**Comment by caoccao** [comment]
Closing this issue as I don't need it any more. I created [swc4j](https://github.com/caoccao/swc4j) which is much more powerful than antlr is.
