### ISSUE TITLE
Antlr4 Java grammar Java 17 mods not handling yield in switch expression.

### ISSUE THREAD

**Issue by gmtschlr** [antlr/grammars-v4#2908]
I got an error parsing the version java.util.Calendar in the Java 17.0.3 source base, using antlr4 (4.10.1), which has a switch expression at about line 1491.  

The "yield" statement in the second case ("iso8601") was parsed as a local variable declaration instead of a yield statement.

The problem appears to be in the syntax for blockStatement, which has localVariableDeclaration before statement.

With some trepidation, I switched them, and the yield statement is now recognized, without any other errors noted in parsing several dozen files.  I remain concerned whether this fix is the proper one.

Relevant grammar file (as modified) and Java test case in attached zip file.
[JavaParser.zip](https://github.com/antlr/grammars-v4/files/9911817/JavaParser.zip)

**Comment by DagSonntag** [comment]
I think this issue can be closed with the merged branch.
