### ISSUE TITLE
Ignoring merge conflicts caused by grammars.json

### ISSUE THREAD

**Issue by msagca** [antlr/grammars-v4#2919]
[grammars.json](https://github.com/antlr/grammars-v4/blob/master/grammars.json) file creates unnecessary merge conflicts when a PR that modified this file gets merged before some other open PRs. It should be okay to ignore merge conflicts caused by this file since the index is updated anyway in case of a change. If you're okay with this, the method described [here](https://gist.github.com/tmaybe/4c9d94712711229cd506) seems to work.

**Comment by kaby76** [comment]
Yes, it's a generated file, but not a "build" product per se, although it is generated on each PR. It's used in lab.antlr.org right now. Eventually, I will be using this file to produce a top-level page for a Github Pages website that contains sortable tables, searching, links, classifications, targets available, etc., for grammars.  Please make a PR to fix the conflict. It seems like the conflict ignore procedure should work.

https://github.com/antlr/grammars-v4/issues/2866
https://github.com/antlr/grammars-v4/issues/2905
https://github.com/antlr/grammars-v4/pull/2830
https://github.com/antlr/grammars-v4/discussions/2872

**Comment by KvanTTT** [comment]
Honestly, I don't like the idea of automatic commits and I still think lab.antlr.org should process repository itself instead of using generated file.

**Comment by kaby76** [comment]
> Honestly, I don't like the idea of automatic commits and I still think lab.antlr.org should process [the] repository itself instead of using [a] generated file.

I'll change the generate of grammars.json around to make it a Github Action artifact. That will work for a while.

But, Antlr4test-maven-plugin, antlr4-maven-plugin, trgen, and the build scripts contain the logic to understand the structure of the grammars-v4 repo. I don't think it's a good idea to add another tool that duplicates the logic. The pom.xml do not encode everything that is needed, e.g., what targets can be run.
