### ISSUE TITLE
ambiguity between ':=' and '=' 

### ISSUE THREAD

**Issue by u-riaz** [antlr/grammars-v4#292]
Hi,
VB uses ':=' for named arguments, and '=' for both, assignments and equality-comparisons.
I'm using ANTLR-v4 parser and want to separate-out assignments. For this i had override method
 enterVsEq(VsEqContext ctx){...}, so that when '=' comes i can print-out something. But this is not hitting for following like statements
var = 5; 
A.B=some_value;
so on...

Although, this method is getting hit when '=' is used in if-conditions. 
What i want is, 
1. when this method will hit for '=' in if-cond, i can bypass/ignore it.
2. when hit for assignments, then i'll print the desired token.

Please help. Thanks

**Comment by teverett** [comment]
Could you provide some example VB files that have both cases?

**Comment by Marti2203** [comment]
I think this is a closeable issue?

**Comment by UsmanRiaz1** [comment]
I'm not working on this anymore, pls close issue.

**Comment by Marti2203** [comment]
@teverett
