### ISSUE TITLE
Typescript template string grammar can't process escaped backtick

### ISSUE THREAD

**Issue by seyoatda** [antlr/grammars-v4#2978]
Hi, I'm new to antlr and trying to make a typescript-like language.
using lexer and parser from `https://github.com/antlr/grammars-v4/tree/master/javascript/typescript`, failed to parse the escaped `` ` ``
```javascript
// parse failed by antlr defined grammar
// native output: a = '`'
var a = ` \` `;

// a = '${'
var a = `\${`

```
besides, is it costly to define every char in the template string as a node? can we define a rule to merge the char into string fragments?
in the native typescript grammar, the above statement works well.

**Comment by bkiers** [comment]
> [...] can we define a rule to merge the char into string fragments?

That would mean that:

```ts
`1 + 2 = ${1 + 2}`
```

would  become a single token, instead of `1 + 2` inside `${...}` becoming an expression.
