### ISSUE TITLE
Problems in TSQL-grammar

### ISSUE THREAD

**Issue by kuseman** [antlr/grammars-v4#299]
Not working:

- AS in parameter not allowed

```
CREATE PROCEDURE dbo.PROCEDURE
(
	-- Param
	@pParam AS SMALLINT
)

```

Not working:

- COLLATE statement

- PRIMARY KEY statement

```
CREATE TABLE #table
	(
		col1		INT		NOT NULL
	,	col2		VARCHAR(60)	COLLATE DATABASE_DEFAULT NOT NULL DEFAULT('')
	,	col3		SMALLINT	NOT NULL
		PRIMARY KEY(col1, col2, col3)
	)
```

CHANGETABLE expressions not working:

https://msdn.microsoft.com/en-us/library/bb934145.aspx

Example query:

```
SELECT	t.id
		FROM	CHANGETABLE(CHANGES testtable, 12345) t		
		WHERE	t.col = 54321
		AND	t.sys_change_operation <> 'D'
```

**Comment by KvanTTT** [comment]
Please also add yourself to the contributors list.

**Comment by kuseman** [comment]
Hmm, how do I do that? :)

**Comment by KvanTTT** [comment]
Add this info to the header of file as another contributors did :)

**Comment by kuseman** [comment]
Fixed :)
