### ISSUE TITLE
TSQL grammar parser has tokens not present in lexer

### ISSUE THREAD

**Issue by fedorusov** [antlr/grammars-v4#3009]
They are:
- IPV4_ADDR
- IPV6_ADDR
- FILESTREAM_ON

**Comment by kaby76** [comment]
This will need to be fixed. https://github.com/antlr/grammars-v4/issues/2998 https://github.com/antlr/grammars-v4/issues/2990 https://github.com/antlr/grammars-v4/issues/2972#issuecomment-1362331961
