### ISSUE TITLE
csharp parse cast_expression error

### ISSUE THREAD

**Issue by ningpp** [antlr/grammars-v4#3020]
when parse code :
```
int a = (int) (1+Math.Log(x));
```

assignment value expression parse result is 
```
parenthesisExpressions + method_invocation
```

**Comment by bkiers** [comment]
How are you testing this? Note that `int a = (int) (1+Math.Log(x));` is matched as a `declarationStatement`:

![parseTree](https://user-images.githubusercontent.com/281616/213113329-672a66ea-8f74-49c1-ba11-62a723b988af.png)

**Comment by ningpp** [comment]
**
![image](https://user-images.githubusercontent.com/2511498/213133547-2eac71ff-6bb0-4234-92ee-687b1d131c28.png)
**

the red one,  my commont is not so good

**Comment by bkiers** [comment]
What about the red one? What is wrong about the resulting parse tree?

**Comment by ningpp** [comment]
```
(int) (1+Math.Log(x))
```
parsed to parenthesisExpressions + method_invocation

![image](https://user-images.githubusercontent.com/2511498/213156709-bf98b4af-3e7d-489f-a77a-1e767d90a5e0.png)

**Comment by ningpp** [comment]
```
//i use var node = new TreeRewriter(root).rewrite();
declarationStatement (
	local_variable_declaration int (
		local_variable_declarator a = (
			primary_expression (parenthesisExpressions ( int)) (
				method_invocation (
					(
						additive_expression 1+ (
							primary_expression Math (
								member_access . Log
							) (method_invocation ( x))
						)
					)
				)
			)
		)
	)
);
```

**Comment by bkiers** [comment]
What is wrong about the resulting parse tree?

**Comment by ningpp** [comment]
`(1+Math.Log(x))`

passed as method_invocation(method arg is `1+Math.Log(x)`), but it's not

**Comment by bkiers** [comment]
> `(1+Math.Log(x))`
> 
> parsed as method_invocation(method arg is `1+Math.Log(x)`), but it's not

Ah, OK, now I see what you mean. But it's just a name. It could've been named `method_invocation_or_expression`, right? The cast is also called `primary_expression_start ` and not something more descriptive. I don't really see what the problem is.
