### ISSUE TITLE
C grammar issue

### ISSUE THREAD

**Issue by ryanmkurtz** [antlr/grammars-v4#303]
In the C grammar, I get an error on this type of function definition:

void \* __stdcall foo()
{
}

It doesn't seem to like the \* between the return type and the __stdcall.

**Comment by ryanmkurtz** [comment]
I added "typeSpecifier pointer?" to declarationSpecifier and that seemed to fix it.  Not sure if that is the best way to go though.

**Comment by parrt** [comment]
thanks. not sure w/o diggin in but __stdcall is likely not handled properly in declarator.

**Comment by jack17529** [comment]
@parrt should I take this issue?

**Comment by parrt** [comment]
@jack17529 sure!

**Comment by jack17529** [comment]
@ryanmkurtz  please tell me where the code is ?

**Comment by parrt** [comment]
I think it is just https://github.com/antlr/grammars-v4/blob/master/c/C.g4

**Comment by teverett** [comment]
It's notable that this works:

```
__stdcall void * foo()
{
}

```

but this

```
void * __stdcall foo()
{
}

```
produces:

```
line 1:7 no viable alternative at input 'void*__stdcall'
line 1:7 extraneous input '__stdcall' expecting {'(', Identifier}

```

**Comment by teverett** [comment]
@ sharwell there is a potential fix here.  Could you take a look?

https://github.com/teverett/grammars-v4/commit/473824c9986d45e7422e76476c1d968cc1f4aed6

**Comment by Marti2203** [comment]
Is this done?

**Comment by ryanmkurtz** [comment]
Closing due to long-term inactivity
