### ISSUE TITLE
Sybase IQ 15.1+ grammar

### ISSUE THREAD

**Issue by xnappy** [antlr/grammars-v4#308]
Hey guys,

i did create a grammar for Sybase IQ 15.1+. Started with the make available tsql grammar and extend it. There are elements of the tsql grammar and more.

If you want use the grammar there it is (because the tsql grammar helped me alot)

[sybaseIq.zip](https://github.com/antlr/grammars-v4/files/148225/sybaseIq.zip)

Have a nice day

**Comment by parrt** [comment]
cool. can you make a pull request for dir sybaseiq/... ?

**Comment by xnappy** [comment]
yes I will make a pull request on monday :+1:  thanks for your great work :) ANTLR helped me alot to build my tool to check sql syntax and semantic
