### ISSUE TITLE
Java grammar fails for comments started with unicode escape sequence

### ISSUE THREAD

**Issue by asmod3us** [antlr/grammars-v4#310]
The parser generated from Java8.g4 fails to parse the following source file:
```
class test3 {
\u002f\u002f another comment
}
```
\u002f is the unicode escape sequence for a slash. The java compiler (1.8.0_73-b02) happily compiles it without warnings or errors.

**Comment by parrt** [comment]
Is that literally the unicode char or \u002f 6-char sequence?

**Comment by asmod3us** [comment]
That's the 6-char sequence in the source file.

**Comment by parrt** [comment]
ah. ok, yeah, the lexer does not handle that (insert cuss word here) that Sun thought was good idea back in the day. sorry ;)
