### ISSUE TITLE
Java grammar fails for line comments preceded by certain unicode escape sequences.

### ISSUE THREAD

**Issue by asmod3us** [antlr/grammars-v4#311]
The parser generated from Java8.g4 fails to parse the following source file:
```
class test4 {
  String somestring = "http://google.com", s = "\u005c""; // ";//google.com
}
```
\u005c is the unicode escape sequence for backslash aka reverse solidus. I'm not sure if it's the same root cause as #310, so I've opened this separately.

**Comment by parrt** [comment]
same issue. java is supposed to race through first to replace \ufoobar and then lex. I'm classifying this as a c-preprocessor like issue and not a grammar issue per se.
