### ISSUE TITLE
PHP in the test matrix is missing

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#3125]
I was looking at this PR for snowflake, and noticed that the PHP target is not being tested. https://github.com/antlr/grammars-v4/actions/runs/4231262914 It needs to be added. https://github.com/antlr/grammars-v4/blob/8b00eaf4b4eab17bfe5493e96260ee89b6f05efa/.github/workflows/main.yml#L15

I think the main problem was that even though the target may work, in some grammars and test suites, the build takes too long because all input is parsed as a group. I think I should have something in the desc.xml file to say to use individual parsing instead of group parsing, and possible have something that says skip this even though the target "works".

Note:

For the CSharp target, it takes minutes to compile. That is because it encodes the table of ~1000 reserved words directly in the grammar. Instead, it should be implemented as a table lookup when an identifier is lexed. This was common knowledge and practice 40 years ago, but got  lost in the deluge of "software developers" without proper training.

In fact, in _Cooper, K.D. and Torczon, L., 2023. Engineering a Compiler_, page 60, it states very clearly that there is a choice in implementing the keywords as rules in the grammar, or as a table lookup in another rule, such as identifiers. It says that either way, the scanner can be efficient. The trade-off is faster build times vs portability across targets. The grammar is already split, and has a base class, so the later concern is moot.

The PHP target is abnormally slow with this grammar.

**Comment by KvanTTT** [comment]
> That is because it encodes the table of ~1000 reserved words directly in the grammar. Instead, it should be implemented as a table lookup when an identifier is lexed.

If I understand correctly, [Token value comparison operator](https://github.com/antlr/antlr4/issues/1965) resolves this problem. Besides the problem that keywords slows down lexer, they also should be placed to `keyword_as_id` parse rule and users often forget doing that. It's especially actual for `sql` grammars with many tokens, mostly useless.

**Comment by kaby76** [comment]
@KvanTTT I was looking at the parse times for some of the SQL grammars, like plsql. I thought that compile time for C# was 5 minutes, but it looks like it's only 45 seconds. But, the "long compile time" is likely not due to PlsqlLexer.cs since it is only 13k lines, but PlsqlParser.cs, which is 195k lines. The alternative implementation I was thinking of would be in an action for the REGULAR_ID rule. It would look up the string in a hash table and return the token type for the reserved word. But, since the build time is insignificant, no change is needed. Just thinking out loud.
