### ISSUE TITLE
Javadoc grammar is incorrect

### ISSUE THREAD

**Issue by ericvergnaud** [antlr/grammars-v4#3143]
Using antlr4 lab, start rule 'documentation' and the SimpleExample from the repo as input: https://raw.githubusercontent.com/antlr/grammars-v4/master/javadoc/examples/javadoc/SimpleExample.java
shows a missing JAVADOC_END token

**Comment by ericvergnaud** [comment]
@kaby76 needing a javadoc-like grammar, I thought of starting from the existing Javadoc one. Turns out the JAVADOC_END token is never matched, looks like the semantic predicate in NEW_LINE does not prevent consumption of the '*' berfor '/'.

**Comment by kaby76** [comment]
> @kaby76 needing a javadoc-like grammar, I thought of starting from the existing Javadoc one. Turns out the JAVADOC_END token is never matched, looks like the semantic predicate in NEW_LINE does not prevent consumption of the '*' before '/'.

I would say almost every grammar in this repo needs work. That Javadoc grammar is seven years old.

**Comment by bkiers** [comment]
@ericvergnaud perhaps predicates are not executed in the "lab" environment? I wouldn't be surprised, given it is dangerous to just run arbitrary code. A manual test shows `JAVADOC_END` _is_ created:

```java
String source = "/**\n" +
    " * A description text.\n" +
    " */";

JavadocLexer lexer = new JavadocLexer(CharStreams.fromString(source));
CommonTokenStream stream = new CommonTokenStream(lexer);
stream.fill();

for (Token t : stream.getTokens()) {
    System.out.printf("%-20s'%s'%n",
        JavadocLexer.VOCABULARY.getSymbolicName(t.getType()),
        t.getText().replace("\n", "\\n"));
}

lexer = new JavadocLexer(CharStreams.fromString(source));
JavadocParser parser = new JavadocParser(new CommonTokenStream(lexer));
ParseTree root = parser.documentation();
System.out.println("\n" + root.toStringTree(parser));
```

prints:

```
JAVADOC_START       '/**'
NEWLINE             '\n *'
SPACE               ' '
NAME                'A'
SPACE               ' '
NAME                'description'
SPACE               ' '
NAME                'text'
TEXT_CONTENT        '.'
NEWLINE             '\n'
JAVADOC_END         ' */'
EOF                 '<EOF>'

(documentation /** (skipWhitespace \n *) (skipWhitespace  ) (documentationContent (description (descriptionLine (descriptionLineStart (descriptionLineNoSpaceNoAt A)   (descriptionLineNoSpaceNoAt description)   (descriptionLineNoSpaceNoAt text) (descriptionLineNoSpaceNoAt .)))) (skipWhitespace \n))  */ <EOF>)
```

**Comment by kaby76** [comment]
@bkiers You are right. The least that http://lab.antlr.org/ can do with a grammar that contains action code is to give a warning. But it does not. I created an issue for lab.antlr.org to output a warning if there is action code in a grammar. https://github.com/antlr/antlr4-lab/issues/71

http://lab.antlr.org/ does not display the start symbol correctly for javadoc. It's correct in [grammars.json](https://github.com/antlr/grammars-v4/blob/825ea1a6544e4041ebd9e697c35aa3b32b700c16/grammars.json), so lab.antlr.org has a bug there. Created an issue. https://github.com/antlr/antlr4-lab/issues/72

The drop down list "Input" is not working for javadoc/: neither of the two input files are listed. Created issue. https://github.com/antlr/grammars-v4/issues/3145

**Comment by ericvergnaud** [comment]
It also doesn't work in the IntelliJ plugin

**Comment by bkiers** [comment]
> It also doesn't work in the IntelliJ plugin

That is correct: it is known (designed) for the plugin to ignore embedded code (predicates are just that: embedded code)

**Comment by ericvergnaud** [comment]
I can understand why actions would not be executed, but predicates are key to correct parsing so maybe we need to think about it...

**Comment by bkiers** [comment]
> I can understand why actions would not be executed, but predicates are key to correct parsing so maybe we need to think about it...

As explained in [the README of the plugin](https://github.com/antlr/intellij-plugin-v4#limitations):

> The ANTLR Preview window is based on a grammar interpreter, not on the actual generated parser. This means that things like actions and predicates will not be evaluated during live preview, because the interpreter is language agnostic.
>
> For the same reasons, if your parser and/or lexer classes extend a custom implementation of the base parser/lexer classes, your custom code will not be run during live preview.

In short:

- when your grammar contains code or predicates (which are the same as embedded code), test it with a small driver class
- this Javadoc grammar is OK (at least for the example mentioned in this issue)

**Comment by ericvergnaud** [comment]
ok, I rarely use the preview, so was not aware of this limitation. A bit frustrating and misleading...

**Comment by bkiers** [comment]
> A bit frustrating and misleading...

Well, given predicates can contain any target specific code, you can hardly expect the plugin to support evaluating around 10 different target languages, right?

**Comment by ericvergnaud** [comment]
Not the plugin, but the lab could...

**Comment by ericvergnaud** [comment]
We support automated testing (including semantic predicates) for these 10 targets so we know how to build a box that can run a parser in any of these. Picking the language from a drop-down would make it possible. I don't see this as being challenging - it's a lot of work, but there aren't any blockers.

**Comment by bkiers** [comment]
Go for it! It's all open-source, you can contribute to its development 😉

**Comment by ericvergnaud** [comment]
Yes, closing. BTW, not sure if your invite to contribute was a joke, but FWIW I have authored the Python2, Python3, JavaScript and TypeScript targets, and the original unified testing framework 😉.

**Comment by bkiers** [comment]
> Yes, closing. BTW, not sure if your invite to contribute was a joke, but FWIW I have authored the Python2, Python3, JavaScript and TypeScript targets, and the original unified testing framework 😉.

No no, not a joke, and I recognized you. I understand it'd be a pretty nice-to-have to be able to select a language to execute target specific code. I think it's just a lot of work to support (and maintain) it (other than in a CI pipeline).
