### ISSUE TITLE
The grammar for the C language is incorrect

### ISSUE THREAD

**Issue by FrostyMemes** [antlr/grammars-v4#3179]
The grammar for the C language works uncorrectly.
Grammar does not allow you to build a complete and correct AST. 
Examples of how this incorrect grammar works are shown in the pictures below. Files from the example folder were taken as test files.

![image](https://user-images.githubusercontent.com/49942326/222542196-46eea30a-6111-4ade-8952-8edd8de30735.png)
![image](https://user-images.githubusercontent.com/49942326/222542592-506533f4-870b-4e19-be00-ba6a746070ae.png)
![image](https://user-images.githubusercontent.com/49942326/222540983-adce72f6-f04a-43e9-a57f-becf18bd8132.png)
![image](https://user-images.githubusercontent.com/49942326/222542825-56f1a693-ebac-4919-bff2-9c96af080cbb.png)
![image](https://user-images.githubusercontent.com/49942326/222542046-808db060-7a57-4899-b321-470ac7aff0f9.png)

**Comment by FrostyMemes** [comment]
Oh, my apologies, this is my first time working with this IDE plugin, I didn't notice that I needed to change the entry point. I figured that the entry point is selected automatically by the plugin.

**Comment by bkiers** [comment]
> Oh, my apologies, this is my first time working with this IDE plugin, I didn't notice that I needed to change the entry point. I figured that the entry point is selected automatically by the plugin.

No problem. The entry point depends on the input you provide. If you had given the input `1 + 2 * 3`, then the rule `primaryExpression` would have succeeded but `compilationUnit` would have given you errors in that case.
