### ISSUE TITLE
TOML grammar does not handle digit-only keys

### ISSUE THREAD

**Issue by DanielBeckwith** [antlr/grammars-v4#3185]
Keys that are made of entirely digits (and other things that look like numbers) are legal (though discouraged) in TOML, but the grammar fails to match them. This is because of overlap between the `UNQUOTED_KEY` token and the `HEX_INT`, `OCT_INT`, `BIN_INT`, most `DEC_INT`, and some `FLOAT` tokens (and potentially some others), all of which take precedence over the `UNQUOTED_KEY` rule. Simply moving the `UNQUOTED_KEY` before them is not a solution because it will misclassify all number values as `UNQUOTED_KEY`s.

All of these are legal TOML documents, but fail to parse:
``` TOML
1234 = "value"
```
``` TOML
1e4 = "value"
```
``` TOML
-4e-3 = "value"
```

Unfortunately, I don't see a simple and/or elegant solution to this, not least because `DEC_INT` and `FLOAT` can have the `+` character in certain positions, while `UNQUOTED_KEY` *can not*.

I think one (hacky) way would be to include the overlapping token types as alternatives in the `unquoted_key` parser rule, but `DEC_INT` and `FLOAT` would have to be broken down into multiple token types so that the positive variants are not included. This has the downside that the token type could end up being surprising.

Another way could be to split the grammar into separate parser and lexer files in order to use modes, but I haven't used them before so I'm not sure how feasible that would be or how complicated it would make the grammar. What I'm envisioning would be to push a mode after what's currently the `key_value`'s `=` token, and having the various value patterns (including the various numbers) only under that mode.

If there's a preference for what the solution should look like, I could try my hand at it.

**Comment by msagca** [comment]
Hi @DanielBeckwith 

In my opinion, splitting the grammar would be the better solution. For a simple example on how to use lexer modes you can check my [desktop-entry](https://github.com/antlr/grammars-v4/blob/master/freedesktop/desktop-entry/DesktopEntryLexer.g4) grammar.
