### ISSUE TITLE
Move Ruby grammar to this repo

### ISSUE THREAD

**Issue by KvanTTT** [antlr/grammars-v4#319]
Found here: https://github.com/AlexBelov/ruby-antlr4

**Comment by parrt** [comment]
Cool.  it looks like that repo has moved https://github.com/AlexBelov/corundum just into somebody's looking at this trail.

**Comment by parrt** [comment]
I don't see any license on it by the way.  I added an issue on that repo, asking about moving. https://github.com/AlexBelov/corundum/issues/1

**Comment by AlexBelov** [comment]
@parrt @KvanTTT Feel free to do what you want! Let's assume that it has GNU GPLv3 license :)
Just want to warn everyone, it's not Ruby grammar, just something quite similar. For example this implementation has for loop (because it was written for Parrot VM). So should I create PR?

**Comment by KvanTTT** [comment]
@AlexBelov, it would be good :)

**Comment by AlexBelov** [comment]
#321 PR is here

**Comment by parrt** [comment]
Ack. GPL is a stain. How about BSD?

**Comment by AlexBelov** [comment]
@parrt I've read readme in repo. So as you can see - now grammar file has text of BSD at the beginning

**Comment by parrt** [comment]
@AlexBelov fantastic. thanks!
