### ISSUE TITLE
Antlr4 is not recognizing Keywords and classifying them as ID

### ISSUE THREAD

**Issue by Dangujba** [antlr/grammars-v4#3197]
I have been searching the internet for almost 3 days now i cant find solution, please Help

Here is the problem

I Have this grammar
[code]grammar EasyBite;
IF                :   'if';
THEN              :   'then';
ELSE              :   'else';
ELSE_IF           :   'else if';
END_IF            :   'end if';
DECLARE : 'declare';
SET : 'set';
TO : 'to';
SHOW : 'show';
ID : [a-zA-Z] [a-zA-Z0-9_]*;
NUMBER : ('+' | '-')? [0-9]+ ('.' [0-9]+)?;
STRING : '"' ( '\\' . | ~[\\"] )* '"' | '\'' ( '\\' . | ~[\\'] )* '\'' ;
INPUT  : 'input';
MUL : '*';
DIV : '/';
MODULO : 'remind';
POW    : '^';
PLUS : '+';
MINUS : '-';
SEMICOLON : ';';
LPAREN : '(';
RPAREN : ')';
AND : 'and';
OR : 'or';
NOT : 'not';
LESS_THAN         :   '<';
LESS_THAN_EQUAL   :   '<=';
GREATER_THAN      :   '>';
GREATER_THAN_EQUAL:   '>=';
EQUAL             :   '==';
NOT_EQUAL         :   '!=';
NEWLINE : '\r'? '\n';
WS : [ \t\n\r]+ -> skip;

// Parser rule
program : statement_list* | EOF;

statement_list : statement (NEWLINE|SEMICOLON)*;

statement : if_statement
            |declare_statement 
            |set_statement
            |input_statement
            |print_statement
            ;

// Declaration statement
if_statement : IF expression THEN statement_list (elseif_statement)* (ELSE statement_list)? END_IF;
elseif_statement : ELSE_IF expression THEN statement_list;

declare_statement : DECLARE ID;
set_statement : (SET ID  | ID) TO expression | value | comparison;

input_statement : (SET ID | ID) TO INPUT LPAREN expression RPAREN;
print_statement : SHOW (LPAREN expression RPAREN | STRING);

expression: logicalOr;

logicalOr: logicalAnd (OR logicalAnd)*;

logicalAnd: equality (AND equality)*;

comparison: equality ((GREATER_THAN | LESS_THAN |  GREATER_THAN_EQUAL | LESS_THAN_EQUAL) equality)*;

equality: term ((EQUAL | NOT_EQUAL) term)*;

term: factor ((PLUS | MINUS) factor)*;

factor: power ((MUL | DIV | MODULO) power)*;
power: value ('^' value)*;
value: NUMBER | STRING | ID;[/code]

I am using Intellij Idea to verify the parse tree, it now indicating 'then' keyword is expecting, and when i went through the parse tree, it classifying `AND` and OR as `ID` also else part of if is not in the tree. Indicating LESS_THAN is expected.

### Here is source i tried the grammar with

declare x
set x to 10
declare y
set y to 20
declare z
set z to x + y * 2
if x < y and y >= z or x == y then
  show("x is less than y and y is greater than or equal to z, or x is not equal to y")
else
  show("none of the above")
end if

Below is the output Tree with error and logical error
![Ask](https://user-images.githubusercontent.com/24245211/223677562-21e54da2-8ab2-42e1-82d8-6879efd89ba1.png)
![Ask](https://user-images.githubusercontent.com/24245211/223677618-9b61a349-9714-47d6-94a4-23b6672a1f08.png)

Thank you.

If possible, i need a grammar that will do what intended and cause of the problem and solution. Please help.

**Comment by kaby76** [comment]
This is best in StackOverflow.com. It has nothing to do with a grammar in grammars-v4.

But, Antlr does not have "parser-aware tokenization". Make sure all "keywords" are before the rule for `ID`. And, you have to add a rule that accepts keywords in expressions.

```
value: NUMBER | STRING | identifier;
identifier: ID | IF | THEN | ELSE | ..................... ;
```

This is how it's done in many grammars here in this repo. For example, [java](https://github.com/antlr/grammars-v4/blob/66d2951f338139da3497189d9391246a117d12e9/java/java/JavaParser.g4#L461).

**Comment by Dangujba** [comment]
Thank you very much Sir. One more question, is it a good practice to do something like this?

```expression       :
                  LPAREN expression RPAREN
                 | expression PLUS expression
                 | expression MINUS expression
                 | expression MUL expression
                 | expression DIV expression
                 | expression MODULO expression
                 | expression POW expression
                 | expression LESS_THAN expression
                 | expression LESS_THAN_EQUAL expression
                 | expression GREATER_THAN expression
                 | expression GREATER_THAN_EQUAL expression
                 | expression EQUAL expression
                 | expression NOT_EQUAL expression
                 | expression AND expression
                 | expression OR expression
                 | NOT expression
                 |STRING
                 | NUMBER
                 | ID
                 ;```

If not help me with example or how break them down. But this one seems to work, because i tried breaking it down many time having errors.

**Comment by kaby76** [comment]
Probably not the best. You should group the operators according to precedence. Check out how it's done in [java](https://github.com/antlr/grammars-v4/blob/66d2951f338139da3497189d9391246a117d12e9/java/java/JavaParser.g4#L609). You can use the lexer symbols as you have right now, or you can use the string literals. If you use string literals, try to keep the lexer rules for those operators because if you decide to split the grammar, it comes in handy to have them defined.

**Comment by Dangujba** [comment]
Okay If i get you right, instead of `expression MUL expression` | `expression DIV expression`. I can simply group them using bracket like in the java, `expression (MUL | DIV | MODULO) expression` since they have same precedence? Right?

Thank you.

**Comment by kaby76** [comment]
Yes. But, make sure the `| expression (PLUS | MINUS) expresion` alt occurs after the `| expression (MUL | DIV | MODULO) expression` alt, and so on with the other operators you may want to define. That way the parse orders `1*2+3*4` as though it was written `(1*2) + (3*4)`, not `1*(2+3)*4` or some other way.

**Comment by KvanTTT** [comment]
> But, Antlr does not have "parser-aware tokenization". Make sure all "keywords" are before the rule for ID. And, you have to add a rule that accepts keywords in expressions.

Yes, Antlr does not. Because of this feature absense, we have problems especially with SQL grammars that contain a lot of tokens. Related issue: https://github.com/antlr/antlr4/issues/1965

**Comment by KvanTTT** [comment]
I'm closing the issue because it doesn't relate to any grammar.
