### ISSUE TITLE
kotlin - class parameters parse error

### ISSUE THREAD

**Issue by mlorek** [antlr/grammars-v4#3210]
optional trailing comma in hte class contructor parameters fails to parse.
```
class C1(
    val a: Int?,
    val b: Int?,
)
```

**Comment by KvanTTT** [comment]
Please use respective language while code snippet posting (see also [Creating and highlighting code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting)):

```md
```kt
```
