### ISSUE TITLE
tsql: column names in INSERT are being parsed as table hints

### ISSUE THREAD

**Issue by scotture** [antlr/grammars-v4#322]
In the grammar for the INSERT statement, there is:

```
  with_table_hints?
  ('(' column_name_list ')')?
```

The problem here is that in `with_table_hints`, the WITH is optional. When I try to parse the following:

```
INSERT INTO Products (ProductName) SELECT * FROM Products
```

it is trying to interpret the (ProductName) as a table hint instead of the list of columns. According to https://msdn.microsoft.com/en-us/library/ms174335.aspx the WITH is not optional for the table hints in an insert statement. I am debating what the best way to fix this is. Some options:
1. Duplicate `with_table_hints` into two versions, one with a mandatory WITH and one without.
2. Create a sub-rule inside `with_table_hints` that only has the hints themselves, and then the INSERT statement can specify the WITH itself.
3. Remove the WITH from `with_table_hints` and make all callers specify it themselves.

All of these are breaking changes, so I don't want to make them unilaterally. Any suggestions?

**Comment by KvanTTT** [comment]
If ```WITH``` keyword required only for insert statement I think the first option is the best. Something like ```insert_with_table_hints```.

**Comment by scotture** [comment]
Ok, I will make that change.

**Comment by Marti2203** [comment]
Is this done?

**Comment by scotture** [comment]
@Marti2203 Yes, this was fixed by https://github.com/antlr/grammars-v4/commit/2f4b16df2e16c94384d947f9ff4f042f3770a6ff
