### ISSUE TITLE
I hope to support Informix sql syntax

### ISSUE THREAD

**Issue by hellozrh** [antlr/grammars-v4#3245]
I hope to support Informix sql syntax。

**Comment by bkiers** [comment]
Seems to be present already: https://github.com/antlr/grammars-v4/tree/master/informix

**Comment by hellozrh** [comment]
> 
What I need is  Informix database dialect of the SQL language, see as
https://www.ibm.com/docs/en/informix-servers/14.10?topic=programming-guide-sql-syntax

**Comment by bkiers** [comment]
Ah, right, indeed the `informix` grammar I linked to seems to be something else than SQL... :)

**Comment by KvanTTT** [comment]
The grammar exists and I guess we can close the issue.

**Comment by hellozrh** [comment]
> The grammar exists and I guess we can close the issue.

Yes, I agree with you. The next we just need to improve it bit by bit  .
