### ISSUE TITLE
In Java/Java grammar record members of interfaces are parsed as class-types

### ISSUE THREAD

**Issue by DagSonntag** [antlr/grammars-v4#3268]
Hi
I noticed an incorrect parsing of record members of Interface types as follows:

```java
public class RecordsTesting {

    interface InnerInterface{
        record PoolKey(Name name, BsmKey bsmKey, Object dynamicType) {}
    }
}
```

Currently the record keyword is parsed as a type, not as a keyword. This problem used to occur for normal MemberDeclarations as well, but was fixed some time back, however the fix was never done for interfaces. So here is the issue for it, merge request coming shortly

**Comment by DagSonntag** [comment]
I suggest we also close #2685 with this fix since it was solved in the previous fix for normal MemberDeclarations and works by now.

**Comment by mlorek** [comment]
which grammar?

**Comment by mlorek** [comment]
![image](https://user-images.githubusercontent.com/7452353/225707368-1c391d73-8d5e-43ce-8aa8-3240c693fc0e.png)
