### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by ooxi** [antlr/grammars-v4#329]
Hi,

please publish your artefacts to maven central. Or is there another repository where I can get the binaries from?

-- ooxi

**Comment by parrt** [comment]
what artifacts? you mean every single generated parser object?

**Comment by wwn** [comment]
Sure he means to include the plugin easaly in pom.

**Comment by ooxi** [comment]
While I don't think it would be unreasonable to publish the generated parsers, publishing the grammar resources would be sufficient.

On the other hand, publishing generated parsers would prevent them from becoming uncompilable. For example the [C# lexer](https://github.com/antlr/grammars-v4/blob/master/csharp/CSharpLexer.g4) contains [C# literals](https://github.com/antlr/grammars-v4/blob/master/csharp/CSharpLexer.g4#L7) which result in a compilation failure when trying to generate a Java parser.

**Comment by ooxi** [comment]
So, no publication planned?

**Comment by parrt** [comment]
hiya. I don't plan on publishing the repo specific test rig nor generated parsers for the grammars. I just don't see the need.

**Comment by ooxi** [comment]
:-( ok than
