### ISSUE TITLE
[PlSql] Cannot parse JSON_OBJECT function

### ISSUE THREAD

**Issue by jiangtao69039** [antlr/grammars-v4#3293]
```sql
SELECT JSON_OBJECT(KEY 'VALUE' VALUE COL) * FROM T;
``` 

Other JSON functions have the same problem. JSON_ARRAY/JSON_ARRAYAGG/JSON_OBJECTAGG...

![image](https://user-images.githubusercontent.com/20572131/226776339-ea791eef-1b28-4a4a-95b1-b2b715abfd34.png)

**Comment by hellozrh** [comment]
> ```sql
> SELECT JSON_OBJECT(KEY 'VALUE' VALUE COL) * FROM T;
> ```
missing semicolon，it should be :
```sql
SELECT JSON_OBJECT(KEY 'VALUE' VALUE COL) , * FROM T;
 ```

**Comment by hellozrh** [comment]
> missing semicolon，it should be :
> 
> ```sql
> SELECT JSON_OBJECT(KEY 'VALUE' VALUE COL) , * FROM T;
> ```

Sorry, I checked this sql with PL/SQL，it's prompted syntax exception. 

The correct syntax is
```sql
SELECT JSON_OBJECT(KEY 'VALUE' VALUE COL), t.*  FROM T t;
```
