### ISSUE TITLE
 Some grammars in PostgreSQLParser.g4 may be incorrect

### ISSUE THREAD

**Issue by hellozrh** [antlr/grammars-v4#3294]
Here are a few examples

1. The current content is as follows

![image](https://user-images.githubusercontent.com/12250931/226863372-66d169ca-b721-43b4-9d80-a83082cf0ca5.png)
mabe it shoud be like this
```sql
createrolestmt
   : CREATE ROLE roleid opt_with? optrolelist
   ;

opt_with
   : WITH
   ;
```

 2.The current content is as follows

![image](https://user-images.githubusercontent.com/12250931/226864277-14343bee-3a21-4e3d-91b3-f0f4130ccc16.png)
mabe it shoud be like this
```sql
opt_in_database
   : IN_P DATABASE name
   ;

alterrolesetstmt
   : ALTER (ROLE | USER) ALL? rolespec opt_in_database? setresetclause
   ;
```

There are many others like this。

**Comment by bkiers** [comment]
Note that:

```
opt_with
   : WITH
   //| WITH_LA
   | /* match nothing */
   ;
```

already matches nothing.

In other words, this:

```
foo : T1 opt_with T2;
```

is the same as:

```
foo : T1 with? T2;
with : WITH;
```

**Comment by hellozrh** [comment]
> 

When I used the plsql grammar parser, I  didn't find such a way like this, so I thought it wasn't allowed.
Now, I know it, Thank you .
