### ISSUE TITLE
[TSQL] Cannot parse "raw" as ID

### ISSUE THREAD

**Issue by svengiegerich** [antlr/grammars-v4#3300]
**What happened:**
I want to be able to create objects called "raw".
However, as there is an own lexer rule `RAW` that appears before the generic `ID` the token is not recognized as such.

**Expected:** I want to parse for example,
- `CREATE DATABASE raw`
- `CREATE SCHEMA raw`
- `CREATE TABLE raw`
- `SELECT * FROM raw`
- ...

(Using brackets, a la `[raw]`, works)

**Actual:** Parsing fails 

---

I can confirm that moving lexer rule `RAW` after `ID` solves it.
 
❓ However, given the complexity of the grammar, I am uncertain whether this is the best fix here? 
As most likely the ordering issue applies to other ID names besides "raw" as well...

---

<img width="197" alt="image" src="https://user-images.githubusercontent.com/1476077/227707565-7270225e-829c-4e15-adfe-0aea9e5f8a7a.png">

**Comment by bkiers** [comment]
If the rule `keyword` includes the `RAW` token, it'd probably parse OK.
