### ISSUE TITLE
[MySql] Positive-Technologies Do you need to start supporting mysql8.0 syntax

### ISSUE THREAD

**Issue by caicancai** [antlr/grammars-v4#3354]

**Comment by caicancai** [comment]
@KvanTTT Excuse me，Can I start supporting mysql8.0 grammars at https://github.com/antlr/grammars-v4/tree/master/sql/mysql/Positive-Technologies

**Comment by KvanTTT** [comment]
Sure, I don't see any reason why not.

**Comment by caicancai** [comment]
Thank you, if possible, I also hope that I can improve the support of mysql8.0 syntax

**Comment by whtblktone** [comment]
> Thank you, if possible, I also hope that I can improve the support of mysql8.0 syntax

Excuse me, When will it be ready ?

**Comment by caicancai** [comment]
@whtblktone hello, now the keyword support for mysql8.0 is relatively complete, and the compatibility can reach 90%. Due to the busy work recently, this part of the work has not been carried out, but this part of the work is not difficult
