### ISSUE TITLE
Antlr4 Grammer for Fortran 90/95

### ISSUE THREAD

**Issue by AkhilAkkapelli** [antlr/grammars-v4#3399]
Can someone add a Antlr4 grammar for Fortran 90/95 or any above version of Fortran to the repository as I am seeking it?

**Comment by kaby76** [comment]
As noted in the [antlr-discussion thread](https://groups.google.com/g/antlr-discussion/c/CSjpelzgRX0), there are two grammars written, but neither have been submitted by the authors to the repo. The best would be to just scrape the grammar (by automated means) from the [Spec](https://www.iso.org/standard/17366.html), but that costs a lot of money.
* https://github.com/OpenFortranProject/open-fortran-parser. There's no grammar labeled with "90", and no clear cut segregation of the different grammars to know how this is supposed to be organized.
* https://github.com/cyrillemidingoyi/PyCropML/blob/master/src/pycropml/transpiler/antlr_py/grammars/Fortran90Parser.g4; https://github.com/cyrillemidingoyi/PyCropML/blob/master/src/pycropml/transpiler/antlr_py/grammars/Fortran90Lexer.g4.

**Comment by AkhilAkkapelli** [comment]
@kaby76  Thank you for taking the time to respond to my email and offer some suggestions for finding the Lexer and Parser grammar for Fortran 90/95 using Antlr4.

I appreciate the links you have provided to the two grammars written. I will take a closer look at these and see if they meet the requirements of my project and see if they are helpful for my project.

Best regards
Akhil

**Comment by kaby76** [comment]
Please reopen. This is a "to do" item. Fortran version 90 and all the many others need to be added.
