### ISSUE TITLE
Errors in XPath

### ISSUE THREAD

**Issue by slavonnet** [antlr/grammars-v4#3402]
https://github.com/antlr/grammars-v4/blob/494877cd60faf13342fbb5ba1d7e76534b61a895/xpath/xpath31/XPath31.g4#LL341C32-L341C32

inn  spec  double quote for {EscapeApos }and ` [^']` in regexp
in file one quote '`\'` and  regexp dows not gave NOT `[']`

```
[116]   	StringLiteral	   ::=   	('"' (EscapeQuot | [^"])* '"') | ("'" (EscapeApos | [^'])* "'")	/* ws: explicit */
[119]   	EscapeQuot	   ::=   	'""'	
[120]   	EscapeApos	   ::=   	"''"
```

**Comment by kaby76** [comment]
You're right. Looks like I forgot to roll some of the changes from [my latest grammar files](https://github.com/kaby76/Domemtech.Trash/blob/8b1b04f8f06dd25481e6af8070b3b1831db980a7/src/ParseTreeEditing/org/eclipse/wst/xml/xpath2/processor/internal/XPath31Lexer.g4#L119) into this repo. The grammar needs to be split,too.
