### ISSUE TITLE
[Java] Complicated rules `creator` and `arrayCreatorRest`

### ISSUE THREAD

**Issue by neNerower** [antlr/grammars-v4#3429]
Rules `creator` and `arrayCreatorRest` at [Java parser](https://github.com/antlr/grammars-v4/blob/master/java/java/JavaParser.g4) looks complicated.
---

Now 'creator' rule looks like:
```antlr
creator
    : nonWildcardTypeArguments createdName classCreatorRest
    | createdName (arrayCreatorRest | classCreatorRest)
    ;
```
And it can be simplified with:
```antlr
creator
    : nonWildcardTypeArguments? createdName classCreatorRest
    | createdName arrayCreatorRest
    ;
```

----
The same situation with `arrayCreatorRest` rule:
```antlr
arrayCreatorRest
    : '[' (']' ('[' ']')* arrayInitializer | expression ']' ('[' expression ']')* ('[' ']')*)
    ;
```
Can be simplified with:
```antlr
arrayCreatorRest
    : ('[' ']')+ arrayInitializer
    | ('[' expression ']')+ ('[' ']')*
    ;
```

---
Is there any reason preventing to simplify the rules ?

**Comment by KvanTTT** [comment]
If it can be simplified in the following way:

```java
creator
    : nonWildcardTypeArguments? createdName classCreatorRest
    | createdName arrayCreatorRest
    ;
```

It can be simplified further:

```java
creator
    : nonWildcardTypeArguments? createdName classCreatorRest
    ;
```

> Is there any reason preventing to simplify the rules ?

I'm not sure about reasons but if you consider these simplications doesn't controverse official Java specification I suggest making as you suggested.

**Comment by neNerower** [comment]
@KvanTTT 
These changes don't affect the meaning of the rules, but only simplify their perception.
So, simplifications won't lead to a Java specification contradiction.
