### ISSUE TITLE
C grammar: blockItem production recognise function call as declaration

### ISSUE THREAD

**Issue by liscju** [antlr/grammars-v4#348]
blockItem production:

```
blockItem
    :   declaration
    |   statement
    ;
```

parses 

``` C
setbuf(stderr);
```

as declaration instead of statement, i don't know what to do with it especially because it can be variable declaration as well like:

```
int(w);
```

Maybe You have any suggestions?

**Comment by parrt** [comment]
yeah, w/o a symbol table I think we can't tell. :(

**Comment by Marti2203** [comment]
I think this can be closed?
