### ISSUE TITLE
PCRE grammar: support for options in non-capturing subpatterns

### ISSUE THREAD

**Issue by jtschichold** [antlr/grammars-v4#357]
According to http://www.pcre.org/pcre.txt you can use a shorthand to enable options in non-capturing subpatterns, like:

`(?i:saturday|sunday) `

This is not supported by the current PCRE grammar, a new alternative should be added to the non_capture rule:

```
non_capture:
[... existing alternatives ...]
 | '(' '?' option_flags ':' alternation ')'
 ;
```

**Comment by teverett** [comment]
I could make this change.  Could you supply me a couple examples, including one that has this alternate syntax?

**Comment by jtschichold** [comment]
2 simple examples coming from PCRE site:
`(?:(?i)saturday|sunday)`
`(?i:saturday|sunday)`

The two patterns match exactly the same strings. In the first pattern you have a non-capturing group with explicit options, in the second pattern the shorthand is used.

**Comment by teverett** [comment]
I think we can close this now please.
