### ISSUE TITLE
[cpp] the new transformGrammar scripts are not exception safe

### ISSUE THREAD

**Issue by pasto9** [antlr/grammars-v4#3630]
I noticed that the file io of the new transformGrammar scripts added in #3619 are not exception safe. In python you can handel that with context managers.

I'm proposing using a context manager for the file io, removing the unused import statements and using regEx for finding and replacing the strings. My Version can be found in pr

**Comment by kaby76** [comment]
https://github.com/antlr/grammars-v4/pull/3631 Close?
