### ISSUE TITLE
[pcre] parse of octal is wrong

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#3687]
According to [this](https://stackoverflow.com/questions/77023896/i-cant-trigger-antlr-rule/77033683#77033683), the priority of `backreference` should be moved to the top in order to parse octal literals correctly.

_Note, in my opinion, I don't think the suggested fix is correct. The problem is that the grammar is ambiguous. Just because Antlr4 allows you to fix ambiguity by alt reordering does not mean you should._

_There's an extra level of complexity with the rule `atom` with the addition of "shared_literal", "shared_atom", "literal", etc. The result is that ambiguity._

_I would have kept atom flat with respect to the "shared" rules, i.e., unfold these rules into "atom" then remove the ambiguity--and not by reordering the alts._

**Comment by bkiers** [comment]
This can be closed since the grammar has been updated (and the issue was also resolved along the way): https://github.com/antlr/grammars-v4/pull/3690

**Comment by kaby76** [comment]
This will be fixed with merge of https://github.com/antlr/grammars-v4/pull/3690.
