### ISSUE TITLE
Java grammar: enumConstantName in switchLabel not used?

### ISSUE THREAD

**Issue by Gottox** [antlr/grammars-v4#371]
```antlr
switchLabel
    :   'case' constantExpression ':'
    |   'case' enumConstantName ':'
    |   'default' ':'
    ;
```

I suspect, that the `'case' enumConstantName ':'` case is never used.

enumConstantName can only consist of an Identifier, but constantExpression can consist of an identifier through `constantExpression` -> `expression` -> `primary` -> `Identifier` too. So the second case is never used.

**Comment by parrt** [comment]
good point. is this Java.g4 or Java8.g4?

**Comment by Gottox** [comment]
oh sorry, Java.g4

**Comment by Marti2203** [comment]
Is this still a valid issue?

**Comment by KvanTTT** [comment]
I don't think so. `switchLabel` now looks like this (https://github.com/antlr/grammars-v4/blob/master/java/java/JavaParser.g4#L433-L436):

```antlr
switchLabel
    : CASE (constantExpression=expression | enumConstantName=IDENTIFIER) ':'
    | DEFAULT ':'
    ;
```
