### ISSUE TITLE
JavaScript parser out of range exception

### ISSUE THREAD

**Issue by TimurBinogerov** [antlr/grammars-v4#3728]
I use antlr4 to parse JavaScript expressions in C# app. I've encountered out of range exception during parsing something like "``` (||```". It occurs in `JavaScriptParserBase.cs` `lineTerminatorAhead()` method. I assume there is missprint in decrement Token index by 2 (instead of 1) or shoud be range check.

**Comment by kaby76** [comment]
Note: For input `(||`, the parser crashes on all targets (CSharp, Go, Java, JavaScript) except Python3. The base class code for each target is supposed to be direct translations of each other, so they should all function exactly the same, but they don't. But, the parsers should not crash.

**Comment by kaby76** [comment]
This code should test whether [possibleIndexEosToken](https://github.com/antlr/grammars-v4/blob/18d8d8962f2876f555105042901b39d210c746e9/javascript/javascript/CSharp/JavaScriptParserBase.cs#L93) is less than zero, and return false if so.

For Python3, [the base class code looks like this](https://github.com/antlr/grammars-v4/blob/18d8d8962f2876f555105042901b39d210c746e9/javascript/javascript/Python3/JavaScriptParserBase.py#L59-L60). However, it looks like the Python3 target is wrong. It *must* check whether the index is out of range, [but it does not do so](https://github.com/antlr/antlr4/blob/0eb38a02d7aa67147bdba23287501d4e5540dfc1/runtime/Python3/src/antlr4/BufferedTokenStream.py#L80-L81)! For a comparison, see [CSharp](https://github.com/antlr/antlr4/blob/0eb38a02d7aa67147bdba23287501d4e5540dfc1/runtime/CSharp/src/BufferedTokenStream.cs#L257-L261) or [Java](https://github.com/antlr/antlr4/blob/0eb38a02d7aa67147bdba23287501d4e5540dfc1/runtime/Java/src/org/antlr/v4/runtime/BufferedTokenStream.java#L185-L188).

**Comment by kaby76** [comment]
https://github.com/antlr/antlr4/issues/4427

**Comment by kaby76** [comment]
This has been fixed.
