### ISSUE TITLE
Code is too large in try statement after xtext generation

### ISSUE THREAD

**Issue by sohaibhamioud** [antlr/grammars-v4#3742]
Hi,
I am using xtext with a mysql antlr grammar to generate java code. When I use Antlrworks to debug the grammar I get the code too large in try statement error. I tried using sql keywords as rules and as terminals but ended up with a java heap error. I tried to split the grammar but with no success. Should I use keywords as rules or as terminals in the grammar? What should I do with the big set of keywords alternatives to solve this issue (a|b|c|...) ?

**Comment by kaby76** [comment]
This repo has nothing to do with the tools and grammars for Antlr3, nor XText. XText generates Antlr3 grammars from XText grammars. And, there is no conversion tool to go from Antlr4 to XText syntax.

**Comment by sohaibhamioud** [comment]
> This repo has nothing to do with the tools and grammars for Antlr3, nor XText. XText generates Antlr3 grammars from XText grammars. And, there is no conversion tool to go from Antlr4 to XText syntax.

Thank you for your reply. I though since xtext is based on antlr and since this issue of java heap and "code is too large in try statement" is relate to antlr based large grammars, the solution would be similar. Thank you anyway.
