### ISSUE TITLE
[lua] clean up

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#3743]
Looks like the lua grammar needs some clean up.
* Add a readme so people can maintain this code.
* Add tests. Lua has a nice set of tests as a download and in the github mirror. We just need to add them. https://www.lua.org/tests/
* Bugs: https://github.com/antlr/grammars-v4/issues/3741 https://github.com/antlr/grammars-v4/issues/3724 https://github.com/antlr/grammars-v4/issues/3652 https://github.com/antlr/grammars-v4/issues/3311 https://github.com/antlr/grammars-v4/issues/1824

**Comment by Dongyang0810** [comment]
my mistake, the #3724 issue occurred during parsing of Lua 5.1.4, and the behavior under Lua 5.4 is consistent with the Lua source code parsing
