### ISSUE TITLE
PL/SQL LISTAGG delimiter is too stict

### ISSUE THREAD

**Issue by danlyons-softek** [antlr/grammars-v4#3821]
The current `LISTAGG` definition limits the delimiter to `CHAR_STRING`:
https://github.com/antlr/grammars-v4/blob/d939aad7310b6a214d6ade30afc90eb28f9fe809/sql/plsql/PlSqlParser.g4#L6377-L6378

While unfortunately, the [Oracle documentation for LISTAGG](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/LISTAGG.html) is not clear about what's allowed for `delimiter`, it appears expansive enough that `CHR` functions with literals, parentheses, and concatenation are all allowed, e.g.:
```sql
SELECT
    terminal
    , LISTAGG(sid, (',' || CHR(13) || CHR(10))) WITHIN GROUP (ORDER BY sid) AS sids
FROM v$session
GROUP BY
    terminal
```
Even against an ancient, 11.2.0.2 instance, this successfully produces groups of terminals with SIDs delimited by commas and CRLF, e.g.,:

TERMINAL|SIDS
|:---|:---|
DRUID|50,<br/>56
THOR|43,<br/>69

**Comment by danlyons-softek** [comment]
In my local project, I resolved my immediate issue by adding the following:
```
delimiter
    : CHAR_STRING
    | CHR '(' UNSIGNED_INTEGER ')'
    | delimiter BAR BAR delimiter
    | '(' delimiter ')'
    ;
```
and changing `LISTAGG` to the following:
```
LISTAGG '(' (ALL | DISTINCT | UNIQUE)? argument (',' delimiter)? listagg_overflow_clause? ')'
```

I'm not _completely_ confident that's correct, though as I didn't do exhaustive testing with it, and I wish I had a more authoritative answer on what `delimiter` was.

**Comment by ViperDave** [comment]
According to the Oracle documentation for LISTAGG found here https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/LISTAGG.html the syntax should be:

```
LISTAGG '(' (ALL | DISTINCT)? measure_expr ( ',' '\'' delimiter '\'' )? listagg_overflow_clause? ')' (WITHIN GROUP '(' order_by_clause ')' )? (OVER '(' query_partition_clause? ')' )?
```

Obviously, this is missing the UNIQUE token, and indicates that the delimiter must be inside single quotes, but as @danlyons-softek indicated, that is simply not true and is easy enough to test.

The documentation goes on to say:

> "If measure_expr is of type RAW, then the delimiter must be of type RAW. You can achieve this by specifying the delimiter as a character string that can be implicitly converted to RAW, or by explicitly converting the delimiter to RAW, for example, using the UTL_RAW.CAST_TO_RAW function."

Ultimately the delimiter rule needs to account for literal strings, or any function that can result in a character string.  I don't think that this parser and lexer should include rules and tokens for other external packages such as UTL_RAW.

```
delimiter
   : CHAR_STRING
   | delimiter BAR BAR delimiter
   | '(' delimiter ')'
   | string_function
   ;
```
`string_function` is already defined within the parser, but the definition is not complete:
```
string_function
    : SUBSTR '(' expression ',' expression (',' expression)? ')'
    | TO_CHAR '(' (table_element | standard_function | expression) (',' quoted_string)? (
        ',' quoted_string
    )? ')'
    | DECODE '(' expressions ')'
    | CHR '(' concatenation USING NCHAR_CS ')'
    | NVL '(' expression ',' expression ')'
    | TRIM '(' ((LEADING | TRAILING | BOTH)? expression? FROM)? concatenation ')'
    | TO_DATE '(' (table_element | standard_function | expression) (
        DEFAULT concatenation ON CONVERSION ERROR
    )? (',' quoted_string (',' quoted_string)?)? ')'
    ;
```
There are several other string functions such as `LTRIM` `INSTR` `UPPER` and `LOWER` etc. that need to be included in the `string_function` definition.
