### ISSUE TITLE
Question about creating a Drools.g4 grammar

### ISSUE THREAD

**Issue by gizmochief7** [antlr/grammars-v4#383]
What would the difficulty level be converting this DroolsRule.g grammar to a g4 grammar? if not too difficult, would it be possible for a member of your community to work on it? Drools is a rule engine. 
http://www.drools.org/

I found a Drools g file here: https://github.com/bdamer/drools-netbeans-plugin/blob/master/src/com/afqa123/drools/grammar/DroolsRule.g

Here is a text version of it:
[DroolsRule.txt](https://github.com/antlr/grammars-v4/files/273568/DroolsRule.txt)

Thanks for your time.

**Comment by teverett** [comment]
A better place to start would be with these Antlr3 grammars from the drools tree:

https://github.com/droolsjbpm/drools/tree/master/drools-compiler/src/main/resources/org/drools/compiler/lang
