### ISSUE TITLE
additional issue with formatting

### ISSUE THREAD

**Issue by teverett** [antlr/grammars-v4#3863]
In the grammar "turing", in the rule "forstatement"

```
forStatement
    : ('for' id_ ':' expn '..' expn ('by' expn)? declarationsAndStatements 'end' 'for')
    | (
        'for' 'decreasing' id_ ':' expn '..' expn ('by' expn)? declarationsAndStatements 'end' 'for'
    )
    ;

```

**Comment by mike-lischke** [comment]
What's the problem here? The wrapping of the second alt over 3 lines? There will always be borderline cases like this: unwrapped the line is 100 chars wide. Auto wrapping starts at 2/3 of the set column width, which is 150, so this alt was formatted as multi line case. You could increase the column width, but then there will certainly be other cases.

**Comment by KvanTTT** [comment]
I don't see a problem. Also, I'd like to mention that top-level parentheses are excess.

**Comment by mike-lischke** [comment]
Right, and without top level parens this alt would perfectly fit on one line. But it's not the task of the formatter to remove them.

**Comment by teverett** [comment]
> @teverett Do you see any need for action here?

Nope, thanks for the explanation

**Comment by teverett** [comment]
> Right, and without top level parens this alt would perfectly fit on one line. But it's not the task of the formatter to remove them.

@mike-lischke could such fixes be added to the formatter?

**Comment by KvanTTT** [comment]
It's not a responsibility of formatter, indeed. It's a responsibility of another tool, kind of simplifier.

**Comment by mike-lischke** [comment]
... or grammar linter

**Comment by kaby76** [comment]
The build already checks for excess parentheses, including [turing](https://github.com/antlr/grammars-v4/actions/runs/7034622792/job/19143097560#step:21:6647). [It's one of many scripts that implement "lint" for Antlr grammars.](https://github.com/kaby76/g4-scripts) Github Actions don't have a "warning" state, only "success" or "failure", so unless someone checks the output, it goes unnoticed.
