### ISSUE TITLE
[build] Reformatter not reaching a fixed point, removed information

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#3895]
@mike-lischke 

This is a problem with the recently added antlr-format. The tool has a bug in reaching a fixed point (i.e., if I take version "before" which is outputed by the tool and rerun the tool on it, the tool should return exactly the same file). In addition it removed a comment that should not have been removed. It's essential that the antlr-format tool outputs a format that reliably follows the coding standard.

Here are four successive versions of PlSqlLexer.g4, the first version the initial. With the second through fourth versions, the `START_CMD` rule was changed by antlr-format, each time to a different format.

1) Version [7fbb97b](https://github.com/antlr/grammars-v4/commit/7fbb97b1ec4792dd936aba0ccb491965ff8c5cad), committed 4 months ago.

2) Version [7535367](https://github.com/antlr/grammars-v4/commit/753536777d827ccc0c9b108531ea67375c2039ac), committed 3 weeks ago. This file is the 1st reformat using antlr-format, which was part of the PR to [reformatted all the grammars](https://github.com/antlr/grammars-v4/pull/3843).

3) Version [f083ee2](https://github.com/antlr/grammars-v4/commit/f083ee2609e7fc316bcace68a238b4035a9a57a4). This file is the 2nd reformat using antlr-format, associated with [my PR to perform "auto reformat"](https://github.com/antlr/grammars-v4/pull/3875).

4) Version [be1d809](https://github.com/antlr/grammars-v4/commit/be1d8094a3497491dc8888361c5464f212e607bc). This file is the 3rd reformat using antlr-format, committed 12 hours ago, and associated with [a PR to modify PlSql](https://github.com/antlr/grammars-v4/pull/3893).

Each version of the file was altered only by the tool.

Starting with the 1st version of START_CMD:

https://github.com/antlr/grammars-v4/blob/7fbb97b1ec4792dd936aba0ccb491965ff8c5cad/sql/plsql/PlSqlLexer.g4#L2457-L2463

After 1st application of antlr-format:

https://github.com/antlr/grammars-v4/blob/753536777d827ccc0c9b108531ea67375c2039ac/sql/plsql/PlSqlLexer.g4#L2469-L2474

The 2nd application of antlr-format (from my PR) reformats it again.

https://github.com/antlr/grammars-v4/blob/f083ee2609e7fc316bcace68a238b4035a9a57a4/sql/plsql/PlSqlLexer.g4#L2469-L2473

Finally, the last PR applies antlr-format a third time, changing the rule again.

https://github.com/antlr/grammars-v4/blob/be1d8094a3497491dc8888361c5464f212e607bc/sql/plsql/PlSqlLexer.g4#L2469-L2472

### Analysis

The comment `//: 'STA' 'RT'? SPACE ~('\r' | '\n')* NEWLINE_EOF` was removed by antlr-format on the 2nd application of antlr-format. *The formatter should not be removing information.*

Of the 16 grammar files that were reformatted with my PR. https://github.com/antlr/grammars-v4/commit/f083ee2609e7fc316bcace68a238b4035a9a57a4 https://github.com/antlr/grammars-v4/actions/runs/7242750577/job/19728583870#step:6:11 , most seem to be minor changes. But, the formatter should output a fixed point version of the grammar on first try. Otherwise I will have to repeat the application until it a fixed point is achieved. 

I wrote a script to repeatably apply antlr-format until a fixed point is achieved.
```
#

rm -rf foo
mkdir foo
pushd foo
cp ../PlSqlLexer.g4.7fbb97b PlSqlLexer.g4
i=1
while :
do
	echo Iteration $i
	cp PlSqlLexer.g4 PlSqlLexer.g4.before
	cp PlSqlLexer.g4 PlSqlLexer.g4.after
	dos2unix *.g4
	antlr-format PlSqlLexer.g4.after 2>&1 1> /dev/null
	dos2unix *.g4
	diff PlSqlLexer.g4.before PlSqlLexer.g4.after
	if [ $? -ne 0 ]
	then
		echo No fixed point yet.
	else
		echo Fixed point achieved.
		break
	fi
	cp PlSqlLexer.g4.after PlSqlLexer.g4
	i=`expr $i + 1`
done
```

We don't see the fixed point achieved for PlSqlLexer.g4 until 5 applications of antlr-format.
[out.txt](https://github.com/antlr/grammars-v4/files/13709663/out.txt)

What is more troubling is whether there is a grammar (or many) that has (have) no fixed point at all. In this case the tool always produces a new version ad infinitum.

**Comment by mike-lischke** [comment]
Odd behaviour indeed. Can you move that issue to the [antlr-format](https://github.com/mike-lischke/antlr-format) repository? I'll take a look as soon as I can.

**Comment by kaby76** [comment]
Moved to https://github.com/mike-lischke/antlr-format/issues/2. Closing this Issue.
