### ISSUE TITLE
VBA Line Continuation example

### ISSUE THREAD

**Issue by Beakerboy** [antlr/grammars-v4#3945]
An example file was added by @SSlinky some time ago. It contains a few With statements that include line continuation. I've tested some similar statements and they fail in MS VBA 7.1:
If i create a module that contains a function:

```
Function foo(B As Range)
    With B _
        .ID = "2"
    End With
    foo = B.ID
End Function
```
I receive an error: "With object must be user-defined type, Object, or Variant"

There is the same error for:
```
Function foo(B As Range)
    With B. _
        ID = "2"
    End With
    foo = B.ID
End Function
```

Both of these examples are listed in example7linecontinuation.bas, and I feel they should be removed. Is there a way to specify a file as containing counter-examples, and must fail?

**Comment by Beakerboy** [comment]
I propose replaceing it with something like:
```
Function _
foo( _
B _
    As _
    Range _
    )
    With _
    B
        .ID _
        = _
        "2"
    End _
        With
    foo = B. _
        ID
End _
    Function
```

**Comment by SSlinky** [comment]
I know this has been closed, but for completeness, neither of those examples are in the file. Only the `With` opening and closing blocks are included, e.g.,

```vba
With A _
    .B
End With
```

Is equivalent to:

```vba
With A.B
End With
```

The ID property, and assigning values to it, were not part of the examples.

**Comment by Beakerboy** [comment]
I know, that’s why I closed it. I was messing around with all kinds of variations of line, continuation and line breaks and mixed up some of my comparisons.
