### ISSUE TITLE
[sql/plsql] Degradation of performance with recent changes

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#4014]
@lbovet @KvanTTT 

There have been changes to plsql that I suspect to impact performance. I wrote a [script](https://github.com/antlr/grammars-v4/files/14582374/c0.sh.txt) to track performance in the grammar over the last 8 relevant PRs. The script performs a grouped-parse of the 374 .sql input files for the grammar 10 times and computes the mean and standard deviation, taking care to make sure no new input files were tested in subsequent PRs, which would add to the length of the time of test and be misleading.. The results are shown in the figure below.

![times](https://github.com/antlr/grammars-v4/assets/11389451/e8852379-9aff-4f78-bd69-4ae46a75b650)
 
I have not done a t-test, but eyeballing the data suggest that the performance took a hit with #4003, which may be caused by a large "k" lookahead being introduced. I suggest investigating whether #4003 indeed caused a performance drop.

I wouldn't say it's a large drop in performance, but I have seen grammars with significant ambiguity or large k. It's sometimes hard to know whether a change causes a catastrophic performance drop given how Github Actions only returns "pass" or "fail".

I am planning to repeat the test with a larger repetition count in order to see if that affects the standard deviation. I also plan to perform an "individual" parse test (one test input file per one run of the test application) to see how the performance was affected.

I am planning to make a PR to test performance changes with a PR.

**Comment by kaby76** [comment]
Updated stats.

![times](https://github.com/antlr/grammars-v4/assets/11389451/17e866bd-f6e7-4c3d-a2e4-3bdc6daee293)

As I look at #4003, rules were added to enforce the type of the expression through syntax. This is something that is never done. Static semantics is enforced by a static analysis phase. Why was this added?

**Comment by lbovet** [comment]
So a solution would be to move `json_condition` as a `unary_logical_operation`. This would maybe make the grammar a bit too lax since this expression could be used in contexts where it is not allowed (not verified, just an assumption).
For me it would be ok. @KvanTTT, what do you think?

**Comment by kaby76** [comment]
The problem is that you added ambiguity to expressions because AND and OR operators are now in two rules for expressions. We now have two different ways to parse logical expressions from condition.

**Comment by lbovet** [comment]
Yes, I completely figure out the problem, now. I am quite new in the grammar area so I did it the naive way.
Working on a fix.
