### ISSUE TITLE
PL/SQL grammar cannot recognise identifiers that start with keywords

### ISSUE THREAD

**Issue by stephendrew** [antlr/grammars-v4#4028]
Target: C#
Grammar: PL/SQL

I am trying to parse parser.sql_script() for this:

```sql
CREATE OR REPLACE PACKAGE ACCESS_SECURITY AS
-- omitted
END;
```

But it fails due to treating ACCESS as a keyword.

```
Token: [@0,0:5='CREATE',<305>,1:0]
Token: [@1,6:6=' ',<2380>,channel=1,1:6]
Token: [@2,7:8='OR',<1237>,1:7]
Token: [@3,9:9=' ',<2380>,channel=1,1:9]
Token: [@4,10:16='REPLACE',<1484>,1:10]
Token: [@5,17:17=' ',<2380>,channel=1,1:17]
Token: [@6,18:24='PACKAGE',<1257>,1:18]
Token: [@7,25:25=' ',<2380>,channel=1,1:25]
Token: [@8,26:31='ACCESS',<4>,1:26]
Token: [@9,32:32='_',<2372>,1:32]
Token: [@10,33:40='SECURITY',<1563>,1:33]
Token: [@11,41:42='\r\n',<2380>,channel=1,1:41]
Token: [@12,43:44='AS',<67>,2:0]
```

```
Exception of type 'Antlr4.Runtime.NoViableAltException' was thrown.
OffendingToken: [@9,32:32='_',<2372>,1:32]
```

**Comment by kaby76** [comment]
This is not a "symbol conflict". It is a regression in the recognition of identifiers with underscore, introduced by @lbovet with https://github.com/antlr/grammars-v4/pull/4012.
```
$ ./bin/Debug/net8.0/Test.exe xxx.in -tokens
[@0,0:5='CREATE',<305>,1:0]
[@1,6:6=' ',<2380>,channel=1,1:6]
[@2,7:8='OR',<1237>,1:7]
[@3,9:9=' ',<2380>,channel=1,1:9]
[@4,10:16='REPLACE',<1484>,1:10]
[@5,17:17=' ',<2380>,channel=1,1:17]
[@6,18:24='PACKAGE',<1257>,1:18]
[@7,25:25=' ',<2380>,channel=1,1:25]
[@8,26:40='ACCESS_SECURITY',<2378>,1:26]
[@9,41:41=' ',<2380>,channel=1,1:41]
[@10,42:43='AS',<67>,1:42]
[@11,44:45='\r\n',<2380>,channel=1,1:44]
[@12,46:57='-- omitted\r\n',<2373>,channel=1,2:0]
[@13,58:60='END',<473>,3:0]
[@14,61:61=';',<2367>,3:3]
[@15,62:63='\r\n',<2380>,channel=1,3:4]
[@16,64:63='<EOF>',<-1>,4:0]

CSharp 0 xxx.in success 0.0849261
Total Time: 0.37991
03/25-06:43:58 ~/issues/g4-4028/sql/plsql/Generated-CSharp-full
```

The identifier `ACCESS_SECURITY` should not be three tokens.

**Comment by lbovet** [comment]
I submitted a PR (https://github.com/antlr/grammars-v4/pull/4029/files) to change the match
`fragment SIMPLE_LETTER  : [A-Z\p{Alphabetic}];` 
Can you test with it?
I suspect the unicode property to be no fully portable outside of Java.

**Comment by stephendrew** [comment]
That fixes the immediate identification of that identifier.  However there are even more errors, most along these lines:

```sql
    p_user_class             VARCHAR(30);
```

```
Token: 2378: p_
Token: 2378: er_
Token: 2378: la
Token: 2380:
Token: 2167: VARCHAR
Token: 2347: (
Token: 2341: 30
Token: 2348: )
Token: 2367: ;
Token: 2380:
```

> I suspect the unicode property to be no fully portable outside of Java.

Is this grammar only supposed to work on Java then?

**Comment by lbovet** [comment]
Looks like there are some differences in the support of unicode properties. I'll try to find the common denominator from a general regexp resource. I found this: https://www.regular-expressions.info/unicode.html

**Comment by lbovet** [comment]
I updated the PR, can you try?

**Comment by stephendrew** [comment]
This can just be closed, it seems I had somehow reverted to an earlier version of the code generator :<

It works fine for me now as it is the master branch.
