### ISSUE TITLE
C.g4 does not handle escaped literal newlines

### ISSUE THREAD

**Issue by brendon-boldt** [antlr/grammars-v4#403]
I found that the C.g4 file does not account for escaped literal newlines in strings. For example,
```c
  printf (_("\
Usage: %s [ignored command line arguments]\n\
  or:  %s OPTION\n\
"),
          program_name, program_name);
```
is a valid statement (and will compile with `gcc -std=c11`), but ANTLR using C.g4 will fail to lex it (find the whole file [here at line 38](https://github.com/coreutils/coreutils/blob/master/src/true.c)).

I am not sure if this is C dialect-specific syntax, but making the following change in C.g4 fixes the issue:
```
fragment
SChar
    :   ~["\\\r\n]
    |   EscapeSequence
    |   '\\\n'   // Added line
    |   '\\\r\n' // Added line
    ;
```

**Comment by teverett** [comment]
Pull request #404
