### ISSUE TITLE
How to recognize schema name at CreateTable

### ISSUE THREAD

**Issue by huiyuanai709** [antlr/grammars-v4#4113]
https://github.com/antlr/grammars-v4/blob/b91b6dae10165db9000fabd9c8ee3b966da2d4cc/sql/mysql/Oracle/MySQLParser.g4#L450

eg: create table if not exists payment.example

**Comment by huiyuanai709** [comment]
should add schema compatible here
https://github.com/antlr/grammars-v4/blob/b91b6dae10165db9000fabd9c8ee3b966da2d4cc/sql/mysql/Oracle/MySQLParser.g4#L4345

```
tableName
    : qualifiedIdentifier
    | dotIdentifier
    ;
```

**Comment by kaby76** [comment]
> should add schema compatible here[?]

I would not do that. This grammar was just added and is maintained by @mike-lischke who works at Oracle on MySQL!

**Comment by mike-lischke** [comment]
A table name can be qualified, e.g. `schemaName.tableName` (so it explicitly contains the schema name) or it can be a dot identifier, e.g. `.tableName`, which uses the current default schema. Is that what you need, or is it something else, @huiyuanai709?

**Comment by huiyuanai709** [comment]
> A table name can be qualified, e.g. `schemaName.tableName` (so it explicitly contains the schema name) or it can be a dot identifier, e.g. `.tableName`, which uses the current schema (which can be set by `use mySchema;`). Is that what you need, or is it something else, @huiyuanai709?

![image](https://github.com/antlr/grammars-v4/assets/19516176/76cea76a-ae85-454a-918a-d8033a1af817)

parse is borken at schemaName and then the DOT_SYMBOL is treated as a ErrorSymbol

**Comment by huiyuanai709** [comment]
> > should add schema compatible here[?]
> 
> I would not do that. This grammar was just added and is maintained by @mike-lischke who works at Oracle on MySQL!

FYI https://dev.mysql.com/doc/refman/8.0/en/create-table.html
![image](https://github.com/antlr/grammars-v4/assets/19516176/d88b17c8-b137-4402-b894-c2945ddc7ba9)

should a nulllable schemaName or databaseName here

**Comment by kaby76** [comment]
> I use CSharp to implement MySQLBaseLexer.cs MySQLBaseRecognizer.cs follow TypeScript Implement

You are not giving us complete, factual code. The Oracle/*.g4 grammar cannot be used as is with the CSharp target. There are many Antlr4ng target-specific codes in the grammar. (NB: this grammar is not Antlr4 TypeScript, but Antlr4ng TypeScript. There is a huge difference.)

1) `@header` actions in the .g4's are in TypeScript syntax. For the CSharp target, these `@header` are not needed because C# has different rules for symbol visibility. The csc.exe compiler will make visible all declarations in the same project, regardless of what directory it may be in.
1) SqlMode referenced in .g4's, within some actions, is undefined in C#.
1) Attribute [type](https://github.com/antlr/grammars-v4/blob/master/sql/mysql/Oracle/MySQLParser.g4#L548) results in a symbol conflict in C#. The Antlr Tool 4.13.1 does not handle this symbol conflict, so the attributes `type` have to be renamed or deleted.
1) The MySQLLexer.g4 grammar contains actions in TypeScript syntax with "this.type". Not only is that in TYpeScript, but the Antlr Runtime API is different between the CSharp and Antlr4ng targets. Actions should only contain function calls, no "this.", no "type", no flow control, comparison operations, etc.

Further, your base classes for lexer and parser (MySQLBaseLexer and MySQLBaseRecognizer) don't compile.

1) Critical C# `using` statements are missing in the beginning of your code.
1) The declaration to override `NextToken()` in your code is wrong. `public IToken? nextToken() {`. It needs to be named `NextToken()` not `nextToken()`.

But, even after correcting all that, it still does not work. It is not clear whether I will port the grammar to the other targets because it should be written in target-agnostic format.

**Comment by huiyuanai709** [comment]
> > I use CSharp to implement MySQLBaseLexer.cs MySQLBaseRecognizer.cs follow TypeScript Implement
> 
> You are not giving us complete, factual code. The grammars-v4/sql/mysql/Oracle/*.g4 grammar cannot be used as is with the CSharp target. There are many Antlr4ng target-specific codes in the grammar. (NB: this grammar is not Antlr4 TypeScript, but Antlr4ng TypeScript. There is a huge difference.)
> 
> 1. `@header` actions in the .g4's are in TypeScript syntax. For the CSharp target, these `@header` are not needed because C# has different rules for symbol visibility. The csc.exe compiler will make visible all declarations in the same project, regardless of what directory it may be in.
> 2. SqlMode referenced in .g4's, within some actions, is undefined in C#.
> 3. Attribute [type](https://github.com/antlr/grammars-v4/blob/master/sql/mysql/Oracle/MySQLParser.g4#L548) results in a symbol conflict in C#. The Antlr Tool 4.13.1 does not handle this symbol conflict, so the attributes `type` have to be renamed or deleted.
> 4. The MySQLLexer.g4 grammar contains actions in TypeScript syntax with "this.type". Not only is that in TYpeScript, but the Antlr Runtime API is different between the CSharp and Antlr4ng targets. Actions should only contain function calls, no "this.", no "type", no flow control, comparison operations, etc.
> 
> Further, your base classes for lexer and parser (MySQLBaseLexer and MySQLBaseRecognizer) don't compile.
> 
> 1. Critical C# `using` statements are missing in the beginning of your code. For example, HashSet<> requires either to be fully qualified `System.Collections.Generic.HashSet<>` or a `using System.Collections.Generic;` statement at the top of the file.
> 2. The declaration to override `NextToken()` in your code is wrong. `public IToken? nextToken() {`. It needs to be named `NextToken()` not `nextToken()`.
> 
> But, even after correcting all that, it still does not work. It is not clear whether I will port the grammar to the other targets because it should be written in target-agnostic format for this repo. That is the current best solution so that the .g4's are not duplicated 8 times (one for each target), and cause a maintenance issue (because people only change the target they want).

Um... Find the problem at the NextToken and the emitDot method in MySQLBaseLexer.cs
NextToken is override from base Lexer.cs,  so it's need to be upper case, the emitDot implement in TypeScript is not same working in CSharp because the TokenStartCharIndex is readonly in Lexer.cs

I try to refactor the emitDot implement in CSharp
``` CSharp
protected void emitDot() {
    pendingTokens.Push(TokenFactory.Create(MySQLLexer.DOT_SYMBOL, Text));
}
```

It seems to be working now.

![image](https://github.com/antlr/grammars-v4/assets/19516176/2480fe87-6525-44ff-a8fa-eb296a9f4bcb)



Here is the full implement MySqlBaseLexer.cs

``` CSharp
using Antlr4.Runtime;

namespace MySql.Antlr4.gen;

public abstract class MySQLBaseLexer : Lexer
{
    protected MySQLBaseLexer(ICharStream input) : base(input)
    {
    }

    protected MySQLBaseLexer(ICharStream input, TextWriter output, TextWriter errorOutput) : base(input, output, errorOutput)
    {
    }
    
    public int serverVersion = 0;
    public HashSet<SqlMode> sqlModes = new();

    /** Enable Multi Language Extension support. */
    public bool supportMle = true;

    public readonly HashSet<string> charSets = new(); // Used to check repertoires.
    protected bool inVersionComment = false;

    private readonly Stack<IToken> pendingTokens = new();

    public const string longString = "2147483647";
    public const int longLength = 10;
    public const string signedLongString = "-2147483648";
    public const string longLongString = "9223372036854775807";
    public const int longLongLength = 19;
    public const string signedLongLongString = "-9223372036854775808";
    public const int signedLongLongLength = 19;
    public const string unsignedLongLongString = "18446744073709551615";
    public const int unsignedLongLongLength = 20;
    
    public bool isSqlModeActive(SqlMode sqlMode)
    {
        return sqlModes.Contains(sqlMode);
    }
    
    /**
     * Converts a mode string into individual mode flags.
     *
     * @param modes The input string to parse.
     */
    public void sqlModeFromString(string modes) {
        sqlModes = new HashSet<SqlMode>();

        var parts = modes.ToUpper().Split(",").ToList();
        parts.ForEach(mode => {
            if (mode == "ANSI" || mode == "DB2" || mode == "MAXDB" || mode == "MSSQL" || mode == "ORACLE" ||
                    mode == "POSTGRESQL")
            {
                sqlModes.Add(SqlMode.AnsiQuotes);
                sqlModes.Add(SqlMode.PipesAsConcat);
                sqlModes.Add(SqlMode.IgnoreSpace);
            } else if (mode == "ANSI_QUOTES") {
                sqlModes.Add(SqlMode.AnsiQuotes);
            } else if (mode == "PIPES_AS_CONCAT") {
                sqlModes.Add(SqlMode.PipesAsConcat);
            } else if (mode == "NO_BACKSLASH_ESCAPES") {
                sqlModes.Add(SqlMode.NoBackslashEscapes);
            } else if (mode == "IGNORE_SPACE") {
                sqlModes.Add(SqlMode.IgnoreSpace);
            } else if (mode == "HIGH_NOT_PRECEDENCE" || mode == "MYSQL323" || mode == "MYSQL40") {
                sqlModes.Add(SqlMode.HighNotPrecedence);
            }
        });
    }
    
    /**
     * Resets the lexer by setting initial values to transient member, resetting the input stream position etc.
     */
    public override void Reset() {
        inVersionComment = false;
        base.Reset();
    }
    
    /**
     * Implements the multi token feature required in our lexer.
     * A lexer rule can emit more than a single token, if needed.
     *
     * @returns The next token in the token stream.
     */
    public override IToken? NextToken() {
        // First respond with pending tokens to the next token request, if there are any.
        if (pendingTokens.TryPop(out var token)) {
            return token;
        }

        // Let the main lexer class run the next token recognition.
        // This might create additional tokens again.
        var next = base.NextToken();
        if (pendingTokens.TryPop(out token)) {
            pendingTokens.Push(next);
            return token;
        }

        return next;
    }
    
    protected bool checkMySQLVersion(string text) {
        if (text.Length < 8) {// Minimum is: /*!12345
            return false;
        }

        // Skip version comment introducer.
        var version = int.Parse(text[3..]);
        if (version <= serverVersion) {
            inVersionComment = true;

            return true;
        }

        return false;
    }

    /**
     * Called when a keyword was consumed that represents an internal MySQL function and checks if that keyword is
     * followed by an open parenthesis. If not then it is not considered a keyword but treated like a normal identifier.
     *
     * @param proposed The token type to use if the check succeeds.
     *
     * @returns If a function call is found then return the proposed token type, otherwise just IDENTIFIER.
     */
    protected int determineFunction(int proposed) {
        // Skip any whitespace character if the sql mode says they should be ignored,
        // before actually trying to match the open parenthesis.
        // Ascii code int to string
        var input = Convert.ToChar(InputStream.LA(1));
        if (isSqlModeActive(SqlMode.IgnoreSpace)) {
            while (input is ' ' or '\t' or '\r' or '\n') {
                Interpreter.Consume(((ITokenSource)this).InputStream);
                Channel = Lexer.Hidden;
                Type = MySQLLexer.WHITESPACE;
                input = Convert.ToChar(InputStream.LA(1));
            }
        }

        return input == '(' ? proposed : MySQLLexer.IDENTIFIER;
    }
    
     /**
     * Checks the given text and determines the smallest number type from it. Code has been taken from sql_lex.cc.
     *
     * @param text The text to parse (which must be a number).
     *
     * @returns The token type for that text.
     */
    protected int determineNumericType(string text) {
        // The original code checks for leading +/- but actually that can never happen, neither in the
        // server parser (as a digit is used to trigger processing in the lexer) nor in our parser
        // as our rules are defined without signs. But we do it anyway for maximum compatibility.
        var length = text.Length - 1;
        if (length < longLength) { // quick normal case
            return MySQLLexer.INT_NUMBER;
        }

        var negative = false;
        var index = 0;
        if (text[index] == '+') { // Remove sign and pre-zeros
            ++index;
            --length;
        } else if (text[index] == '-') {
            ++index;
            --length;
            negative = true;
        }

        while (text[index] == '0' && length > 0) {
            ++index;
            --length;
        }

        if (length < longLength) {
            return MySQLLexer.INT_NUMBER;
        }

        int smaller;
        int bigger;
        string cmp;
        if (negative) {
            if (length == longLength) {
                cmp = signedLongString[1..];
                smaller = MySQLLexer.INT_NUMBER; // If <= signed_long_str
                bigger = MySQLLexer.LONG_NUMBER; // If >= signed_long_str
            } else if (length < signedLongLongLength) {
                return MySQLLexer.LONG_NUMBER;
            } else if (length > signedLongLongLength) {
                return MySQLLexer.DECIMAL_NUMBER;
            } else {
                cmp = signedLongLongString[1..];
                smaller = MySQLLexer.LONG_NUMBER; // If <= signed_longlong_str
                bigger = MySQLLexer.DECIMAL_NUMBER;
            }
        } else {
            if (length == longLength) {
                cmp = longString;
                smaller = MySQLLexer.INT_NUMBER;
                bigger = MySQLLexer.LONG_NUMBER;
            } else if (length < longLongLength) {
                return MySQLLexer.LONG_NUMBER;
            } else if (length > longLongLength) {
                if (length > unsignedLongLongLength) {
                    return MySQLLexer.DECIMAL_NUMBER;
                }
                cmp = unsignedLongLongString;
                smaller = MySQLLexer.ULONGLONG_NUMBER;
                bigger = MySQLLexer.DECIMAL_NUMBER;
            } else {
                cmp = longLongString;
                smaller = MySQLLexer.LONG_NUMBER;
                bigger = MySQLLexer.ULONGLONG_NUMBER;
            }
        }
        var otherIndex = 0;
        while (index < text.Length && cmp[otherIndex++] == text[index++]) {
            //
        }

        return text[index - 1] <= cmp[otherIndex - 1] ? smaller : bigger;
    }
     
    /**
    * Checks if the given text corresponds to a charset defined in the server (text is preceded by an underscore).
    *
    * @param text The text to check.
    *
    * @returns UNDERSCORE_CHARSET if so, otherwise IDENTIFIER.
    */
    protected int checkCharset(string text) {
        return charSets.Contains(text) ? MySQLLexer.UNDERSCORE_CHARSET : MySQLLexer.IDENTIFIER;
    }
    
    /**
    * Creates a DOT token in the token stream.
    */
    protected void emitDot() {
        pendingTokens.Push(TokenFactory.Create(MySQLLexer.DOT_SYMBOL, Text));
    }
}

**Comment by huiyuanai709** [comment]
There is a problem at TableName definitiion at `MySQLParser.g4` maybe explict schemaName.tableName or tableName, this approach better aligns with semantic conventions.

**Comment by huiyuanai709** [comment]
Try to remove DOT_IDENTIFIER in MySQLLexer.g4 and then add strong type for tableName
The pendingTokens and NextToken is not need anymore in MySQLBaseLexer

``` Antlr4
tableNameWithOptionalDatabase
    : (databaseName=identifier DOT_SYMBOL tableName=identifier)
    | tableName=identifier
    ;
```

**Comment by mike-lischke** [comment]
I still have no idea, what you are after @huiyuanai709. What's wrong with the existing `tableName` rule? It supports qualified names (which is in this case schema and table name) or just a single identifier (table name).
