### ISSUE TITLE
antlr4 can't process left-recursive?

### ISSUE THREAD

**Issue by longsebo** [antlr/grammars-v4#417]
[ERROR] error(119): MySQLParser.g4::: The following sets of rules are mutually l
eft-recursive [expr, exprs, boolean_primary, predicate, bit_expr, simple_expr]
[ERROR] E:\git\grammars-v4\mysql\MySQLParser.g4 [-1:-1]: The following sets of r
ules are mutually left-recursive [expr, exprs, boolean_primary, predicate, bit_e
xpr, simple_expr]

**Comment by KvanTTT** [comment]
ANTLR 4 is able to process only direct left-recursion:

```
expr
    : expr '*' expr
    | expr '+' expr
    | id
    ;
```

But it's not able to process mutual left-recursion:

```
expr
    : expr1 '*' expr1
    | expr1 '+' expr1
    | id
    ;

expr1
    : expr '==' expr  // indirect left-recursion to expr rule.
    | id
    ;
```

I was not working with MySQL grammar but it seems to me that this grammar is not written properly.

**Comment by longsebo** [comment]
How resolve it problem?

**Comment by teverett** [comment]
I'm not sure it qualifies as a problem, it's designed into Antlr.  @parrt do you agree?

**Comment by parrt** [comment]
Yup. that is a limitation of ANTLR not a bug.

**Comment by kant111** [comment]
Can we expect support for this in antlr5?

**Comment by parrt** [comment]
I doubt there will be a 5 but unrestricted left recursion wouldn’t be an option. You maybe want GLR
