### ISSUE TITLE
TSQL parser

### ISSUE THREAD

**Issue by openai0229** [antlr/grammars-v4#4171]
I am trying to parse the following SQL statement using ANTLR:

~~~sql

IF EXISTS (SELECT * FROM sys.all_objects WHERE object_id = OBJECT_ID(N'[dbo].[table_name']') AND type IN ('U'))
    DROP TABLE [dbo].[table_name']
GO
~~~
However, I encountered an issue with N'[dbo].[table_name']' because [table_name'] contains a single quote ', causing the parsing to fail.

**Comment by bkiers** [comment]
Isn't it expected to fail because of the invalid string literal `N'[dbo].[table_name']'`, which should be `N'[dbo].[table_name]'`?

**Comment by bkiers** [comment]
Note that `N'[dbo].[table_name']'` is not a valid string literal. So if your change accepts such a string literal, it is not a good implementation.

As I said earlier: if your table name really includes a (single) quote, `table_name'`, then that single quote will need to be escaped inside the string literal: `N'[dbo].[table_name'']'`. But this is what the grammar already accepts.
