### ISSUE TITLE
C# Build errors "name _mode does not exist in the current context" when compiling PHPLexer.g4

### ISSUE THREAD

**Issue by in-the-name-of-science** [antlr/grammars-v4#419]
I am getting the following errors when attempting to build a C# project that will lex and parse PHP code:

```
The name '_mode' does not exist in the current context	ConsoleApplication1 PHPLexer.cs
The name '_channel' does not exist in the current context ConsoleApplication1 PHPLexer.cs	
The name '_input' does not exist in the current context	ConsoleApplication1 PHPLexer.cs
```
The PHPLexer.cs and PHPParser.cs were generated on the command line with the ANTLRv4 tool using the PHP grammar found in this repo and have been added and correctly referenced in the test project. I can't seem to find any documentation that states that the developer must declare the variables  `_mode`,` _channel `or `_input` so it seems likely that there may be a bug or at least an expectation of how the code is used that is not clearly stated.

The test case code is very simple:

```csharp
using System;
using Antlr4.Runtime;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            String input = "D:\\test.php";
            AntlrInputStream stream = new AntlrInputStream(input);
            ITokenSource lexer = new PHPLexer(stream);
            ITokenStream tokens = new CommonTokenStream(lexer);
            PHPParser parser = new PHPParser(tokens);
            parser.BuildParseTree = true;   
        }
    }
}
```

But when I try to build the project the missing variables inside PHPLexer.cs break the process. Please advise.

**Comment by in-the-name-of-science** [comment]
You are correct. After your suggestions the code successfully compiled. Thank you.

**Comment by jpwiddy** [comment]
Is there any way that we can get the grammar that will work with the proper/now current supported runtime for C#? I am getting the same error for the `ECMAScript.g4`
