### ISSUE TITLE
PHP bitshifts with wrong labels

### ISSUE THREAD

**Issue by harrison3000** [antlr/grammars-v4#4196]
at https://github.com/antlr/grammars-v4/blob/feb9e9e082842d9cafed1e1558e9d1aad7052b87/php/PhpParser.g4#L510
the bitshifts are labelled as `ComparisonExpression` when they are, in fact, `ArithmeticExpression`

**Comment by kaby76** [comment]
I wrote a PR to change the labeling in the alts for expressions. I wasn't happy with the old labels, so I renamed a bunch to mirror the symbols in the operator precedence/Floyd grammar from the ["spec"](https://github.com/php/php-langspec/blob/master/spec/19-grammar.md).
