### ISSUE TITLE
[build] Update find-useless-parentheses.sh

### ISSUE THREAD

**Issue by kaby76** [antlr/grammars-v4#4218]
Three bugs have been fixed for the Trash script [find-useless-parentheses.sh](https://github.com/kaby76/g4-scripts/blob/5d94da10c285fbbd69eac3b3a429b8ccec4513fa/find-useless-parentheses.sh). 
* https://github.com/kaby76/g4-scripts/issues/1
* https://github.com/kaby76/g4-scripts/issues/2
* https://github.com/kaby76/g4-scripts/issues/3

Testing here gets an older version. https://github.com/antlr/grammars-v4/blob/2a3a6bdcbe1f9b975591d194d69df22e336dd7da/_scripts/test-static-checks.sh#L360. It should be updated.

**Comment by MasterKuat** [comment]
Hi @kaby76, seems this fix break the test.
Please see https://github.com/antlr/grammars-v4/actions/runs/10629557556/job/29466637942?pr=4223
```
sql/snowflake,useless-parens:
main: line 19: trparse: command not found
Computing useless parentheses in SnowflakeLexer.g4 SnowflakeParser.g4
main: line 21: trparse: command not found

```

**Comment by kaby76** [comment]
Sorry, the script was changed to use a ["global" trparse](https://github.com/kaby76/g4-scripts/blob/5d94da10c285fbbd69eac3b3a429b8ccec4513fa/find-useless-parentheses.sh#L19) (i.e., calling "trparse" from the command line), when it should have stayed with the ["local" trparse](https://github.com/kaby76/g4-scripts/blob/9e70a6392783936ddd51cd270f6ac29fecbefef8/find-useless-parentheses.sh#L19) (calling "trparse" via "dotnet").

Will fix today.
