### ISSUE TITLE
nchar here seem not working

### ISSUE THREAD

**Issue by huiyuanai709** [antlr/grammars-v4#4221]
Hello 
nchar here is an exception? 

``` Antlr4
| type = (BOOL_SYMBOL | BOOLEAN_SYMBOL)
    | type = CHAR_SYMBOL fieldLength? charsetWithOptBinary?
    | nchar fieldLength? BINARY_SYMBOL?
    | type = BINARY_SYMBOL fieldLength?
    | (type = CHAR_SYMBOL VARYING_SYMBOL | type = VARCHAR_SYMBOL) fieldLength charsetWithOptBinary?
    | (
        type = NATIONAL_SYMBOL VARCHAR_SYMBOL
        | type = NVARCHAR_SYMBOL
        | type = NCHAR_SYMBOL VARCHAR_SYMBOL
        | type = NATIONAL_SYMBOL CHAR_SYMBOL VARYING_SYMBOL
        | type = NCHAR_SYMBOL VARYING_SYMBOL
    ) fieldLength BINARY_SYMBOL?
```

https://github.com/antlr/grammars-v4/blob/e07dbbf3445d31da61af5f54f04df78ea40ab9f8/sql/mysql/Oracle/MySQLParser.g4#L3748C1-L3759C33

**Comment by kaby76** [comment]
You don't provide:
* any explanation of the problem;
* any example that fails to parse or results in a bad parse tree.

There is nothing to go on here.

**Comment by huiyuanai709** [comment]
> You don't provide:
> 
> * any explanation of the problem;
> 
> * any example that fails to parse or results in a bad parse tree.
> 
> 
> 
> There is nothing to go on here.

it's clearly to see the nchar is not consistent as others type

I think nchar should consistent with other types

**Comment by kaby76** [comment]
I still don't understand what the inconsistency is here. You don't propose a change for [the dataType parser rule](https://github.com/antlr/grammars-v4/blob/e07dbbf3445d31da61af5f54f04df78ea40ab9f8/sql/mysql/Oracle/MySQLParser.g4#L3736C1-L3789).

But, more importantly, this grammar is maintained by @mike-lischke who works at Oracle on MySQL. Changes should go through him at Oracle on an official MySQL github repo.
* Yacc grammar for MySQL: https://github.com/mysql/mysql-server/blob/8.0/sql/sql_yacc.yy
* Antlr grammar translation: https://github.com/mysql/mysql-workbench/tree/a1a527a89ee6412abed8ae0cca58f2e572b46ce7/library/parsers/grammars

**Comment by huiyuanai709** [comment]
> I still don't understand what the inconsistency is here. You don't propose a change for [the dataType parser rule](https://github.com/antlr/grammars-v4/blob/e07dbbf3445d31da61af5f54f04df78ea40ab9f8/sql/mysql/Oracle/MySQLParser.g4#L3736C1-L3789).
> 
> But, more importantly, this grammar is maintained by @mike-lischke who works at Oracle on MySQL. Changes should go through him at Oracle on an official MySQL github repo.
> 
> * Yacc grammar for MySQL: https://github.com/mysql/mysql-server/blob/8.0/sql/sql_yacc.yy
> * Antlr grammar translation: https://github.com/mysql/mysql-workbench/tree/a1a527a89ee6412abed8ae0cca58f2e572b46ce7/library/parsers/grammars
> 
> I think we're going to need a change to the [readme](https://github.com/antlr/grammars-v4/blob/e07dbbf3445d31da61af5f54f04df78ea40ab9f8/sql/mysql/Oracle/README.md) to note how to propose changes.

Sorry, My mistake nchar has National Char and nchar two express, 
Try to Translate MYSQL DDL dataType to object relation model commonly get type but nchar flash
![image](https://github.com/user-attachments/assets/c7c4eeba-bfab-48d5-8fd3-2b1c5a1c4684)
