### ISSUE TITLE
ANTLR4 ECMAScript grammar - dot expression

### ISSUE THREAD

**Issue by premun** [antlr/grammars-v4#423]
`SingleExpression` breaks up into a dot-expression alternative:

``` antlr
singleExpression :
      ...
      | singleExpression '.' identifierName       # MemberDotExpression
      ...
```

but `identifierName` breaks up into a reserved keyword too:

``` antlr
identifierName
      : Identifier
      | reservedWord
      ;
```

If I am not wrong, this can lead to weird situations, such as:
foo.break
foo.var
foo.if
and so on...

I have noticed this, after I imported this language inside JetBrains MPS and tried to use it and noticed this anomaly.
It might not be a bug per se, because keywords could be names of object properties, but parser then recognizes identifiers as reserved keywords.
Feel free to reject this issue, if you feel it's not important.

**Comment by Marti2203** [comment]
This is a normal thing I think. I just checked it in the node REPL and it worked. Should I check the ECMAScript standard or can this issue be closed?

**Comment by studentmain** [comment]
I believe ECMAScript standard allow this kind of thing.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords

**Comment by Marti2203** [comment]
Then this can be closed. @KvanTTT
