### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by KvanTTT** [antlr/grammars-v4#426]
Inspired by [Java8 performance issue](https://github.com/antlr/grammars-v4/issues/215). I suggest perormance tests additing for files like this: [ManyStringConcatenation.java](https://gist.github.com/KvanTTT/bf20f6a4aac708b49df2);

``` Java
assertTrue(actualExecTime <= expectedExecTime);
```

**Comment by teverett** [comment]
It's a good idea.  Are you suggesting augmenting the ANTLR4 language?

**Comment by KvanTTT** [comment]
I didn't completely understand you. I mean the same grammars can be written by the different way. For example, take a look at this: http://blog.ptsecurity.com/2016/06/theory-and-practice-of-source-code.html#java--and-java8-grammars
So, it would be nice to test deep expression files not only for correctness, but for performance too.

**Comment by Marti2203** [comment]
Is this issue still valid?

**Comment by KvanTTT** [comment]
Maybe yes. I've created a repository [AntlrBenchmarks](https://github.com/KvanTTT/AntlrBenchmarks) for checking performance in different runtimes. But I still don't know how to use benchmarks in this grammar repository in a better way.

**Comment by Marti2203** [comment]
Maybe keep benchmarks of the grammar before any changes and after the pull request?

**Comment by KvanTTT** [comment]
I'm closing this issue because of it's indeed not completely valid. Performance benchmarks are very tricky.
