### ISSUE TITLE
PLSQL V4 grammar issue - INSERT INTO 

### ISSUE THREAD

**Issue by RobertPastor** [antlr/grammars-v4#427]
the SQL example in file insert02.sql
insert into t values trec

is not compatible with the rules
values_clause
    : VALUES expression_list
    ;
expression_list
    : '(' expression? (',' expression)\* ')'
    ;
Hence the test file insert02.sql should read
insert into t values ( trec )

in the following oracle 
https://docs.oracle.com/cd/B14117_01/server.101/b10759/statements_9014.htm#SQLRF01604
LEFT_parenthesis and RIGHT_parenthesis are mandatory.

**Comment by teverett** [comment]
Please issue a pull request for this too
