### ISSUE TITLE
Java20ParserBaseListener print nothing

### ISSUE THREAD

**Issue by quantrpeter** [antlr/grammars-v4#4281]
Hi
   why my listener print nothing for getText()? I am using Java20Parser.g4

```
public class MyListener extends Java20ParserBaseListener {

	@Override
	public void enterClassDeclaration(Java20Parser.ClassDeclarationContext ctx) {
		System.out.println(">>" + ctx.getText());
	}

	@Override
	public void enterClassBodyDeclaration(Java20Parser.ClassBodyDeclarationContext ctx) {
		System.out.println(">" + ctx.getText());
	}

	@Override
	public void enterClassBody(Java20Parser.ClassBodyContext ctx) {
		System.out.println(">" + ctx.getText());
	}
	
	@Override
	public void enterMethodName(Java20Parser.MethodNameContext ctx) {
		System.out.println(">" + ctx.getText());
	}

}
```

```
	@Test
	public void test() throws IOException {
		String content = FileUtils.readFileToString(new File("testFiles/Java8Function3.java"), "utf-8");
		Java20Lexer lexer = new Java20Lexer(CharStreams.fromString(content));
		CommonTokenStream tokenStream = new CommonTokenStream(lexer);

		Java20Parser parser = new Java20Parser(tokenStream);
		parser.addParseListener(new MyListener());
		Java20Parser.Start_Context context = parser.start_();
		System.out.println(context);
	}
```

thanks

**Comment by kaby76** [comment]
You don't give the input file. It's impossible to know. It could be an empty file, for example.

**Comment by quantrpeter** [comment]
thanks, this is the input file:

```
package com.mkyong;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

public class Java8Function3 {

    public static void main(String[] args) {

        Java8Function3 obj = new Java8Function3();

        List<String> list = Arrays.asList("node", "c++", "java", "javascript");

        // lambda
        Map<String, Integer> map = obj.convertListToMap(list, x -> x.length());

        System.out.println(map);    // {node=4, c++=3, java=4, javascript=10}

        // method reference
        Map<String, Integer> map2 = obj.convertListToMap(list, obj::getLength);

        System.out.println(map2);
    }

    public <T, R> Map<T, R> convertListToMap(List<T> list, Function<T, R> func) {

        Map<T, R> result = new HashMap<>();
        for (T t : list) {
            result.put(t, func.apply(t));
        }
        return result;

    }

    public Integer getLength(String str) {
        return str.length();
    }

}
```

**Comment by kaby76** [comment]
The parser listener is fine (I had to add imports, 
[MyParserListener.java.txt](https://github.com/user-attachments/files/17350806/MyParserListener.java.txt)). I'm not sure why you read the file into a string, and then use the string API. Use [CharStreams.fromFileName()](https://github.com/antlr/grammars-v4/blob/c82c128d980f4ce46fb3536f87b06b45b9619922/_scripts/templates/Java/st.Test.java#L139). In addition, you really should print out the parse tree. `System.out.println(context);` does not do that. Use [tree.toStringTree(parser)](https://github.com/antlr/grammars-v4/blob/c82c128d980f4ce46fb3536f87b06b45b9619922/_scripts/templates/Java/st.Test.java#L217). (I cannot stand the name "context" for a parse tree node. It's a ***tree*** node.) Verify that you are actually parsing anything.

**Comment by quantrpeter** [comment]
I think the parse does the job correctly, just don't know why ctx.getText() return nothing. CharStrems.fromFileName no help.

<img width="1348" alt="Screenshot 2024-10-13 at 1 23 21 AM" src="https://github.com/user-attachments/assets/cc878d92-31b6-45ec-8ae1-9b7935050713">

<img width="1338" alt="Screenshot 2024-10-13 at 1 27 08 AM" src="https://github.com/user-attachments/assets/347708d7-07e5-44cb-ba58-cc485d5c0f9e">

![a](https://github.com/user-attachments/assets/1a1c8d6f-57c7-4439-b7cb-1ea2bb689c6e)

**Comment by quantrpeter** [comment]
```
		Java20Lexer lexer = new Java20Lexer(CharStreams.fromFileName("testFiles/Java8Function3.java"));
		CommonTokenStream tokenStream = new CommonTokenStream(lexer);

		Java20Parser parser = new Java20Parser(tokenStream);
		parser.addParseListener(new MyListener());
		ParseTree tree = parser.start_();
		System.err.println(tree.toStringTree(parser));
```

give me:


(start_ (compilationUnit (ordinaryCompilationUnit (packageDeclaration package (identifier com) . (identifier mkyong) ;) (importDeclaration (singleTypeImportDeclaration import (typeName (packageName (identifier java) . (packageName (identifier util) . (packageName (identifier Arrays))))) ;)) (importDeclaration (singleTypeImportDeclaration import (typeName (packageName (identifier java) . (packageName (identifier util) . (packageName (identifier HashMap))))) ;)) (importDeclaration (singleTypeImportDeclaration import (typeName (packageName (identifier java) . (packageName (identifier util) . (packageName (identifier List))))) ;)) (importDeclaration (singleTypeImportDeclaration import (typeName (packageName (identifier java) . (packageName (identifier util) . (packageName (identifier Map))))) ;)) (importDeclaration (singleTypeImportDeclaration import (typeName (packageName (identifier java) . (packageName (identifier util) . (packageName (identifier function) . (packageName (identifier Function)))))) ;)) (topLevelClassOrInterfaceDeclaration (classDeclaration (normalClassDeclaration (classModifier public) class (typeIdentifier Java8Function3) (classBody { (classBodyDeclaration (classMemberDeclaration (methodDeclaration (methodModifier public) (methodModifier static) (methodHeader (result void) (methodDeclarator (identifier main) ( (formalParameterList (formalParameter (unannType (unannReferenceType (unannArrayType (unannClassOrInterfaceType (typeIdentifier String)) (dims [ ])))) (variableDeclaratorId (identifier args)))) ))) (methodBody (block { (blockStatements (blockStatement (localVariableDeclarationStatement (localVariableDeclaration (localVariableType (unannType (unannReferenceType (unannClassOrInterfaceType (typeIdentifier Java8Function3))))) (variableDeclaratorList (variableDeclarator (variableDeclaratorId (identifier obj)) = (variableInitializer (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (primary (primaryNoNewArray (unqualifiedClassInstanceCreationExpression new (classOrInterfaceTypeToInstantiate (identifier Java8Function3)) ( )))))))))))))))))))))))) ;)) (blockStatement (localVariableDeclarationStatement (localVariableDeclaration (localVariableType (unannType (unannReferenceType (unannClassOrInterfaceType (typeIdentifier List) (typeArguments < (typeArgumentList (typeArgument (referenceType (classOrInterfaceType (typeIdentifier String))))) >))))) (variableDeclaratorList (variableDeclarator (variableDeclaratorId (identifier list)) = (variableInitializer (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (primary (primaryNoNewArray (typeName (packageName (identifier Arrays))) . (identifier asList) ( (argumentList (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (primary (primaryNoNewArray (literal "node"))))))))))))))))))) , (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (primary (primaryNoNewArray (literal "c++"))))))))))))))))))) , (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (primary (primaryNoNewArray (literal "java"))))))))))))))))))) , (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (primary (primaryNoNewArray (literal "javascript")))))))))))))))))))) ))))))))))))))))))))))) ;)) (blockStatement (localVariableDeclarationStatement (localVariableDeclaration (localVariableType (unannType (unannReferenceType (unannClassOrInterfaceType (typeIdentifier Map) (typeArguments < (typeArgumentList (typeArgument (referenceType (classOrInterfaceType (typeIdentifier String)))) , (typeArgument (referenceType (classOrInterfaceType (typeIdentifier Integer))))) >))))) (variableDeclaratorList (variableDeclarator (variableDeclaratorId (identifier map)) = (variableInitializer (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (primary (primaryNoNewArray (typeName (packageName (identifier obj))) . (identifier convertListToMap) ( (argumentList (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (expressionName (identifier list)))))))))))))))))) , (expression (lambdaExpression (lambdaParameters (identifier x)) -> (lambdaBody (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (primary (primaryNoNewArray (typeName (packageName (identifier x))) . (identifier length) ( ))))))))))))))))))))))) ))))))))))))))))))))))) ;)) (blockStatement (statement (statementWithoutTrailingSubstatement (expressionStatement (statementExpression (methodInvocation (typeName (packageName (identifier System) . (packageName (identifier out)))) . (identifier println) ( (argumentList (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (expressionName (identifier map))))))))))))))))))) ))) ;)))) (blockStatement (localVariableDeclarationStatement (localVariableDeclaration (localVariableType (unannType (unannReferenceType (unannClassOrInterfaceType (typeIdentifier Map) (typeArguments < (typeArgumentList (typeArgument (referenceType (classOrInterfaceType (typeIdentifier String)))) , (typeArgument (referenceType (classOrInterfaceType (typeIdentifier Integer))))) >))))) (variableDeclaratorList (variableDeclarator (variableDeclaratorId (identifier map2)) = (variableInitializer (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (primary (primaryNoNewArray (typeName (packageName (identifier obj))) . (identifier convertListToMap) ( (argumentList (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (expressionName (identifier list)))))))))))))))))) , (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (primary (primaryNoNewArray (expressionName (identifier obj)) :: (identifier getLength)))))))))))))))))))) ))))))))))))))))))))))) ;)) (blockStatement (statement (statementWithoutTrailingSubstatement (expressionStatement (statementExpression (methodInvocation (typeName (packageName (identifier System) . (packageName (identifier out)))) . (identifier println) ( (argumentList (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (expressionName (identifier map2))))))))))))))))))) ))) ;))))) }))))) (classBodyDeclaration (classMemberDeclaration (methodDeclaration (methodModifier public) (methodHeader (typeParameters < (typeParameterList (typeParameter (typeIdentifier T)) , (typeParameter (typeIdentifier R))) >) (result (unannType (unannReferenceType (unannClassOrInterfaceType (typeIdentifier Map) (typeArguments < (typeArgumentList (typeArgument (referenceType (classOrInterfaceType (typeIdentifier T)))) , (typeArgument (referenceType (classOrInterfaceType (typeIdentifier R))))) >))))) (methodDeclarator (identifier convertListToMap) ( (formalParameterList (formalParameter (unannType (unannReferenceType (unannClassOrInterfaceType (typeIdentifier List) (typeArguments < (typeArgumentList (typeArgument (referenceType (classOrInterfaceType (typeIdentifier T))))) >)))) (variableDeclaratorId (identifier list))) , (formalParameter (unannType (unannReferenceType (unannClassOrInterfaceType (typeIdentifier Function) (typeArguments < (typeArgumentList (typeArgument (referenceType (classOrInterfaceType (typeIdentifier T)))) , (typeArgument (referenceType (classOrInterfaceType (typeIdentifier R))))) >)))) (variableDeclaratorId (identifier func)))) ))) (methodBody (block { (blockStatements (blockStatement (localVariableDeclarationStatement (localVariableDeclaration (localVariableType (unannType (unannReferenceType (unannClassOrInterfaceType (typeIdentifier Map) (typeArguments < (typeArgumentList (typeArgument (referenceType (classOrInterfaceType (typeIdentifier T)))) , (typeArgument (referenceType (classOrInterfaceType (typeIdentifier R))))) >))))) (variableDeclaratorList (variableDeclarator (variableDeclaratorId (identifier result)) = (variableInitializer (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (primary (primaryNoNewArray (unqualifiedClassInstanceCreationExpression new (classOrInterfaceTypeToInstantiate (identifier HashMap) (typeArgumentsOrDiamond <>)) ( )))))))))))))))))))))))) ;)) (blockStatement (statement (forStatement (enhancedForStatement for ( (localVariableDeclaration (localVariableType (unannType (unannReferenceType (unannClassOrInterfaceType (typeIdentifier T))))) (variableDeclaratorList (variableDeclarator (variableDeclaratorId (identifier t))))) : (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (expressionName (identifier list)))))))))))))))))) ) (statement (statementWithoutTrailingSubstatement (block { (blockStatements (blockStatement (statement (statementWithoutTrailingSubstatement (expressionStatement (statementExpression (methodInvocation (typeName (packageName (identifier result))) . (identifier put) ( (argumentList (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (expressionName (identifier t)))))))))))))))))) , (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (primary (primaryNoNewArray (typeName (packageName (identifier func))) . (identifier apply) ( (argumentList (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (expressionName (identifier t))))))))))))))))))) )))))))))))))))))))) ))) ;))))) }))))))) (blockStatement (statement (statementWithoutTrailingSubstatement (returnStatement return (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (expressionName (identifier result)))))))))))))))))) ;))))) }))))) (classBodyDeclaration (classMemberDeclaration (methodDeclaration (methodModifier public) (methodHeader (result (unannType (unannReferenceType (unannClassOrInterfaceType (typeIdentifier Integer))))) (methodDeclarator (identifier getLength) ( (formalParameterList (formalParameter (unannType (unannReferenceType (unannClassOrInterfaceType (typeIdentifier String)))) (variableDeclaratorId (identifier str)))) ))) (methodBody (block { (blockStatements (blockStatement (statement (statementWithoutTrailingSubstatement (returnStatement return (expression (assignmentExpression (conditionalExpression (conditionalOrExpression (conditionalAndExpression (inclusiveOrExpression (exclusiveOrExpression (andExpression (equalityExpression (relationalExpression (shiftExpression (additiveExpression (multiplicativeExpression (unaryExpression (unaryExpressionNotPlusMinus (postfixExpression (primary (primaryNoNewArray (typeName (packageName (identifier str))) . (identifier length) ( ))))))))))))))))))) ;))))) }))))) })))))) <EOF>)

**Comment by kaby76** [comment]
The reason that getText() is null is because the tree has not been constructed yet. You can verify this in a debugger. The "enter" methods are called before parsing children. This brings up the point: why are you using parser listeners?

**Comment by quantrpeter** [comment]
> The reason that getText() is null is because the tree has not been constructed yet. You can verify this in a debugger. The "enter" methods are called before parsing children. This brings up the point: why are you using parser listeners?

oh yeah, you are right. I changed to use exit methods, thanks a lot
