### ISSUE TITLE
Parser seems to get exponentially slower the more clauses i add to an expression

### ISSUE THREAD

**Issue by ArthwitRail** [antlr/grammars-v4#429]
First thing to say is that i am convinced my problem is a grammar problem and not an issue with ANTLR but feel i should post something as the behaviour i am see is quite odd...

I am working on a grammar for a legacy language for a 4GL called PROIV i can parse pretty much everything from its scripting language called logic (its basic like) but there is one thing which has alluded me so far and try as i might i cannot seem to create a grammar which will parse a certain type of expression. 

I've refactored my grammar and distilled it down to the attached. 

So one of the wierd things in this language is that there is a shorthand mechanism for defining multiple AND and OR operations; e.g.

if A = 1, 3, 4, 5, b,  c + d
then
  do stuff
endif

what this really means is 

if A = 1 OR A = 3 OR A = 4 OR A = 5 OR A = b OR A = c+d
then
do stuff
endif

You can also do the same with not equals operations which equate to AND

e.g. 

if A # 3, 4, 5
then
do stuff
endif

means

if A # 3 AND A # 4 AND A # 5
then
do stuff
endif

Below (and attached) are snips from my cut down grammar, what i find is that as soon as i add in the highlighted line for the expression list then the parse gets exponentially slower:

Parsing 

A = 1 AND B = 2 AND C = 3 AND  D = 4 AND E = 5 AND F = 6 AND G = 7 AND H = 8 AND I = 9 

is reasonably quick; blink and you miss it in my junit tests, however, add on a couple more clauses and it starts to slow down to a point where its viable as i know i have code to parse which is at least 20+ AND clauses.

expression
    :   primary
    |   'NOT' expression
    **|     expression ('=' | '#' | '<>') expression_list**
    |   expression ('AND' | 'OR' ) expression
    ;

expression_list
    :   expression (',' expression)*
    ;

primary
    :   Identifier
    |   NumericLiteral
    |   '(' expression ')'
    ;

So my question - its kind of a bit of everything :

Is my grammar too general and / or am i asking too much of the recursion in the parser to parse these types of expression ?

Any advice greatly appreciated as i this is driving me nuts !

thanks!

[lgc.txt](https://github.com/antlr/grammars-v4/files/355989/lgc.txt)

**Comment by KvanTTT** [comment]
Try to convert left-recursive expression to non left-recursive as it [described](http://blog.ptsecurity.com/2016/06/theory-and-practice-of-source-code.html#java--and-java8-grammars) in my article.

**Comment by ArthwitRail** [comment]
ok - i can see where you are going with this - I'll give it a go and see what happens.
thanks

**Comment by KvanTTT** [comment]
Such conversion especially important for deep recursion expressions (long AND clause sequence in your case).

**Comment by teverett** [comment]
@ArthwitRail, @KvanTTT can I close this issue?

**Comment by ArthwitRail** [comment]
Sure can do

The technique suggested did work OK I should have responded accordingly

Thanks
James


On 12 Apr 2017 15:04, "Tom Everett" <notifications@github.com> wrote:

@ArthwitRail <https://github.com/ArthwitRail>, @KvanTTT
<https://github.com/KvanTTT> can I close this issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/antlr/grammars-v4/issues/429#issuecomment-293587353>,
or mute the thread
