### ISSUE TITLE
PLSQL g4 grammar : suggestion to split and group functions

### ISSUE THREAD

**Issue by RobertPastor** [antlr/grammars-v4#431]
in the g4 grammar, the standard_function rule may be re organised some where like this :+1: 

standard_function
    :   string_function
    |       numeric_function_wrapper
    |   other_function
    ;

string_function
    :    SUBSTR '(' table_element COMMA numeric (COMMA numeric)? ')'
    |    TO_CHAR '(' (table_element|standard_function)  ( COMMA quoted_string)? ')' 
    |    DECODE '(' expression_wrapper ( COMMA expression_wrapper )\*  ')'
    |    CHR '(' concatenation_wrapper USING NCHAR_CS ')'
        |    NVL '(' expression_wrapper COMMA expression_wrapper ')'
    |    TRIM '(' ((LEADING | TRAILING | BOTH)? quoted_string? FROM)? concatenation_wrapper ')'
    ;

numeric_function_wrapper
    :   numeric_function ( single_column_for_loop | multi_column_for_loop )?
    ;

numeric_function
    :   SUM '(' (DISTINCT|ALL)? expression ')'
    |   COUNT '(' ( '*' | ((DISTINCT | UNIQUE | ALL)? concatenation_wrapper)? ) ')' over_clause?
    |   ROUND '(' expression_wrapper (COMMA UNSIGNED_INTEGER)?  ')'
    |   AVG '(' (DISTINCT | ALL)? expression_wrapper ')'
    |   MAX '(' (DISTINCT | ALL)? expression_wrapper ')'
    ;

It is possible to create another sub group of DATETIME function.

**Comment by teverett** [comment]
Please issue a pull request

**Comment by StephenDrewLDS** [comment]
@RobertPastor  What exactly are the criteria for adding functions here, like `SUBSTR` and `TO_CHAR`, but not others, like `INSTR` or `TO_DATE`?

**Comment by stephendrew** [comment]
I can see the need for some of these functions with peculiar syntax, e.g. `CHR(n USING NCHAR_CS)`, `TRIM` and `DECODE`.

But others such as `TO_CHAR`, `SUBSTR` seem to be simple functions from the `STANDARD` package....shouldn't these be treated as any other function call?  If not, I propose the entirety of the `STANDARD` package functions are added to the grammar.

**Comment by RobertPastor** [comment]
The idea was to group functions according to their return type.

**Comment by KvanTTT** [comment]
@stephendrew I think your approach more proper.

**Comment by stephendrew** [comment]
I appreciate the rule separation - what I am asking is why only some of the functions from `STANDARD` are provided.  

Also, why draw a distinction between `NVL(expression, expression)`  and `general_element`?

After all, NVL is not necessarily the function from the `STANDARD` package:

```
DECLARE
  
  c VARCHAR2(100);

  FUNCTION NVL(a VARCHAR2, b VARCHAR2)
  RETURN VARCHAR2
  IS
  BEGIN
    DBMS_OUTPUT.put_line('Calling overloaded function');
    IF a IS NULL THEN
      RETURN b;
    END IF;
    RETURN a;
  END;
  
BEGIN
  
  c := NVL('aaa', 'bbb');
  
END;
```

Isn't the grammar supposed to detect syntax, rather than (and indeed, is incapable of detecting) context?

**Comment by stephendrew** [comment]
Additionally, NVL is not just a string function....

```
  function NVL (B1 BOOLEAN, B2 BOOLEAN) return BOOLEAN;

  function NVL(s1 VARCHAR2 CHARACTER SET ANY_CS, s2 VARCHAR2 CHARACTER SET s1%CHARSET)
  return VARCHAR2 CHARACTER SET s1%CHARSET;

  function NVL(n1 NUMBER, n2 NUMBER) return NUMBER;

  --etc...
```

**Comment by RobertPastor** [comment]
Adding more functions should be easier for a grammar's user having an adequate test set.
