### ISSUE TITLE
PL-SQL g4 - duplicated rule in table_ref_aux

### ISSUE THREAD

**Issue by RobertPastor** [antlr/grammars-v4#440]
suggest to suppress one duplicated alternative << dml_table_expression_clause (pivot_clause | unpivot_clause)? >> in
table_ref_aux
    : (dml_table_expression_clause (pivot_clause | unpivot_clause)?
      | '(' table_ref subquery_operation_part\* ')' (pivot_clause | unpivot_clause)?
      | ONLY '(' dml_table_expression_clause ')'
      | dml_table_expression_clause (pivot_clause | unpivot_clause)?)
    flashback_query_clause\* (/_{isTableAlias()}?_/ table_alias)?
    ;

**Comment by teverett** [comment]
Would you be able to submit a pull request with this change?

**Comment by RobertPastor** [comment]
Dear sir , i Will not be able to submit this request before the end of August. Regards.
