### ISSUE TITLE
Swift treatment of 'is' and 'as'

### ISSUE THREAD

**Issue by natefrechette** [antlr/grammars-v4#471]
It seems as though whenever there is a token value used in swift (such as 'is' or 'as', 'for', while, etc) that it fails to parse.  Any ideas about how to resolve this issue?

```
func x(is: Sting) -> String {

}
```

**Comment by artyom-razinov** [comment]
This will be fixed in Swift 3 grammar https://github.com/antlr/grammars-v4/pull/573
