### ISSUE TITLE
Begin syntax is not updated with correct rule

### ISSUE THREAD

**Issue by minne6** [antlr/grammars-v4#482]
I ran the vb6 grammar in antlr parser. First line Begin is going to errornodeimpl. 
I checked the grammar . It is written as 
begin newline+
Moduleconfig+
End

But the syntax of begin from my form is like below

Begin Vb.Form formname

    Begin vb.text txtname

      End

End

Please help me

**Comment by teverett** [comment]
After some grammar cleanup, I think it works now.  #483 483

See here:

https://github.com/antlr/grammars-v4/blob/master/vb6/examples/form2.vb

**Comment by teverett** [comment]
Can you please validate that your example works, so that we can close this?

**Comment by minne6** [comment]
It's working now.. thanks
