### ISSUE TITLE
EDN Format Grammar.

### ISSUE THREAD

**Issue by eprozium** [antlr/grammars-v4#491]
Please add an EDN Format https://github.com/edn-format/edn grammar too (it's a subset of Clojure).

Thanks.

**Comment by Marti2203** [comment]
Hi. I am gonna make a grammar. Could you please make some examples? I hope it is not too late... @eprozium

**Comment by aadrian** [comment]
@Marti2203 a few EDN file examples:

 - https://github.com/bpsm/edn-java/blob/master/src/test/resources/us/bpsm/edn/serializability.edn
 - all files in https://github.com/bpsm/edn-java/tree/master/src/test/resources/us/bpsm/edn/performance
 - https://github.com/clojure/java.jdbc/blob/master/deps.edn
 - https://github.com/seancorfield/dot-clojure/blob/develop/deps.edn

**Comment by Marti2203** [comment]
Thank you! I am currently working on making it, I just need to add tests so that whenever somebody changes something, it can easily be tested.
