### ISSUE TITLE
Calculator.g4 - Lower precedence for '^' to '/'

### ISSUE THREAD

**Issue by tanmaysn** [antlr/grammars-v4#501]
Hi

I was testing the Calculator.g4 grammar for a project of mine and realised that it takes Div '/' as higher precedence to exponent '^', which is wrong.

I tried the following expression and received the attached result in tree.

123 + ((234^4.23 / 345) * 456789) - ((345 / 567) * (7^ 14.23))

![antlr4_parse_tree](https://cloud.githubusercontent.com/assets/7475939/19587637/96fc5c54-977d-11e6-8eb0-858ce1de3e3e.png)

You can see here that [(234^4.23 / 345)] is broken as 234 ^ (4.23/345), while it should have been (234^4.23)/345.

Regards,
Tanmay

**Comment by teverett** [comment]
@tanmaysn please take a look at pull request #502 and let me know if it resolves the problem.

**Comment by tanmaysn** [comment]
@teverett yeah, that works. Thanks!
