### ISSUE TITLE
Found a bug in PHPLexer_CSharpSharwell.g4 

### ISSUE THREAD

**Issue by Hinaser** [antlr/grammars-v4#504]
Hi

I am currently developing original asp parser referring to php parser in this repository and found possibly bug in PHPLexer_CSharpSharwell.g4.

```
public override IToken NextToken()
{
    CommonToken token = (CommonToken)base.NextToken();
    if (token.Type == PHPEnd || token.Type == PHPEndSingleLineComment)
    {
        if (_mode == SingleLineCommentMode)
        {
            // SingleLineCommentMode for such allowed syntax:
            // <?php echo "Hello world"; // comment ?>
            PopMode(); // exit from SingleLineComment mode.
        }
        PopMode(); // exit from PHP mode.
        
        if (string.Equals(token.Text, "</script>", System.StringComparison.Ordinal))
        {
            _phpScript = false;
            token = new CommonToken(ScriptClose);
```

At the last line in the above code snippet, local variable `token` is reassigned with `new CommonToken(ScriptClose)`, but current context stored in token `(CommonToken)base.NextToken()` is completely ignored.

As a result, the new reassigned token misses `StartIndex` and `Line` and so on.

It should be fixed like this:
**BEFORE**
```
token = new CommonToken(ScriptClose);
```
**AFTER**
```
token.type = ScriptClose;
```

Best Regards.

**Comment by KvanTTT** [comment]
Do you want to suggest pull request for this? :)

**Comment by Hinaser** [comment]
Hello @KvanTTT 

Thanks for the suggestion! :D
This will be my first pull request!

I'll soon make it :)

**Comment by Hinaser** [comment]
Please note that I modified source code as
```
token.Type = ScriptClose;
```

I posted to modify `token.type = ...` which was a mistake but `token.Type = ...` is correct.
I didn't notice that `token.type` is not accessible.
