### ISSUE TITLE
Issue with Antlr4 Java 7 Grammar  expression  Parser rule

### ISSUE THREAD

**Issue by sufail** [antlr/grammars-v4#509]
I found this issue for the following input 

public String publishAbsencesApprovalsEvent(Map<String,Object> absenceValues) {

// inside this method there is a pretty much long string which spans around 150 lines.

}

When I try to create a ParseTree for this input file, it's got  hanged like forever.  I guess there is a decision-making issue for the grammar for the below two rules.

typeArguments
    :   '<' typeArgument (',' typeArgument)* '>'
    ;

expression
   :  //many alternatives
   |  expression ('<=' | '>=' | '>' | '<') expression  #logical

When I commented out the #logical alternative and re-ran it's worked. 

I  guess there is a token matching decision from lexer to Parser level which makes it hang forever.
Please let me know if there is a solution for this without altering much of the grammar file.

**Comment by KvanTTT** [comment]
I guess it was fixed in [ANTLR 4.6](https://github.com/antlr/antlr4/releases/tag/4.6) (see `Major performance improvement` section).

So, I'm closing. Reopen if needed.
