### ISSUE TITLE
Issue with PHPParser.g4

### ISSUE THREAD

**Issue by daniangelos** [antlr/grammars-v4#510]
I keep getting the error "cannot create implicit token for string literal" when I try to run the PHPParser.g4 file. 
I always run the PHPLexer.g4 first.
Am I doing something wrong?

**Comment by gqqnbig** [comment]
For anyone else who has the same issue, you have to run something like

```
D:\grammars-v4>antlr4.bat java\java\JavaParser.g4 java\java\JavaLexer.g4
```

If the errors are from IDE (plugin), the errors should disappear too.
