### ISSUE TITLE
Scala Grammar doesn't give correct tokens with ANTLR4 

### ISSUE THREAD

**Issue by shiva10162** [antlr/grammars-v4#517]
I am working on ANTLR tool to parse the Scala file. I used the following grammar for it 👍 [][https://github.com/antlr/grammars-v4/tree/master/scala]((https://github.com/antlr/grammars-v4/tree/master/scala)) .But using this grammar it doesn't give me correct tokens. I addressed my problem here completely with source code and example : [http://stackoverflow.com/questions/40482259/antlr-doesnt-give-correct-output-tokens-for-scala-grammar](http://stackoverflow.com/questions/40482259/antlr-doesnt-give-correct-output-tokens-for-scala-grammar). Please have a look. Cheers !

**Comment by teverett** [comment]
Could you submit a pull request pls.

**Comment by shiva10162** [comment]
yes sure . but I am working on Antlr tool to parse Scala language. I am not working on Scala language grammar.

**Comment by JeremyMarshall** [comment]
It would seem it is this rule
```
opchar           ::= // printableChar not matched by (whiteSpace | upper | lower |
                     // letter | digit | paren | delim | opchar | Unicode_Sm | Unicode_So)
```
which is actually defined as 
```
opchar ::= printableChar
```
and therefore matching square brackets as part of identifiers and so on...

**Comment by chengniansun** [comment]
Hi, 

I came across the same problem. Is there gonna be a fix for this?

Thank you.

**Comment by chengniansun** [comment]
Could some one suggest how to fix this? I am new to Antlr too, but need the scalar parser to work. 

Thanks.

**Comment by tanvohub** [comment]
My recommendation: don't waste of your time on this grammar. It was written by careless people who have no idea about Scala and even didn't care about going through the Scala Specification.

It's even bad that they changed the syntax of Scala language.

**Comment by KvanTTT** [comment]
Feel free to not use it. This repository is developing by the community for free. So, no claims to authors.

**Comment by nomailforme** [comment]
Hi @KvanTTT ,
Are there any efforts / plans to fix this at the moment ? Or is it not on the priority list for now ?
Please update us so that we can look at other options / try to fix it

**Comment by KvanTTT** [comment]
I have no plans to improve Scala grammar :)
