### ISSUE TITLE
Protobuf 3 grammar

### ISSUE THREAD

**Issue by mwillema** [antlr/grammars-v4#519]
I've written an [ANTLR 4 grammar for Protobuf 3](https://github.com/mwillema/protobuf-parser/blob/master/src/main/antlr4/com/marcowillemart/protobuf/parser/Protobuf.g4). I'd be more than happy to share it and to contribute to this repository.

**Comment by teverett** [comment]
Fantastic.  Please submit a pull request, with some test cases.

**Comment by mwillema** [comment]
The pull request is in [issue #521](https://github.com/antlr/grammars-v4/pull/521). Sorry I didn't figure out how to attach the pull request to this issue.

**Comment by mwillema** [comment]
I guess the issue can be closed since the pull request has been merged :-)
