### ISSUE TITLE
Java8 grammar unbearably slow

### ISSUE THREAD

**Issue by ghost** [antlr/grammars-v4#528]
I work on a source level static analysis tool and tried to use the Java8 grammar. It's impossible to use, because parsing a moderate Java project takes almost *a minute* ! I've tried my parser on multiple Java projects, and it's the same. I understand the Java7 grammar is faster, but that doesn't help me since we must target Java 8 (Java 7 is EOL'ed anyway)

What can be done? As it is, the grammar is complete, yet unusable.

**Comment by pureconfig** [comment]
I should add that Eclipse (JDT) parses the same sample project in less than two seconds.

**Comment by KvanTTT** [comment]
I'am working on Java8 optimized grammar but not so fast as I would like to.

**Comment by pureconfig** [comment]
@KvanTTT Not working as fast as you would like to, or is the grammar not as fast as you would like to? :)

**Comment by KvanTTT** [comment]
Oops, ambiguity :) the statement related to me.

**Comment by maybeec** [comment]
Any progress here? Maybe an intermediate version of the optimized grammar, I can try? :)

**Comment by KvanTTT** [comment]
No :(

2017-03-01 0:06 GMT+03:00 Malte Brunnlieb <notifications@github.com>:

**Comment by jundl77** [comment]
Having the same issue, but with Javascript target

**Comment by KvanTTT** [comment]
Relative simple advice: rewrite all expression rules to left-recursive. I mean [conditionalExpression](https://github.com/antlr/grammars-v4/blob/master/java8/Java8.g4#L1225) and descendants. This should decrease rules count and improve performance.

**Comment by jundl77** [comment]
Is there no Java8 grammar out there that has this already done? Seems like a very tedious thing to do.

**Comment by KvanTTT** [comment]
Sure. Java7 for example: https://github.com/antlr/grammars-v4/blob/master/java/Java.g4#L497

**Comment by maybeec** [comment]
Is there any way of checking some complexity metrics for a grammar? I found the antlr4 IntelliJ plugin already quite useful, but it provides just a profiler for specific inputs. I would like to have something like given a grammar, the ANTLR4 parser would have X DFA states, Y NFA states, etc. Or more easy as you indicated, the grammar summarizes Z productions. Is there any tool providing such analysis results?

**Comment by KvanTTT** [comment]
Try a new optimized [java8-pt](https://github.com/antlr/grammars-v4/tree/master/java8-pt) grammar which based on Java7.

**Comment by KvanTTT** [comment]
Please, use fast and optimized [java](https://github.com/antlr/grammars-v4/tree/master/java) grammar.
