### ISSUE TITLE
Swift grammar not yet converted to v4?

### ISSUE THREAD

**Issue by palfvin** [antlr/grammars-v4#533]
I tried using the Swift grammar with v4 and found it wouldn't handle the most basic parsing tasks properly. For example, it parsed the expression `import rx.java` as the statement `import rx` followed by the expression `.java`.

I traced the problem to an error in the definition of `import_path`. Instead of the acceptable `import_path_identifier ('.' import_path_identifier)*` or `import_path '.' import_path_idenfitier | import_path_identifier`, it is using 'import_path_identifier | import_path_identifier . import_path`.

I don't know if this used to work in antlr3 and stopped working in antlr4 or whether this has always been a problem. The v4 documentation describes the acceptable "left tail recursion" patterns, but doesn't mention "right tail recursion", which I gather (?) the existing format represents.

This in turn led me to wonder if anyone was using this grammar. Does the fact that the Swift compiler is now open sourced mean that people are using the compiler software direction for translation tasks? I tried looking at the Swift repository and it wasn't obvious to me how one could "plug in" to the parser in the way that ANTLR allows.

**Comment by johndpope** [comment]
This should be fixed now.

I had a java parser working the other day  - see here
https://github.com/johndpope/Antlr-Swift-Runtime/tree/master/Test/Test

Can close this / reopen if necessary

**Comment by johndpope** [comment]
Re-reading this / you may find this library more appropriate https://github.com/yanagiba/swift-ast

**Comment by palfvin** [comment]
@johndpope Thanks. I did end up finding and using the swift-ast library for my needs, but am glad to see this get addressed.
