### ISSUE TITLE
Java8 grammar code generation with Python3 target causes a symbol conflict

### ISSUE THREAD

**Issue by metebalci** [antlr/grammars-v4#540]
Java8 grammar includes a rule named "type" and this clashes with Python3 target, antlr tool raises this error "error(134): Java8.g4:73:0: symbol type conflicts with generated code in target language or runtime" but generates the code. The generated Python3 code is - I believe - syntactically correct since type is not a keyword but a builtin, however this should be avoided as well. Is it the purpose of this repo to have all grammars to be compatible with all target languages ?

**Comment by teverett** [comment]
This repo was created as a repository of grammars that generate valid Java code and work with a minimal Java test suite.  In fact, I am trying to enforce that all changes which go in include test cases and work with the latest version of Antlr4.  

At this time, I accept grammars which generate code for languages other than Java, but it's beyond the scope of the repo, or the existing test framework, to validate those.

**Comment by metebalci** [comment]
OK thanks, then I will close this issue and #541 since both is related to non-Java targets.
