### ISSUE TITLE
Java8 grammar is not target agnostic

### ISSUE THREAD

**Issue by metebalci** [antlr/grammars-v4#541]
Similar to #117 (which I think has been fixed in 8debf366ea94d358303feb095f853c1c23bda9bb) , Java8 grammar includes Java code actions for JavaLetter and JavaLetterOrDigit which causes Java code to be generated in other target languages. (trying with Python3)

Maybe similar to my other question in #540, should a single grammar work with all target languages, or should a different grammar be created in such cases ?

**Comment by metebalci** [comment]
Closing this issue per discussion in #540

**Comment by cowang** [comment]
See my [comments](https://github.com/antlr/antlr4/issues/1885) for more than you ever wanted to know.
