### ISSUE TITLE
tsql predicates

### ISSUE THREAD

**Issue by bbeuning** [antlr/grammars-v4#545]
My use of tsql.g4 with C++ is failing to parse

```sql
IF @ResultedQuery IS NOT NULL  AND LEN(RTRIM(LTRIM(@ResultedQuery))) > 0  
```

with error
   no viable alternative at input 'LEN('

I am a long time LEX/YACC user but new to ANTLR.
This part of the tsql grammar seems ambiguous to me.

```antlr
predicate
    | expression comparison_operator expression
```

```antlr
expression
    | expression comparison_operator expression                #binary_operator_expression
```

**Comment by KvanTTT** [comment]
Pull request is welcome! :)

**Comment by ohyesboy** [comment]
The lasted grammar as I post this comment should be able to parse your line from the root 'batch'

Here is a parse tree of 

```sql
IF @ResultedQuery IS NOT NULL AND LEN(RTRIM(LTRIM(@ResultedQuery))) > 0
    Print 'hello'
```

LEN is a **scala_function_name**


![image](https://cloud.githubusercontent.com/assets/3621688/22664306/0d51bec6-ec7e-11e6-96df-0ec50b21bc99.png)

**Comment by ohyesboy** [comment]
The book **The Definitive ANTLR 4 Reference** by Terence should cover all the details,

`#binary_operator_expression` is a 'label' of rule `expression`, it's kind of like a shortcut to define subrules, it makes the rule `expression` 'invisible' as a virtual method in the listener, but you can listen to all the 'subrules' defined by labels, in C# it looks like this.

```CSharp
public virtual string VisitBinary_operator_expression(tsqlParser.Binary_operator_expressionContext context)
{...}
```

**Comment by zcao** [comment]
The grammar is good for your expression, maybe you are not running on latest grammar on the correct root rule (tsql_file) ?

**Comment by KvanTTT** [comment]
So, can we close this issue eventually?
