### ISSUE TITLE
Java Grammar - booleanLiterals true and false won't work

### ISSUE THREAD

**Issue by timbriant** [antlr/grammars-v4#549]
BooleanLiterals, when assigned to an identifier are not working.

**Comment by maybeec** [comment]
which grammar are you talking about? java7 or java8?

**Comment by KvanTTT** [comment]
It works, take a look at https://github.com/antlr/grammars-v4/blob/master/java/examples/AllInOne7.java#L68 Otherwise it's not clear what you mean.
