### ISSUE TITLE
Error while generating Lexer with Python3 "antlr4 -Dlanguage=Python3 Python3.g4"

### ISSUE THREAD

**Issue by aptrishu** [antlr/grammars-v4#562]
error(134): Python3.g4:677:0: symbol str conflicts with generated code in target language or runtime
error(134): Python3.g4:569:3: symbol str conflicts with generated code in target language or runtime

**Comment by KvanTTT** [comment]
Try to replace `str` to `str_` and say whether this issue has been resolved.

**Comment by KvanTTT** [comment]
Already fixed. I recommend using universal Python 2/3 grammar from https://github.com/antlr/grammars-v4/tree/master/python
