### ISSUE TITLE
Create C# target for grammars-v4/antlr4

### ISSUE THREAD

**Issue by zcao** [antlr/grammars-v4#570]
The Lexer file there has a custom base class LexerAdaptor which is in java and python, someone please write a C# target of LexerAdaptor class, so the grammar can be used in C#

**Comment by KvanTTT** [comment]
What grammars are you interested in?

**Comment by Marti2203** [comment]
I think you can close this issue, because there is a LexerAdaptor. Not so sure if it properly working, because of anoter issue that is with the ANTLRv4 grammar C# version (#1108).
