### ISSUE TITLE
Event ExitVsICS without EnterVsICS using grammar VisualBasic6.g4

### ISSUE THREAD

**Issue by lsalamon** [antlr/grammars-v4#578]
It is correct to have an event ExitVsICS without occurrence of EnterVsICS ?
The code I try parse is:
VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ConstDirective"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Const EvalDirective = 0

Public Function EvalConstDirective() As Long
#If EvalDirective Then
    EvalConstDirective = 1
#Else
    EvalConstDirective = 0
#End If
End Function

Using Antlr4.4.5.3 on Visual Studio 2015 C# project.

**Comment by lsalamon** [comment]
The code above do not parse if line with Const is like that:
#Const EvalDirective = 0

#Const directive is used to define conditional compiler constants for Visual Basic.. (From book Language Reference - Volume 1, pag. 3)

**Comment by teverett** [comment]
Please try again using Antlr 4.7

**Comment by lsalamon** [comment]
Hi, thanks for response but no way to try. Get this error:
Uninstall-Package : Unable to uninstall 'Antlr4.Runtime.4.5.3' because 'Antlr4.4.5.3' depends on it.

I have this packages:
PM> Get-Package
Id                                  Versions                                 ProjectName                                                                                                                                                                           
--                                  --------                                 -----------                                                                                                                                                                           
Antlr4                              {4.5.3}                                  VisualBasic6                                                                                                                                                                          
Antlr4.Runtime                {4.5.3}                                  VisualBasic6

**Comment by lsalamon** [comment]
Are there any suggestions?

**Comment by teverett** [comment]
I've committed your example to the source tree and I can confirm that it parses.  In terms of your question, I'm not an expert in VB6, so I can't answer.

**Comment by lsalamon** [comment]
There is a mistake in my code. I left line with error out.
That's it:

It is correct to have an event ExitVsICS without occurrence of EnterVsICS ?
The code I try parse is:
VERSION 1.0 CLASS
BEGIN
MultiUse = -1 'True
Persistable = 0 'NotPersistable
DataBindingBehavior = 0 'vbNone
DataSourceBehavior = 0 'vbNone
MTSTransactionMode = 0 'NotAnMTSObject
END
Attribute VB_Name = "ConstDirective"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
#Const EvalDirective = 0 ' HERE THE BUG

Public Function EvalConstDirective() As Long
#If EvalDirective Then
EvalConstDirective = 1
#Else
EvalConstDirective = 0
#End If
End Function

Using Antlr4.4.5.3 on Visual Studio 2015 C# project.

**Comment by lsalamon** [comment]
The code above generate two situations:
1) generate ExitVsICS without event EnterVsICS;
2) line "Const EvalDirective = 0" start with # it not parse
#Const directive is used to define conditional compiler constants for Visual Basic.. (From book Language Reference - Volume 1, pag. 3)

**Comment by lsalamon** [comment]
Are there any suggestions?

**Comment by teverett** [comment]
No suggestions yet.  Maintenance of the grammars tree is a strictly volunteer effort.  Perhaps later someone will find time.

**Comment by Marti2203** [comment]
Hello, is this issue still valid?

**Comment by KvanTTT** [comment]
> Maintenance of the grammars tree is a strictly volunteer effort.

Not strictly but rather mostly.

**Comment by Marti2203** [comment]
I just checked this issue and all is good, both code examples work. This can be closed.
