### ISSUE TITLE
C grammar function calls

### ISSUE THREAD

**Issue by jhcrain** [antlr/grammars-v4#579]
When I use the latest version of the C.g4 grammar to parse this code I get an unexpected result:

    void main ()  {
        a = f (b); /* recognized by the statement rule (expected behavior) */
        f (a);     /* recognized by the declaration rule (unexpected behavior) */
        g (a, b);  /* recognized by the statement rule (expected behavior) since there's more than one arg */
    }

Any suggestions for how to correct this in the grammar would be helpful. I could probably hack around it while processing the parse tree but would rather avoid.

PNG of the parse tree generated by Antlr4 test rig:
![c-function-calls](https://cloud.githubusercontent.com/assets/16268092/24169098/87119702-0e4a-11e7-9412-e9e9149ce8bf.png)

----- Update -----

The second line of the directDeclarator rule (commented-out below) is the one causing the behavior. Now to see the effect of removing this on real declarations.

    directDeclarator
        :   Identifier
        // |   '(' declarator ')'
        |   directDeclarator '[' typeQualifierList? assignmentExpression? ']'
        |   directDeclarator '[' 'static' typeQualifierList? assignmentExpression ']'
        |   directDeclarator '[' typeQualifierList 'static' assignmentExpression ']'
        |   directDeclarator '[' typeQualifierList? '*' ']'
        |   directDeclarator '(' parameterTypeList ')'
        |   directDeclarator '(' identifierList? ')'
        ;

Still hoping for suggestions on how to work around this ambiguity.

**Comment by teverett** [comment]
@jhcrain hello.  Thanks for the issue report.  Were you able to resolve the problem?

**Comment by jhcrain** [comment]
@teverett, no I haven't resolved it by fixing the grammar. I only hacked around the problem as described above (commenting out part of the directDeclarator rule). Luckily that change hasn't affected any work since then. Thx.

**Comment by Marti2203** [comment]
Hi, is this issue still valid?

**Comment by jhcrain** [comment]
Marti2203: It can be closed.
