### ISSUE TITLE
c# eacmscript _input

### ISSUE THREAD

**Issue by zgsxtyzgd** [antlr/grammars-v4#582]
C# version of the "ECMAScript.G4" has some errors.
For example, `IToken ahead = _input. Get(possibleIndexEosToken);`.
In fact the current object does not `_input` this member.

**Comment by KvanTTT** [comment]
Try to use [Sam Harwell C# runtime](https://www.nuget.org/packages/Antlr4/) instead of [standart C# runtime](https://www.nuget.org/packages/Antlr4.Runtime.Standard/).

**Comment by zgsxtyzgd** [comment]
Using the " Sam Harwell C# runtime  4.5.3" You still have errors
=====
Context.Stop = _input.Lt(-1);
error:  Context.Stop  is readonly

**Comment by KvanTTT** [comment]
`Context.Stop = _input.Lt(-1);` string is not presented in this grammar. Where did you find it?

**Comment by zgsxtyzgd** [comment]
in ECMAScriptParser.cs at 3776 line `Context.Stop = TokenStream.Lt(-1);`

**Comment by KvanTTT** [comment]
Sorry, my fault. For EcmaScript you should use C# standard runtime.

**Comment by zgsxtyzgd** [comment]
but standard c#runtime not `_input`?  @

**Comment by xied75** [comment]
Guys, just use ```InputStream.LT``` to replace ```_input.Lt```.

**Comment by jpwiddy** [comment]
I also get errors for both runtimes as well.

**Comment by jpwiddy** [comment]
Is this resolved?

**Comment by KvanTTT** [comment]
Try to use the new [JavaScrit](https://github.com/antlr/grammars-v4/tree/master/javascript) grammar. It's working both for C# and Java runtimes.
