### ISSUE TITLE
Problem with the C grammar but it's a more general question...

### ISSUE THREAD

**Issue by smourier** [antlr/grammars-v4#585]
With the C sample grammar (https://github.com/antlr/grammars-v4/blob/master/c/C.g4), with ANTLR4 C#, this expression "(x) * (y)" doesn't parse correctly (it doesn't see the multiplication operator but thinks it's a cast operation) while this "x * y" does. I have the same kind of problem with my own grammar. Since the grammar is supposed to follow the C standard, I was wondering if it's a general problem to the way ANTLR parses whitespaces or something else? or is it just the grammar is wrong? Or it's me who's wrong?

**Comment by smourier** [comment]
With the C sample grammar, this expression "(x) * (y)" doesn't parse correctly while this "x * y" does. I have the same kind of problem with my own grammar. I was wondering if it's a general problem to the way ANTLR parses whitespaces, or is it just the grammar is wrong?

**Comment by jhcrain** [comment]
I'm using the Antlr C grammar with Antlr4 C# also, so I tried your example. But I don't get the results you report. It's not handled by the CAST rule; it's handled by the PrimaryExpression rule (as I'd expect).

When I try this C code, I get the parse tree in the attached PNG (from Antlr's test rig).
    int main (void)  {
        (x) * (y);
    }

I see the same thing if the multiplication is assigned:
    int main (void)  {
        z = (x) * (y);
    }

I believe I'm using the latest C.g4. It's date Feb 10, '17.

Cheers -

![x-times-y-w-parens](https://cloud.githubusercontent.com/assets/16268092/25006360/3890b75e-2022-11e7-9a5c-da31b1f37a49.png)

**Comment by smourier** [comment]
Hi, thanks for your answer. The code I was running was this one:

        static void Main(string[] args)
        {
            string text = @"(x) * (y)";

            var stream = new AntlrInputStream(text);
            var lexer = new CLexer(stream);
            var tokens = new CommonTokenStream(lexer);
            var parser = new CParser(tokens);

            var expr = parser.expression();
        }

And it's giving me back a cast expression.

**Comment by jhcrain** [comment]
Perhaps it's a context problem; no shortage of those in C/C++. I posted about a different parsing ambiguity issue for C declarations here recently.

If so, you might resolve it by giving the parser more context.

I'm building a transpiler, so I never feed source text directly into the Lexer as you're doing. Instead, I feed it a file stream, like this.
```
    using (StreamReader fileStream = new StreamReader (srcFileName))   {
        var inputStream = new AntlrInputStream (fileStream);
        var lexer       = new CLexer (inputStream);
        var tokenStream = new CommonTokenStream (lexer);
        var parser      = new CParser (tokenStream);
        var cst  = parser.translationUnit ();
```
My input files are always complete C programs. The parser has always behaved as expected with those files (aside from the issue I mentioned earlier).

Unless you're trying to build an interactive interpreter, sending complete C programs might work better by providing more context.

Cheers -

**Comment by pureformat** [comment]
I can't even get C.g4 to accept C files containing #include statements. Not even in the 4.7 IntelliJ tool window.

**Comment by jhcrain** [comment]
@pureformat, IIRC the C parser does not handle C preprocessor commands (such as #include, #define, etc.). 

If you want support for those, you'd need to modify the C4 grammar or develop your own. Here's some [discussion of the topic](http://antlr.1301665.n2.nabble.com/How-to-do-preprocessing-in-antlr-v4-td7579253.html).

**Comment by pureformat** [comment]
I guess

    /** C 2011 grammar built from the C11 Spec */

is a blatant lie then.

**Comment by jimidle** [comment]
The C specification does not cover macro processing and pre-processing
directives. You need a separate C pre-processor to deal with those
directives before passing it to the C parser. this is the case for all tool
chains. If you are not compiling it, but just want to parse it, then you
could extend the grammar to accept lines beginning with # as a PREPROCESS
token, but that won't expand macros or process conditionals etc.

There are no lies here.

Jim

**Comment by pureformat** [comment]
@jimidle since #include is most definitely part of the spec, there are *some* lies here.

**Comment by jimidle** [comment]
Ok. Then don't use it. What do I know eh?

**Comment by pureformat** [comment]
> Ok. Then don't use it. What do I know eh?

Dunno.

**Comment by Enerccio** [comment]
That grammar is useless since macros should not even be there after preprocessing so why are they included in the grammar?

**Comment by briancullinan** [comment]
I switched to CPP14.g4 for parsing C files, and it works with great success! But I am debugging a unary operator not getting picked up for some reason.
```
	style &= ~UI_PULSE;
```
Parses as 
```
{
  "type": "IdexpressionContext",
  "children": [
    {
      "type": "UnqualifiedidContext",
      "children": [
        {
          "type": "TerminalNode",
          "value": "~",
          "range": [
            3250,
            3250
          ]
        },
        {
          "type": "ClassnameContext",
          "children": [
            {
              "type": "TerminalNode",
              "value": "UI_PULSE",
              "range": [
                3251,
                3258
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by Marti2203** [comment]
Hi,
Do you think this issue is still valid or can it be closed?

**Comment by smourier** [comment]
@Marti2203 - as for me it's ok to close.

**Comment by Marti2203** [comment]
Okay
