### ISSUE TITLE
Issue with parsing exponents in Php grammar

### ISSUE THREAD

**Issue by prateekgulati** [antlr/grammars-v4#586]
E(exponential) symbol is not parsed by the antlr using Php grammar
eg `$float = 7E-10;` gives an error node in multiplicationExpression

**Comment by KvanTTT** [comment]
It's case insensitive issue. Please read [doc](https://github.com/antlr/antlr4/blob/master/doc/case-insensitive-lexing.md) and use `CaseChangingCharStream` for this grammar.
