### ISSUE TITLE
grammars-v4 C parsers

### ISSUE THREAD

**Issue by ty6tu7uytr** [antlr/grammars-v4#587]
Can ANTLR create C parsers for the grammars in *grammars-v4*? Or can it only create parsers for Java?

**Comment by teverett** [comment]
This may be of interest to you

https://github.com/antlr/antlr4-cpp

**Comment by ty6tu7uytr** [comment]
> This may be of interest to you

That's C++ only, thuogh. No C.

**Comment by teverett** [comment]
Correct. AFAIK there is no C backend for Antlr4 yet.
