### ISSUE TITLE
TSQL - create_index doesn't support multiple columns

### ISSUE THREAD

**Issue by zhongxiao37** [antlr/grammars-v4#597]
TSQL allows index on multiple columns. `create_index` can be updated as below.

`create_index`
    `: CREATE UNIQUE? clustered? INDEX id ON table_name_with_hint '(' id (ASC | DESC)? ( ',' id (ASC | DESC)? )* ')'`
    `(index_options)?`
    `(ON id)?`
   ` ';'?`
  `  ;`

**Comment by KvanTTT** [comment]
Hi! Can you propose a pull request for this?

**Comment by zhongxiao37** [comment]
Can be closed since this is covered in #608
