### ISSUE TITLE
CPP grammar: Creating a reference of typename 'class'

### ISSUE THREAD

**Issue by prateekgulati** [antlr/grammars-v4#598]
When creating a reference variable for classtype, statement is parsed as an expression statement instead of declaration statement
eg 
`string foo = 'Hello';` is parsed as declaration statement 
but `string& fooRef = foo;` is parsed as expression statement and hence the complete subtree after that is flawed.

**Comment by Marti2203** [comment]
Hi, I am currently reworking the C++ grammar. For the given code `string& fooRef = foo;` I get this
![image](https://user-images.githubusercontent.com/7456946/91658979-f30a7c00-eacc-11ea-8347-7acfc7013bf8.png)
Can you please check whether you wanted that?

**Comment by Marti2203** [comment]
Close please @teverett
