### ISSUE TITLE
Migrating grammar from Antlr3 to Antlr4

### ISSUE THREAD

**Issue by mandeepsb** [antlr/grammars-v4#604]
The following is my grammar file from Antlr3. When I try to migrate this to Antlr4 the errors appear. Please see the list of error at the end. Can you please let me know how these errors can be resolved and migrate this file to Antlr4?
-------------------------------------------------------------------------------------------------------
grammar Pvrs;

options
{
    language=CSharp3;
	output=AST;
	ASTLabelType=CommonTree;
}

tokens	//	Imaginary Tokens
{
	Assignation;
	Integer;
	Float;
	String;
	Variable;
	MemberInvocation;
	ParameterList;
	Statement;
	Script;
	Product;
	Sum;
	Substraction;
	Negative;
	Negation;
	And;
	Or;
	LogicalRelation;
	Branching;
}

@lexer::header {#pragma warning disable 3021}
@lexer::modifier{internal}
@lexer::namespace{Energy.Test.Com.ABC.Mobility.Scripting}
@parser::header {#pragma warning disable 3021}
@parser::modifier{internal}
@parser::namespace{Energy.Test.Com.ABC.Mobility.Scripting}

//	Parser Rules
 
//	Script ; needs to start with a lower case, otherwise interpreted as a lexer rule
public script : statement* -> ^(Script statement*);

//	Statements
statement : ('if' '(') => branching
//	Early catch of an error
 | (LITERAL '(') => (LITERAL) {throw new ParsingException();}
 | assignation;

//	Branching
branching : 'if' '(' branchingCondition ')' '{' script '}' ('else' '{' script '}')? ->
	^(Branching branchingCondition script script?);
branchingCondition : logicArithExp;

//	Assignation
assignation : leftHandExp EQUAL rightHandExp -> ^(Assignation leftHandExp rightHandExp);
leftHandExp : memberInvocation;
rightHandExp options{backtrack=true;} : 
//	Early catch of an error
(LITERAL '(') => (LITERAL) {throw new ParsingException();}
 | numArithExp
 | string
 | '(' logicArithExp ')' -> logicArithExp
 | '(' logicalRelation ')' -> logicalRelation;

//	Member Invocations
memberInvocation : memberInvocAtom memberInvocationItem+ -> ^(MemberInvocation memberInvocAtom memberInvocationItem+);
memberInvocAtom : '(' numArithExp ')' -> numArithExp
 | leafObject;
memberInvocationItem : (DOT LITERAL parameterList)
 => DOT LITERAL parameterList -> ^(LITERAL parameterList)
 | DOT LITERAL -> ^(LITERAL);
parameterList : '(' rightHandExp (',' rightHandExp)* ')' -> ^(ParameterList rightHandExp rightHandExp*)
  | '(' ')' -> ^(ParameterList);

//	Logical arithmetics
logicArithExp : andExp ('||' andExp)* -> ^(Or andExp andExp*);
andExp : andAtom ('&&' andAtom)* -> ^(And andAtom andAtom*);
andAtom : logicArithAtom | '!' logicArithAtom -> ^(Negation logicArithAtom);
logicArithAtom options{backtrack=true;} : '(' logicArithExp ')' -> logicArithExp
 | '(' logicalRelation ')' -> logicalRelation
 | logicalRelation
 | memberInvocation
 | variable;

//	Logical relations
logicalRelation : logicalRelationAtom r=('==' | '!=' | '<' | '<=' | '>' | '>=') logicalRelationAtom
   -> ^(LogicalRelation $r logicalRelationAtom logicalRelationAtom);
logicalRelationAtom : numArithExp | string;

//	Numerical arithmetics
numArithExp : productExp sumItem* -> ^(Sum productExp sumItem*);
sumItem : op=('+' | '-') productExp -> ^($op productExp);
productExp : productAtom productItem* -> ^(Product productAtom productItem*);
productItem : op=('*' | '/') productAtom -> ^($op productAtom);
productAtom : arithAtom	| '-' arithAtom -> ^(Negative arithAtom);
arithAtom options{backtrack=true;} : memberInvocation
 | '(' numArithExp ')' -> numArithExp
 | variable
 | number;

//	Leaf Objects
variable  : LITERAL -> ^(Variable LITERAL);
number : INTEGER -> ^(Integer INTEGER) | INTEGER'.'INTEGER -> ^(Float INTEGER INTEGER);
string : QUOTED_TEXT -> ^(String QUOTED_TEXT);
leafObject : number | variable | string;

//	Lexer Rules
INTEGER  : ('0'..'9')+;
LITERAL  : ('a'..'z' | 'A'..'Z')(('a'..'z' | 'A'..'Z') | '0'..'9')*;
TEXT  : (('a'..'z' | 'A'..'Z') | '0'..'9')*;
QUOTED_TEXT : '"' (~ '"')* '"';
EQUAL    : '=';
WS :  (' '|'\t'|'\r'|'\n')+ {Skip();};
DOT : '.' ;
-------------------------------------------------------------------------------------------------------

**ERRORS**
Error		'^' came as a complete surprise to me	108	
Error		'∩' came as a complete surprise to me	1	
Error		'┐' came as a complete surprise to me	1	
Error		'╗' came as a complete surprise to me	1	
Error		(...)=> syntactic predicates are not supported in ANTLR 4	48	
Error		(...)=> syntactic predicates are not supported in ANTLR 4	50	
Error		(...)=> syntactic predicates are not supported in ANTLR 4	63	
Error		(...)=> syntactic predicates are not supported in ANTLR 4	74	
Error		mismatched input 'grammar' expecting SEMI	1	
Error		Pvrs.g4::: syntax error: mismatched character '/' expecting '{'

**Comment by teverett** [comment]
Here's a blind translation.   I don't know if it's right since I don't know what PVR is (well, I can guess...).  Now that you have a antlr4 grammar it would be kind of you to issue a pull request, explain what PVR is and give some example input files.


grammar pvrs;

script : statement* ;

statement 
    : ('if' '(') 
    | (LITERAL '(') 
    | assignation;

branching 
    : 'if' '(' branchingCondition ')' '{' script '}' ('else' '{' script '}')? 
    ;

branchingCondition 
    : logicArithExp
    ;

assignation 
    : leftHandExp EQUAL rightHandExp 
    ;

leftHandExp 
    : memberInvocation
    ;

rightHandExp  
    : (LITERAL '(') 
    | numArithExp
    | string
    | '(' logicArithExp ')' 
    | '(' logicalRelation ')';

memberInvocation 
    : memberInvocAtom memberInvocationItem+ 
    ;

memberInvocAtom 
    : '(' numArithExp ')' 
    | leafObject;

memberInvocationItem 
    : (DOT LITERAL parameterList)
    | DOT LITERAL ;

parameterList 
    : '(' rightHandExp (',' rightHandExp)* ')' 
    | '(' ')';

logicArithExp 
    : andExp ('||' andExp)* ;

andExp 
    : andAtom ('&&' andAtom)* ;

andAtom 
    : logicArithAtom | '!' logicArithAtom ;

logicArithAtom  
    : '(' logicArithExp ')' 
    | '(' logicalRelation ')'
    | logicalRelation
    | memberInvocation
    | variable;

logicalRelation 
    : logicalRelationAtom r=('==' | '!=' | '<' | '<=' | '>' | '>=') logicalRelationAtom;

logicalRelationAtom 
    : numArithExp | string;

numArithExp 
    : productExp sumItem*;

sumItem 
    : ('+' | '-') productExp ;

productExp 
    : productAtom productItem* ;

productItem 
    : ('*' | '/') productAtom;

productAtom 
    : arithAtom	| '-' arithAtom ;

arithAtom  
    : memberInvocation
    | '(' numArithExp ')' 
    | variable
    | number;

variable 
    : LITERAL ;

number 
    : INTEGER  | INTEGER'.'INTEGER ;

string 
    : QUOTED_TEXT ;

leafObject 
    : number | variable | string;

INTEGER 
    : ('0'..'9')+;

LITERAL 
    : ('a'..'z' | 'A'..'Z')(('a'..'z' | 'A'..'Z') | '0'..'9');

TEXT 
    : (('a'..'z' | 'A'..'Z') | '0'..'9');

QUOTED_TEXT 
    : '"' (~ '"')* '"';

EQUAL 
    : '=';

WS 
    : (' '|'\t'|'\r'|'\n')+ ->skip;

DOT 
    : '.' ;`
`

**Comment by mandeepsb** [comment]
I have used the above grammar file, however now I am getting below
exception. I have removed the white spacing from the business rules and
also changed the white spacing rule to* WS*
*: (' '|'\t'|'\r'|'\n')+ ->channel(HIDDEN);*

*{"Exception of type 'Antlr4.Runtime.NoViableAltException' was thrown."}*

**Comment by teverett** [comment]
@mandeepsb I am closing this issue.
