### ISSUE TITLE
CSharpPreprocessor of CSharp

### ISSUE THREAD

**Issue by deadmarston** [antlr/grammars-v4#609]
I want to know how to use the CSharpPreprocessor.g4, the link in the page(https://gist.github.com/KvanTTT/d95579de257531a3cc15) is not valid any more. Is there any of demo to show how it works?

**Comment by KvanTTT** [comment]
I checked it being unauthorized just now and the page is valid. But anyway I'm going to upload content to this repository.

**Comment by deadmarston** [comment]
I try again with VPN and access it finally. Maybe it's blocked. Anyway, I could see the code and thanks again.

**Comment by deadmarston** [comment]
I try the code， but in preprocessorparser, the func **SetInputStream** doesn't exist, and the **InputStream** of preprocessorparser is a readonly variant. So how can I continue to work?

**Comment by KvanTTT** [comment]
What C# runtime are you using? Try to use [ANTLR 4 sharwell](https://www.nuget.org/packages/Antlr4.Runtime) instead of [ANTLR 4 standart](https://www.nuget.org/packages/Antlr4.Runtime.Standard/).

**Comment by Marti2203** [comment]
I think this issue can be closed?
