### ISSUE TITLE
Any ES6 / ES7 grammar? Anyone?

### ISSUE THREAD

**Issue by sithembiso** [antlr/grammars-v4#632]
Has anyone written a grammar for Ecmascript versions after 2015? I've had a hard time writing one myself and I'm hoping I don't have to reinvent the wheel.

**Comment by KvanTTT** [comment]
Did you try and improve the current version [ecmascript](https://github.com/antlr/grammars-v4/tree/master/ecmascript)?

**Comment by sithembiso** [comment]
I'm trying that now, I was writing one from scratch. Both are quite a bit of work, hence my quest to see if anyone else has already tried that before.

**Comment by johndpope** [comment]
Is the gramma failing to generate valid code? If so what target language?

It can lay to dig around online / gist / github. I couldn't find an updated one specifically though. I'm targeting swift and it does fail to produce valid code but presumably this has something to do with reserved words currently not supported.

**Comment by johndpope** [comment]
Does this help? https://github.com/antlr/grammars-v4/pull/596

**Comment by KvanTTT** [comment]
@sithembiso I'm working on ES6 grammar for now.

**Comment by KvanTTT** [comment]
Eventually JavaScript grammar with ECMAScript 6 support is ready: https://github.com/antlr/grammars-v4/tree/master/javascript
