### ISSUE TITLE
Python Grammars Missing module def rule

### ISSUE THREAD

**Issue by GraydenH** [antlr/grammars-v4#638]
Unless I am missing something there is no way to get the name of the current module in antlr4 with the current python grammars. 

could this be achieved by adding a rule? Such as:

```antlr
moduledef: 'module' NAME ':' suite
    ;
```

**Comment by Marti2203** [comment]
Hi! Can you show me example code which uses this? I had never heard of such a struct in Python

**Comment by KvanTTT** [comment]
Such syntax does not exist not in [Python2](https://docs.python.org/2/reference/grammar.html) nor in [Python3](https://docs.python.org/3/reference/grammar.html) grammars.
