### ISSUE TITLE
Issue with distinguishing Identifier with String Literal or Constant in C grammar

### ISSUE THREAD

**Issue by prateekgulati** [antlr/grammars-v4#654]
In the primary expression in C grammar, there is no further distinction between an Identifier, Constant or StringLiteral. 
Can I try to fix this issue?

**Comment by KvanTTT** [comment]
What do you mean? `primaryExpression` contains these rules.

**Comment by prateekgulati** [comment]
This is code for 
`x=1;`
`y='a;`
`z=x;`
![image](https://cloud.githubusercontent.com/assets/9799617/25722066/6a10d060-3130-11e7-9d98-4489c19e0611.png)
If you see the last node (primary expression) for each statement, there is no further distinction between literal, constant and an identifier.

**Comment by KvanTTT** [comment]
Maybe terminals are not displayed here?

**Comment by prateekgulati** [comment]
Yeah, I converted those identifier, constant and string literal terminals to intermediate nodes and used them further.

**Comment by KvanTTT** [comment]
It's not necessary because it's also possible to distinguish between terminals in visitor methods.
