### ISSUE TITLE
Issue with parsing declaration in C

### ISSUE THREAD

**Issue by prateekgulati** [antlr/grammars-v4#655]
When I try to parse code like 
`int x;` or `long int x;` then in declaration, all the tokens get parsed as declarationSpecifiers.
Can I try to fix this issue?

**Comment by teverett** [comment]
@prateekgulati, anyone is welcome to fix any issue and to submit pull requests.

**Comment by KvanTTT** [comment]
Try to use the following declaration rule
`declarationSpecifiers initDeclaratorList | declarationSpecifiers`

instead of the old one:
`declarationSpecifiers initDeclaratorList?`

I'll upload an updated version of Objective-C grammar soon with such improvement. It works fine.

**Comment by prateekgulati** [comment]
This works fine. Thanks

**Comment by KvanTTT** [comment]
Could you also suggest a pull request for this?
