### ISSUE TITLE
Help Using CSharp Grammar

### ISSUE THREAD

**Issue by raghungithub** [antlr/grammars-v4#662]
Hi
I need to parse Csharp source files in Java.   I created a eclipse project with grammar from
https://github.com/antlr/grammars-v4/tree/master/csharp
When I run the Maven build there are compilation errors as the generated files like /csharp/target/generated-sources/antlr4/CSharpLexer.java   have Csharp code in them and throwing compilation errors.   
Please help me get started.

**Comment by KvanTTT** [comment]
I'll upload a Java version of C# parser ASAP.
