### ISSUE TITLE
Synchronize topics, labels and directories

### ISSUE THREAD

**Issue by KvanTTT** [antlr/grammars-v4#700]
I suppose to use the same names in lowercase for unification and beauty.

Rename the following labels:
* `C` -> `c`
* `c#` -> `csharp`
* `t-sql` -> `tsql`
* `Swift` -> `swift`
* `objc` -> `objective-c`
* `VB` -> `vb`

Also use the same colors (at least the same hue) for C languages (`csharp`, `cpp`, `objective-c`, maybe `java`), SQL languages (`mysql`, `sqlite`, `plsql`, `tsql`) and other one family languages.

**Comment by teverett** [comment]
done
