### ISSUE TITLE
Python2 grammar

### ISSUE THREAD

**Issue by prateekgulati** [antlr/grammars-v4#723]
The class files generated by antlr4 for Python2.g4 have a lot of errors and are not compilable using javac.
The reason I believe is the code in Python2.g4 is written in python instead of java. 
Eg: This is inside lexer::header

![image](https://cloud.githubusercontent.com/assets/9799617/26391197/4a936bf4-407f-11e7-8a34-c16db47d603b.png)

**Comment by quaeler** [comment]
More verbosity and probably mis-filed here: https://github.com/antlr/antlr4/issues/1893

**Comment by quaeler** [comment]
... and related to https://github.com/antlr/grammars-v4/issues/564

**Comment by teverett** [comment]
the python2 grammar is written for a python2 target.  The generated sources don't compile for java, nor are they intended to.  this grammar is now included in the standard test suite, in that it is passed to antlr to verify that antlr can parse the .g4 file and generate sources.  test cases are not run.

PR #890

**Comment by aliahsan07** [comment]
@teverett Python2 grammar results in a "mismatched input '....' expecting NEWLINE" error.
