### ISSUE TITLE
GraphQL grammar quite out of date

### ISSUE THREAD

**Issue by mohawk2** [antlr/grammars-v4#727]
I'm writing a Pegex grammar for GraphQL and stumbled across your GraphQL grammar. It was helpful but I have quickly discovered it is a bit out of date (eg it doesn't know about enums!) with latest spec at https://github.com/facebook/graphql/blob/master/spec/Appendix%20B%20--%20Grammar%20Summary.md

**Comment by teverett** [comment]
@mohawk2 thanks.

**Comment by mohawk2** [comment]
You're welcome! You may find useful the Pegex grammar I made: https://github.com/graphql-perl/graphql-perl/blob/master/graphql.pgx

**Comment by andimarek** [comment]
for everybody who might looking for an comprehensive antlr grammar for GraphQL: https://github.com/graphql-java/graphql-java/tree/master/src/main/antlr it powers GraphQL java is actively maintained

**Comment by Marti2203** [comment]
I think this issue can be closed as the grammar in the current repo has been updated in the past years.
