### ISSUE TITLE
Javascript target + Java8.g4 -> out of memory

### ISSUE THREAD

**Issue by jundl77** [antlr/grammars-v4#729]
When generating the parser with the [Java8.g4](https://github.com/antlr/grammars-v4/blob/master/java8/Java8.g4) grammar, and Javascript as the target language, the parser does not terminate until it runs out of heap-memory. 

More specifically, the following code proposed in the [docs](https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md) does not work with the Java 8 grammar:

```js
const chars = new antlr4.InputStream(input)
const lexer = new Java8Lexer.Java8Lexer(chars)
const tokens = new antlr4.CommonTokenStream(lexer)
const parser = new Java8Parser.Java8Parser(tokens)
parser.buildParseTrees = true
const tree = parser.compilationUnit()
```

It is the  ```const tree = parser.compilationUnit()``` that does not terminate until it runs out of memory.

Using other grammars like the [Java.g4](https://github.com/antlr/grammars-v4/blob/master/java/Java.g4) grammar works like a charm, it just seems to be the Java8.g4 that causes the out-of-memory exception.

I saw a similar problem on [SO](https://stackoverflow.com/questions/32910013/antlr-v4-java8-grammar-outofmemoryexception) with a proposed solution in Java. I tried porting the solution to Javascript with limited success. 

Perhaps it has something to do with [this issue](https://github.com/antlr/antlr4/issues/1885)?

**Comment by KvanTTT** [comment]
Try a new [java8-pt](https://github.com/antlr/grammars-v4/tree/master/java8-pt) grammar.

**Comment by KvanTTT** [comment]
I don't think this is a grammar issue.
