### ISSUE TITLE
R grammer not working

### ISSUE THREAD

**Issue by mcheung63** [antlr/grammars-v4#730]
https://github.com/antlr/grammars-v4/blob/master/r/R.g4
Try to parse a R source with only one line "# hello", it failed.
thanks

**Comment by teverett** [comment]
Please provide some demo code which illustrates this issue.

**Comment by teverett** [comment]
@mcheung63 PR #820 shows that R source with "# hello" does indeed work.  The test file is here:

https://github.com/antlr/grammars-v4/blob/master/r/examples/example2.txt

**Comment by mcheung63** [comment]
thanks
