### ISSUE TITLE
MySQL doesn't recognize "AS" in alias syntax

### ISSUE THREAD

**Issue by nicomp42** [antlr/grammars-v4#732]
"select x AS xx from FOO" throws this error:
line 1:12 extraneous input 'xx' expecting {<EOF>, 'from', 'where', ','}

"select x xx from FOO"
this works. 

There are other issues as well such as not recognizing quoted strings: I think perhaps the MySQL grammar is incomplete?

**Comment by ivan-khudyashev** [comment]
With new grammar. It is all work :)
This not actual issue
