### ISSUE TITLE
Keyword "var" is missing in the CSharp grammar.

### ISSUE THREAD

**Issue by Chris2011** [antlr/grammars-v4#734]
I'm have not so much experiences with Lexer and Parser but when I saw the keywords, one keyword (ATM) is missing in the list. It is the context sensitive "var" keyword. I know it is not a normal keyword, as MSDN says it but where is it than? It is neither in the lexer nor in the parser grammar file.

Can someone explain it to me please?

Regards

Chris

**Comment by Chris2011** [comment]
Is it really missing or will it be handled otherwise?

**Comment by Chris2011** [comment]
I'm in contact with the creator of the antlr lexer files for C# and I see in your repo, there is a file missing: https://github.com/antlr/grammars-v4/tree/master/csharp

in the origional one you have one more file called CSharp.g: https://github.com/ChristianWulf/CSharpGrammar/tree/master/grammars

And inside this file, there is the var keyword. Was there a specific reason to remove the file in this repo?

**Comment by KvanTTT** [comment]
I suppose that `var` treated as `identifier`. Actually, this is context sensitive keyword because of it's possible to use the `var` variable:
```CSharp
var var = 42;
```

**Comment by Chris2011** [comment]
Yeah C# has some context sensitives keywords like var and some other, so it is not possible to add var to the lexer as a normal keyword right?

**Comment by Chris2011** [comment]
And this was handled by the CSharp4.g file?

**Comment by Chris2011** [comment]
Other contextual keywords are: get, set, value, add, remove, since C# 1.0. I don't have enough knowledge of Lexer/Parser, can you maybe help to start with some context sensitive pattern and I can try to jump in and add the rest? Those keywords are essential for C#.

**Comment by xied75** [comment]
@Chris2011 The long list you saw in CSharpLexer.g4 beginning section does includes lots of "contextual keywords", the way to make it a "contextual", is by also including it in CSharpParser.g4 end section where rule "identifier" is defined, of cause you then need to actually use those keywords in the rules where it acts as a keyword, if left unconsumed, then it turns into an normal "identifier". A clever trick by the original author.

**Comment by Chris2011** [comment]
Ok but the var keyword is still missing, and he commented it out. Here is the comment of him:

```
Hi Chris,

nice work! Thanks for referencing me and my project.
According to my comment in grammars/CSharp4.g, the keyword "var" is covered by the following rule:
/*
local_variable_type 
  : type
  | 'var'
  ;
*/
local_variable_type 
    : type // includes 'var'
    ;
I do not know exactly anymore why I removed the keyword "var". But I think it's because the rule "type" starts with an IDENTIFIER which includes the string "var". And ANTLR 3 does not know whether it should follow the rule "type" or the keyword "var" because "type" also starts with characters (due to IDENTIFIER).

Regards
Christian

```

So the other part is, the var keyword is written in this file: https://github.com/ChristianWulf/CSharpGrammar/blob/master/grammars/CSharp4.g

But this file dosn't exist anymore in your repo. Was there a specific reason for this to remove it?

Thx for the hints with the contextual keywords.


Regards

Chris

**Comment by KvanTTT** [comment]
@Chris2011 in this file the `var` keyword is commented out =)

**Comment by Chris2011** [comment]
You mean add it to here: https://github.com/antlr/grammars-v4/blob/master/csharp/CSharpParser.g4#L1123 ?

**Comment by KvanTTT** [comment]
Yes. But I don't know is this right and correspond to the latest documentation.

**Comment by ChristianWulf** [comment]
As @xied75 explained very well, you can add the `VAR` token to the `identifier` parser rule and reintroduce the `local_variable_type` parser rule. The resulting file can be found here:
[CSharpParser.g4.txt](https://github.com/antlr/grammars-v4/files/1184988/CSharpParser.g4.txt)

Note to the implementation: it is important that `VAR` is the first alternative and `type` the second one. Otherwise, `var` will be interpreted by `type`.

Additionally, I had to adapt the lexer so that `var` is recognized as an own token called `VAR`:
[CSharpLexer.g4.txt](https://github.com/antlr/grammars-v4/files/1184989/CSharpLexer.g4.txt)

@KvanTTT Perhaps you want to include my small adaptations.

**Comment by KvanTTT** [comment]
@ChristianWulf you can do a pull request by yourself :)

**Comment by ChristianWulf** [comment]
Sounded like, you would not accept a pull request because you do not know whether the changes still corresponds to the C# spec. But here it is: https://github.com/antlr/grammars-v4/pull/826

**Comment by KvanTTT** [comment]
Ok then!

**Comment by Chris2011** [comment]
Thx for the PR @ChristianWulf I will try to generate what I need :)
