### ISSUE TITLE
Character.isJavaIdentifier usage in Python target syntactically incorrect

### ISSUE THREAD

**Issue by shashanksingh28** [antlr/grammars-v4#739]
I was trying to create a lexer, parser and visitor for Java8 grammar with a python target with the below command:

```
antlr4 -visitor -Dlanguage=Python3 Java8.g4
```

In line 727 of Java8Lexer.py, I get a syntax error on import:

```java
return Character.isJavaIdentifierStart(Character.toCodePoint((char)_input.LA(-2), (char)_input.LA(-1)))
```

I am completely new to antlr and do not know how anltr4 creates these .py files for identifying the root cause.

**Comment by jeviss** [comment]
I'm getting this error while I'm trying to pass java code to Java8Lexer.
I mean: `$ python start.py test.java`
Tried to comment problematic lines in Java8Lexer, and after that I got response:
`line 1:0 extraneous input 'import' expecting <INVALID>
line 1:17 mismatched input '*' expecting {<INVALID>, '@'}`

**Comment by jeviss** [comment]
hi,
Im afraid, that this solution:
https://github.com/antlr/antlr4/issues/1037
is still actual.
@teverett maybe you have any better solutions?
@shashanksingh28 
regards,
Matt

**Comment by KvanTTT** [comment]
@shashanksingh28 you should rewrite this code fragment to Python or just use universal Java grammar (Java.g4 instead of Java8.g4).
