### ISSUE TITLE
Tsql. error during parsing join condition in `table_source` rule

### ISSUE THREAD

**Issue by DmitriiKosenko** [antlr/grammars-v4#745]
When i try to parse statement like this:
`select a.col1, b.col2 from actions AS a JOIN interactions AS b ON a.key = b.key`
there is an error in parsed tree. The join part of this statement is not recognized. The test screen and ast screen below

![1_test_join](https://user-images.githubusercontent.com/3405927/26873115-f3b14f70-4ba2-11e7-8c2c-49de44c2b882.jpg)
<img width="1440" alt="2_ 2017-06-07 12 52 06" src="https://user-images.githubusercontent.com/3405927/26873119-f68ec0c4-4ba2-11e7-90a2-7bb1517975f5.png">

First of all, i supposed, that the problem in greedy algorithm. I tried to change the rule and had an interesting results.
### 1 case. 
Rules:
```
table_source
    : rule2 | rule1
    ;

rule1
    : table_source_item
    ;

rule2
    : table_source_item JOIN table_source_item ON
    ;
```

And the result:
![3_result_1](https://user-images.githubusercontent.com/3405927/26873539-61760342-4ba4-11e7-85f5-49e5b00575b9.jpg)
![3_result_11](https://user-images.githubusercontent.com/3405927/26873673-d4ef7614-4ba4-11e7-85bb-43a40d72f7d3.jpg)

### case 2 
Rules:
```
table_source
    : rule2 | rule1
    ;

rule1
    : table_source_item
    ;

rule2
    : table_source_item JOIN table_source_item ON search_condition
    ;
```
And the result:

![4_result_2](https://user-images.githubusercontent.com/3405927/26873700-ee3ad9f6-4ba4-11e7-8d83-8587f4a457c3.jpg)
![4_result_22](https://user-images.githubusercontent.com/3405927/26873705-f905afbe-4ba4-11e7-8f01-297d5ea8bd6f.jpg)

I was check a `search_condition` rule, and can't find features of non-greedy algorithm. So, the ideas and suggestions welcome.

**Comment by tuxmania87** [comment]
Seems to be a problem with the keyword KEY. I just replaced key by key1 and it works:

`select a.col1, b.col2 from actions AS a JOIN interactions AS b ON a.key1 = b.key1`

**Comment by KvanTTT** [comment]
Probably adding `KEY` token to `simple_id` parse rule resolves this issue?

**Comment by tuxmania87** [comment]
This Issue should be resolved with latest merge #803

**Comment by KvanTTT** [comment]
Has this issue been resolved? Can I close it?

**Comment by Muhamedali** [comment]
Unfortunatelly, in sql server rdbms not allowed to execute statement like this:
`CREATE TABLE some_tab (key int);`
Error will be arrised:
```
mssql> CREATE TABLE some_tab (key int);
Error: Incorrect syntax near the keyword 'key'.
```

Thats why, it's necessary to check the grammar according https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql , and fix it.
Sorry for late answer and lack of opportunity to contribute to grammar just now. Thanks @tuxmania87  for help.

**Comment by siggemannen** [comment]
This issue is probably obsolete since key must be quoted to work and the original query isn't validated by sql server.

Btw, is sybase syntax included in this grammar? I'm not sure how in sync those parts are, or if it's even supported, but some of these issues might actually be sybase-specific?
