### ISSUE TITLE
TSql. ISNULL and other functions not well parsed

### ISSUE THREAD

**Issue by TheSharpSwan** [antlr/grammars-v4#771]
Hi, 
I found this issue but i dont understand what's the problem.

This query:
```
select isnull(id,0,1)
from pippo
where id = isnull(id,0,1)
```

throw parse error
`line 1:18 missing ')' at ','`

And this is right, because ISNULL accepts only two arguments

BUT

This query:
```
select 1
from pippo
where id = isnull(id,0,1) and MyFunct(id) = 1
```
does not throw any error and  Function_call is not visited and Search_condition is not visited 

Also, for example, this query works fine ( Function_call  visited, Search_condition visited )
```
select 1
from pippo
where MyFunct(id) = 1
```
It also happens with other functions like IFNULL.

Any idea?

**Comment by siggemannen** [comment]
This seems to be parsed OK now.

In my opinion, though, probably the built-in's should be removed from the grammer since they pollute name space, better just use generic function calls unless there's specific reason for it, for example in case of CAST and CHECKSUM that has a special syntax parts

**Comment by KvanTTT** [comment]
> In my opinion, though, probably the built-in's should be removed from the grammer since they pollute name space, better just use generic function calls unless there's specific reason for it, for example in case of CAST and CHECKSUM that has a special syntax parts

I completely agree with this, namespace pollution is also related to some context keywords, but it's harder to fix, see https://github.com/antlr/grammars-v4/issues/1606
