### ISSUE TITLE
grammars-v4/antlr4: three.g4 file

### ISSUE THREAD

**Issue by HSorensen** [antlr/grammars-v4#773]
Just being curious. Is there a reason this file is at the top level of the antlr4 grammar directory.
[grammars-v4/antlr4/three.g4](https://github.com/antlr/grammars-v4/blob/master/antlr4/three.g4)

**Comment by teverett** [comment]
None that I know of.

**Comment by teverett** [comment]
Corrected in pr775.  The problem was that the three.g4 doesn't actually parse.  I moved the file into /examples and added a .errors file.
