### ISSUE TITLE
Please add Rust grammar to this repo

### ISSUE THREAD

**Issue by Chris2011** [antlr/grammars-v4#801]
I saw this ticket: #323 that the other repo is outdated, I searched a bit and I only found this: https://doc.rust-lang.org/grammar.html Maybe a talk to the Mozilla gues could be helpful too?

So all in all, would be great to see rust here.

Regards

Chris

**Comment by KvanTTT** [comment]
You can talk to Mozilla or develop a Rust grammar by yourself :)

**Comment by Chris2011** [comment]
I talked to them, they only have the above doc link, but I found the intelliJ rust plugin, and they have a bnf file: https://github.com/intellij-rust/intellij-rust/tree/master/src/main/grammars

**Comment by draffensperger** [comment]
There is one by jbclements@ (https://github.com/jbclements/rust-antlr) that is Apache 2.0 licensed. Would that be suitable to import?

**Comment by bkiers** [comment]
There's this repo: https://github.com/jbclements/rust-antlr

**Comment by KvanTTT** [comment]
The author is not going to move this grammar to the official repository. See this issue: https://github.com/jbclements/rust-antlr/issues/2

**Comment by bkiers** [comment]
Ah, yes, missed that!

**Comment by Chris2011** [comment]
So we can close this ticket I think. Thx for clarification.

**Comment by KvanTTT** [comment]
I don't think so because Rust grammar is still missing.

**Comment by Chris2011** [comment]
I just closed it due to the comments and no rust lexer here after 2 years. Thats why. But if you are still optimistical, why not :)
