### ISSUE TITLE
Unsupported Packages track in Oracle11g (PLSQL/plsqlParser.g4)

### ISSUE THREAD

**Issue by trrao** [antlr/grammars-v4#807]
Hi,

Does Plsql parser have a knowledge of supported built-in packages in Oracle 11g? 

Because, while I was working on parsing Oracle11g function, unknowingly I passed one of the Oracle12c function which has an 12c new built-in package called "UTL_CALLSTACK". I expected the parser will spit out the package name as its not in Oracle 11g. Hence I am raising this question, does this parser has knowledge of what all supported built-in packages ?

Regards
Raghav

**Comment by KvanTTT** [comment]
I don't think so but you can explore PL/SQL grammar by yourself.

**Comment by trrao** [comment]
Sure. Thank you
