### ISSUE TITLE
Remove outdated branch grosenberg-master and tags from repository

### ISSUE THREAD

**Issue by KvanTTT** [antlr/grammars-v4#811]
This repository does not have "releases". In this way branches and tags are meaningless.
Maybe it makes sense tags for every year or month for statistics.

**Comment by teverett** [comment]
@parrt I've left this branch b/c it was in place when i inherited the repo.  Do you have any objection to removing it?

**Comment by parrt** [comment]
No objection.

**Comment by KvanTTT** [comment]
Why did you close it? @teverett has not removed it yet.

**Comment by teverett** [comment]
No big deal.  I will.  :)
