### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mcheung63** [antlr/grammars-v4#817]
Test error
![Uploading Screen Shot 2017-07-27 at 4.34.36 PM.png…]()

**Comment by KvanTTT** [comment]
Could you reload your image?

**Comment by teverett** [comment]
@mcheung63 the image you uploaded is not visible

**Comment by mcheung63** [comment]
<img width="1680" alt="screen shot 2017-07-29 at 6 36 43 am" src="https://user-images.githubusercontent.com/1779905/28738808-50bbe24a-7428-11e7-916e-832c80e2ece8.png">

**Comment by KvanTTT** [comment]
Try to use the latest version from master: Travis-CI tests passing.

**Comment by mcheung63** [comment]
just git clone the latest version, "mvn package" command still generate the same error.

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T03:39:06+08:00)
Maven home: /Users/peter/Downloads/apache-maven-3.5.0
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"

**Comment by teverett** [comment]
Am i ok to close this?

**Comment by mcheung63** [comment]
yes, thx
