### ISSUE TITLE
i can't use the antlr4 grammars in my project

### ISSUE THREAD

**Issue by mcheung63** [antlr/grammars-v4#823]
i can't use the antlr4 grammars in my project, i dropped ANTLRv4Lexer.g4, ANTLRv4Parser.g4 and LexBasic.g4, it has compile error, here is my pom.xml [https://github.com/mcheung63/netbeans-antlr/blob/master/pom.xml](url)

<img width="1680" alt="screen shot 2017-07-29 at 6 39 45 am" src="https://user-images.githubusercontent.com/1779905/28738870-b9a9cf6a-7428-11e7-9a2a-91c15a71f801.png">

**Comment by teverett** [comment]
@mcheung63 your project is private.

**Comment by mcheung63** [comment]
https://github.com/mcheung63/netbeans-antlr/blob/master/pom.xml

please try this link

**Comment by mcheung63** [comment]
after i set the correct path to <sourceDirectory> in pom.xml, i can compile it, thanks
