### ISSUE TITLE
Rewrite C# expression parse rules as left-recursive

### ISSUE THREAD

**Issue by KvanTTT** [antlr/grammars-v4#825]
This simplifies grammar and improves parser performance.

**Comment by xied75** [comment]
Are you working on this already? Would you mind to give some concrete example?

**Comment by KvanTTT** [comment]
I'm not working on it. See my note about [java7 and java8 grammar](http://blog.ptsecurity.com/2016/06/theory-and-practice-of-source-code.html#java--and-java8-grammars).

**Comment by Marti2203** [comment]
Any update on this issue?
