### ISSUE TITLE
PLSQL grammar not working

### ISSUE THREAD

**Issue by aaraujo666** [antlr/grammars-v4#854]
A very simple test case:

CREATE OR REPLACE PACKAGE BODY general_pkg
IS
procedure get_emplid (userid in varchar2,emplid out varchar2,retval out number) IS 
operid varchar2(50);
slashcount number(4);
rowcount number(4) := 0;
BEGIN
   retval := 0;

   slashcount := to_number(instr(userid,'\'));

   if slashcount = 0
   then
      operid := userid;
   else
      operid := substr(userid,instr(userid,'\') + 1,length(userid));
   end if;
EXCEPTION
   WHEN OTHERS THEN
      retval := 1;
END;

end;

Gets the following errors:

line 1:31 token recognition error at: 'g'
line 1:32 token recognition error at: 'e'
line 1:33 token recognition error at: 'n'
line 1:34 token recognition error at: 'e'
line 1:35 token recognition error at: 'r'
line 1:36 token recognition error at: 'a'
line 1:37 token recognition error at: 'l'
line 1:39 token recognition error at: 'pk'
line 1:41 token recognition error at: 'g'
line 3:0 token recognition error at: 'proc'
line 3:4 token recognition error at: 'e'
line 3:5 token recognition error at: 'd'
line 3:6 token recognition error at: 'u'
line 3:7 token recognition error at: 'r'
line 3:8 token recognition error at: 'e'
line 3:10 token recognition error at: 'g'
line 3:11 token recognition error at: 'e'
line 3:12 token recognition error at: 't'
line 2:0 mismatched input 'IS' expecting {'A', 'ADD', 'AFTER', 'AGENT', 'AGGREGA
TE', 'ANALYZE', 'ARRAY', 'ASSOCIATE', 'AT', 'ATTRIBUTE', 'AUDIT', 'AUTHID', 'AUT
O', 'AUTOMATIC', 'AUTONOMOUS_TRANSACTION', 'BATCH', 'BEFORE', 'BFILE', 'BINARY_D
OUBLE', 'BINARY_FLOAT', 'BINARY_INTEGER', 'BLOB', 'BLOCK', 'BODY', 'BOOLEAN', 'B
OTH', 'BULK', 'BYTE', 'C', 'CALL', 'CANONICAL', 'CASCADE', 'CAST', 'CHAR', 'CHAR
_CS', 'CHARACTER', 'CHR', 'CLOB', 'CLOSE', 'CLUSTER', 'COLLECT', 'COLUMNS', 'COM
MENT', 'COMMIT', 'COMMITTED', 'COMPATIBILITY', 'COMPILE', 'COMPOUND', 'CONSTANT'
, 'CONSTRAINT', 'CONSTRAINTS', 'CONSTRUCTOR', 'CONTENT', 'CONTEXT', 'CONTINUE',
'CONVERT', 'CORRUPT_XID', 'CORRUPT_XID_ALL', 'COST', 'COUNT', 'CROSS', 'CUBE', '
CURRENT_USER', 'CURSOR', 'CUSTOMDATUM', 'CYCLE', 'DATA', 'DATABASE', 'DAY', 'DB_
ROLE_CHANGE', 'DBTIMEZONE', 'DDL', 'DEBUG', 'DEC', 'DECIMAL', 'DECOMPOSE', 'DECR
EMENT', 'DEFAULTS', 'DEFERRED', 'DEFINER', 'DELETE', 'DETERMINISTIC', 'DIMENSION
', 'DISABLE', 'DISASSOCIATE', 'DOCUMENT', 'DOUBLE', 'DSINTERVAL_UNCONSTRAINED',
'EACH', 'ELEMENT', 'EMPTY', 'ENABLE', 'ENCODING', 'ENTITYESCAPING', 'ERR', 'ERRO
RS', 'ESCAPE', 'EVALNAME', 'EXCEPTION', 'EXCEPTION_INIT', 'EXCEPTIONS', 'EXCLUDE
', 'EXECUTE', 'EXIT', 'EXPLAIN', 'EXTERNAL', 'EXTRACT', 'FAILURE', 'FINAL', 'FIR
ST', 'FIRST_VALUE', 'FLOAT', 'FOLLOWING', 'FOLLOWS', 'FORALL', 'FORCE', 'FULL',
'FUNCTION', 'GROUPING', 'HASH', 'HIDE', 'HOUR', 'IGNORE', 'IMMEDIATE', 'INCLUDE'
, 'INCLUDING', 'INCREMENT', 'INDENT', 'INDEXED', 'INDICATOR', 'INDICES', 'INFINI
TE', 'INLINE', 'INNER', 'INOUT', 'INSTANTIABLE', 'INSTEAD', 'INT', 'INTEGER', 'I
NTERVAL', 'INVALIDATE', 'ISOLATION', 'ITERATE', 'JAVA', 'JOIN', 'KEEP', 'KEY', '
LANGUAGE', 'LAST', 'LAST_VALUE', 'LEADING', 'LEFT', 'LEVEL', 'LIBRARY', 'LIKE2',
 'LIKE4', 'LIKEC', 'LIMIT', 'LOCAL', 'LOCKED', 'LOG', 'LOGOFF', 'LOGON', 'LONG',
 'LOOP', 'MAIN', 'MAP', 'MATCHED', 'MAXVALUE', 'MEASURES', 'MEMBER', 'MERGE', 'M
INUTE', 'MINVALUE', 'MLSLABEL', 'MODEL', 'MODIFY', 'MONTH', 'MULTISET', 'NAME',
'NAN', 'NATURAL', 'NATURALN', 'NAV', 'NCHAR', 'NCHAR_CS', 'NCLOB', 'NESTED', 'NE
W', 'NO', 'NOAUDIT', 'NOCOPY', 'NOCYCLE', 'NOENTITYESCAPING', 'NONE', 'NOSCHEMAC
HECK', 'NULLS', 'NUMBER', 'NUMERIC', 'NVARCHAR2', 'OBJECT', 'OFF', 'OID', 'OLD',
 'ONLY', 'OPEN', 'ORADATA', 'ORDINALITY', 'OSERROR', 'OUT', 'OUTER', 'OVER', 'OV
ERRIDING', 'PACKAGE', 'PARALLEL_ENABLE', 'PARAMETERS', 'PARENT', 'PARTITION', 'P
ASSING', 'PATH', 'PIPELINED', 'PLAN', 'PLS_INTEGER', 'POSITIVE', 'POSITIVEN', 'P
RAGMA', 'PRECEDING', 'PRECISION', 'PRESENT', 'RAISE', 'RANGE', 'RAW', 'READ', 'R
EAL', 'RECORD', 'REF', 'REFERENCE', 'REFERENCING', 'REJECT', 'RELIES_ON', 'RENAM
E', 'REPLACE', 'RESPECT', 'RESTRICT_REFERENCES', 'RESULT', 'RESULT_CACHE', 'RETU
RN', 'RETURNING', 'REUSE', 'REVERSE', 'RIGHT', 'ROLLBACK', 'ROLLUP', 'ROW', 'ROW
ID', 'ROWS', 'RULES', 'SAMPLE', 'SAVE', 'SAVEPOINT', 'SCHEMA', 'SCHEMACHECK', 'S
CN', 'SECOND', 'SEED', 'SEGMENT', 'SELF', 'SEQUENTIAL', 'SERIALIZABLE', 'SERIALL
Y_REUSABLE', 'SERVERERROR', 'SESSIONTIMEZONE', 'SET', 'SETS', 'SETTINGS', 'SHOW'
, 'SHUTDOWN', 'SIBLINGS', 'SIGNTYPE', 'SIMPLE_INTEGER', 'SINGLE', 'SKIP', 'SMALL
INT', 'SNAPSHOT', 'SOME', 'SPECIFICATION', 'SQLDATA', 'SQLERROR', 'STANDALONE',
'STARTUP', 'STATEMENT', 'STATEMENT_ID', 'STATIC', 'STATISTICS', 'STRING', 'SUBMU
LTISET', 'SUBPARTITION', 'SUBSTITUTABLE', 'SUBTYPE', 'SUCCESS', 'SUSPEND', 'TIME
', 'TIMESTAMP', 'TIMESTAMP_LTZ_UNCONSTRAINED', 'TIMESTAMP_TZ_UNCONSTRAINED', 'TI
MESTAMP_UNCONSTRAINED', 'TIMEZONE_ABBR', 'TIMEZONE_HOUR', 'TIMEZONE_MINUTE', 'TI
MEZONE_REGION', 'TRAILING', 'TRANSACTION', 'TRANSLATE', 'TREAT', 'TRIGGER', 'TRU.......

Made a small change to the lexer:

//{ Rule #504 <SIMPLE_LETTER> - simple_latin _letter was generalised into SIMPLE_LETTER
//  Unicode is yet to be implemented - see NSF0
fragment
SIMPLE_LETTER
    : [A-Z]
    ;
//}
changed it to:

//{ Rule #504 <SIMPLE_LETTER> - simple_latin _letter was generalised into SIMPLE_LETTER
//  Unicode is yet to be implemented - see NSF0
fragment
SIMPLE_LETTER
    : [A-Za-z]
    ;
//}

Same test case now generates:

line 3:21 mismatched input '(' expecting {'DEFAULT', 'NOT', ':=', ';'}
line 3:32 mismatched input 'varchar2' expecting {'DEFAULT', 'NOT', ':=', ';'}
line 3:52 mismatched input 'varchar2' expecting {'DEFAULT', 'NOT', ':=', ';'}
line 3:72 mismatched input 'number' expecting {'DEFAULT', 'NOT', ':=', ';'}
line 4:15 mismatched input '(' expecting {'DEFAULT', 'NOT', ':=', ';'}
line 5:17 mismatched input '(' expecting {'DEFAULT', 'NOT', ':=', ';'}
line 6:15 mismatched input '(' expecting {'DEFAULT', 'NOT', ':=', ';'}
line 12:17 mismatched input '=' expecting {'DEFAULT', 'NOT', ':=', ';'}
line 19:3 no viable alternative at input 'EXCEPTIONWHEN'
line 21:0 extraneous input 'END' expecting ';'

**Comment by aaraujo666** [comment]
Update:

Changing the test case to all uppercase (the entire file), eliminates the errors. But I think it should support lowercase since it is not part of the PLSQL spec that everything be uppercase.

**Comment by KvanTTT** [comment]
This grammar support any case. Please use [CaseInsensitiveInputStream](https://gist.github.com/sharwell/9424666).

**Comment by aaraujo666** [comment]
Don't want to nitpick... But if I have to use a case-insensitive stream to get this grammar to work, then by definition, the grammar does not "support any case". 

But whatever, I resolved the case issue... Not by using the case insensitive stream since the C# implementation of Antlr does not implement it.

**Comment by KvanTTT** [comment]
Actually, such stream does not affect on input case for token values, see comment on gist:

>For truly case-insensitive languages, a case-insensitive lookahead stream causes the ANTLR lexer to behave as though the input contained only lowercase letters, but messaging and other getText() methods return data from the original input string.

C# and other runtimes also support case insensitive streams: [AntlrCaseInsensitiveInputStream](https://github.com/KvanTTT/DAGE/blob/master/AntlrGrammarEditor/Runtimes/CSharp/AntlrCaseInsensitiveInputStream.cs).

**Comment by balahsen** [comment]
Yes of course it's important to implement an Antlr case insensitive input stream for grammar that are case insensitive like Oracle.
But it's not necessary to have a boolean because the use of this class implcitly and clearly that the stream is case insensitive.
An uses ANTLRInputStream for the other grammar ( that is not case insensitive).
