### ISSUE TITLE
Scala lexer/parser for target language Go not working

### ISSUE THREAD

**Issue by jeep87c** [antlr/grammars-v4#857]
While trying to get Scala lexer/parser in target language Go, you get the following issues:

    antlr4 -o ~/go/src/antlr/parser2 -Dlanguage=Go Scala.g4
    error(134): Scala.g4:61:0: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:62:27: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:106:5: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:120:5: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:292:5: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:293:10: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:294:5: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:365:16: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:392:13: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:396:13: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:429:13: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:439:29: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:106:15: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:272:39: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:272:52: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:272:65: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:272:77: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:318:21: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:364:13: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:400:17: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:408:31: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:408:44: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:424:35: symbol type conflicts with generated code in target language or runtime
    error(134): Scala.g4:433:17: symbol type conflicts with generated code in target language or runtime

Here's my main.go file:

	package main
	
	import (
		"github.com/antlr/antlr4/runtime/Go/antlr"
		"antlr/parser2"
		"os"
		"fmt"
	)
	
	type TreeShapeListener struct {
		*parser.BaseScalaListener
	}
	
	func NewTreeShapeListener() *TreeShapeListener {
		return new(TreeShapeListener)
	}
	
	func (this *TreeShapeListener) EnterEveryRule(ctx antlr.ParserRuleContext) {
		fmt.Println(ctx.GetText())
	}
	
	func main() {
		input, _ := antlr.NewFileStream(os.Args[1])
		lexer := parser.NewScalaLexer(input)
		stream := antlr.NewCommonTokenStream(lexer,0)
		p := parser.NewScalaParser(stream)
		p.AddErrorListener(antlr.NewDiagnosticErrorListener(true))
		p.BuildParseTrees = true
		tree := p.CompoundType()
		antlr.ParseTreeWalkerDefault.Walk(NewTreeShapeListener(), tree)
	}

And the output while running it with your example1.txt file in subfolder Scala/examples

    go run main.go scala.txt                                        
    line 3:0 no viable alternative at input 'object HelloWorld {  def main(args: Array[String]): Unit = {'
    object HelloWorld {  def main(args: Array[String]): Unit = {    println("Hello, world!")  }}
    object HelloWorld {  def main(args: Array[String]): Unit = {    println("Hello, world!")  }}
    object HelloWorld {  def main(args: Array[String]): Unit = {    println("Hello, world!")  }}

I was expecting no errors while generating both lexer/parser and also I was expecting a proper tree after analyzing your example file.

Am I missing something? Is there an issue?

**Comment by maba18** [comment]
It seems that the Scala grammar is not correct and there is no future plan of fixing it. See issue [517](https://github.com/antlr/grammars-v4/issues/517).

**Comment by KvanTTT** [comment]
Specifically for this issue, Scala grammar can be easily fixed. Just rename `type` identifier to `type_`.

**Comment by maba18** [comment]
Can you please explain what exactly do you mean "rename  `type` identifier to `type_` ". Also, why should this work?

**Comment by KvanTTT** [comment]
@maba18 because `type` identifier conflicts with the same keyword in Go runtime. `type_` is not.
