### ISSUE TITLE
Can you add a test program under the scala?

### ISSUE THREAD

**Issue by tigermlt** [antlr/grammars-v4#859]
What I mean is inside java8, there is a test.java program that uses shows how to use Java8Lexer, Java8Parser etc. However, inside scala, there is not test program like that.

I tried to use test.java in scala and change Java8Lexer to ScalaLexer, Java8Parser to ScalaParser and the program can build and run. But it can not parse anything. Inside "parseFile" function, when I ran to "ParserRuleContext t = parser.compilationUnit();", t is just a empty which means the compilationUnit is empty and I am not able to get any token from the parse tree. 

So can you provide a test program that can demonstrate how to use the generated ScalaLexer, ScalaParser from Scala.g4? Or could you point out where I did wrong while modifying the test.java program?

Thanks!

**Comment by teverett** [comment]
There is an example of using antlr here:

https://github.com/teverett/antlr4example

This example uses the arithmetic example, but the concepts are the same.
