### ISSUE TITLE
Java 7 Grammar can not parse "instanceof" expressions

### ISSUE THREAD

**Issue by jangraefen** [antlr/grammars-v4#860]
Hello everyone,

apparently the Java 7 grammar is unable to parse an "instanceof" expression.
```
typeType
    :   classOrInterfaceType ('[' ']')*
    |   primitiveType ('[' ']')*
    ;

classOrInterfaceType
    :   Identifier typeArguments? ('.' Identifier typeArguments? )*
    ;

expression
    :   primary
    |   expression '.' Identifier
    |   expression 'instanceof' typeType
    ;
```

This is the minified grammar that causes the issue. If `typeType` is a qualified name and not just an identifier, the parser seems to be unable to decide wherever he should go with the `expression '.' Identifier` or the `Identifier typeArguments? ('.' Identifier typeArguments? )*` part.

Any help is appreciated.

**Comment by NoizeMe** [comment]
Okay, I think I already figured it out. Modifying the grammar to the following fixed it for me:
```
<assoc=right> expression 'instanceof' typeType
```

**Comment by KvanTTT** [comment]
Can you add a minimal test sample with `instanceof` and try again on a new grammar?

**Comment by Marti2203** [comment]
Hi,
I just tested all three Java grammars and all of them parse 
```
//Instanceof
class InstanceOf{
    public static void main(String[] args){
        if(args instanceof String[]){

        }
        if(args instanceof a.String[]){

        }
    }
}
```
without issues.
