### ISSUE TITLE
"C" grammar has a warning

### ISSUE THREAD

**Issue by jrialland** [antlr/grammars-v4#863]
When compiling the [C grammar](https://github.com/antlr/grammars-v4/blob/master/c/C.g4) I have the following warning :
```
warning(125): C.g4:95:8: implicit definition of token DigitSequence in parser
```
having a 'DigitSequence' in a castExpression is really weird, I think that it is an error.

fyi , This is the rule itself 

```
castExpression
    :   unaryExpression
    |   '(' typeName ')' castExpression
    |   '__extension__' '(' typeName ')' castExpression
    |   DigitSequence // for
```

**Comment by teverett** [comment]
Fixed with PR #864 

The problem was that the token was specified as a fragment which made it unavailable to the parser.
