### ISSUE TITLE
CPP grammar : Don't know how to  compile

### ISSUE THREAD

**Issue by z-banu** [antlr/grammars-v4#869]
Hello sir 
I am a beginner . This is the first time im working with grammars or antlr . 
These are the steps i used : 
1.cd C:\Javalib\new
2...\antlr4.bat CPP14.g4
3.javac *.java
4...\grun CPP14 test.cpp
After this my command prompt stands still
Can u tell me steps for compiling it.
Thanks and Regards
Zuvairiya Banu K

**Comment by teverett** [comment]
@z-banu can we see test.cpp please?

**Comment by teverett** [comment]
@z-banu please look here https://github.com/teverett/antlr4-cpp-example
