### ISSUE TITLE
PGN: why is san_move not parsed further?

### ISSUE THREAD

**Issue by RedTailedHawk** [antlr/grammars-v4#874]
If the move is NC3, this gets put in the san_move node as "NC3".  Why isn't this parsed further into things like piece (N) and square (C3)?  If I wrote a program against it, I would have to manually parse this myself.

For a more complicated move, like dxe8=Q+, there's a bit more parsing that I would have to do.

Should the PGN grammar be updated to further decompose the move?

Thanks.

**Comment by teverett** [comment]
I simply didn't go that far when implementing the grammar. Pull requests are welcome.
