### ISSUE TITLE
url grammar g4

### ISSUE THREAD

**Issue by enggei** [antlr/grammars-v4#875]
This url is not parseable:

https://github.com/dpaukov/combinatoricslib3#3-simple-permutations

line 1:46 token recognition error at: '-'
line 1:45 extraneous input '3' expecting STRING

**Comment by teverett** [comment]
Try it now pls.  Your example is example21.txt in /examples.

**Comment by enggei** [comment]
This is now working!

**Comment by teverett** [comment]
supercalifragilisticexpialidocious
