### ISSUE TITLE
MySQL grammar accepts only upper case characters in IDs

### ISSUE THREAD

**Issue by Lacuno** [antlr/grammars-v4#878]
In the MySqlLexer.g4 file the ID_LITERAL is defined as follows:
`fragment ID_LITERAL:                 [A-Z_$0-9]*?[A-Z_$]+?[A-Z_$0-9]*;`

Therefore lowercase IDs/ID Qualifiers/etc. are not accepted.
But even the examples in the [documentation](https://dev.mysql.com/doc/refman/5.6/en/identifier-qualifiers.html) state that it should be valid syntax.

My suggestion is to change the ID_LITERAL token to 
`fragment ID_LITERAL:                 [A-Za-z_$0-9]*?[A-Za-z_$]+?[A-Za-z_$0-9]*;`

**Comment by Lacuno** [comment]
Submitted PR #879

**Comment by KvanTTT** [comment]
Please close. We are using special case insensitive input stream and [caseInsensitiveType](https://github.com/antlr/antlr4test-maven-plugin#caseinsensitivetype) parameter.
