### ISSUE TITLE
MySQL grammar GRANT statement not working

### ISSUE THREAD

**Issue by fruether** [antlr/grammars-v4#905]
Hello,

I think the grant statement definition[1] is not working correctly in the MySQL grammar. Especially if we compare it with the MySQL [2] documentation we see that 

>  priv_obj_type=(TABLE | FUNCTION | PROCEDURE)? 

should rather be an optional value as it is defined as  [object_type]

Furthermore, the priv value seems to be wrong but I don't know what the problem is there. However, the following statement is rejected by the grammar but in my opinion it should be accepted:

> GRANT ALL ON table.* TO admin;

 

[1] : https://github.com/antlr/grammars-v4/blob/master/mysql/MySqlParser.g4#L1400
[2] : https://dev.mysql.com/doc/refman/5.7/en/grant.html

**Comment by ivan-khudyashev** [comment]
Hello, fruether.

Yes, there was problem with userName rule in grammar (not in grantStatement itself)
With new pull-request https://github.com/antlr/grammars-v4/pull/985  that was fixed.
Such as there are add some test for grant-statement
