### ISSUE TITLE
Where to find JavaScriptBaseParser?

### ISSUE THREAD

**Issue by schabluk** [antlr/grammars-v4#907]
In the options of grammar files, there is reference to "superClass"
```
options {
    tokenVocab=JavaScriptLexer;
    superClass=JavaScriptBaseParser;
}
```
Where do I get this class from? It wasn't generated along with JavaScriptLexer and JavaScriptParser files.

**Comment by KvanTTT** [comment]
They are placed to [CSharpSharwell](https://github.com/antlr/grammars-v4/tree/master/javascript/CSharpSharwell) and [Java](https://github.com/antlr/grammars-v4/tree/master/javascript/Java) directories.

**Comment by schabluk** [comment]
Hm, but I'm generating the target for JavaScript. Do I have to create "JavaScriptBaseParser.js" myself?

**Comment by KvanTTT** [comment]
Yes, JavaScript target is not supported for now.

**Comment by starFelix** [comment]
@KvanTTT  Is there a `JavaScriptBaseParser.g4` file which I can use to create `JavaScriptBaseParser.swift` by myself
