### ISSUE TITLE
TSQL Identifiers for local parameters need to allow lower case

### ISSUE THREAD

**Issue by hvogeler** [antlr/grammars-v4#919]
LOCAL_ID defines function parameters as upper case only in the current grammar.
`LOCAL_ID:           '@' ([A-Z_$@#0-9] | FullWidthLetter)+;`
Microsoft states that they can be lower case:
https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers

**Comment by KvanTTT** [comment]
Duplicate: https://github.com/antlr/grammars-v4/issues/920

**Comment by KvanTTT** [comment]
We are using case insensitive stream for this.
