### ISSUE TITLE
TSQL data_type tokens in upper case only

### ISSUE THREAD

**Issue by hvogeler** [antlr/grammars-v4#920]
Tokens for data types are defined as upper case only. 
The TSQL I have to parse often have mixed or lower case tokens for data types.
Any suggestion how to best cope with this? Would this be of general interest?

```CREATE FUNCTION heiko.ufn_FindReports (@INEMPID INTEGER)
	RETURNS @RETFINDREPORTS TABLE
	(
		EmployeeID int primary key NOT NULL,
		FirstName nvarchar(255) NOT NULL,
		LastName nvarchar(255) NOT NULL,
		JobTitle nvarchar(50) NOT NULL,
		RecursionLevel int NOT NULL
	)
	--Returns a result set that lists all the employees who report to the
	--specific employee directly or indirectly.*/
AS
	BEGIN
		WITH EMP_cte(EmployeeID, OrganizationNode, FirstName, LastName, JobTitle, RecursionLevel) -- CTE name and columns
		AS (
			-- Get the initial list of Employees for Manager n
			SELECT e.BusinessEntityID, e.OrganizationNode, p.FirstName, p.LastName, e.JobTitle, 0
			FROM HumanResources.Employee e
				INNER JOIN Person.Person p
					ON p.BusinessEntityID = e.BusinessEntityID
			WHERE e.BusinessEntityID = @InEmpID
			UNION ALL
			-- Join recursive member to anchor
			SELECT e.BusinessEntityID, e.OrganizationNode, p.FirstName, p.LastName, e.JobTitle, RecursionLevel + 1
			FROM HumanResources.Employee e
				INNER JOIN EMP_cte
					ON e.OrganizationNode.GetAncestor(1) = EMP_cte.OrganizationNode
				INNER JOIN Person.Person p
					ON p.BusinessEntityID = e.BusinessEntityID
		)
		-- copy the required columns to the result of the function
		INSERT @retFindReports
			SELECT EmployeeID, FirstName, LastName, JobTitle, RecursionLevel
			FROM EMP_cte
		RETURN
	END;
GO```

**Comment by KvanTTT** [comment]
Grammar supports both. We are using UPPER case insensitive input stream, see [caseInsensitiveType](https://github.com/antlr/antlr4test-maven-plugin#caseinsensitivetype).

**Comment by hvogeler** [comment]
>Grammar supports both.

Can you help me how I can use the grammar to parse this?
```CREATE FUNCTION [Report].[ModulKundeneinheit]
  (
      @IN_Stichtag          DATE
    , @IN_VergleichStichtag DATE
    , @IN_Datenaspekt       VARCHAR(30) = 'Gesamt'
  )
  RETURNS TABLE
````
Trying to parse this using the grammar I get:
```line 3:28 extraneous input 'DATE' expecting {')', ','}
line 4:28 extraneous input 'DATE' expecting {')', ','}
line 5:28 mismatched input 'VARCHAR' expecting {')', ','}
```

**Comment by KvanTTT** [comment]
You can use case insensitive input stream for any runtime, see [Runtimes](https://github.com/KvanTTT/DAGE/tree/master/AntlrGrammarEditor/Runtimes). Here is usage in Java: https://github.com/antlr/antlr4test-maven-plugin/blob/master/src/main/java/com/khubla/antlr/antlr4test/GrammarTestMojo.java#L296

What runtime do you use?

**Comment by hvogeler** [comment]
I am using Kotlin which effectively is a Java runtime. I could use this case insensitive stream but I don't like it. I rather have a grammar that exactly covers the language definition than tweaking the source. I was hoping there was some other way that was natively supported by Antlr4.  Reading antlr/antlr4#2046 I understand there is no native antlr4 supported way to do this other than changing the grammar which I - unhappily - will do for my purposes now. Thank you for your help, Ivan.

**Comment by KvanTTT** [comment]
Firstly it's impossible to exactly cover T-SQL language definition without tweaks (context dependency). Secondly, the source is not changed: case insensitive stream influence only on lexer. In parser or parse tree traversing you can rely on chars case.

**Comment by hvogeler** [comment]
Ivan, since you are the far more experienced expert on Antlr than me I decided to follow your advice. It works fine. But aside from the more academic problem that the grammar should match the language definition as closely as possible I encountered two more technical problems with this approach:

1. Base class Antlr4FileStream is deprectated
2. (and this is really a problem): Very helpful tools like the Antlr4 plugin for Intellij don't use the Antlr4CaseInsensitiveFileStream and therefore can't be used with the grammar.

Do you have any suggestion how to at least be able to use the tools without modifying the grammar?

**Comment by KvanTTT** [comment]
1. I tried to use a new 4.7 API but failed. I'll try again later. Maybe @bhamiltoncx can help.
2. I'm not using this plugin. But I developed a new cross-platform and cross-runtime ANTLR editor with case insensitive stream support. Draft is available here: https://github.com/KvanTTT/DAGE
Maybe @parrt can help with Intellij plugin.
