### ISSUE TITLE
git clone leaves modified files (line endings)

### ISSUE THREAD

**Issue by ohumbel** [antlr/grammars-v4#923]
Hi,

I did a fresh clone on Mac, Linux and Windows.
On every platform `git status` lists between one and two dozens of modified files right after, without doing anything.

Should I try to fix this (as described in https://help.github.com/articles/dealing-with-line-endings/#platform-all) and file a pull request, or do you already have a plan how to handle this?

Thanks,
Oti.

**Comment by KvanTTT** [comment]
Yes, please try to fix it. I'll look.

**Comment by hvogeler** [comment]
It is not only the line endings. It is also whitespaces before the line endings. Only correcting the line endings (lf, crlf...) is not enough. It would take one clone and commit to clean it up with a correctly configured git clien.

**Comment by luyseyal** [comment]
It is annoying. I worked around it locally by editing .gitattributes. You can submit a patch by just doing `git add` with the files you actually changed plus `git commit` (versus the usual `git commit -a` which I tend to do...)

```diff --git a/.gitattributes b/.gitattributes
index bc41405..393e747 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -1,3 +1 @@
-*.* eol=lf
-
 **/examples/* linguist-vendored
```

**Comment by ohumbel** [comment]
I'll only use the git command line, and will use my own fork to exercise with.
I'll try to keep the modifications as minimal as possible.
But - to be honest - this is a sensitive area, from what I learned so far.

**Comment by ohumbel** [comment]
Pull Request #930 is now ready to be merged. This would fix this problem.

**Comment by ohumbel** [comment]
To @hvogeler: The line endings versus the whitespace before them are IMHO different issues. My pull request did not change any grammar nor whitespace in the parse trees. But it changed line endings in both input files and (as a special case) line endings in the Visual Basic expectations. This way I was able to really make `pull` and `mvn test` platform independent - safely.

This does not mean though that Visual Basic and Grapheme Grammars are not sensitive to line endings and/or white space. See for example #937.

**Comment by azrdev** [comment]
@ohumbel I just cloned the repo (71353936d126f206b85776cacea565d27e1dbda3) on archlinux, and the `vb6/**.cls` files are marked as changed. git `checkout` or `reset --hard`don't change this, only thing I can do is add them to the index with `git add --renormalize -u`.
`file` tells me they have CRLF.

`git config --list` has none of the settings `core.crlf` `.eol` etc, so I think it's not simply a config issue of mine.

**Comment by teverett** [comment]
Does this issue still exist?  @ohumbel could you verify pls?

**Comment by KvanTTT** [comment]
I'm closing it. Reopen if it's still reproducing.
