### ISSUE TITLE
TSQL count(*) not recognized

### ISSUE THREAD

**Issue by hvogeler** [antlr/grammars-v4#934]
`SELECT count(*) FROM Table` does not parse.
I added asterisk to the expression rule which solves my problem but I don't oversee if this is really a proper solution and if it might not break something else.

Could someone check my suggestion?

```g4
expression
    : primitive_expression
    | function_call
    | expression COLLATE id
    | case_expression
    | full_column_name
    | bracket_expression
    | unary_operator_expression
    | expression op=('*' | '/' | '%') expression
    | expression op=('+' | '-' | '&' | '^' | '|') expression
    | expression comparison_operator expression
    | expression assignment_operator expression
    | over_clause
    | asterisk
    ;
```

**Comment by vonloxley** [comment]
"Table" is a reserved word in sql. `Select count(*) from atable` works.

**Comment by hvogeler** [comment]
„Table“ was meant as a placeholder. Of course the name of the table is not „Table“ in the real test case.
Have you really tried it? For me it only works if I add asterisk to the expression rule.

**Comment by hvogeler** [comment]
I checked again. The problem is not the asterisk I have to admit. But ``Select count(*) from atable`` doesn't work either.

```
line 1:21 missing ':' at 'atable'
line 1:27 missing ':' at '<EOF>'
```
The problem is the lower case key words like "count" or "Select" or "from". 
``SELECT COUNT(*) FROM atable`` works.

This damn case insensitivity thing is really confusing.

**Comment by vonloxley** [comment]
Thats why it worked for me, I used the testrig and `examples/countstar.sql` works.

However, sql is case-sensitive, so this is a bit annoying.

44aa3b6bebeec9b29397eb7cf5866597ddc19e7e is the first bad commit
commit 44aa3b6bebeec9b29397eb7cf5866597ddc19e7e
Author: Ivan Kochurkin <kvanttt@gmail.com>
Date:   Mon Jun 5 21:43:21 2017 +0300

    Removed fragment rules from PL/SQL and T-SQL grammars. Tokens transformed: S E L F -> 'SELF';

The offending commit seems to be

**Comment by vonloxley** [comment]
Ah, this grammar won’t work for mere mortals until https://github.com/antlr/antlr4/pull/2046 has been resolved.

**Comment by KvanTTT** [comment]
I said many times that CaseInsensitive input stream should be used for *SQL and other case-insensitive languages. See https://github.com/antlr/grammars-v4/issues/920 and other related issues.

**Comment by vonloxley** [comment]
That’s very kind of you, but wouldn’t the ReadMe.md be a better place for this information?

**Comment by KvanTTT** [comment]
You are right: there are too many case insensitive issues. I'll do it later due to the lack of time or you can try it by yourself.

**Comment by hvogeler** [comment]
We had the discussion about case insensitive input stream in another thread. to me it is not a complete solution as long as antlr tools like the intellij antlr plugin don‘t support it and as long as it is based on deprecated stuff. 
I am not repeating this because I want to complain or rush anyone. Just for information.

**Comment by KvanTTT** [comment]
The full solution doesn't depend on me, sorry.

**Comment by hvogeler** [comment]
Ivan, because you wrote "sorry" I want to make one thing really clear:
The benefit and joy I gain by being allowed to use the stuff you guys maintain outweighs the little annoyance with the case sensitivity by far. No reason to apologize in any form especially not to me! Also I discovered that there already is an implementation of case insensitive char stream which is not based on anything deprecated.  I am going to use that and manually upper case the SQL when using the intellij plugin. I can certainly live with that.

**Comment by vonloxley** [comment]
Is this implementation in Antlr 4.7? I only found ANTLRFileStream, ANTLRInputStream, CodePointCharStream, UnbufferedCharStream, which, prima vista, aren’t applyable.

if you point me in the right direction I’ll update the readmes.

**Comment by hvogeler** [comment]
The case insensitive charstream is not merged into ANTLR. They decided to wait until it has become implemented for all runtimes. Check antlr/antlr4#2046 for complete information. I plan to grab the code from antlr/antlr4#2048

**Comment by KvanTTT** [comment]
> I am going to use that and manually upper case the SQL when using the intellij plugin.

Case insensitive streams have been supporting since version [1.13](https://github.com/antlr/intellij-plugin-v4/releases/tag/1.13).
