### ISSUE TITLE
Java8-js: Files are Missing

### ISSUE THREAD

**Issue by gchallen** [antlr/grammars-v4#946]
The refactored Java8 grammar for the JavaScript target done by @teverett in 32eb56d06d061437ef57d78156d69536ed3c4909 requires several files to do unicode processing:

```
@lexer::members {
    let Character_toCodePoint = require('App/java_functions/Character_toCodePoint.js');
    let Character_isJavaIdentifierStart = require('App/java_functions/Character_isJavaIdentifierStart.js');
    let Character_isJavaIdentifierPart = require('App/java_functions/Character_isJavaIdentifierPart.js');
}
```
Where do you get these files? I've looked in the main antlr repo and here but can't seem to locate them. I'd be happy to help test them, etc. Thanks in advance for the help.

**Comment by KvanTTT** [comment]
Try to use [java](https://github.com/antlr/grammars-v4/tree/master/java) grammar. It supports Java 8.

**Comment by teverett** [comment]
@gchallen can we close this?

**Comment by gchallen** [comment]
OK—I'll give this a try. Thanks.

**Comment by silentbalanceyh** [comment]
How to use java grammar for javascript parser, I also met the issue:
Cannot find module 'App/java_functions/Character_toCodePoint.js'

**Comment by cancerberoSgx** [comment]
This is a real issue, without the missing files the grammar is unusable. I think it should be opened.
