### ISSUE TITLE
Pascal empty field-list

### ISSUE THREAD

**Issue by MartijnDwars** [antlr/grammars-v4#947]
According to the ISO 7185:1990 that is included with `pascal.g`, a record-type contains a field-list that may be empty.

> A field-list containing neither a fixed-part nor a variant-part shall have no components, shall define a single null value, and shall be designated _empty_.

However, the [current definition](https://github.com/antlr/grammars-v4/blob/5c680cd7e637973fb9ae87239f07789245f32c10/pascal/pascal.g4#L185-L192) of field-list in `pascal.g` does not permit empty field lists. Can someone confirm whether this is a bug?

**Comment by teverett** [comment]
@MartijnDwars do you have example code that shows the unexpected behaviour?

**Comment by MartijnDwars** [comment]
For example:

```
program x (x);

type
  T = record end;

begin
  writeln('Hi');
end.
```

Compiling this with the [Free Pascal Compiler](https://www.freepascal.org):

```
➜  tmp fpc x.pas
Free Pascal Compiler version 3.0.0 [2016/02/18] for x86_64
Copyright (c) 1993-2015 by Florian Klaempfl and others
Target OS: Darwin for x86_64
Compiling x.pas
Assembling (pipe) x.s
Linking x
8 lines compiled, 0.1 sec
➜  tmp ./x
Hi
```

Compiling this with the ANTLRv4-generated parser:

```
Parsing :/private/tmp/grammars-v4/pascal/examples/x.pas
line 4:13 mismatched input 'end' expecting {CASE, IDENT}
```

**Comment by teverett** [comment]
Do a fresh pull please, and let me know if the problem is resolved.

https://github.com/antlr/grammars-v4/pull/949

**Comment by MartijnDwars** [comment]
Works, thanks!
