### ISSUE TITLE
PGN grammar misses first game

### ISSUE THREAD

**Issue by future2r** [antlr/grammars-v4#948]
Hi there,

looks like the PGN grammar is missing the first game in a database file. At least when I use it with the ANTLR4 listener. This happens even with the provided examples like 'Karpov.pgn'. In fact, if I have a file with just one game it reads nothing.

This is my code (ANTLR 4.7):

        CharStream cs = CharStreams.fromPath(file);
        PGNLexer lexer = new PGNLexer(cs);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        PGNParser parser = new PGNParser(tokens);
        parser.pgn_game();

        ParseTreeWalker walker = new ParseTreeWalker();
        PGNListener listener = new PGNListener();
        walker.walk(listener, parser.pgn_database());

The listener:

    final class PGNListener extends PGNBaseListener {

        @Override
        public void enterPgn_game(PGNParser.Pgn_gameContext ctx) {
            System.out.println("enter game");
        }
    }

Is it the grammar or just the way I am using it?

Thank you!

**Comment by teverett** [comment]
The start rule is "parse". 

`grammar PGN;

// The entry point of the grammar.
parse
 : pgn_database EOF
 ;
`

**Comment by future2r** [comment]
As soon as you do it right it will work. (TM)

Thank you very much. I don't known how I could miss this. It has been a while since I worked with ANTLR...

Great work!
