### ISSUE TITLE
Java8 Unicode one or more 'u'

### ISSUE THREAD

**Issue by MartijnDwars** [antlr/grammars-v4#952]
According to the [Unicode Escape](https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.3) section in the JLS 1.8, a unicode escape can contain one or more 'u' characters:

```
UnicodeInputCharacter:
  UnicodeEscape 
  RawInputCharacter

UnicodeEscape:
  \ UnicodeMarker HexDigit HexDigit HexDigit HexDigit

UnicodeMarker:
  u {u}

HexDigit:
  (one of) 
  0 1 2 3 4 5 6 7 8 9 a b c d e f A B C D E F

RawInputCharacter:
  any Unicode character
```

In the [current grammar Java8.g4](https://github.com/antlr/grammars-v4/blob/4075d480f86b2ed82fea5728ec60c08cd3d34733/java8/Java8.g4#L1670), exactly one 'u' is allowed, but no more.

**Comment by KvanTTT** [comment]
Could you also fix it in fast [Java](https://github.com/antlr/grammars-v4/tree/master/java) grammar?
