### ISSUE TITLE
Oracle is case insensitive

### ISSUE THREAD

**Issue by balahsen** [antlr/grammars-v4#972]
https://github.com/antlr/grammars-v4/blob/3b1eb3f6a5b38cd4847b5f3cdf02b51402bce106/plsql/PlSqlParser.g4#L1241
The grammar should accept WITH or with.
Wheb the file "query_factoring01.sql" has been used for test theris a syntax error generated.

**Comment by KvanTTT** [comment]
Duplicate: https://github.com/antlr/grammars-v4/issues/854

**Comment by balahsen** [comment]
In antlr4_cpp there is no CaseInsensitiveInputStream defined.

**Comment by KvanTTT** [comment]
You can write your own one or ask @mike-lischke for help.
