### ISSUE TITLE
<identifier name>

### ISSUE THREAD

**Issue by balahsen** [antlr/grammars-v4#973]
https://github.com/antlr/grammars-v4/blob/3b1eb3f6a5b38cd4847b5f3cdf02b51402bce106/plsql/PlSqlParser.g4#L1241
The grammar should accept WITH or with.
Wheb the file "query_factoring01.sql" has been used for test theris a syntax error generated.

The <identifier name> for the query, tables, views, routines, packages, columns, ..., could be prefixed and should be like  [a-zA-Z]( [a-zA-Z][0-9]_)* (charater followed by any characters or digits or '_') and not a "regular_id"

Used antlr4Cpp with PlSqlParser.g4.

**Comment by kmillerdevx3** [comment]
This is in the lexer, not the parser. The WITH keyword (and the rest of the keywords) are specified in uppercase only.

    WITH:                         'WITH';

In other grammars that need to ignore case, they define things a little differently in the lexer.

    WITH:                         W I T H ;
    
    ...
    fragment H: [Hh];
    fragment I: [Ii];
    ...
    fragment T: [Tt];
    ...
    fragment W: [Ww];

**Comment by KvanTTT** [comment]
It works fine. Please read doc https://github.com/antlr/antlr4/blob/master/doc/case-insensitive-lexing.md and use case-insensitive stream `CaseChangingCharStream`.
