### ISSUE TITLE
mysql grammer run test fail

### ISSUE THREAD

**Issue by HotHat** [antlr/grammars-v4#976]
create database new_t;

lexer display :
[@0,0:1='\r\n',<SPACE>,channel=1,1:0]
[@1,2:2='c',<ERROR_RECONGNIGION>,channel=3,2:0]
[@2,3:3='r',<ERROR_RECONGNIGION>,channel=3,2:1]
[@3,4:4='e',<ERROR_RECONGNIGION>,channel=3,2:2]
[@4,5:5='a',<ERROR_RECONGNIGION>,channel=3,2:3]
[@5,6:6='t',<ERROR_RECONGNIGION>,channel=3,2:4]
[@6,7:7='e',<ERROR_RECONGNIGION>,channel=3,2:5]
[@7,8:8=' ',<SPACE>,channel=1,2:6]
[@8,9:9='d',<ERROR_RECONGNIGION>,channel=3,2:7]
[@9,10:10='a',<ERROR_RECONGNIGION>,channel=3,2:8]
[@10,11:11='t',<ERROR_RECONGNIGION>,channel=3,2:9]
[@11,12:12='a',<ERROR_RECONGNIGION>,channel=3,2:10]
[@12,13:13='b',<ERROR_RECONGNIGION>,channel=3,2:11]
[@13,14:14='a',<ERROR_RECONGNIGION>,channel=3,2:12]
[@14,15:15='s',<ERROR_RECONGNIGION>,channel=3,2:13]
[@15,16:16='e',<ERROR_RECONGNIGION>,channel=3,2:14]
[@16,17:17=' ',<SPACE>,channel=1,2:15]
[@17,18:18='n',<ERROR_RECONGNIGION>,channel=3,2:16]
[@18,19:19='e',<ERROR_RECONGNIGION>,channel=3,2:17]
[@19,20:20='w',<ERROR_RECONGNIGION>,channel=3,2:18]
[@20,21:21='_',<ID>,2:19]
[@21,22:22='t',<ERROR_RECONGNIGION>,channel=3,2:20]
[@22,23:23=';',<';'>,2:21]
[@23,24:23='<EOF>',<EOF>,2:22]
line 2:19 extraneous input '_' expecting {<EOF>, 'ALTER', 'ANALYZE', 'CALL', 'CHANGE', 'CHECK', 'CREATE', 'DELETE', 'DESC', 'DESCRIBE', 'DROP', 'EXPLAI

**Comment by KvanTTT** [comment]
Use case insensitive input stream. Duplicate: https://github.com/antlr/grammars-v4/issues/878

**Comment by HotHat** [comment]
thanks

**Comment by HotHat** [comment]
@KvanTTT thanks
