### ISSUE TITLE
TSQL Token 'R' causes pain

### ISSUE THREAD

**Issue by hvogeler** [antlr/grammars-v4#978]
This perfectly valid SQL
```
UPDATE #TEMP_DG_RIPO
SET UEBERGEORDNETE_HANDELSSTELLE_NAME = H.BEZEICHNUNG_DE
FROM #TEMP_DG_RIPO R
  LEFT JOIN DM.VW_DM_PR_HANDELSSTELLE H WITH (NOLOCK) ON H.HANDELSSTELLE = R.UEBERGEORDNETE_HANDELSSTELLE_NUMMER
```
doesn't parse complaining it expects a '.' instead of 'FROM' because letter 'R' is a token.

**Comment by KvanTTT** [comment]
Just try to add `R` token to the `simple_id` rule.

**Comment by vonloxley** [comment]
This parses fine with #945.

**Comment by hvogeler** [comment]
I just commented the R token out which is quite a bold move but I would be interested to see how you solved it. Could you point me to the specific commit(s) that address this problem? I didn’t see it when I quickly scanned the commits of #945 .

**Comment by vonloxley** [comment]
a887f011d4173b8bcf76020e2e15db5f7a07a01f

**Comment by KvanTTT** [comment]
I suppose we can close it?

**Comment by hvogeler** [comment]
Yes, please close it. Thanks
