### ISSUE TITLE
Scala grammar support

### ISSUE THREAD

**Issue by bingoko** [antlr/grammars-v4#981]
Hi, the Scala grammar provided in this repo is buggy. The Scala code cannot be parsed via it. Is there anyone can fix it?

**Comment by chakpongchung** [comment]
Same problem here.

https://github.com/antlr/grammars-v4/blob/master/scala/Scala.g4

for example, I want to test whether the grammar is accurate enough to parse this code:

https://raw.githubusercontent.com/cs-au-dk/TIP/master/src/tip/interpreter/Interpreter.scala

Some official ebnf grammar:

https://dotty.epfl.ch/docs/internals/syntax.html
https://www.scala-lang.org/files/archive/spec/2.11/13-syntax-summary.html

**Comment by sherlockwang** [comment]
Same issue here. It seems the the Scala.g4 file in this repo doesn't work. Can someone provide a valid Scala ANTLR4 grammar file please? Thanks.

**Comment by loonydev** [comment]
Hi, currently Scala grammar works, not sure if fully correct, but parsing code and we improve the result.

For entry rule you can use `compilationUnit`. 
You can take a look on an `example` folder inside.
``` bash
$ antlr4 Scala.g4
$ javac Scala*.java
$ grun Scala compilationUnit  examples/class.scala -tree
```

@KvanTTT I think you can close this issue.
