### ISSUE TITLE
Java shift expressions

### ISSUE THREAD

**Issue by MartijnDwars** [antlr/grammars-v4#997]
[Java shift operator](https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.19) does not allow whitespace between the less-than and greater-than signs, i.e. the following should not be a legal Java program:

```
class X {
        public X() {
                int x = 1;
                System.out.println(x > > 1);
        }
}
```

The [Java8 grammar](https://github.com/antlr/grammars-v4/blob/master/java8/Java8.g4#L1273-L1275) and [Java grammar](https://github.com/antlr/grammars-v4/blob/master/java/JavaParser.g4#L480), however, allow whitespace between the less-than and greater-than signs.

**Comment by KvanTTT** [comment]
In the sample below two angle bracket will be recognized as one operator `RSHIFT` instead of two operators `GT`. This is incorrect.

```
public static void main(String[] args) {
    Map<Integer, List<String>> mappy =
        new HashMap<Integer, List<String>>();

    test(mappy);
}
```

**Comment by KvanTTT** [comment]
There is no convenient solution to resolve this issue. So, I'm closing it.
